<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { computed, ref, useAttrs } from "vue";
import { useSidebarContext } from "./SidebarContext.js";

defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{
    side?: "left" | "right";
    variant?: "sidebar" | "floating" | "inset";
    collapsible?: "offcanvas" | "icon";
  }>(),
  { side: "left", variant: "sidebar", collapsible: "offcanvas" },
);
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const element = ref<HTMLDivElement | null>(null);
const context = useSidebarContext();
const collapsedMode = computed(() =>
  context.state.value === "collapsed" ? props.collapsible : "",
);
defineExpose({ element });
</script>
<template>
  <div
    ref="element"
    v-bind="attrs"
    data-sw-sidebar
    :data-state="context.state.value"
    :data-collapsible="collapsedMode"
    :data-collapsible-mode="props.collapsible"
    :data-variant="props.variant"
    :data-side="props.side"
  >
    <slot />
  </div>
</template>
