<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { computed, defineComponent, ref, useAttrs, useSlots } from "vue";
import { createVueAsChild } from "../_internal/as-child.js";
import { useSidebarContext } from "./SidebarContext.js";

defineOptions({ inheritAttrs: false });
const props = withDefaults(defineProps<{ asChild?: boolean }>(), { asChild: false });
const attrs = useAttrs();
const slots = useSlots();
const element = ref<HTMLElement | null>(null);
const context = useSidebarContext();
const asChild = createVueAsChild("Sidebar.Trigger", element);
const protectedProps = computed(() => ({
  "data-sw-sidebar-trigger": "",
  "aria-expanded": context.expanded.value,
  "data-state": context.state.value,
}));
const AsChildRoot = defineComponent({
  inheritAttrs: false,
  setup() {
    return () =>
      asChild.render({
        children: slots.default?.() ?? [],
        consumerProps: attrs,
        defaultNativeButtonType: "button",
        protectedProps: protectedProps.value,
      });
  },
});
defineExpose({ element });
</script>
<template>
  <AsChildRoot v-if="props.asChild" />
  <button
    v-else
    ref="element"
    v-bind="attrs"
    type="button"
    data-sw-sidebar-trigger
    :aria-expanded="context.expanded.value"
    :data-state="context.state.value"
  >
    <slot />
  </button>
</template>
