<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    ariaAtomic?: boolean | "false" | "true";
    ariaLive?: "assertive" | "off" | "polite";
    hidden?: boolean;
    role?: string;
  }>(),
  {
    ariaAtomic: "true",
    ariaLive: "polite",
    hidden: true,
    role: "status",
  },
);
defineSlots<{
  default?: () => unknown;
}>();
const rootRef = ref<HTMLDivElement | null>(null);

defineExpose({
  element: rootRef,
});
</script>

<template>
  <div
    ref="rootRef"
    v-bind="$attrs"
    :role="props.role"
    :aria-live="props.ariaLive"
    :aria-atomic="props.ariaAtomic"
    :hidden="props.hidden"
    data-sw-form-error-summary
    data-slot="form-error-summary"
  >
    <slot />
  </div>
</template>
