/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import DialogBackdrop from "./DialogBackdrop.vue";
import DialogClose from "./DialogClose.vue";
import DialogDescription from "./DialogDescription.vue";
import DialogPopup from "./DialogPopup.vue";
import DialogRoot from "./DialogRoot.vue";
import DialogTitle from "./DialogTitle.vue";
import DialogTrigger from "./DialogTrigger.vue";

const Dialog = {
  Root: DialogRoot,
  Trigger: DialogTrigger,
  Backdrop: DialogBackdrop,
  Popup: DialogPopup,
  Title: DialogTitle,
  Description: DialogDescription,
  Close: DialogClose,
};

export { default as DialogBackdrop } from "./DialogBackdrop.vue";
export { default as DialogClose } from "./DialogClose.vue";
export { default as DialogDescription } from "./DialogDescription.vue";
export { default as DialogPopup } from "./DialogPopup.vue";
export { default as DialogRoot } from "./DialogRoot.vue";
export { default as DialogTitle } from "./DialogTitle.vue";
export { default as DialogTrigger } from "./DialogTrigger.vue";
export { Dialog };

export default Dialog;

export type { DialogCloseCompleteDetails, DialogOpenChangeDetails } from "@starwind-ui/runtime";
