<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Svelte proof output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { useSelectContext } from "./SelectRoot.svelte";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & { children?: Snippet; align?: "start" | "center" | "end"; alignOffset?: number; alignItemWithTrigger?: boolean; avoidCollisions?: boolean; ref?: (element: HTMLDivElement | null) => void; side?: "top" | "right" | "bottom" | "left"; sideOffset?: number };
  let { children, align = "start", alignOffset = 0, alignItemWithTrigger = true, avoidCollisions = true, ref, side = "bottom", sideOffset = 4, ...rest }: Props = $props();
  const select = useSelectContext("Positioner");
  const initialOpen = untrack(() => select.open);
  const attachRef: Attachment<HTMLDivElement> = (element) => { const callback = ref; untrack(() => callback?.(element)); return () => callback?.(null); };
</script>
<div {...rest} data-sw-select-positioner="" data-sw-part="positioner"  data-state={initialOpen ? "open" : "closed"} data-side={side} data-align={align} data-side-offset={sideOffset} data-align-offset={alignOffset} data-align-item-with-trigger={alignItemWithTrigger ? "true" : "false"} data-avoid-collisions={avoidCollisions ? "true" : "false"} {@attach attachRef}>{@render children?.()}</div>
