<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Svelte proof output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & { children?: Snippet; ref?: (element: HTMLDivElement | null) => void };
  let { children, ref, ...rest }: Props = $props();
  const attachRef: Attachment<HTMLDivElement> = (element) => { const callback = ref; untrack(() => callback?.(element)); return () => callback?.(null); };
</script>
<div {...rest} data-sw-select-list="" data-sw-part="list"  {@attach attachRef}>{@render children?.()}</div>
