<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { useSelectContext } from "./SelectRoot.svelte";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & { children?: Snippet; align?: "start" | "center" | "end"; alignOffset?: number;  avoidCollisions?: boolean; ref?: (element: HTMLDivElement | null) => void; side?: "top" | "right" | "bottom" | "left"; sideOffset?: number };
  let { children, align = "start", alignOffset = 0,  avoidCollisions = true, ref, side = "bottom", sideOffset = 4, ...rest }: Props = $props();
  const select = useSelectContext("Popup");
  const initialOpen = untrack(() => select.open);
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>
<div {...rest} data-sw-select-popup="" data-sw-part="popup" role="listbox" tabindex="-1" hidden={!initialOpen} data-state={initialOpen ? "open" : "closed"} data-side={side} data-align={align} data-side-offset={sideOffset} data-align-offset={alignOffset}  data-avoid-collisions={avoidCollisions ? "true" : "false"} {@attach attachRef}>{@render children?.()}</div>
