<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Svelte proof output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script lang="ts">
  import { setContext, untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { SelectItemContext, useSelectContext, type SelectItemContextValue } from "./SelectRoot.svelte";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & { children?: Snippet; disabled?: boolean; ref?: (element: HTMLDivElement | null) => void; value: string };
  let { children, disabled = false, ref, value, ...rest }: Props = $props();
  const select = useSelectContext("Item");
  let selected = $derived(select.value === value);
  setContext<SelectItemContextValue>(SelectItemContext, { get disabled() { return disabled; }, get value() { return value; } });
  const attachRef: Attachment<HTMLDivElement> = (element) => { const callback = ref; untrack(() => callback?.(element)); return () => callback?.(null); };
</script>
<div {...rest} data-sw-select-item="" data-sw-part="item" data-value={value} role="option" aria-selected={selected} aria-disabled={disabled ? "true" : undefined} data-disabled={disabled ? "" : undefined} data-selected={selected ? "" : undefined} tabindex="-1" {@attach attachRef}>{@render children?.()}</div>
