<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { getComboboxContext } from "./ComboboxRoot.svelte";
  type Props = Omit<HTMLAttributes<HTMLSpanElement>, "children"> & { children?: Snippet; placeholder?: string; ref?: (element: HTMLSpanElement | null) => void };
  let { children, placeholder, ref, ...rest }: Props = $props();
  const combobox = getComboboxContext();


  let elementProps = $derived({ ...rest });
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLSpanElement>(() => ref);
</script>
<span {...elementProps} data-sw-combobox-value={children ? undefined : ""} data-sw-part="value" data-placeholder={placeholder}  {@attach attachRef}>{#if children}{@render children()}{:else}{placeholder ?? ""}{/if}</span>
