<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { getComboboxContext } from "./ComboboxRoot.svelte";
  type Props = Omit<HTMLAttributes<HTMLSpanElement>, "children"> & { children?: Snippet;  ref?: (element: HTMLSpanElement | null) => void };
  let { children,  ref, ...rest }: Props = $props();
  const combobox = getComboboxContext();


  let elementProps = $derived({ ...rest });
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLSpanElement>(() => ref);
</script>
<span {...elementProps} data-sw-combobox-icon="" data-sw-part="icon" aria-hidden="true" data-state={combobox?.open ? "open" : "closed"}  {@attach attachRef}>{@render children?.()}</span>
