/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

// Svelte 5 public beta adapter output.
import ComboboxClear from "./ComboboxClear.svelte";
import ComboboxEmpty from "./ComboboxEmpty.svelte";
import ComboboxGroup from "./ComboboxGroup.svelte";
import ComboboxGroupLabel from "./ComboboxGroupLabel.svelte";
import ComboboxIcon from "./ComboboxIcon.svelte";
import ComboboxInput from "./ComboboxInput.svelte";
import ComboboxInputGroup from "./ComboboxInputGroup.svelte";
import ComboboxItem from "./ComboboxItem.svelte";
import ComboboxItemIndicator from "./ComboboxItemIndicator.svelte";
import ComboboxItemText from "./ComboboxItemText.svelte";
import ComboboxLabel from "./ComboboxLabel.svelte";
import ComboboxList from "./ComboboxList.svelte";
import ComboboxPopup from "./ComboboxPopup.svelte";
import ComboboxPortal from "./ComboboxPortal.svelte";
import ComboboxPositioner from "./ComboboxPositioner.svelte";
import ComboboxRoot from "./ComboboxRoot.svelte";
import ComboboxSeparator from "./ComboboxSeparator.svelte";
import ComboboxTrigger from "./ComboboxTrigger.svelte";
import ComboboxValue from "./ComboboxValue.svelte";
const Combobox = {
  Root: ComboboxRoot,
  Label: ComboboxLabel,
  InputGroup: ComboboxInputGroup,
  Input: ComboboxInput,
  Trigger: ComboboxTrigger,
  Icon: ComboboxIcon,
  Clear: ComboboxClear,
  Value: ComboboxValue,
  Portal: ComboboxPortal,
  Positioner: ComboboxPositioner,
  Popup: ComboboxPopup,
  Empty: ComboboxEmpty,
  List: ComboboxList,
  Group: ComboboxGroup,
  GroupLabel: ComboboxGroupLabel,
  Item: ComboboxItem,
  ItemText: ComboboxItemText,
  ItemIndicator: ComboboxItemIndicator,
  Separator: ComboboxSeparator,
};
export {
  Combobox,
  ComboboxClear,
  ComboboxEmpty,
  ComboboxGroup,
  ComboboxGroupLabel,
  ComboboxIcon,
  ComboboxInput,
  ComboboxInputGroup,
  ComboboxItem,
  ComboboxItemIndicator,
  ComboboxItemText,
  ComboboxLabel,
  ComboboxList,
  ComboboxPopup,
  ComboboxPortal,
  ComboboxPositioner,
  ComboboxRoot,
  ComboboxSeparator,
  ComboboxTrigger,
  ComboboxValue,
};
export default Combobox;
export type { ButtonChildProps, ButtonChildPayload } from "../button/ButtonRoot.svelte";
export type {
  ComboboxInputValueChangeDetails,
  ComboboxOpenChangeDetails,
  ComboboxValueChangeDetails,
} from "@starwind-ui/runtime/combobox";
