/**
 * Generated by scripts/portable-runtime/generate-astro-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import RadioGroupRoot from "./RadioGroupRoot.astro";

const RadioGroup = {
  Root: RadioGroupRoot,
};

export { RadioGroup, RadioGroupRoot };

export default RadioGroup;

export type { RadioGroupValue, RadioGroupValueChangeDetails } from "@starwind-ui/runtime";
