import Avatar from "./Avatar.svelte";
import AvatarImage from "./AvatarImage.svelte";
import AvatarFallback from "./AvatarFallback.svelte";
import { avatar, avatarFallback, avatarImage } from "./variants.js";
export type { AvatarProps } from "./Avatar.svelte";
export type { AvatarImageProps } from "./AvatarImage.svelte";
export type { AvatarFallbackProps } from "./AvatarFallback.svelte";
const AvatarVariants = { avatar, avatarFallback, avatarImage };
const AvatarParts = { Root: Avatar, Image: AvatarImage, Fallback: AvatarFallback };
export { Avatar, AvatarFallback, AvatarImage, AvatarVariants };
export default AvatarParts;
