/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

// Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies.

import TooltipArrow from "./TooltipArrow.vue";
import TooltipPopup from "./TooltipPopup.vue";
import TooltipPortal from "./TooltipPortal.vue";
import TooltipPositioner from "./TooltipPositioner.vue";
import TooltipRoot from "./TooltipRoot.vue";
import TooltipTrigger from "./TooltipTrigger.vue";

const Tooltip = {
  Root: TooltipRoot,
  Trigger: TooltipTrigger,
  Portal: TooltipPortal,
  Positioner: TooltipPositioner,
  Popup: TooltipPopup,
  Arrow: TooltipArrow,
};

export { default as TooltipArrow } from "./TooltipArrow.vue";
export { default as TooltipPopup } from "./TooltipPopup.vue";
export { default as TooltipPortal } from "./TooltipPortal.vue";
export { default as TooltipPositioner } from "./TooltipPositioner.vue";
export { default as TooltipRoot } from "./TooltipRoot.vue";
export { default as TooltipTrigger } from "./TooltipTrigger.vue";
export { Tooltip };

export default Tooltip;

export type { TooltipOpenChangeDetails } from "@starwind-ui/runtime";
