<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { reportPortalPlacement, resolvePortalPlacement } from "@starwind-ui/runtime/tooltip";
import { inject, onBeforeUnmount, onMounted, ref } from "vue";
import { useVuePortalPlacement } from "../_internal/portal";
import { TooltipContext } from "./TooltipRoot.vue";

defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{ container?: string | HTMLElement; disabled?: boolean }>(),
  { disabled: false },
);
defineSlots<{ default?: () => unknown }>();
const root = inject(TooltipContext);
if (!root) throw new TypeError("TooltipPortal must be nested inside TooltipRoot.");
const owner = Symbol("TooltipPortal");
const element = ref<HTMLElement | null>(null);
const placement = useVuePortalPlacement({
  active: () => root.mounted.value,
  container: () => props.container,
  disabled: () => props.disabled,
  element,
  reference: () => root.element.value,
  runtime: { reportPortalPlacement, resolvePortalPlacement },
});
onMounted(() => root.registerPortal(owner, element.value));
onBeforeUnmount(() => root.registerPortal(owner, null));
defineExpose({ element });
</script>
<template>
  <Teleport :to="placement.target.value" :disabled="placement.disabled.value">
    <div
      ref="element"
      v-bind="$attrs"
      data-sw-tooltip-portal
      :data-container="typeof props.container === 'string' ? props.container : undefined"
      :data-disabled="props.disabled ? '' : undefined"
      :data-placement="placement.ready.value ? 'ready' : 'pending'"
      data-sw-portal-placement="framework"
      data-floating-root
      data-sw-part="portal"
    >
      <slot />
    </div>
  </Teleport>
</template>
