<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script lang="ts">
import type { InjectionKey, Ref } from "vue";

export type TooltipContextValue = {
  element: Readonly<Ref<HTMLElement | null>>;
  mounted: Readonly<Ref<boolean>>;
  registerPortal: (owner: symbol, element: HTMLElement | null) => void;
};

export const TooltipContext: InjectionKey<TooltipContextValue> = Symbol("TooltipContext");
</script>

<script setup lang="ts">
import { createTooltip, type TooltipOpenChangeDetails } from "@starwind-ui/runtime/tooltip";
import { computed, nextTick, onBeforeUnmount, onMounted, provide, ref, useAttrs, watch } from "vue";
import { useVueAsChildRuntimeOwner } from "../_internal/as-child";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    defaultOpen?: boolean;
    open?: boolean;
    closeDelay?: number;
    closeOnEscape?: boolean;
    closeOnOutsideInteract?: boolean;
    disabled?: boolean;
    disableHoverableContent?: boolean;
    openDelay?: number;
  }>(),
  {
    defaultOpen: false,
    open: undefined,
    closeDelay: 200,
    closeOnEscape: true,
    closeOnOutsideInteract: true,
    disabled: false,
    disableHoverableContent: false,
    openDelay: 200,
  },
);
const emit = defineEmits<{
  openChange: [open: boolean, detail: TooltipOpenChangeDetails];
  "update:open": [open: boolean];
}>();
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const rootRef = ref<HTMLElement | null>(null);
const mounted = ref(false);
const initialDefaultOpen = props.defaultOpen;
const uncontrolledOpen = ref(initialDefaultOpen);
const renderedOpen = computed(() => !props.disabled && (props.open ?? uncontrolledOpen.value));
let instance: ReturnType<typeof createTooltip> | undefined;
let portalOwner: symbol | undefined;
let runtimeGeneration = 0;
let disposed = false;

provide(TooltipContext, {
  element: rootRef,
  mounted,
  registerPortal(owner, element) {
    if (element) portalOwner = owner;
    else if (portalOwner === owner) portalOwner = undefined;
  },
});

defineExpose({ element: rootRef });

function handleOpenChange(nextOpen: boolean, detail: TooltipOpenChangeDetails): void {
  emit("openChange", nextOpen, detail);
  if (detail.isCanceled) return;
  if (props.open === undefined) uncontrolledOpen.value = nextOpen;
  emit("update:open", nextOpen);
}

function destroyOwnedInstance(): void {
  const owned = instance;
  if (!owned) return;
  if (instance === owned) instance = undefined;
  owned.destroy();
}

function setupRuntime(): void {
  const root = rootRef.value;
  if (!root) return;
  instance = createTooltip(root, {
    defaultOpen: renderedOpen.value,
    closeDelay: props.closeDelay,
    closeOnEscape: props.closeOnEscape,
    closeOnOutsideInteract: props.closeOnOutsideInteract,
    disabled: props.disabled,
    disableHoverableContent: props.disableHoverableContent,
    openDelay: props.openDelay,
    onOpenChange: handleOpenChange,
    ...(props.open === undefined ? {} : { open: props.open }),
  });
}

async function recreateRuntime(): Promise<void> {
  const generation = ++runtimeGeneration;
  const acceptedOpen = instance?.getOpen() ?? renderedOpen.value;
  destroyOwnedInstance();
  mounted.value = false;
  await nextTick();
  if (disposed || generation !== runtimeGeneration) return;

  if (props.open === undefined) uncontrolledOpen.value = acceptedOpen;
  setupRuntime();
  mounted.value = true;
}

useVueAsChildRuntimeOwner(rootRef, recreateRuntime);
onMounted(() => {
  disposed = false;
  setupRuntime();
  mounted.value = true;
});

watch(
  () => props.open,
  (open) => {
    if (open === undefined || !instance || Object.is(instance.getOpen(), open)) return;
    instance.setOpen(open, { emit: false });
  },
  { flush: "post" },
);
watch(
  [
    () => props.closeDelay,
    () => props.closeOnEscape,
    () => props.closeOnOutsideInteract,
    () => props.disableHoverableContent,
    () => props.openDelay,
  ],
  () => {
    void recreateRuntime();
  },
  { flush: "post" },
);

watch(
  () => props.disabled,
  (disabled) => {
    instance?.setDisabled(disabled);
    if (disabled && props.open === undefined) uncontrolledOpen.value = false;
  },
  { flush: "post" },
);

onBeforeUnmount(() => {
  disposed = true;
  runtimeGeneration += 1;
  mounted.value = false;
  portalOwner = undefined;
  destroyOwnedInstance();
});
</script>

<template>
  <div
    ref="rootRef"
    v-bind="attrs"
    data-sw-tooltip
    data-sw-part="root"
    :data-default-open="initialDefaultOpen ? 'true' : undefined"
    :data-close-delay="props.closeDelay"
    :data-close-on-escape="props.closeOnEscape ? 'true' : 'false'"
    :data-close-on-outside-interact="props.closeOnOutsideInteract ? 'true' : 'false'"
    :data-content-hoverable="props.disableHoverableContent ? 'false' : 'true'"
    :data-disabled="props.disabled ? '' : undefined"
    :data-open-delay="props.openDelay"
    :data-state="renderedOpen ? 'open' : 'closed'"
  >
    <slot />
  </div>
</template>
