<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { ref, useAttrs } from "vue";

defineOptions({ inheritAttrs: false });

type Variant = "default" | "error" | "info" | "loading" | "success" | "warning";

const props = withDefaults(defineProps<{ variant?: Variant }>(), {
  variant: "default",
});
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const rootRef = ref<HTMLDivElement | null>(null);

defineExpose({ element: rootRef });
</script>

<template>
  <div
    ref="rootRef"
    v-bind="attrs"
    data-sw-toast-root
    data-state="open"
    :data-variant="props.variant"
    role="dialog"
    aria-modal="false"
  >
    <slot />
  </div>
</template>
