/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import { getContext } from "svelte";
export type SidebarContextValue = Readonly<{
  open: boolean;
  mobileOpen: boolean;
  state: "collapsed" | "expanded";
  expanded: boolean;
  isMobile: boolean;
  /** Accept a Sheet binding output through the Provider's silent public setter. */
  setMobileOpen(open: boolean): void;
}>;
export const SidebarContext: symbol = Symbol("StarwindSidebarContext");
export function useSidebarContext(): SidebarContextValue {
  const context = getContext<SidebarContextValue | undefined>(SidebarContext);
  if (!context) throw new Error("Sidebar parts must be used within SidebarProvider.");
  return context;
}
