<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { HTMLAttributes, HTMLButtonAttributes } from "svelte/elements";
  import { useSidebarContext } from "./SidebarContext.js";
  type Props = Omit<HTMLButtonAttributes, "children"> & { children?: Snippet; ref?: (element: HTMLButtonElement|null)=>void;  };
  let { children, ref,  ...rest }:Props=$props();
  const context=useSidebarContext();
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLButtonElement>(() => ref);
</script>
<button {...rest} data-sw-sidebar-rail={''} data-sw-part={"rail"} data-state={context.state} aria-expanded={context.expanded} type={'button'} tabindex={-1} {@attach attachRef}>{@render children?.()}</button>
