<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { setAccordionItemContext, type AccordionItemContextValue } from "./AccordionItemContext";

  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    children?: Snippet;
    value?: string;
    disabled?: boolean;
    ref?: (element: HTMLDivElement | null) => void;
  };
  let { children, value, disabled = false, ref, ...rest }: Props = $props();
  const context: AccordionItemContextValue = {
    get disabled() { return disabled; },
  };
  setAccordionItemContext(context);
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>

<div
  {...rest}
  data-sw-accordion-item=""
  data-sw-part="item"
  data-value={value}
  data-disabled={disabled ? "" : undefined}
  data-state="closed"
  {@attach attachRef}
>
  {@render children?.()}
</div>
