<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";

  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & { children?: Snippet;  ref?: (element: HTMLDivElement | null) => void };
  let { children, ref, ...rest }: Props = $props();
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>

<div
  {...rest}
  data-sw-drawer-viewport=""
  data-sw-part="viewport"
  {@attach attachRef}
>
  {@render children?.()}
</div>
