/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

// Svelte 5 public beta adapter output.

import DrawerBackdrop from "./DrawerBackdrop.svelte";
import DrawerClose from "./DrawerClose.svelte";
import DrawerDescription from "./DrawerDescription.svelte";
import DrawerPopup from "./DrawerPopup.svelte";
import DrawerPortal from "./DrawerPortal.svelte";
import DrawerRoot from "./DrawerRoot.svelte";
import DrawerTitle from "./DrawerTitle.svelte";
import DrawerTrigger from "./DrawerTrigger.svelte";
import DrawerViewport from "./DrawerViewport.svelte";

const Drawer = {
  Root: DrawerRoot,
  Trigger: DrawerTrigger,
  Portal: DrawerPortal,
  Backdrop: DrawerBackdrop,
  Viewport: DrawerViewport,
  Popup: DrawerPopup,
  Title: DrawerTitle,
  Description: DrawerDescription,
  Close: DrawerClose,
};

export {
  Drawer,
  DrawerBackdrop,
  DrawerClose,
  DrawerDescription,
  DrawerPopup,
  DrawerPortal,
  DrawerRoot,
  DrawerTitle,
  DrawerTrigger,
  DrawerViewport,
};

export default Drawer;
export type { ButtonChildProps, ButtonChildPayload } from "../button/ButtonRoot.svelte";

export type { DrawerCloseCompleteDetails, DrawerOpenChangeDetails } from "@starwind-ui/runtime";
