<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { defineComponent, type HTMLAttributes, inject, useAttrs, type VNode } from "vue";
import { useVueNativeControl } from "../_internal/native-control";
import { AlertDialogContext } from "./AlertDialogRoot.vue";

defineOptions({ inheritAttrs: false });

type NativeElementProps = /* @vue-ignore */ HTMLAttributes;
const props = withDefaults(
  defineProps<{ asChild?: boolean; targetId?: string } & NativeElementProps>(),
  { asChild: false },
);
const slots = defineSlots<{ default?: () => VNode[] }>();
const attrs = useAttrs();
const root = inject(AlertDialogContext, undefined);
const {
  element,
  render: renderAsChild,
  setElement,
} = useVueNativeControl("AlertDialogTrigger", () => root?.requestRefresh(), true);
const AsChildControl = defineComponent({
  inheritAttrs: false,
  setup() {
    return () =>
      renderAsChild({
        children: slots.default?.() ?? [],
        consumerProps: attrs,
        defaultNativeButtonType: "button",
        protectedProps: {
          "data-sw-alert-dialog-trigger": "",
          "data-sw-part": "trigger",
          "aria-haspopup": "dialog",
          "data-sw-alert-dialog-target-id": props.targetId,
          "data-state": "closed",
        },
      });
  },
});

defineExpose({ element });
</script>

<template>
  <AsChildControl v-if="props.asChild" />
  <button
    :ref="setElement"
    v-else
    v-bind="$attrs"
    data-sw-alert-dialog-trigger
    data-sw-part="trigger"
    type="button"
    aria-haspopup="dialog"
    :data-sw-alert-dialog-target-id="props.targetId"
    data-state="closed"
  >
    <slot />
  </button>
</template>
