<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { type HTMLAttributes, ref } from "vue";

defineOptions({ inheritAttrs: false });

type NativeElementProps = /* @vue-ignore */ HTMLAttributes;
defineProps<NativeElementProps>();
defineSlots<{ default?: () => unknown }>();
const element = ref<HTMLDialogElement | null>(null);

defineExpose({ element });
</script>

<template>
  <dialog
    ref="element"
    v-bind="$attrs"
    data-sw-alert-dialog-popup
    data-sw-part="popup"
    role="alertdialog"
    data-state="closed"
  >
    <slot />
  </dialog>
</template>
