/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import {
  createInput,
  type InputValue,
  type InputValueChangeDetails,
} from "@starwind-ui/runtime/input";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export type InputRootProps = Omit<
  React.InputHTMLAttributes<HTMLInputElement>,
  "defaultValue" | "value"
> & {
  defaultValue?: InputValue;
  onValueChange?: (value: string, details: InputValueChangeDetails) => void;
  value?: InputValue;
};

const InputRoot = React.forwardRef<HTMLInputElement, InputRootProps>(function InputRoot(
  { defaultValue, disabled = false, onChange, onValueChange, readOnly, value, ...props },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLInputElement>(null);
  const instanceRef = React.useRef<ReturnType<typeof createInput> | undefined>(undefined);
  const valueRef = React.useRef(value);
  const onValueChangeRef = React.useRef(onValueChange);
  const valueChangeDetailsRef = React.useRef<InputValueChangeDetails | undefined>(undefined);
  const controlledSyncTimerRef = React.useRef<number | undefined>(undefined);
  const defaultValueRef = React.useRef(defaultValue);

  useIsomorphicLayoutEffect(() => {
    valueRef.current = value;
  }, [value]);

  useIsomorphicLayoutEffect(() => {
    onValueChangeRef.current = onValueChange;
  }, [onValueChange]);

  const composedRef = React.useCallback(
    (node: HTMLInputElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  useIsomorphicLayoutEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const instance = createInput(root, {
      defaultValue: defaultValueRef.current,
      disabled,
      onValueChange: (_nextValue, details) => {
        valueChangeDetailsRef.current = details;
      },
      ...(valueRef.current !== undefined ? { value: valueRef.current } : {}),
    });
    instanceRef.current = instance;

    return () => {
      if (controlledSyncTimerRef.current !== undefined) {
        window.clearTimeout(controlledSyncTimerRef.current);
        controlledSyncTimerRef.current = undefined;
      }
      instance.destroy();
      if (instanceRef.current === instance) {
        instanceRef.current = undefined;
      }
    };
  }, []);

  useIsomorphicLayoutEffect(() => {
    if (value === undefined) return;
    const instance = instanceRef.current;
    if (!instance) return;
    if (instance.getValue() === String(value)) return;

    instance.setValue(value, { emit: false });
  }, [value]);

  useIsomorphicLayoutEffect(() => {
    const instance = instanceRef.current;
    if (!instance) return;

    instance.setDisabled(disabled);
  }, [disabled]);

  const scheduleControlledSync = React.useCallback(() => {
    if (valueRef.current === undefined) return;

    if (controlledSyncTimerRef.current !== undefined) {
      window.clearTimeout(controlledSyncTimerRef.current);
    }

    controlledSyncTimerRef.current = window.setTimeout(() => {
      controlledSyncTimerRef.current = undefined;
      const root = rootRef.current;
      const instance = instanceRef.current;
      if (!root || !instance) return;

      instance.setValue(root.value, { emit: false });
    }, 0);
  }, []);

  const handleChange = React.useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      const nextValue = event.currentTarget.value;
      const details = valueChangeDetailsRef.current;

      onChange?.(event);

      if (details?.value === nextValue) {
        valueChangeDetailsRef.current = undefined;
        onValueChangeRef.current?.(nextValue, details);
      }
      scheduleControlledSync();
    },
    [onChange, scheduleControlledSync],
  );
  const valueProps = value !== undefined ? { value } : { defaultValue: defaultValueRef.current };

  return (
    <input
      data-sw-input
      data-disabled={disabled ? "" : undefined}
      disabled={disabled}
      onChange={handleChange}
      readOnly={readOnly}
      ref={composedRef}
      {...valueProps}
      {...props}
    />
  );
});

InputRoot.displayName = "Input.Root";

export default InputRoot;
