/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

// Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies.

import SelectGroup from "./SelectGroup.vue";
import SelectGroupLabel from "./SelectGroupLabel.vue";
import SelectIcon from "./SelectIcon.vue";
import SelectItem from "./SelectItem.vue";
import SelectItemIndicator from "./SelectItemIndicator.vue";
import SelectItemText from "./SelectItemText.vue";
import SelectLabel from "./SelectLabel.vue";
import SelectList from "./SelectList.vue";
import SelectPopup from "./SelectPopup.vue";
import SelectPortal from "./SelectPortal.vue";
import SelectPositioner from "./SelectPositioner.vue";
import SelectRoot from "./SelectRoot.vue";
import SelectScrollDownArrow from "./SelectScrollDownArrow.vue";
import SelectScrollUpArrow from "./SelectScrollUpArrow.vue";
import SelectSeparator from "./SelectSeparator.vue";
import SelectTrigger from "./SelectTrigger.vue";
import SelectValue from "./SelectValue.vue";

export type { SelectContextValue, SelectItemContextValue } from "./SelectRoot.vue";
export {
  SelectContext,
  SelectItemContext,
  useSelectContext,
  useSelectItemContext,
} from "./SelectRoot.vue";

const Select = {
  Root: SelectRoot,
  Label: SelectLabel,
  Trigger: SelectTrigger,
  Value: SelectValue,
  Icon: SelectIcon,
  Portal: SelectPortal,
  Positioner: SelectPositioner,
  Popup: SelectPopup,
  List: SelectList,
  Group: SelectGroup,
  GroupLabel: SelectGroupLabel,
  Item: SelectItem,
  ItemText: SelectItemText,
  ItemIndicator: SelectItemIndicator,
  Separator: SelectSeparator,
  ScrollUpArrow: SelectScrollUpArrow,
  ScrollDownArrow: SelectScrollDownArrow,
};

export { default as SelectGroup } from "./SelectGroup.vue";
export { default as SelectGroupLabel } from "./SelectGroupLabel.vue";
export { default as SelectIcon } from "./SelectIcon.vue";
export { default as SelectItem } from "./SelectItem.vue";
export { default as SelectItemIndicator } from "./SelectItemIndicator.vue";
export { default as SelectItemText } from "./SelectItemText.vue";
export { default as SelectLabel } from "./SelectLabel.vue";
export { default as SelectList } from "./SelectList.vue";
export { default as SelectPopup } from "./SelectPopup.vue";
export { default as SelectPortal } from "./SelectPortal.vue";
export { default as SelectPositioner } from "./SelectPositioner.vue";
export { default as SelectRoot } from "./SelectRoot.vue";
export { default as SelectScrollDownArrow } from "./SelectScrollDownArrow.vue";
export { default as SelectScrollUpArrow } from "./SelectScrollUpArrow.vue";
export { default as SelectSeparator } from "./SelectSeparator.vue";
export { default as SelectTrigger } from "./SelectTrigger.vue";
export { default as SelectValue } from "./SelectValue.vue";
export { Select };

export default Select;

export type { SelectOpenChangeDetails, SelectValueChangeDetails } from "@starwind-ui/runtime";
