<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();
const elementRef = ref<HTMLDivElement | null>(null);
defineExpose({ element: elementRef });
</script>

<template>
  <div ref="elementRef" v-bind="$attrs" data-sw-select-group-label data-sw-part="groupLabel">
    <slot />
  </div>
</template>
