<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { ref, useAttrs } from "vue";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const elementRef = ref<HTMLDivElement | null>(null);
defineExpose({ element: elementRef });
</script>

<template>
  <div ref="elementRef" v-bind="attrs" data-sw-select-group data-sw-part="group" role="group">
    <slot />
  </div>
</template>
