<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";
import { useSelectContext } from "./SelectRoot.vue";

defineOptions({ inheritAttrs: false });
const props = defineProps<{ placeholder?: string }>();
defineSlots<{ default?: (props: { label: string | null; value: string | null }) => unknown }>();
const valueRef = ref<HTMLSpanElement | null>(null);
const select = useSelectContext("Value");
defineExpose({ element: valueRef });
</script>

<template>
  <span
    ref="valueRef"
    v-bind="$attrs"
    data-sw-select-value
    data-sw-part="value"
    :data-placeholder="props.placeholder"
  >
    <slot :label="select.selectedLabel.value" :value="select.value.value">{{
      select.selectedLabel.value ?? props.placeholder
    }}</slot>
  </span>
</template>
