<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script lang="ts">
import { type ComputedRef, type InjectionKey, inject, type Ref } from "vue";

export type SelectContextValue = Readonly<{
  disabled: ComputedRef<boolean>;
  mounted: Readonly<Ref<boolean>>;
  open: ComputedRef<boolean>;
  readOnly: ComputedRef<boolean>;
  registerPortal(owner: symbol, element: HTMLElement | null): void;
  required: ComputedRef<boolean>;
  selectedLabel: ComputedRef<string | null>;
  value: ComputedRef<string | null>;
}>;

export type SelectItemContextValue = Readonly<{
  disabled: ComputedRef<boolean>;
  value: ComputedRef<string>;
}>;

export const SelectContext: InjectionKey<SelectContextValue> = Symbol("StarwindSelectContext");
export const SelectItemContext: InjectionKey<SelectItemContextValue> = Symbol(
  "StarwindSelectItemContext",
);

export function useSelectContext(part = "part"): SelectContextValue {
  const value = inject(SelectContext);
  if (!value) throw new Error(`Select.${part} requires an owning Select.Root.`);
  return value;
}

export function useSelectItemContext(part = "part"): SelectItemContextValue {
  const value = inject(SelectItemContext);
  if (!value) throw new Error(`Select.${part} requires an owning Select.Item.`);
  return value;
}
</script>
<script setup lang="ts">
import {
  createSelect,
  type SelectOpenChangeDetails,
  type SelectValueChangeDetails,
} from "@starwind-ui/runtime/select";
import { computed, nextTick, onBeforeUnmount, onMounted, provide, ref, useAttrs, watch } from "vue";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();

const props = withDefaults(
  defineProps<{
    autoComplete?: string;
    defaultOpen?: boolean;
    defaultValue?: string | null;
    disabled?: boolean;
    form?: string;
    highlightItemOnHover?: boolean;
    modal?: boolean;
    name?: string;
    open?: boolean;
    readOnly?: boolean;
    required?: boolean;
    modelValue?: string | null;
  }>(),
  {
    defaultOpen: false,
    defaultValue: null,
    disabled: false,
    highlightItemOnHover: true,
    modal: true,
    open: undefined,
    readOnly: false,
    required: false,
    modelValue: undefined,
  },
);
const emit = defineEmits<{
  "update:modelValue": [value: string | null];
  "update:open": [open: boolean];
  openChange: [open: boolean, detail: SelectOpenChangeDetails];
  valueChange: [value: string | null, detail: SelectValueChangeDetails];
}>();
const attrs = useAttrs();
const rootRef = ref<HTMLDivElement | null>(null);
const inputRef = ref<HTMLInputElement | null>(null);
const mounted = ref(false);
const initialDefaultOpen = props.defaultOpen;
const initialDefaultValue = props.defaultValue;
const uncontrolledOpen = ref(props.disabled ? false : initialDefaultOpen);
const uncontrolledValue = ref<string | null>(initialDefaultValue);
const selectedLabelState = ref<{ label: string | null; value: string | null }>({
  label: null,
  value: null,
});
const renderedOpen = computed(() =>
  props.disabled ? false : (props.open ?? uncontrolledOpen.value),
);
const renderedValue = computed(() =>
  props.modelValue !== undefined ? props.modelValue : uncontrolledValue.value,
);
const selectedLabel = computed(() =>
  selectedLabelState.value.value === renderedValue.value ? selectedLabelState.value.label : null,
);
const disabled = computed(() => props.disabled);
const readOnly = computed(() => props.readOnly);
const required = computed(() => props.required);
let instance: ReturnType<typeof createSelect> | undefined;
let portalOwner: symbol | undefined;
let portalReference: HTMLElement | null = null;
let resetForm: HTMLFormElement | null = null;
let resetTimer: number | undefined;
let lifecycleGeneration = 0;

provide(SelectContext, {
  disabled,
  mounted,
  open: renderedOpen,
  readOnly,
  registerPortal(owner, element) {
    if (element) {
      portalOwner = owner;
      portalReference = element;
    } else if (portalOwner === owner) {
      portalOwner = undefined;
      portalReference = null;
    }
  },
  required,
  selectedLabel,
  value: renderedValue,
});

defineExpose({
  element: rootRef,
  close: () => instance?.close(),
  open: () => {
    if (!props.disabled) instance?.open();
  },
  updatePosition: () => instance?.updatePosition(),
});

function readItemLabel(item: HTMLElement | undefined): string | null {
  if (!item) return null;
  const textElement = item.querySelector<HTMLElement>("[data-sw-select-item-text]");
  const text = (textElement ?? item).textContent?.trim() ?? "";
  return text.length > 0 ? text : null;
}

function findSelectedLabel(value: string | null): string | null {
  if (value === null || !rootRef.value) return null;
  const roots = [rootRef.value, portalReference].filter(
    (candidate): candidate is HTMLElement => candidate instanceof HTMLElement,
  );
  const item = roots
    .flatMap((candidate) => [...candidate.querySelectorAll<HTMLElement>("[data-sw-select-item]")])
    .find((candidate) => candidate.getAttribute("data-value") === value);
  return readItemLabel(item);
}

function syncSelectedLabel(value: string | null, item?: HTMLElement): void {
  selectedLabelState.value = { label: readItemLabel(item) ?? findSelectedLabel(value), value };
}

function handleOpenChange(open: boolean, detail: SelectOpenChangeDetails): void {
  emit("openChange", open, detail);
  if (detail.isCanceled) return;
  if (props.open === undefined) uncontrolledOpen.value = open;
  emit("update:open", open);
}

function handleValueChange(value: string | null, detail: SelectValueChangeDetails): void {
  emit("valueChange", value, detail);
  if (detail.isCanceled) return;
  syncSelectedLabel(value, detail.item);
  if (props.modelValue === undefined) uncontrolledValue.value = value;
  emit("update:modelValue", value);
}

function unbindFormReset(): void {
  if (resetTimer !== undefined) window.clearTimeout(resetTimer);
  resetTimer = undefined;
  resetForm?.removeEventListener("reset", handleFormReset);
  resetForm = null;
}

function handleFormReset(): void {
  if (resetTimer !== undefined) window.clearTimeout(resetTimer);
  resetTimer = window.setTimeout(() => {
    resetTimer = undefined;
    if (!instance) return;
    if (props.modelValue !== undefined) {
      instance.setValue(props.modelValue, { emit: false });
      return;
    }
    uncontrolledValue.value = instance.getValue();
    syncSelectedLabel(uncontrolledValue.value);
  }, 0);
}

function bindFormReset(): void {
  const nextForm = inputRef.value?.form ?? null;
  if (resetForm === nextForm) return;
  unbindFormReset();
  resetForm = nextForm;
  resetForm?.addEventListener("reset", handleFormReset);
}

function destroyOwnedInstance(): void {
  unbindFormReset();
  const ownedInstance = instance;
  instance = undefined;
  ownedInstance?.destroy();
}

function setupRuntime(): void {
  destroyOwnedInstance();
  const element = rootRef.value;
  if (!element) return;
  instance = createSelect(element, {
    autoComplete: props.autoComplete,
    defaultOpen: props.disabled ? false : uncontrolledOpen.value,
    defaultValue: uncontrolledValue.value,
    disabled: props.disabled,
    form: props.form,
    highlightItemOnHover: props.highlightItemOnHover,
    modal: props.modal,
    name: props.name,
    onOpenChange: handleOpenChange,
    onValueChange: handleValueChange,
    portalReference: portalReference ?? undefined,
    readOnly: props.readOnly,
    required: props.required,
    ...(props.open === undefined ? {} : { open: props.disabled ? false : props.open }),
    ...(props.modelValue === undefined ? {} : { value: props.modelValue }),
  });
  syncSelectedLabel(instance.getValue());
  bindFormReset();
}

async function recreateRuntimeAfterControllednessChange(): Promise<void> {
  const generation = ++lifecycleGeneration;
  mounted.value = false;
  await nextTick();
  if (generation !== lifecycleGeneration || !rootRef.value) return;
  setupRuntime();
  mounted.value = true;
}

onMounted(() => {
  setupRuntime();
  mounted.value = true;
});

watch(
  () => props.open,
  (open, previousOpen) => {
    if ((open === undefined) !== (previousOpen === undefined)) {
      if (open === undefined && instance) uncontrolledOpen.value = instance.getOpen();
      void recreateRuntimeAfterControllednessChange();
      return;
    }
    if (open === undefined || props.disabled || !instance || Object.is(instance.getOpen(), open))
      return;
    instance.setOpen(open, { emit: false });
  },
  { flush: "post" },
);
watch(
  () => props.modelValue,
  async (value, previousValue) => {
    if ((value === undefined) !== (previousValue === undefined)) {
      if (value === undefined && instance) uncontrolledValue.value = instance.getValue();
      void recreateRuntimeAfterControllednessChange();
      return;
    }
    if (value === undefined || !instance || Object.is(instance.getValue(), value)) return;
    instance.setValue(value, { emit: false });
    await nextTick();
    syncSelectedLabel(value);
  },
  { flush: "post" },
);
watch(
  () => props.disabled,
  (value) => {
    if (!instance) return;
    instance.setDisabled(value);
    if (value) {
      if (props.open === undefined) uncontrolledOpen.value = false;
      return;
    }

    const nextOpen = props.open ?? uncontrolledOpen.value;
    if (!Object.is(instance.getOpen(), nextOpen)) {
      instance.setOpen(nextOpen, { emit: false });
    }
  },
);
watch(
  () => props.readOnly,
  (value) => instance?.setReadOnly(value),
);
watch(
  () => props.modal,
  (value) => instance?.setModal(value),
);
watch(
  () => props.highlightItemOnHover,
  (value) => instance?.setHighlightItemOnHover(value),
);
watch(
  () => [props.autoComplete, props.form, props.name, props.required] as const,
  ([autoComplete, form, name, required]) => {
    instance?.setFormOptions({ autoComplete, form, name, required });
    bindFormReset();
  },
  { flush: "post" },
);

onBeforeUnmount(() => {
  lifecycleGeneration += 1;
  mounted.value = false;
  destroyOwnedInstance();
});
</script>

<template>
  <div
    ref="rootRef"
    v-bind="attrs"
    data-sw-select
    data-sw-part="root"
    :data-autocomplete="props.autoComplete"
    :data-default-open="initialDefaultOpen ? 'true' : undefined"
    :data-default-value="initialDefaultValue ?? undefined"
    :data-disabled="props.disabled ? '' : undefined"
    :data-form="props.form"
    :data-highlight-item-on-hover="props.highlightItemOnHover ? 'true' : 'false'"
    :data-modal="props.modal ? 'true' : 'false'"
    :data-name="props.name"
    :data-readonly="props.readOnly ? '' : undefined"
    :data-required="props.required ? '' : undefined"
    :data-state="renderedOpen ? 'open' : 'closed'"
    :data-value="renderedValue ?? undefined"
    :data-placeholder="renderedValue === null ? '' : undefined"
    :data-selected-value="
      selectedLabel !== null && renderedValue !== null ? renderedValue : undefined
    "
    :data-selected-label="selectedLabel ?? undefined"
  >
    <input
      ref="inputRef"
      data-sw-select-input
      data-sw-part="input"
      type="hidden"
      :autocomplete="props.autoComplete"
      :disabled="props.disabled"
      :form="props.form"
      :name="props.name"
      :required="props.required"
      aria-hidden="true"
      tabindex="-1"
    />
    <slot />
  </div>
</template>
