<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, useAttrs } from "vue";
import { useSelectContext } from "./SelectRoot.vue";

defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{ container?: string | HTMLElement; disabled?: boolean }>(),
  {
    container: "body",
    disabled: false,
  },
);
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const portalRef = ref<HTMLDivElement | null>(null);
const select = useSelectContext("Portal");
const owner = Symbol("SelectPortalOwner");
onMounted(() => select.registerPortal(owner, portalRef.value));
onBeforeUnmount(() => select.registerPortal(owner, null));
defineExpose({ element: portalRef });
</script>

<template>
  <Teleport :to="props.container" :disabled="props.disabled || !select.mounted.value">
    <div
      ref="portalRef"
      v-bind="attrs"
      data-sw-select-portal
      data-sw-part="portal"
      data-floating-root
    >
      <slot />
    </div>
  </Teleport>
</template>
