packages:
  - packages/*
  - apps/*
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - sharp
allowBuilds:
  esbuild: true
  sharp: true
peerDependencyRules:
  allowAny:
    - "astro"
    - "vite"

resolutionMode: highest

# 2 day minimum release age
minimumReleaseAge: 2880
minimumReleaseAgeStrict: true

# allow starwind related packages and others I created
minimumReleaseAgeExclude:
  - "starwind"
  - "@starwind-ui/*"
  # below packages are missing the "time" field
  - "@tailwindcss/oxide"
  - "@astrojs/markdown-remark"
  - js-yaml@4.3.0
  - svgo@4.0.2
  - fast-uri@3.1.4
  - sharp@0.35.0

overrides:
  fast-uri@>=3.0.0 <=3.1.3: ^3.1.4
  js-yaml@>=4.0.0 <4.3.0: ^4.3.0
  sharp@<0.35.0: ^0.35.0
  svgo@>=4.0.0 <4.0.2: ^4.0.2
