/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import SliderControl from "./SliderControl";
import SliderIndicator from "./SliderIndicator";
import SliderLabel from "./SliderLabel";
import SliderRoot from "./SliderRoot";
import SliderThumb from "./SliderThumb";
import SliderTrack from "./SliderTrack";

const Slider = {
  Root: SliderRoot,
  Control: SliderControl,
  Track: SliderTrack,
  Indicator: SliderIndicator,
  Label: SliderLabel,
  Thumb: SliderThumb,
};

export {
  Slider,
  SliderControl,
  SliderIndicator,
  SliderLabel,
  SliderRoot,
  SliderThumb,
  SliderTrack,
};

export default Slider;

export type {
  SliderValue,
  SliderValueChangeDetails,
  SliderValueCommitDetails,
} from "@starwind-ui/runtime";
