/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type SliderControlProps = React.HTMLAttributes<HTMLDivElement>;

const SliderControl = React.forwardRef<HTMLDivElement, SliderControlProps>(
  function SliderControl(props, forwardedRef) {
    return <div data-sw-slider-control ref={forwardedRef} {...props} />;
  },
);

SliderControl.displayName = "Slider.Control";

export default SliderControl;
