/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import {
  createSlider,
  type SliderOrientation,
  type SliderValue,
  type SliderValueChangeDetails,
  type SliderValueCommitDetails,
} from "@starwind-ui/runtime/slider";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export type SliderRootProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  "defaultValue" | "onChange"
> & {
  defaultValue?: SliderValue;
  disabled?: boolean;
  form?: string;
  largeStep?: number;
  max?: number;
  min?: number;
  minStepsBetweenValues?: number;
  name?: string;
  onValueChange?: (value: SliderValue, details: SliderValueChangeDetails) => void;
  onValueCommitted?: (value: SliderValue, details: SliderValueCommitDetails) => void;
  orientation?: SliderOrientation;
  step?: number;
  /**
   * Controlled value. Slider controlledness is fixed when the Runtime is created; do not switch between controlled and uncontrolled after mount.
   */
  value?: SliderValue;
};

const SliderRoot = React.forwardRef<HTMLDivElement, SliderRootProps>(function SliderRoot(
  {
    defaultValue = 0,
    disabled = false,
    form,
    largeStep = 10,
    max = 100,
    min = 0,
    minStepsBetweenValues = 0,
    name,
    onValueChange,
    onValueCommitted,
    orientation = "horizontal",
    step = 1,
    value,
    ...props
  },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const instanceRef = React.useRef<ReturnType<typeof createSlider> | undefined>(undefined);
  const defaultValueRef = React.useRef(defaultValue);
  const disabledRef = React.useRef(disabled);
  const formRef = React.useRef(form);
  const largeStepRef = React.useRef(largeStep);
  const maxRef = React.useRef(max);
  const minRef = React.useRef(min);
  const minStepsBetweenValuesRef = React.useRef(minStepsBetweenValues);
  const nameRef = React.useRef(name);
  const onValueChangeRef = React.useRef(onValueChange);
  const onValueCommittedRef = React.useRef(onValueCommitted);
  const orientationRef = React.useRef(orientation);
  const stepRef = React.useRef(step);
  const valueRef = React.useRef(value);
  const [uncontrolledValue, setUncontrolledValue] = React.useState<SliderValue>(
    () => defaultValueRef.current,
  );
  const uncontrolledValueRef = React.useRef(uncontrolledValue);

  useIsomorphicLayoutEffect(() => {
    disabledRef.current = disabled;
  }, [disabled]);

  useIsomorphicLayoutEffect(() => {
    onValueChangeRef.current = onValueChange;
  }, [onValueChange]);

  useIsomorphicLayoutEffect(() => {
    onValueCommittedRef.current = onValueCommitted;
  }, [onValueCommitted]);

  useIsomorphicLayoutEffect(() => {
    valueRef.current = value;
  }, [value]);

  const composedRef = React.useCallback(
    (node: HTMLDivElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  useIsomorphicLayoutEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const instance = createSlider(root, {
      defaultValue: defaultValueRef.current,
      disabled: disabledRef.current,
      form: formRef.current,
      largeStep: largeStepRef.current,
      max: maxRef.current,
      min: minRef.current,
      minStepsBetweenValues: minStepsBetweenValuesRef.current,
      name: nameRef.current,
      orientation: orientationRef.current,
      step: stepRef.current,
      ...(valueRef.current !== undefined ? { value: valueRef.current } : {}),
    });
    instanceRef.current = instance;
    const unsubscribeChange = instance.subscribe("valueChange", (details) => {
      onValueChangeRef.current?.(details.value, details);
      if (details.isCanceled) return;

      if (valueRef.current === undefined) {
        uncontrolledValueRef.current = details.value;
        setUncontrolledValue(details.value);
      }
    });
    const unsubscribeCommitted = instance.subscribe("valueCommitted", (details) => {
      onValueCommittedRef.current?.(details.value, details);
    });

    return () => {
      unsubscribeChange();
      unsubscribeCommitted();
      instance.destroy();
      if (instanceRef.current === instance) {
        instanceRef.current = undefined;
      }
    };
  }, []);

  useIsomorphicLayoutEffect(() => {
    const instance = instanceRef.current;
    if (!instance) return;

    instance.setDisabled(disabled);
  }, [disabled]);

  useIsomorphicLayoutEffect(() => {
    nameRef.current = name;
    const instance = instanceRef.current;
    if (!instance) return;

    instance.setName(name);
  }, [name]);

  useIsomorphicLayoutEffect(() => {
    const instance = instanceRef.current;
    if (!instance) return;

    instance.setOptions({
      form,
      largeStep,
      max,
      min,
      minStepsBetweenValues,
      orientation,
      step,
    });

    if (valueRef.current === undefined) {
      const nextUncontrolledValue = instance.getValue();
      if (!areSliderValuesEqual(uncontrolledValueRef.current, nextUncontrolledValue)) {
        uncontrolledValueRef.current = nextUncontrolledValue;
        setUncontrolledValue(nextUncontrolledValue);
      }
    }
  }, [form, largeStep, max, min, minStepsBetweenValues, orientation, step]);

  useIsomorphicLayoutEffect(() => {
    if (value === undefined) return;
    const instance = instanceRef.current;
    if (!instance) return;
    instance.refresh();
    if (areSliderValuesEqual(instance.getValue(), value)) return;

    instance.setValue(value, { emit: false });
  }, [value]);

  const renderedValue = value ?? uncontrolledValue;
  const valueAttribute = serializeSliderValue(renderedValue);
  const defaultValueAttribute = serializeSliderValue(defaultValueRef.current);

  return (
    <div
      {...props}
      data-sw-slider
      data-default-value={defaultValueAttribute}
      data-disabled={disabled ? "" : undefined}
      data-form={form}
      data-large-step={largeStep}
      data-max={max}
      data-min={min}
      data-min-steps-between-values={minStepsBetweenValues}
      data-name={name}
      data-orientation={orientation}
      data-step={step}
      data-value={valueAttribute}
      ref={composedRef}
      role="group"
    />
  );
});

SliderRoot.displayName = "Slider.Root";

export default SliderRoot;

function areSliderValuesEqual(left: SliderValue, right: SliderValue): boolean {
  const leftValues = Array.isArray(left) ? left : [left];
  const rightValues = Array.isArray(right) ? right : [right];

  return (
    leftValues.length === rightValues.length &&
    leftValues.every((item, index) => item === rightValues[index])
  );
}

function serializeSliderValue(value: SliderValue): string {
  return Array.isArray(value) ? JSON.stringify(value) : String(value);
}
