/**
 * Generated by scripts/portable-runtime/generate-astro-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import FieldsetLegend from "./FieldsetLegend.astro";
import FieldsetRoot from "./FieldsetRoot.astro";

const Fieldset = {
  Legend: FieldsetLegend,
  Root: FieldsetRoot,
};

export { Fieldset, FieldsetLegend, FieldsetRoot };

export default Fieldset;
