/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import ScrollAreaRoot from "./ScrollAreaRoot.svelte";
import ScrollAreaViewport from "./ScrollAreaViewport.svelte";
import ScrollAreaContent from "./ScrollAreaContent.svelte";
import ScrollAreaScrollbar from "./ScrollAreaScrollbar.svelte";
import ScrollAreaThumb from "./ScrollAreaThumb.svelte";
import ScrollAreaCorner from "./ScrollAreaCorner.svelte";
const ScrollArea = {
  Root: ScrollAreaRoot,
  Viewport: ScrollAreaViewport,
  Content: ScrollAreaContent,
  Scrollbar: ScrollAreaScrollbar,
  Thumb: ScrollAreaThumb,
  Corner: ScrollAreaCorner,
};
export {
  ScrollArea,
  ScrollAreaRoot,
  ScrollAreaViewport,
  ScrollAreaContent,
  ScrollAreaScrollbar,
  ScrollAreaThumb,
  ScrollAreaCorner,
};
export type { ScrollAreaOverflowEdgeThreshold } from "./ScrollAreaRoot.svelte";
export default ScrollArea;
