<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  type Props = HTMLAttributes<HTMLDivElement> & { children?: Snippet; ref?: (element: HTMLDivElement | null) => void;  };
  let { children, ref, style, tabindex, ...rest }: Props = $props();
  let viewportStyle = $derived((style ?? "") + ";overflow:scroll!important");
  const initialTabIndex = untrack(() => tabindex ?? -1);

  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>
<!-- Runtime updates viewport focusability from measured overflow. -->
<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
<div {...rest} data-sw-scroll-area-viewport role="presentation" tabindex={initialTabIndex} style={viewportStyle} {@attach attachRef}>
  {@render children?.()}
</div>
