<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script module lang="ts">
  export type ScrollAreaOverflowEdgeThreshold = number | Partial<{ xStart: number; xEnd: number; yStart: number; yEnd: number }>;
</script>
<script lang="ts">
  import { createScrollArea } from "@starwind-ui/runtime/scroll-area";
  import { untrack, type Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { Attachment } from "svelte/attachments";
  type Props = HTMLAttributes<HTMLDivElement> & { children?: Snippet; ref?: (element: HTMLDivElement | null) => void; overflowEdgeThreshold?: ScrollAreaOverflowEdgeThreshold };
  let { children, ref, overflowEdgeThreshold, ...rest }: Props = $props();
  let instance = $state.raw<ReturnType<typeof createScrollArea> | null>(null);
type ScrollAreaOverflowEdgeThresholdAttributes = { shared?: number; xEnd?: number; xStart?: number; yEnd?: number; yStart?: number; };
function getOverflowEdgeThresholdAttributes(threshold: ScrollAreaOverflowEdgeThreshold | undefined): ScrollAreaOverflowEdgeThresholdAttributes {
  if (typeof threshold === "number") {
    const shared = normalizeOverflowEdgeThresholdValue(threshold);
    return shared === undefined ? {} : { shared };
  }
  if (!threshold) return {};
  return {
    xEnd: normalizeOverflowEdgeThresholdValue(threshold.xEnd),
    xStart: normalizeOverflowEdgeThresholdValue(threshold.xStart),
    yEnd: normalizeOverflowEdgeThresholdValue(threshold.yEnd),
    yStart: normalizeOverflowEdgeThresholdValue(threshold.yStart),
  };
}
function normalizeOverflowEdgeThresholdValue(value: number | undefined): number | undefined {
  if (value === undefined || !Number.isFinite(value)) return undefined;
  return Math.max(value, 0);
}
  let thresholds = $derived(getOverflowEdgeThresholdAttributes(overflowEdgeThreshold));
  const attachRoot: Attachment<HTMLDivElement> = (element) => {
    const controller = untrack(() => createScrollArea(element));
    instance = controller;
    return () => { if (instance === controller) instance = null; controller.destroy(); };
  };
  $effect(() => {
    const controller = instance;
    void thresholds;
    if (controller) untrack(() => controller.refresh());
  });
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>
<div {...rest} data-sw-scroll-area role="presentation"
  data-overflow-edge-threshold={thresholds.shared}
  data-overflow-edge-threshold-x-start={thresholds.xStart}
  data-overflow-edge-threshold-x-end={thresholds.xEnd}
  data-overflow-edge-threshold-y-start={thresholds.yStart}
  data-overflow-edge-threshold-y-end={thresholds.yEnd}
  {@attach attachRoot} {@attach attachRef}>
  {@render children?.()}
</div>
