<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { createToggle, type TogglePressedChangeDetails } from "@starwind-ui/runtime/toggle";
import { computed, onBeforeUnmount, onMounted, ref, useAttrs, watch } from "vue";

import { useToggleGroupContext } from "../toggle-group/ToggleGroupContext";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    pressed?: boolean;
    defaultPressed?: boolean;
    disabled?: boolean;
    nativeButton?: boolean;
    syncGroup?: string;
    value?: string;
  }>(),
  {
    pressed: undefined,
    defaultPressed: false,
    disabled: false,
    nativeButton: true,
  },
);
const emit = defineEmits<{
  pressedChange: [value: boolean, detail: TogglePressedChangeDetails];
  "update:pressed": [value: boolean];
}>();
defineSlots<{
  default?: () => unknown;
}>();
const attrs = useAttrs();
const rootRef = ref<HTMLElement | null>(null);
const toggleGroup = useToggleGroupContext();
const isGroupOwned = toggleGroup !== undefined;
const groupPressed = computed(() =>
  toggleGroup && props.value !== undefined
    ? toggleGroup.value.value.includes(props.value)
    : undefined,
);
const effectiveDisabled = computed(() => props.disabled || toggleGroup?.disabled.value === true);
const initialDefaultPressed = props.defaultPressed;
const uncontrolledPressed = ref(initialDefaultPressed);
const runtimePressed = ref(initialDefaultPressed);
const renderedPressed = computed(
  () =>
    groupPressed.value ??
    (isGroupOwned ? runtimePressed.value : (props.pressed ?? uncontrolledPressed.value)),
);
let instance: ReturnType<typeof createToggle> | undefined;
let observer: MutationObserver | undefined;
let instanceGeneration = 0;
let mounted = false;

defineExpose({
  element: rootRef,
});

function handlePressedChange(pressed: boolean, detail: TogglePressedChangeDetails): void {
  const eventInstance = instance;
  const eventGeneration = instanceGeneration;
  const eventWasGroupOwned = isGroupOwned;
  const eventWasControlled = !eventWasGroupOwned && props.pressed !== undefined;
  emit("pressedChange", pressed, detail);
  queueMicrotask(() => {
    if (
      detail.isCanceled ||
      !mounted ||
      instance !== eventInstance ||
      instanceGeneration !== eventGeneration
    ) {
      return;
    }

    if (!eventWasGroupOwned && !eventWasControlled) {
      uncontrolledPressed.value = pressed;
    }
    emit("update:pressed", pressed);
  });
}

function destroyOwnedInstance(): void {
  instanceGeneration += 1;
  observer?.disconnect();
  observer = undefined;
  const ownedInstance = instance;
  if (!ownedInstance) return;

  if (instance === ownedInstance) instance = undefined;
  ownedInstance.destroy();
}

function setupRuntime(): void {
  destroyOwnedInstance();
  const element = rootRef.value;
  if (!element) return;

  instance = createToggle(element, {
    defaultPressed: renderedPressed.value,
    disabled: effectiveDisabled.value,
    nativeButton: props.nativeButton,
    syncGroup: props.syncGroup,
    value: props.value,
    onPressedChange: handlePressedChange,
    ...(isGroupOwned
      ? { pressed: renderedPressed.value }
      : props.pressed === undefined
        ? {}
        : { pressed: props.pressed }),
  });

  const syncRuntimePressed = () => {
    runtimePressed.value = element.getAttribute("aria-pressed") === "true";
  };
  observer = new MutationObserver(syncRuntimePressed);
  observer.observe(element, {
    attributes: true,
    attributeFilter: ["aria-pressed"],
  });
  syncRuntimePressed();
}

onMounted(() => {
  mounted = true;
  setupRuntime();
});

watch(
  () => props.pressed,
  (pressed, previousPressed) => {
    if (isGroupOwned) return;
    const controllednessChanged = (pressed === undefined) !== (previousPressed === undefined);
    if (controllednessChanged) {
      if (pressed === undefined && instance) {
        uncontrolledPressed.value = instance.getPressed();
      }
      setupRuntime();
      return;
    }
    if (pressed === undefined || !instance || Object.is(instance.getPressed(), pressed)) {
      return;
    }

    instance.setPressed(pressed, { emit: false, sync: true });
  },
  { flush: "post" },
);
watch(groupPressed, (nextPressed) => {
  if (
    !isGroupOwned ||
    nextPressed === undefined ||
    !instance ||
    Object.is(instance.getPressed(), nextPressed)
  ) {
    return;
  }
  instance.setPressed(nextPressed, { emit: false, sync: true });
});
watch(effectiveDisabled, (nextDisabled) => {
  if (!instance || rootRef.value?.hasAttribute("data-disabled") === nextDisabled) return;
  instance.setDisabled(nextDisabled);
});
watch(() => [props.nativeButton, props.syncGroup, props.value] as const, setupRuntime, {
  flush: "post",
});

onBeforeUnmount(() => {
  mounted = false;
  destroyOwnedInstance();
});
</script>

<template>
  <component
    :is="props.nativeButton ? 'button' : 'span'"
    ref="rootRef"
    v-bind="attrs"
    data-sw-toggle
    data-sw-part="root"
    :type="props.nativeButton ? 'button' : undefined"
    :role="props.nativeButton ? undefined : 'button'"
    :aria-disabled="!props.nativeButton && effectiveDisabled ? 'true' : undefined"
    :aria-pressed="String(renderedPressed)"
    :data-default-pressed="
      !isGroupOwned && props.pressed === undefined && initialDefaultPressed ? 'true' : undefined
    "
    :data-disabled="effectiveDisabled ? '' : undefined"
    :data-native="props.nativeButton ? undefined : 'false'"
    :data-pressed="renderedPressed ? '' : undefined"
    :data-state="renderedPressed ? 'on' : 'off'"
    :data-sync-group="props.syncGroup"
    :data-unpressed="renderedPressed ? undefined : ''"
    :data-value="props.value"
    :disabled="props.nativeButton ? effectiveDisabled : undefined"
    :tabindex="props.nativeButton ? undefined : effectiveDisabled ? -1 : 0"
    :value="props.nativeButton ? props.value : undefined"
  >
    <slot />
  </component>
</template>
