<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import type {
  ColorPickerInitialChannel,
  ColorPickerValue,
} from "@starwind-ui/runtime/color-picker";
import { computed, provide, readonly, ref, useAttrs } from "vue";
import {
  ColorPickerAreaContext,
  ColorPickerChannelSliderContext,
  useColorPickerAreaContext,
  useColorPickerChannelSliderContext,
  useColorPickerPartProjection,
} from "./ColorPickerContext.js";

defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{
    axis?: "x" | "y";
    step?: number;
  }>(),
  { axis: "x" },
);

const attrs = useAttrs();
const element = ref<HTMLElement | null>(null);
const area = useColorPickerAreaContext();
const { props: projectedProps, text } = useColorPickerPartProjection(
  () => ({
    part: "areaInput",
    xChannel: area.xChannel.value,
    yChannel: area.yChannel.value,
    axis: props.axis,
    ...(props.axis === "x"
      ? { xStep: props.step ?? area.xStep.value }
      : { yStep: props.step ?? area.yStep.value }),
  }),
  attrs,
  () => ({
    "data-sw-color-picker-area-input": "",
    "data-axis": props.axis,
    "data-step": props.step ?? (props.axis === "x" ? area.xStep.value : area.yStep.value),
  }),
);
defineExpose({ element });
</script>

<template><input ref="element" v-bind="projectedProps" /></template>
