<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import type {
  ColorPickerInitialChannel,
  ColorPickerValue,
} from "@starwind-ui/runtime/color-picker";
import { computed, provide, readonly, ref, useAttrs } from "vue";
import {
  ColorPickerAreaContext,
  ColorPickerChannelSliderContext,
  useColorPickerAreaContext,
  useColorPickerChannelSliderContext,
  useColorPickerPartProjection,
} from "./ColorPickerContext.js";

defineOptions({ inheritAttrs: false });
const props = withDefaults(defineProps<{}>(), {});
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const element = ref<HTMLElement | null>(null);
const slider = useColorPickerChannelSliderContext();
const { props: projectedProps, text } = useColorPickerPartProjection(
  () => ({
    part: "channelSliderThumb",
    channel: slider.channel.value,
    orientation: slider.orientation.value,
    step: slider.step.value,
  }),
  attrs,
  () => ({ "data-sw-color-picker-channel-slider-thumb": "" }),
);
defineExpose({ element });
</script>

<template>
  <span ref="element" v-bind="projectedProps"><slot /></span>
</template>
