<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { type CheckboxCheckedChangeDetails, createCheckbox } from "@starwind-ui/runtime/checkbox";
import { computed, onBeforeUnmount, onMounted, ref, useAttrs, watch } from "vue";
import { useCheckboxGroupContext } from "../checkbox-group/CheckboxGroupContext";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    checked?: boolean;
    defaultChecked?: boolean;
    disabled?: boolean;
    form?: string;
    id?: string;
    indeterminate?: boolean;
    name?: string;
    nativeButton?: boolean;
    readOnly?: boolean;
    required?: boolean;
    uncheckedValue?: string;
    value?: string;
  }>(),
  {
    checked: undefined,
    disabled: false,
    indeterminate: false,
    nativeButton: false,
    readOnly: false,
    required: false,
  },
);
const emit = defineEmits<{
  checkedChange: [value: boolean, detail: CheckboxCheckedChangeDetails];
  "update:checked": [value: boolean];
}>();
defineSlots<{
  default?: () => unknown;
}>();
const attrs = useAttrs();
const rootRef = ref<HTMLElement | null>(null);
const inputRef = ref<HTMLInputElement | null>(null);
const checkboxGroup = useCheckboxGroupContext();
const groupItemValue = computed(() => props.value ?? props.name);
const groupChecked = computed(() => {
  const itemValue = groupItemValue.value;
  return checkboxGroup && itemValue !== undefined
    ? checkboxGroup.value.value.includes(itemValue)
    : undefined;
});
const effectiveDisabled = computed(() => props.disabled || checkboxGroup?.disabled.value === true);
const initialDefaultChecked = props.defaultChecked ?? false;
const initialChecked = props.checked ?? groupChecked.value ?? initialDefaultChecked;
const uncontrolledChecked = ref(groupChecked.value ?? initialDefaultChecked);
const renderedChecked = computed(
  () => props.checked ?? groupChecked.value ?? uncontrolledChecked.value,
);
const renderedIndeterminate = ref(props.indeterminate);
let instance: ReturnType<typeof createCheckbox> | undefined;
let resetForm: HTMLFormElement | null = null;
let resetTimer: number | undefined;

defineExpose({
  element: rootRef,
});

function handleCheckedChange(checked: boolean, detail: CheckboxCheckedChangeDetails): void {
  emit("checkedChange", checked, detail);
  if (detail.isCanceled) return;

  if (props.checked === undefined) {
    uncontrolledChecked.value = checked;
  }
  if (!props.indeterminate) renderedIndeterminate.value = false;
  emit("update:checked", checked);
}

function clearResetTimer(): void {
  if (resetTimer === undefined) return;

  window.clearTimeout(resetTimer);
  resetTimer = undefined;
}

function unbindFormReset(): void {
  clearResetTimer();
  resetForm?.removeEventListener("reset", handleFormReset);
  resetForm = null;
}

function handleFormReset(): void {
  clearResetTimer();
  resetTimer = window.setTimeout(() => {
    const ownedInstance = instance;
    if (ownedInstance && props.checked === undefined) {
      uncontrolledChecked.value = ownedInstance.getChecked();
      if (!props.indeterminate) renderedIndeterminate.value = false;
    }
    resetTimer = undefined;
  }, 0);
}

function bindFormReset(): void {
  const formElement = inputRef.value?.form ?? null;
  if (resetForm === formElement) return;

  unbindFormReset();
  resetForm = formElement;
  resetForm?.addEventListener("reset", handleFormReset);
}

function destroyOwnedInstance(): void {
  unbindFormReset();
  const ownedInstance = instance;
  if (!ownedInstance) return;

  if (instance === ownedInstance) instance = undefined;
  ownedInstance.destroy();
  removeRuntimeOwnedUncheckedInput();
}

function removeRuntimeOwnedUncheckedInput(): void {
  const candidate = inputRef.value?.nextElementSibling;
  if (
    candidate instanceof HTMLInputElement &&
    candidate.hasAttribute("data-sw-checkbox-unchecked-input")
  ) {
    candidate.remove();
  }
}

function setupRuntime(): void {
  destroyOwnedInstance();
  const element = rootRef.value;
  if (!element) return;

  const options = {
    defaultChecked: renderedChecked.value,
    disabled: effectiveDisabled.value,
    form: props.form,
    id: props.id,
    indeterminate: props.indeterminate,
    name: props.name,
    readOnly: props.readOnly,
    required: props.required,
    uncheckedValue: props.uncheckedValue,
    value: props.value,
    onCheckedChange: handleCheckedChange,
    ...(props.checked !== undefined
      ? { checked: props.checked }
      : groupChecked.value !== undefined
        ? { checked: groupChecked.value }
        : {}),
  };
  instance = createCheckbox(element, options);
  bindFormReset();
}

onMounted(setupRuntime);

watch(
  () => props.checked,
  (checked, previousChecked) => {
    const controllednessChanged = (checked === undefined) !== (previousChecked === undefined);
    if (controllednessChanged) {
      if (checked === undefined && instance) {
        uncontrolledChecked.value = instance.getChecked();
      }
      setupRuntime();
      return;
    }
    if (checked === undefined || !instance || Object.is(instance.getChecked(), checked)) {
      return;
    }

    instance.setChecked(checked, { emit: false });
  },
  { flush: "post" },
);
watch(groupChecked, (checked) => {
  if (checked === undefined || props.checked !== undefined || !instance) return;
  if (Object.is(instance.getChecked(), checked)) return;
  instance.setChecked(checked, { emit: false });
});
watch(effectiveDisabled, (value) => instance?.setDisabled(value));
watch(
  () => props.indeterminate,
  (value) => {
    renderedIndeterminate.value = value;
    instance?.setIndeterminate(value, { emit: false });
  },
);
watch(
  () => [
    props.form,
    props.id,
    props.name,
    props.nativeButton,
    props.readOnly,
    props.required,
    props.uncheckedValue,
    props.value,
  ],
  setupRuntime,
  { flush: "post" },
);

onBeforeUnmount(destroyOwnedInstance);
</script>

<template>
  <component
    :is="props.nativeButton ? 'button' : 'span'"
    ref="rootRef"
    v-bind="attrs"
    data-sw-checkbox
    data-sw-part="root"
    :type="props.nativeButton ? 'button' : undefined"
    role="checkbox"
    :aria-checked="renderedIndeterminate ? 'mixed' : String(renderedChecked)"
    :aria-disabled="effectiveDisabled ? 'true' : undefined"
    :aria-readonly="String(props.readOnly)"
    :aria-required="String(props.required)"
    :data-default-checked="initialDefaultChecked ? 'true' : undefined"
    :data-checked="renderedChecked ? '' : undefined"
    :data-unchecked="renderedChecked ? undefined : ''"
    :data-disabled="effectiveDisabled ? '' : undefined"
    :data-form="props.form"
    :data-id="props.id"
    :data-indeterminate="renderedIndeterminate ? '' : undefined"
    :data-name="props.name"
    :data-readonly="props.readOnly ? '' : undefined"
    :data-required="props.required ? '' : undefined"
    :data-unchecked-value="props.uncheckedValue"
    :data-value="props.value"
    :tabindex="effectiveDisabled ? -1 : 0"
    :disabled="props.nativeButton ? effectiveDisabled : undefined"
  >
    <slot />
    <input
      v-if="!props.nativeButton"
      ref="inputRef"
      data-sw-checkbox-input
      aria-hidden="true"
      tabindex="-1"
      type="checkbox"
      :checked="initialChecked"
      :disabled="effectiveDisabled"
      :form="props.form"
      :id="props.id"
      :name="props.name"
      :required="props.required"
      :value="props.value"
      style="
        position: absolute;
        width: 1px;
        height: 1px;
        margin: -1px;
        overflow: hidden;
        clip: rect(0 0 0 0);
        white-space: nowrap;
        border: 0;
      "
    />
  </component>
  <input
    v-if="props.nativeButton"
    ref="inputRef"
    data-sw-checkbox-input
    aria-hidden="true"
    tabindex="-1"
    type="checkbox"
    :checked="initialChecked"
    :disabled="effectiveDisabled"
    :form="props.form"
    :id="props.id"
    :name="props.name"
    :required="props.required"
    :value="props.value"
    style="
      position: absolute;
      width: 1px;
      height: 1px;
      margin: -1px;
      overflow: hidden;
      clip: rect(0 0 0 0);
      white-space: nowrap;
      border: 0;
    "
  />
</template>
