<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    keepMounted?: boolean;
  }>(),
  {
    keepMounted: false,
  },
);
defineSlots<{
  default?: () => unknown;
}>();
const indicatorRef = ref<HTMLElement | null>(null);

defineExpose({
  element: indicatorRef,
});
</script>

<template>
  <span
    ref="indicatorRef"
    v-bind="$attrs"
    data-sw-checkbox-indicator
    data-sw-part="indicator"
    :data-keep-mounted="props.keepMounted ? '' : undefined"
    data-unchecked
    :hidden="!props.keepMounted"
  >
    <slot />
  </span>
</template>
