/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import CheckboxIndicator from "./CheckboxIndicator.vue";
import CheckboxRoot from "./CheckboxRoot.vue";

const Checkbox = {
  Root: CheckboxRoot,
  Indicator: CheckboxIndicator,
};

export { default as CheckboxIndicator } from "./CheckboxIndicator.vue";

export { default as CheckboxRoot } from "./CheckboxRoot.vue";
export { Checkbox };

export default Checkbox;

export type { CheckboxCheckedChangeDetails } from "@starwind-ui/runtime";
