<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";

  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    children?: Snippet;
    index?: number;
    ref?: (element: HTMLDivElement | null) => void;
    inputRef?: (element: HTMLInputElement | null) => void;
  };
  let { children, index, ref, inputRef, ...rest }: Props = $props();
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
  import { createRefAttachment as createAttachInputRef } from "../_internal/ref-attachment.js";
  const attachInputRef = createAttachInputRef<HTMLInputElement>(() => inputRef);
</script>

<div
  {...rest}
  data-sw-slider-thumb=""
  data-index={index}
  data-sw-part="thumb"
  {@attach attachRef}
>
  {@render children?.()}
  <input
    data-sw-slider-input=""
    aria-hidden="true"
    tabindex={-1}
    type="range"
    style:border="0"
    style:clip-path="inset(50%)"
    style:height="1px"
    style:margin="-1px"
    style:overflow="hidden"
    style:position="absolute"
    style:white-space="nowrap"
    style:width="1px"
    {@attach attachInputRef}
  />
</div>
