/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type CarouselItemProps = React.HTMLAttributes<HTMLDivElement>;

const CarouselItem = React.forwardRef<HTMLDivElement, CarouselItemProps>(
  function CarouselItem(props, forwardedRef) {
    return (
      <div
        role="group"
        aria-roledescription="slide"
        {...props}
        data-sw-carousel-item
        ref={forwardedRef}
      />
    );
  },
);

CarouselItem.displayName = "Carousel.Item";

export default CarouselItem;
