/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type MenuCheckboxItemIndicatorProps = React.HTMLAttributes<HTMLSpanElement>;

const MenuCheckboxItemIndicator = React.forwardRef<HTMLSpanElement, MenuCheckboxItemIndicatorProps>(
  function MenuCheckboxItemIndicator(props, forwardedRef) {
    return (
      <span
        data-sw-menu-checkbox-item-indicator
        aria-hidden="true"
        data-state="unchecked"
        ref={forwardedRef}
        {...props}
      />
    );
  },
);

MenuCheckboxItemIndicator.displayName = "Menu.CheckboxItemIndicator";

export default MenuCheckboxItemIndicator;
