/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import { reportPortalPlacement, resolvePortalPlacement } from "@starwind-ui/runtime/menu";
import * as React from "react";
import { ReactPortal, type ReactPortalProps } from "../internal/portal";

export type MenuPortalProps = ReactPortalProps;

const MenuPortal = React.forwardRef<HTMLDivElement, MenuPortalProps>(
  function MenuPortal(props, forwardedRef) {
    return (
      <ReactPortal
        discoveryAttribute="data-sw-menu-portal"
        reportPlacement={reportPortalPlacement}
        resolvePlacement={resolvePortalPlacement}
        ref={forwardedRef}
        {...props}
      />
    );
  },
);

MenuPortal.displayName = "Menu.Portal";

export default MenuPortal;
