/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import type { MenuCheckedChangeDetails } from "@starwind-ui/runtime/menu";
import * as React from "react";
import { setRef } from "../internal/compose-refs";

export type MenuCheckboxItemProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  "aria-checked" | "role"
> & {
  checked?: boolean;
  defaultChecked?: boolean;
  onCheckedChange?: (checked: boolean, details: MenuCheckedChangeDetails) => void;
  closeOnClick?: boolean;
  disabled?: boolean;
};

const MenuCheckboxItem = React.forwardRef<HTMLDivElement, MenuCheckboxItemProps>(
  function MenuCheckboxItem(
    {
      checked,
      defaultChecked = false,
      onCheckedChange,
      closeOnClick = false,
      disabled = false,
      ...props
    },
    forwardedRef,
  ) {
    const itemRef = React.useRef<HTMLDivElement>(null);
    const checkedRef = React.useRef(checked);
    const defaultCheckedRef = React.useRef(defaultChecked);
    const onCheckedChangeRef = React.useRef(onCheckedChange);
    const [uncontrolledChecked, setUncontrolledChecked] = React.useState(
      () => defaultCheckedRef.current,
    );

    React.useEffect(() => {
      checkedRef.current = checked;
    }, [checked]);

    React.useEffect(() => {
      onCheckedChangeRef.current = onCheckedChange;
    }, [onCheckedChange]);

    const composedRef = React.useCallback(
      (node: HTMLDivElement | null) => {
        itemRef.current = node;
        return setRef(forwardedRef, node);
      },
      [forwardedRef],
    );

    React.useEffect(() => {
      const item = itemRef.current;
      if (!item) return;

      const handleCheckedChange = (event: Event) => {
        const details = (event as CustomEvent<MenuCheckedChangeDetails>).detail;
        onCheckedChangeRef.current?.(details.checked, details);
        if (details.isCanceled) return;

        if (checkedRef.current === undefined) {
          setUncontrolledChecked(details.checked);
          return;
        }

        queueMicrotask(() => {
          const controlledChecked = checkedRef.current;
          if (controlledChecked !== undefined && item.isConnected) {
            syncCheckboxItemState(item, controlledChecked);
          }
        });
      };

      item.addEventListener("starwind:checked-change", handleCheckedChange);

      return () => {
        item.removeEventListener("starwind:checked-change", handleCheckedChange);
      };
    }, []);

    React.useEffect(() => {
      const item = itemRef.current;
      if (!item || checked === undefined) return;

      syncCheckboxItemState(item, checked);
    }, [checked]);

    const renderedChecked = checked ?? uncontrolledChecked;

    return (
      <div
        data-sw-menu-checkbox-item
        data-default-checked={defaultCheckedRef.current ? "true" : undefined}
        data-close-on-click={closeOnClick ? "true" : undefined}
        role="menuitemcheckbox"
        aria-checked={renderedChecked}
        aria-disabled={disabled || undefined}
        data-checked={renderedChecked ? "" : undefined}
        data-disabled={disabled ? "" : undefined}
        data-unchecked={!renderedChecked ? "" : undefined}
        tabIndex={0}
        ref={composedRef}
        {...props}
      />
    );
  },
);

MenuCheckboxItem.displayName = "Menu.CheckboxItem";

export default MenuCheckboxItem;

function syncCheckboxItemState(item: HTMLElement, checked: boolean): void {
  item.setAttribute("aria-checked", String(checked));
  item.toggleAttribute("data-checked", checked);
  item.toggleAttribute("data-unchecked", !checked);

  item
    .querySelectorAll<HTMLElement>("[data-sw-menu-checkbox-item-indicator]")
    .forEach((indicator) => {
      indicator.setAttribute("aria-hidden", "true");
      indicator.setAttribute("data-state", checked ? "checked" : "unchecked");
      indicator.toggleAttribute("data-visible", checked);
      indicator.toggleAttribute("data-hidden", !checked);
    });
}
