/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";
import type { RefCapableElementProps } from "../internal/compose-refs";
import {
  getAsChildElement,
  getElementRef,
  mergeAsChildProps,
  useComposedRefs,
} from "../internal/compose-refs";

export type MenuTriggerProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  asChild?: boolean;
};

const MenuTrigger = React.forwardRef<HTMLElement, MenuTriggerProps>(function MenuTrigger(
  { asChild = false, children, className, ...props },
  forwardedRef,
) {
  const protectedTriggerProps = {
    "data-sw-menu-trigger": "",
    "aria-haspopup": "menu",
    "aria-expanded": "false",
    "data-state": "closed",
  } satisfies React.HTMLAttributes<HTMLElement> & Record<`data-${string}`, string>;
  const triggerProps = {
    ...protectedTriggerProps,
    ...props,
  } satisfies React.HTMLAttributes<HTMLElement> & Record<`data-${string}`, string>;

  const asChildElement = getAsChildElement(children);
  const composedRef = useComposedRefs(
    forwardedRef,
    asChildElement ? getElementRef(asChildElement) : undefined,
  );

  if (asChild && asChildElement) {
    const child = asChildElement;
    const childProps = child.props;
    const mergedProps = mergeAsChildProps({ ...triggerProps, className }, childProps, {
      protectedProps: protectedTriggerProps,
    });

    return React.cloneElement(child, {
      ...mergedProps,
      ref: composedRef,
    });
  }

  return (
    <button
      type="button"
      className={className}
      ref={forwardedRef as React.Ref<HTMLButtonElement>}
      {...(triggerProps as React.ButtonHTMLAttributes<HTMLButtonElement>)}
    >
      {children}
    </button>
  );
});

MenuTrigger.displayName = "Menu.Trigger";

export default MenuTrigger;
