export type {
  StyledOutputAttribute,
  StyledOutputClientBehavior,
  StyledOutputComponent,
  StyledOutputComponentGroup,
  StyledOutputComponentNode,
  StyledOutputConditionNode,
  StyledOutputConstant,
  StyledOutputDefaultExport,
  StyledOutputDestructure,
  StyledOutputDestructureProp,
  StyledOutputElementNode,
  StyledOutputExportMember,
  StyledOutputFragmentNode,
  StyledOutputIconNode,
  StyledOutputImport,
  StyledOutputModel,
  StyledOutputPrimitiveAlias,
  StyledOutputPrimitiveNode,
  StyledOutputPropExtend,
  StyledOutputPropField,
  StyledOutputProps,
  StyledOutputRenderNode,
  StyledOutputRepeatNode,
  StyledOutputSlotNode,
  StyledOutputStyleSideEffect,
  StyledOutputTextNode,
  StyledOutputValueExpression,
  StyledOutputVariable,
  StyledOutputVariant,
} from "../styled-output-model/index.js";
export {
  analyzeStyledOutputComponent,
  analyzeStyledOutputGroup,
  collectStyledOutputComposedComponentReferences,
  collectStyledOutputNamedSlots,
  collectStyledOutputPrimitiveReferences,
  collectStyledOutputSlots,
  collectStyledOutputVariantReferences,
  createStyledOutputModelSkeleton,
  projectStyledOutputModel,
  toStyledAdapterContract,
  usesStyledOutputDefaultSlot,
} from "../styled-output-model/index.js";
export { astroFrameworkAdapter, astroFrameworkAdapterTarget } from "./astro/index.js";
export {
  createFrameworkAdapterConformanceFixture,
  defineFrameworkAdapter,
  printAdapterOutput,
  printFrameworkAdapterConformanceFixture,
} from "./conformance.js";
export type {
  FrameworkAdapterExportPrinter,
  FrameworkAdapterRuntimeTypeReExportArgs,
} from "./export-printer.js";
export {
  type AdapterExportInventory,
  type AdapterExportMode,
  type AdapterNamespaceExportFacts,
  type AdapterNamespaceMemberFacts,
  type AdapterReExportFacts,
  type AdapterReExportRole,
  type AdapterTypeFacadeFacts,
  createAdapterExportInventory,
  createHelperExportFacts,
  createRuntimeTypeExportFacts,
  createValueExportFacts,
} from "./export-toolkit.js";
export {
  type FrameworkAdapterReadiness,
  type FrameworkAdapterReadinessTarget,
  type FutureFrameworkAdapterReadiness,
  SVELTE_FRAMEWORK_ADAPTER_DEFERRED,
} from "./future-readiness.js";
export { reactFrameworkAdapter, reactFrameworkAdapterTarget } from "./react/index.js";
export { solidFrameworkAdapter, solidFrameworkAdapterReadiness } from "./solid/index.js";
export { defineFrameworkAdapterTarget } from "./target-definition.js";
export {
  type FrameworkAdapterRegisteredTarget,
  type FrameworkAdapterTargetStyledCapabilityEntry,
  frameworkAdapterTargets,
  getFrameworkAdapterTargetsWithStyledCapability,
  getPrimitiveFrameworkAdapterTarget,
  getPrimitiveFrameworkAdapterTargetNames,
  getPrimitiveFrameworkAdapterTargetsWithOutputModelCapability,
  type PrimitiveFrameworkAdapterOutputModelCapability,
  type PrimitiveFrameworkAdapterTarget,
  primitiveFrameworkAdapterTargets,
} from "./target-registry.js";
export type {
  AdapterAnchoredMenuOverlayComponentProjection,
  AdapterAnchoredMenuOverlayFacts,
  AdapterAnchoredMenuOverlayIndexProjection,
  AdapterAnchoredMenuOverlayPartName,
  AdapterAttribute,
  AdapterBooleanFormControlComponentProjection,
  AdapterBooleanFormControlFacts,
  AdapterBooleanFormControlIndexProjection,
  AdapterCodeBlock,
  AdapterComponentFamilyProjection,
  AdapterComponentFile,
  AdapterComponentModel,
  AdapterCompositeMenuOverlayComponentProjection,
  AdapterCompositeMenuOverlayFacts,
  AdapterCompositeMenuOverlayHelperProjection,
  AdapterCompositeMenuOverlayIndexProjection,
  AdapterCompositeMenuOverlayPartName,
  AdapterContextProjection,
  AdapterControlledStateSync,
  AdapterControlledValuePresenceComponentProjection,
  AdapterControlledValuePresenceFacts,
  AdapterControlledValuePresenceHelperProjection,
  AdapterControlledValuePresenceIndexProjection,
  AdapterControlledValuePresencePartName,
  AdapterDefaultValue,
  AdapterDisclosurePresenceComponentProjection,
  AdapterDisclosurePresenceFacts,
  AdapterDisclosurePresenceIndexProjection,
  AdapterEditableCollectionOverlayComponentProjection,
  AdapterEditableCollectionOverlayFacts,
  AdapterEditableCollectionOverlayIndexProjection,
  AdapterEditableCollectionOverlayPartName,
  AdapterEditableCollectionOverlaySetter,
  AdapterEditableCollectionOverlayState,
  AdapterEditableCollectionOverlayValueEvent,
  AdapterElementRenderNode,
  AdapterEngineViewportComponentProjection,
  AdapterEngineViewportControl,
  AdapterEngineViewportFacts,
  AdapterEngineViewportIndexProjection,
  AdapterEngineViewportPartName,
  AdapterEventBridge,
  AdapterExportMember,
  AdapterExpression,
  AdapterExpressionRenderNode,
  AdapterFamilyHelperProjection,
  AdapterFamilyIndexProjection,
  AdapterFamilyPart,
  AdapterFamilyProp,
  AdapterFileDropControlComponentProjection,
  AdapterFileDropControlFacts,
  AdapterFileDropControlIndexProjection,
  AdapterFileDropControlPartName,
  AdapterFormControlCompositionComponentProjection,
  AdapterFormControlCompositionFacts,
  AdapterFormControlCompositionIndexProjection,
  AdapterFormControlCompositionPartName,
  AdapterFormFieldCoordinatorComponentProjection,
  AdapterFormFieldCoordinatorFacts,
  AdapterFormFieldCoordinatorIndexProjection,
  AdapterFormMessageProjection,
  AdapterFormRootStateProjection,
  AdapterFormTimingProjection,
  AdapterGroupedValueControlComponentProjection,
  AdapterGroupedValueControlFacts,
  AdapterGroupedValueControlHelperProjection,
  AdapterGroupedValueControlIndexProjection,
  AdapterHelperFile,
  AdapterHiddenInputVisualSlotComponentProjection,
  AdapterHiddenInputVisualSlotFacts,
  AdapterHiddenInputVisualSlotIndexProjection,
  AdapterHiddenInputVisualSlotPartName,
  AdapterImport,
  AdapterImportMember,
  AdapterIndexFile,
  AdapterMediaStatusComponentProjection,
  AdapterMediaStatusFacts,
  AdapterMediaStatusIndexProjection,
  AdapterNamespaceExport,
  AdapterNativeOverlayComponentProjection,
  AdapterNativeOverlayFacts,
  AdapterNativeOverlayIndexProjection,
  AdapterNativeOverlayPartName,
  AdapterNotificationSystemActionButton,
  AdapterNotificationSystemAttributeOption,
  AdapterNotificationSystemCloseButton,
  AdapterNotificationSystemComponentProjection,
  AdapterNotificationSystemCssOption,
  AdapterNotificationSystemFacts,
  AdapterNotificationSystemIndexProjection,
  AdapterNotificationSystemPartName,
  AdapterOptionCollectionOverlayComponentProjection,
  AdapterOptionCollectionOverlayFacts,
  AdapterOptionCollectionOverlayHelperProjection,
  AdapterOptionCollectionOverlayIndexProjection,
  AdapterOptionCollectionOverlayPartName,
  AdapterOutputFile,
  AdapterOutputModel,
  AdapterPortal,
  AdapterPresenceFloatingOverlayComponentProjection,
  AdapterPresenceFloatingOverlayFacts,
  AdapterPresenceFloatingOverlayIndexProjection,
  AdapterPresenceFloatingOverlayPartName,
  AdapterPrintedFile,
  AdapterProp,
  AdapterRangeControlComponentProjection,
  AdapterRangeControlFacts,
  AdapterRangeControlIndexProjection,
  AdapterRangeControlPartName,
  AdapterRef,
  AdapterRenderNode,
  AdapterRepeatedDisclosureComponentProjection,
  AdapterRepeatedDisclosureFacts,
  AdapterRepeatedDisclosureIndexProjection,
  AdapterRepeatedDisclosurePartName,
  AdapterRuntimeLifecycle,
  AdapterRuntimeOption,
  AdapterSharedViewportNavigationComponentProjection,
  AdapterSharedViewportNavigationFacts,
  AdapterSharedViewportNavigationIndexProjection,
  AdapterSharedViewportNavigationPartName,
  AdapterSharedViewportNavigationValueEvent,
  AdapterSidebarComponentProjection,
  AdapterSidebarFacts,
  AdapterSidebarHelperProjection,
  AdapterSidebarIndexProjection,
  AdapterSidebarPartName,
  AdapterSidebarStateControl,
  AdapterSidebarValueEvent,
  AdapterSingleBooleanControlComponentProjection,
  AdapterSingleBooleanControlFacts,
  AdapterSingleBooleanControlIndexProjection,
  AdapterSlotRenderNode,
  AdapterTextRenderNode,
  AdapterTimedFloatingOverlayComponentProjection,
  AdapterTimedFloatingOverlayFacts,
  AdapterTimedFloatingOverlayIndexProjection,
  AdapterTimedFloatingOverlayPartName,
  AdapterTypeFacade,
  AdapterTypeFacadeFile,
  AdapterViewportMeasurementComponentProjection,
  AdapterViewportMeasurementFacts,
  AdapterViewportMeasurementIndexProjection,
  FrameworkAdapter,
  FrameworkAdapterTarget,
  FrameworkAdapterTargetGeneratePrimitiveEntries,
  FrameworkAdapterTargetGeneratePrimitiveEntriesArgs,
  FrameworkAdapterTargetManualPrimitiveArgs,
  FrameworkAdapterTargetManualPrimitiveGenerator,
  FrameworkAdapterTargetManualPrimitiveGenerators,
  FrameworkAdapterTargetPrimitiveCapability,
  FrameworkAdapterTargetPrimitiveOutputArgs,
  FrameworkAdapterTargetPrimitiveOutputModel,
  FrameworkAdapterTargetPrimitivePackageArgs,
  FrameworkAdapterTargetPrimitivePackageGenerator,
  FrameworkAdapterTargetPublicSupport,
  FrameworkAdapterTargetRegistration,
  FrameworkAdapterTargetStyledCapability,
  FrameworkAdapterTargetStyledProjectArgs,
  FrameworkAdapterTargetStyledWriteArgs,
} from "./types.js";
export { vueFrameworkAdapter, vueFrameworkAdapterReadiness } from "./vue/index.js";
