import type { RuntimeAdapterContract } from "../types.js";

export const checkboxRuntimeAdapterContract = {
  component: "checkbox",
  category: "single-boolean-control",
  displayName: "Checkbox",
  runtime: {
    factory: "createCheckbox",
    importSource: "@starwind-ui/runtime/checkbox",
    rootPart: "root",
    optionProps: [
      "checked",
      "defaultChecked",
      "disabled",
      "form",
      "id",
      "indeterminate",
      "name",
      "readOnly",
      "required",
      "uncheckedValue",
      "value",
    ],
    destroys: true,
  },
  parts: [
    {
      name: "root",
      defaultElement: "span",
      discoveryAttribute: "data-sw-checkbox",
      forwardsRef: true,
      ownsRuntime: true,
      role: "checkbox",
      initialAttributes: [
        { name: "aria-checked", source: "state" },
        { name: "aria-readonly", source: "prop" },
        { name: "aria-required", source: "prop" },
        { name: "data-checked", source: "state" },
        { name: "data-default-checked", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "data-form", source: "prop" },
        { name: "data-id", source: "prop" },
        { name: "data-indeterminate", source: "state" },
        { name: "data-name", source: "prop" },
        { name: "data-readonly", source: "prop" },
        { name: "data-required", source: "prop" },
        { name: "data-unchecked", source: "state" },
        { name: "data-unchecked-value", source: "prop" },
        { name: "data-value", source: "prop" },
      ],
    },
    {
      name: "indicator",
      defaultElement: "span",
      discoveryAttribute: "data-sw-checkbox-indicator",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-keep-mounted", source: "prop" },
        { name: "data-unchecked", source: "state" },
      ],
    },
    {
      name: "input",
      defaultElement: "input",
      discoveryAttribute: "data-sw-checkbox-input",
      initialAttributes: [
        { name: "type", source: "constant", value: "checkbox" },
        { name: "aria-hidden", source: "constant", value: "true" },
        { name: "tabIndex", source: "constant", value: "-1" },
      ],
    },
    {
      name: "uncheckedInput",
      defaultElement: "input",
      discoveryAttribute: "data-sw-checkbox-unchecked-input",
      initialAttributes: [{ name: "type", source: "constant", value: "hidden" }],
    },
  ],
  props: [
    { name: "checked", kind: "control", type: "boolean" },
    { defaultValue: "false", name: "defaultChecked", kind: "control", type: "boolean" },
    { defaultValue: "false", name: "disabled", kind: "option", type: "boolean" },
    { name: "form", kind: "option", type: "string" },
    { name: "id", kind: "option", type: "string" },
    { defaultValue: "false", name: "indeterminate", kind: "control", type: "boolean" },
    {
      defaultValue: "false",
      name: "keepMounted",
      kind: "rendering",
      targets: ["indicator"],
      type: "boolean",
    },
    { name: "name", kind: "option", type: "string" },
    {
      defaultValue: "false",
      name: "nativeButton",
      kind: "rendering",
      targets: ["root"],
      type: "boolean",
    },
    { defaultValue: "false", name: "readOnly", kind: "option", type: "boolean" },
    { defaultValue: "false", name: "required", kind: "option", type: "boolean" },
    { name: "uncheckedValue", kind: "option", type: "string" },
    { name: "value", kind: "option", type: "string" },
    { name: "onCheckedChange", kind: "callback", type: "CheckboxCheckedChangeDetails" },
  ],
  stateModels: [
    {
      name: "checked",
      controlledProp: "checked",
      defaultProp: "defaultChecked",
      initialAttribute: "data-default-checked",
      runtimeGetter: "getChecked",
      runtimeSetter: "setChecked",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
    {
      name: "indeterminate",
      controlledProp: "indeterminate",
      initialAttribute: "data-indeterminate",
      runtimeSetter: "setIndeterminate",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
  ],
  events: [
    {
      name: "checkedChange",
      callbackProp: "onCheckedChange",
      detailsType: "CheckboxCheckedChangeDetails",
      domEvent: "starwind:checked-change",
      emitsFrom: "root",
      valueProperty: "checked",
      valueType: "boolean",
      callbackTiming: "before-state-commit",
      cancelable: true,
    },
  ],
  setters: [
    { method: "setChecked", options: { emit: false }, stateModel: "checked", suppressesEmit: true },
    {
      method: "setIndeterminate",
      options: { emit: false },
      stateModel: "indeterminate",
      suppressesEmit: true,
    },
    { method: "setDisabled", prop: "disabled" },
  ],
  context: [
    {
      name: "checkbox-group",
      direction: "consumes",
      values: ["disabled", "value"],
    },
  ],
  form: {
    hiddenInput: { part: "input", type: "checkbox" },
    fieldIntegration: true,
    props: ["form", "id", "name", "required", "uncheckedValue", "value"],
  },
  presence: {
    keepMountedProp: "keepMounted",
    initialHiddenParts: ["indicator"],
    unmountPolicy: "runtime-owned",
  },
  refs: [
    { part: "root", public: true },
    { part: "indicator", public: true },
  ],
  initialMarkup: [
    {
      part: "root",
      attributes: [
        "data-sw-checkbox",
        "role",
        "aria-checked",
        "data-checked",
        "data-unchecked",
        "data-default-checked",
        "data-disabled",
        "data-indeterminate",
      ],
      reason: "The visible ARIA control needs correct semantics before controller hydration.",
    },
    {
      part: "input",
      attributes: ["data-sw-checkbox-input"],
      reason:
        "The runtime needs the nested input placeholder so it can attach form state after hydration.",
    },
  ],
  frameworkNotes: {
    astro: ["Render uncontrolled initial state only; updates are runtime-owned after hydration."],
    react: [
      "Bridge controlled checked changes through setChecked without emitting duplicate events.",
    ],
  },
  escapeHatches: [
    {
      affectedFrameworks: ["astro", "react", "solid", "svelte", "vue"],
      boundary:
        "The component template still owns native button vs span rendering, React group-context lookup, indicator hidden/ref composition, nested input placement, and runtime-created unchecked input timing.",
      contractOwnedFacts: [
        "component id",
        "display name",
        "runtime factory/import",
        "root/indicator/input/unchecked-input parts and discovery attributes",
        "public prop names and defaults",
        "checked and indeterminate state models",
        "checked-change event/callback/details value",
        "checked and disabled setter names",
        "checkbox-group context dependency",
        "presence keep-mounted prop",
        "form props and runtime-created unchecked input part",
        "initial root/input placeholder attributes",
      ],
      demotionCriteria:
        "Demote when a shared boolean form-control template can express group-context value derivation, indicator presence, hidden input placement, and framework ref wiring.",
      reason:
        "Checkbox shares the boolean-control model but adds indicator presence, group consumption, indeterminate rendering, and form input choreography.",
      tests: [
        "scripts/portable-runtime/tests/generator-structure.test.ts",
        "scripts/portable-runtime/tests/generate-astro-wrappers.test.ts",
        "scripts/portable-runtime/tests/generate-react-wrappers.test.ts",
      ],
    },
  ],
} as const satisfies RuntimeAdapterContract;
