import type { RuntimeAdapterContract } from "../types.js";

export const comboboxRuntimeAdapterContract = {
  component: "combobox",
  category: "floating-value-control",
  displayName: "Combobox",
  runtime: {
    factory: "createCombobox",
    importSource: "@starwind-ui/runtime/combobox",
    rootPart: "root",
    optionProps: [
      "autoComplete",
      "defaultInputValue",
      "defaultOpen",
      "defaultValue",
      "disabled",
      "filterMode",
      "form",
      "highlightItemOnHover",
      "inputValue",
      "locale",
      "modal",
      "name",
      "open",
      "readOnly",
      "required",
      "value",
    ],
    optionPropLifecycles: {
      autoComplete: "setter-backed",
      defaultInputValue: "constructor-only",
      defaultOpen: "constructor-only",
      defaultValue: "constructor-only",
      disabled: "setter-backed",
      filterMode: "constructor-only",
      form: "setter-backed",
      highlightItemOnHover: "constructor-only",
      inputValue: "setter-backed",
      locale: "constructor-only",
      modal: "constructor-only",
      name: "setter-backed",
      open: "setter-backed",
      readOnly: "constructor-only",
      required: "setter-backed",
      value: "setter-backed",
    },
    destroys: true,
  },
  parts: [
    {
      name: "root",
      defaultElement: "div",
      discoveryAttribute: "data-sw-combobox",
      forwardsRef: true,
      ownsRuntime: true,
      initialAttributes: [
        { name: "data-state", source: "state" },
        { name: "data-autocomplete", source: "prop" },
        { name: "data-default-input-value", source: "prop" },
        { name: "data-default-open", source: "prop" },
        { name: "data-default-value", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "data-filter-mode", source: "prop" },
        { name: "data-form", source: "prop" },
        { name: "data-highlight-item-on-hover", source: "prop" },
        { name: "data-input-value", source: "state" },
        { name: "data-locale", source: "prop" },
        { name: "data-modal", source: "prop" },
        { name: "data-name", source: "prop" },
        { name: "data-readonly", source: "prop" },
        { name: "data-required", source: "prop" },
      ],
    },
    {
      name: "label",
      defaultElement: "div",
      discoveryAttribute: "data-sw-combobox-label",
      forwardsRef: true,
    },
    {
      name: "inputGroup",
      defaultElement: "div",
      discoveryAttribute: "data-sw-combobox-input-group",
      forwardsRef: true,
    },
    {
      name: "input",
      defaultElement: "input",
      discoveryAttribute: "data-sw-combobox-input",
      forwardsRef: true,
      role: "combobox",
      initialAttributes: [
        { name: "aria-autocomplete", source: "constant", value: "list" },
        { name: "aria-controls", source: "prop" },
        { name: "aria-expanded", source: "state" },
        { name: "autocomplete", source: "constant", value: "off" },
        { name: "value", source: "state" },
      ],
    },
    {
      name: "trigger",
      defaultElement: "button",
      discoveryAttribute: "data-sw-combobox-trigger",
      forwardsRef: true,
      initialAttributes: [
        { name: "aria-haspopup", source: "constant", value: "listbox" },
        { name: "aria-expanded", source: "state" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "icon",
      defaultElement: "span",
      discoveryAttribute: "data-sw-combobox-icon",
      forwardsRef: true,
      initialAttributes: [{ name: "aria-hidden", source: "constant", value: "true" }],
    },
    {
      name: "clear",
      defaultElement: "button",
      discoveryAttribute: "data-sw-combobox-clear",
      forwardsRef: true,
      initialAttributes: [{ name: "type", source: "constant", value: "button" }],
    },
    {
      name: "value",
      defaultElement: "span",
      discoveryAttribute: "data-sw-combobox-value",
      forwardsRef: true,
    },
    {
      name: "hiddenInput",
      defaultElement: "input",
      discoveryAttribute: "data-sw-combobox-hidden-input",
      initialAttributes: [
        { name: "type", source: "constant", value: "hidden" },
        { name: "form", source: "prop" },
        { name: "name", source: "prop" },
        { name: "value", source: "state" },
        { name: "aria-hidden", source: "constant", value: "true" },
        { name: "tabIndex", source: "constant", value: "-1" },
      ],
    },
    {
      name: "portal",
      defaultElement: "div",
      discoveryAttribute: "data-sw-combobox-portal",
      forwardsRef: true,
    },
    {
      name: "positioner",
      defaultElement: "div",
      discoveryAttribute: "data-sw-combobox-positioner",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-align-offset", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
      ],
    },
    {
      name: "popup",
      defaultElement: "div",
      discoveryAttribute: "data-sw-combobox-popup",
      forwardsRef: true,
      role: "listbox",
      initialAttributes: [
        { name: "hidden", source: "state" },
        { name: "tabIndex", source: "constant", value: "-1" },
        { name: "data-state", source: "state" },
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-align-offset", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
      ],
    },
    {
      name: "empty",
      defaultElement: "div",
      discoveryAttribute: "data-sw-combobox-empty",
      forwardsRef: true,
      initialAttributes: [{ name: "hidden", source: "state" }],
    },
    { name: "list", defaultElement: "div", discoveryAttribute: "data-sw-combobox-list" },
    {
      name: "group",
      defaultElement: "div",
      discoveryAttribute: "data-sw-combobox-group",
      forwardsRef: true,
      role: "group",
    },
    {
      name: "groupLabel",
      defaultElement: "div",
      discoveryAttribute: "data-sw-combobox-group-label",
      forwardsRef: true,
    },
    {
      name: "item",
      defaultElement: "div",
      discoveryAttribute: "data-sw-combobox-item",
      forwardsRef: true,
      role: "option",
      initialAttributes: [
        { name: "data-value", source: "prop" },
        { name: "aria-selected", source: "state" },
        { name: "aria-disabled", source: "prop" },
        { name: "data-disabled", source: "prop" },
      ],
    },
    {
      name: "itemText",
      defaultElement: "span",
      discoveryAttribute: "data-sw-combobox-item-text",
      forwardsRef: true,
    },
    {
      name: "itemIndicator",
      defaultElement: "span",
      discoveryAttribute: "data-sw-combobox-item-indicator",
      forwardsRef: true,
      initialAttributes: [
        { name: "aria-hidden", source: "constant", value: "true" },
        { name: "data-state", source: "state" },
        { name: "data-hidden", source: "state" },
        { name: "hidden", source: "state" },
      ],
    },
    {
      name: "separator",
      defaultElement: "div",
      discoveryAttribute: "data-sw-combobox-separator",
      forwardsRef: true,
      role: "separator",
      initialAttributes: [{ name: "aria-orientation", source: "constant", value: "horizontal" }],
    },
  ],
  props: [
    { name: "open", kind: "control", type: "boolean" },
    { name: "defaultOpen", kind: "control", type: "boolean" },
    { name: "value", kind: "control", type: "string | null" },
    { name: "defaultValue", kind: "control", type: "string | null" },
    { name: "inputValue", kind: "control", type: "string" },
    { name: "defaultInputValue", kind: "control", type: "string" },
    { name: "autoComplete", kind: "option", type: "string" },
    { name: "disabled", kind: "option", type: "boolean" },
    {
      defaultValue: '"contains"',
      name: "filterMode",
      kind: "option",
      type: '"contains" | "startsWith"',
    },
    { name: "form", kind: "option", type: "string" },
    { defaultValue: "true", name: "highlightItemOnHover", kind: "option", type: "boolean" },
    { name: "locale", kind: "option", type: "string" },
    { defaultValue: "false", name: "modal", kind: "option", type: "boolean" },
    { name: "name", kind: "option", type: "string" },
    { defaultValue: "false", name: "readOnly", kind: "option", type: "boolean" },
    { name: "required", kind: "option", type: "boolean" },
    { name: "onInputValueChange", kind: "callback", type: "ComboboxInputValueChangeDetails" },
    { name: "onOpenChange", kind: "callback", type: "ComboboxOpenChangeDetails" },
    { name: "onValueChange", kind: "callback", type: "ComboboxValueChangeDetails" },
    { name: "asChild", kind: "rendering", targets: ["clear", "trigger"], type: "boolean" },
    {
      defaultValue: '"bottom"',
      name: "side",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"top" | "right" | "bottom" | "left"',
    },
    {
      defaultValue: '"start"',
      name: "align",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"start" | "center" | "end"',
    },
    {
      defaultValue: "4",
      name: "sideOffset",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "number",
    },
    {
      defaultValue: "0",
      name: "alignOffset",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "number",
    },
    {
      defaultValue: "true",
      name: "avoidCollisions",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "boolean",
    },
  ],
  stateModels: [
    {
      name: "inputValue",
      controlledProp: "inputValue",
      defaultProp: "defaultInputValue",
      initialAttribute: "data-default-input-value",
      runtimeGetter: "getInputValue",
      runtimeSetter: "setInputValue",
      valueType: "string",
      controlledStateSync: "unsupported",
    },
    {
      name: "open",
      controlledProp: "open",
      defaultProp: "defaultOpen",
      initialAttribute: "data-default-open",
      runtimeGetter: "getOpen",
      runtimeSetter: "setOpen",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
    {
      name: "value",
      controlledProp: "value",
      defaultProp: "defaultValue",
      initialAttribute: "data-default-value",
      runtimeGetter: "getValue",
      runtimeSetter: "setValue",
      valueType: "string | null",
      controlledStateSync: "unsupported",
    },
  ],
  events: [
    {
      name: "inputValueChange",
      callbackProp: "onInputValueChange",
      cancelable: true,
      detailsType: "ComboboxInputValueChangeDetails",
      domEvent: "starwind:input-value-change",
      emitsFrom: "root",
      valueProperty: "inputValue",
      valueType: "string",
    },
    {
      name: "openChange",
      callbackProp: "onOpenChange",
      cancelable: true,
      detailsType: "ComboboxOpenChangeDetails",
      domEvent: "starwind:open-change",
      emitsFrom: "root",
      valueProperty: "open",
      valueType: "boolean",
    },
    {
      name: "valueChange",
      callbackProp: "onValueChange",
      cancelable: true,
      detailsType: "ComboboxValueChangeDetails",
      domEvent: "starwind:value-change",
      emitsFrom: "root",
      valueProperty: "value",
      valueType: "string | null",
    },
  ],
  setters: [
    { method: "setDisabled", prop: "disabled" },
    {
      method: "setInputValue",
      options: { emit: false, filter: false },
      stateModel: "inputValue",
      suppressesEmit: true,
    },
    { method: "setOpen", stateModel: "open", suppressesEmit: true },
    { method: "setValue", stateModel: "value", suppressesEmit: true },
  ],
  form: {
    hiddenInput: { part: "hiddenInput", type: "hidden" },
    fieldIntegration: true,
    props: ["autoComplete", "form", "name", "required", "value"],
  },
  presence: {
    initialHiddenParts: ["empty", "popup", "itemIndicator"],
    unmountPolicy: "runtime-owned",
  },
  floating: {
    anchorPart: "inputGroup",
    portalPart: "portal",
    positionerPart: "positioner",
    popupPart: "popup",
    optionProps: ["side", "align", "sideOffset", "alignOffset", "avoidCollisions"],
  },
  refs: [
    { part: "root", public: true },
    { part: "input", public: true },
    { part: "trigger", public: true },
    { part: "popup", public: true },
    { part: "item", public: true },
  ],
  asChild: [
    { part: "clear", merges: ["aria", "className", "data", "events", "ref"] },
    { part: "trigger", merges: ["aria", "className", "data", "ref"] },
  ],
  initialMarkup: [
    {
      part: "input",
      attributes: ["role", "aria-autocomplete", "aria-controls", "aria-expanded", "autocomplete"],
      reason: "Editable combobox semantics must be available before hydration.",
    },
    {
      part: "hiddenInput",
      attributes: ["type", "form", "name", "value", "aria-hidden", "tabIndex"],
      reason: "Form value submission must work without waiting for the runtime.",
    },
    {
      part: "popup",
      attributes: ["role", "hidden", "data-state", "data-side", "data-align"],
      reason: "Floating content starts closed and is positioned by the runtime once opened.",
    },
  ],
  frameworkNotes: {
    astro: ["Generate static combobox markup plus self-init; do not promise controlled props."],
    react: [
      "Bridge inputValue/open/value as separate controlled models and keep callbacks in latest refs.",
    ],
  },
  escapeHatches: [
    {
      affectedFrameworks: ["astro", "react", "solid", "svelte", "vue"],
      boundary:
        "Adapters own Combobox markup, part composition, controlled-state projection, and collection rendering; Runtime owns editable input behavior, filtering, clear action behavior, collection registration, item text extraction, hidden input sync, floating updates, and dismissal.",
      contractOwnedFacts: [
        "runtime bridge",
        "parts",
        "controlled state models",
        "events",
        "form input",
        "floating parts",
        "asChild trigger and clear merge requirements",
      ],
      demotionCriteria:
        "Demote when shared editable collection and floating templates can render Combobox without component-specific branches.",
      reason:
        "Combobox combines form control, text input, filtering, and floating listbox behavior, so it is larger than the generic renderer boundary.",
      tests: [
        "scripts/portable-runtime/tests/runtime-adapter-contract.test.ts",
        "scripts/portable-runtime/tests/generate-astro-wrappers.test.ts",
        "scripts/portable-runtime/tests/generate-react-wrappers.test.ts",
      ],
    },
  ],
} as const satisfies RuntimeAdapterContract;
