import type { PrimitivePartContract, RuntimeAdapterContract } from "../types.js";
import { menuRuntimeAdapterContract } from "./menu.js";

const contextMenuMenuBackedParts: PrimitivePartContract[] = menuRuntimeAdapterContract.parts
  .filter((part) => part.name !== "root" && part.name !== "trigger")
  .map((part) => {
    const clone: PrimitivePartContract = { ...part };

    if ("initialAttributes" in part && part.initialAttributes) {
      clone.initialAttributes = part.initialAttributes.map((attribute) => ({ ...attribute }));
    }

    return clone;
  });

export const contextMenuRuntimeAdapterContract = {
  component: "context-menu",
  category: "composite-menu-overlay",
  displayName: "ContextMenu",
  runtime: {
    factory: "createContextMenu",
    importSource: "@starwind-ui/runtime/context-menu",
    rootPart: "root",
    optionProps: [
      "closeDelay",
      "defaultOpen",
      "disabled",
      "modal",
      "onCloseComplete",
      "onOpenChange",
      "open",
    ],
    optionPropLifecycles: {
      closeDelay: "constructor-only",
      defaultOpen: "constructor-only",
      disabled: "constructor-only",
      modal: "constructor-only",
      onCloseComplete: "constructor-only",
      onOpenChange: "constructor-only",
      open: "setter-backed",
    },
    destroys: true,
  },
  parts: [
    {
      name: "root",
      defaultElement: "div",
      discoveryAttribute: "data-sw-context-menu",
      forwardsRef: true,
      ownsRuntime: true,
      initialAttributes: [
        { name: "data-sw-menu", source: "constant", value: "" },
        { name: "data-default-open", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "data-modal", source: "prop" },
        { name: "data-close-delay", source: "prop" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "trigger",
      defaultElement: "div",
      discoveryAttribute: "data-sw-context-menu-trigger",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-sw-menu-trigger", source: "constant", value: "" },
        { name: "aria-haspopup", source: "constant", value: "menu" },
        { name: "aria-expanded", source: "state" },
        { name: "aria-disabled", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "data-state", source: "state" },
        { name: "tabindex", source: "prop" },
      ],
    },
    {
      name: "anchor",
      defaultElement: "span",
      discoveryAttribute: "data-sw-context-menu-anchor",
      initialAttributes: [
        { name: "data-sw-context-menu-anchor", source: "runtime" },
        { name: "style", source: "runtime" },
      ],
    },
    ...contextMenuMenuBackedParts,
  ],
  props: [
    { name: "open", kind: "control", targets: ["root"], type: "boolean" },
    {
      defaultValue: "false",
      name: "defaultOpen",
      kind: "control",
      targets: ["root"],
      type: "boolean",
    },
    {
      defaultValue: "false",
      name: "disabled",
      kind: "option",
      targets: [
        "root",
        "trigger",
        "item",
        "linkItem",
        "checkboxItem",
        "radioItem",
        "submenuTrigger",
      ],
      type: "boolean",
    },
    { defaultValue: "true", name: "modal", kind: "option", targets: ["root"], type: "boolean" },
    {
      defaultValue: "200",
      name: "closeDelay",
      kind: "option",
      targets: ["root", "submenuRoot"],
      type: "number",
    },
    {
      name: "onCloseComplete",
      kind: "callback",
      targets: ["root"],
      type: "ContextMenuCloseCompleteDetails",
    },
    {
      name: "onOpenChange",
      kind: "callback",
      targets: ["root"],
      type: "ContextMenuOpenChangeDetails",
    },
    {
      defaultValue: '"bottom"',
      name: "side",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"top" | "right" | "bottom" | "left"',
    },
    {
      defaultValue: '"start"',
      name: "align",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"start" | "center" | "end"',
    },
    {
      defaultValue: "4",
      name: "sideOffset",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "number",
    },
    {
      defaultValue: "true",
      name: "avoidCollisions",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "boolean",
    },
    {
      name: "checked",
      kind: "control",
      targets: ["checkboxItem", "radioItem"],
      type: "boolean",
    },
    {
      defaultValue: "false",
      name: "defaultChecked",
      kind: "control",
      targets: ["checkboxItem", "radioItem"],
      type: "boolean",
    },
    {
      defaultValue: "true",
      name: "closeOnClick",
      kind: "option",
      targets: ["item"],
      type: "boolean",
    },
    {
      defaultValue: "false",
      name: "closeOnClick",
      kind: "option",
      targets: ["linkItem"],
      type: "boolean",
    },
    {
      defaultValue: "false",
      name: "closeOnClick",
      kind: "option",
      targets: ["checkboxItem", "radioItem"],
      type: "boolean",
    },
    {
      name: "onCheckedChange",
      kind: "callback",
      targets: ["checkboxItem"],
      type: "MenuCheckedChangeDetails",
    },
    { name: "value", kind: "control", targets: ["radioGroup"], type: "string" },
    { name: "defaultValue", kind: "control", targets: ["radioGroup"], type: "string" },
    { name: "value", kind: "option", required: true, targets: ["radioItem"], type: "string" },
    {
      name: "onValueChange",
      kind: "callback",
      targets: ["radioGroup"],
      type: "MenuValueChangeDetails",
    },
  ],
  stateModels: [
    {
      name: "open",
      controlledProp: "open",
      defaultProp: "defaultOpen",
      initialAttribute: "data-default-open",
      runtimeGetter: "getOpen",
      runtimeSetter: "setOpen",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
    {
      name: "checked",
      controlledProp: "checked",
      defaultProp: "defaultChecked",
      initialAttribute: "data-default-checked",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
    {
      name: "radioValue",
      controlledProp: "value",
      defaultProp: "defaultValue",
      initialAttribute: "data-value",
      valueType: "string",
      controlledStateSync: "unsupported",
    },
  ],
  events: [
    {
      name: "openChange",
      callbackTiming: "before-state-commit",
      cancelable: true,
      callbackProp: "onOpenChange",
      detailsType: "ContextMenuOpenChangeDetails",
      domEvent: "starwind:open-change",
      emitsFrom: "root",
      valueProperty: "open",
      valueType: "boolean",
    },
    {
      name: "closeComplete",
      callbackTiming: "after-state-commit",
      cancelable: false,
      callbackProp: "onCloseComplete",
      detailsType: "ContextMenuCloseCompleteDetails",
      domEvent: "starwind:close-complete",
      emitsFrom: "root",
      valueProperty: "open",
      valueType: "boolean",
    },
    {
      name: "checkedChange",
      callbackTiming: "before-state-commit",
      cancelable: true,
      callbackProp: "onCheckedChange",
      detailsType: "MenuCheckedChangeDetails",
      domEvent: "starwind:checked-change",
      emitsFrom: "checkboxItem",
      valueProperty: "checked",
      valueType: "boolean",
    },
    {
      name: "valueChange",
      callbackTiming: "before-state-commit",
      cancelable: true,
      callbackProp: "onValueChange",
      detailsType: "MenuValueChangeDetails",
      domEvent: "starwind:value-change",
      emitsFrom: "radioGroup",
      valueProperty: "value",
      valueType: "string",
    },
  ],
  setters: [
    { method: "setOpen", options: { emit: false }, stateModel: "open", suppressesEmit: true },
  ],
  context: [
    {
      name: "context-menu-radio-group",
      direction: "provides",
      values: ["value", "defaultValue", "onValueChange"],
    },
    {
      name: "context-menu-radio-group",
      direction: "consumes",
      values: ["value"],
    },
  ],
  presence: {
    initialHiddenParts: ["popup"],
    unmountPolicy: "runtime-owned",
  },
  floating: {
    anchorPart: "anchor",
    portalPart: "portal",
    positionerPart: "positioner",
    popupPart: "popup",
    optionProps: ["side", "align", "sideOffset", "avoidCollisions"],
  },
  refs: [
    { part: "root", public: true },
    { part: "trigger", public: true },
    { part: "anchor", public: false },
    { part: "portal", public: true },
    { part: "positioner", public: true },
    { part: "popup", public: true },
    { part: "item", public: true },
    { part: "linkItem", public: true },
    { part: "checkboxItem", public: true },
    { part: "checkboxItemIndicator", public: true },
    { part: "radioGroup", public: true },
    { part: "radioItem", public: true },
    { part: "radioItemIndicator", public: true },
    { part: "group", public: true },
    { part: "label", public: true },
    { part: "separator", public: true },
    { part: "shortcut", public: true },
    { part: "submenuRoot", public: true },
    { part: "submenuTrigger", public: true },
  ],
  initialMarkup: [
    {
      part: "root",
      attributes: [
        "data-sw-context-menu",
        "data-sw-menu",
        "data-default-open",
        "data-disabled",
        "data-modal",
        "data-close-delay",
        "data-state",
      ],
      reason:
        "The context menu root needs both context-menu and Menu discovery attributes plus open, disabled, modal, close-delay, and initial state markers before hydration.",
    },
    {
      part: "trigger",
      attributes: [
        "data-sw-context-menu-trigger",
        "data-sw-menu-trigger",
        "aria-haspopup",
        "aria-expanded",
        "aria-disabled",
        "data-disabled",
        "data-state",
        "tabindex",
      ],
      reason:
        "Context menu triggers are focusable trigger regions that provide Menu trigger affordances before pointer, keyboard, and touch listeners attach.",
    },
    {
      part: "anchor",
      attributes: ["data-sw-context-menu-anchor", "style"],
      reason:
        "The runtime creates a hidden document-positioned anchor at the pointer or keyboard-open position for the shared Menu floating runtime.",
    },
    {
      part: "popup",
      attributes: [
        "data-sw-menu-popup",
        "role",
        "tabindex",
        "data-state",
        "data-side",
        "data-align",
        "data-side-offset",
        "data-avoid-collisions",
        "hidden",
      ],
      reason:
        "The Menu-backed popup starts hidden and closed with menu semantics and placement hints before runtime positioning.",
    },
  ],
  frameworkNotes: {
    astro: [
      "Render static context-menu root and trigger anatomy, alias Menu-backed parts through index exports, and self-initialize with cleanup before Astro swaps.",
    ],
    react: [
      "Bridge controlled root open state through setOpen, pass close completion through the factory, and alias Menu-backed parts through React exports; pointer/keyboard/touch anchoring stays in the runtime.",
    ],
  },
  escapeHatches: [
    {
      affectedFrameworks: ["astro", "react", "solid", "svelte", "vue"],
      boundary:
        "The component template still owns static root/trigger wrappers, framework-specific touch-callout style syntax, generated index aliases to Menu-backed parts, and Astro lifecycle cleanup; the runtime owns pointer and keyboard anchoring, long-press timing, trigger event interception, hidden anchor creation/removal, Menu instance delegation, portal reference selection, floating updates, and open-change details forwarded from Menu.",
      contractOwnedFacts: [
        "component id",
        "display name",
        "runtime factory/import",
        "root/trigger/anchor parts and discovery attributes",
        "Menu-backed portal/positioner/popup/item/linkItem/checkboxItem/checkboxItemIndicator/radioGroup/radioItem/radioItemIndicator/group/label/separator/shortcut/submenuRoot/submenuTrigger parts and discovery attributes",
        "root open state model",
        "checkbox item checked state model",
        "radio group value state model",
        "open-change event/callback/details value",
        "close-complete event/callback/details value",
        "radio-group value-change event/callback/details value",
        "open setter name and suppressed emit option",
        "root disabled, modal, and close-delay option prop names and defaults",
        "runtime-created anchor as the floating reference",
        "initial root/trigger/anchor/popup attributes",
      ],
      demotionCriteria:
        "Demote when shared Menu-backed alias templates and framework lifecycle helpers can express context-menu root/trigger wrappers and cleanup without component-specific branches.",
      reason:
        "Context Menu is intentionally a thin anchoring adapter over Menu; duplicating Menu collection behavior in this contract would make future framework adapters harder to maintain.",
      tests: [
        "scripts/portable-runtime/tests/runtime-adapter-contract.test.ts",
        "scripts/portable-runtime/tests/generator-structure.test.ts",
        "scripts/portable-runtime/tests/generate-astro-wrappers.test.ts",
        "scripts/portable-runtime/tests/generate-react-wrappers.test.ts",
      ],
    },
  ],
} as const satisfies RuntimeAdapterContract;
