import type { RuntimeAdapterContract } from "../types.js";

export const inputOtpRuntimeAdapterContract = {
  component: "input-otp",
  category: "form-value-control",
  displayName: "InputOtp",
  runtime: {
    factory: "createInputOtp",
    importSource: "@starwind-ui/runtime/input-otp",
    rootPart: "root",
    optionProps: [
      "defaultValue",
      "disabled",
      "form",
      "id",
      "maxLength",
      "name",
      "onValueChange",
      "pattern",
      "readOnly",
      "required",
      "value",
    ],
    optionPropLifecycles: {
      defaultValue: "constructor-only",
      disabled: "setter-backed",
      form: "setter-backed",
      id: "setter-backed",
      maxLength: "refresh-required",
      name: "setter-backed",
      onValueChange: "constructor-only",
      pattern: "constructor-only",
      readOnly: "constructor-only",
      required: "setter-backed",
      value: "setter-backed",
    },
    destroys: true,
  },
  parts: [
    {
      name: "root",
      defaultElement: "div",
      discoveryAttribute: "data-sw-input-otp",
      forwardsRef: true,
      ownsRuntime: true,
      initialAttributes: [
        { name: "data-default-value", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "data-form", source: "prop" },
        { name: "data-id", source: "prop" },
        { name: "data-max-length", source: "prop" },
        { name: "data-name", source: "prop" },
        { name: "data-pattern", source: "prop" },
        { name: "data-readonly", source: "prop" },
        { name: "data-required", source: "prop" },
        { name: "data-value", source: "state" },
        { name: "aria-disabled", source: "prop" },
        { name: "tabindex", source: "state" },
        { name: "tabIndex", source: "state" },
      ],
    },
    {
      name: "input",
      defaultElement: "input",
      discoveryAttribute: "data-sw-input-otp-input",
      initialAttributes: [
        { name: "autocomplete", source: "constant", value: "one-time-code" },
        { name: "autoComplete", source: "constant", value: "one-time-code" },
        { name: "class", source: "constant", value: "sr-only" },
        { name: "className", source: "constant", value: "sr-only" },
        { name: "disabled", source: "prop" },
        { name: "form", source: "prop" },
        { name: "id", source: "prop" },
        { name: "inputmode", source: "prop" },
        { name: "inputMode", source: "prop" },
        { name: "maxlength", source: "prop" },
        { name: "maxLength", source: "prop" },
        { name: "name", source: "prop" },
        { name: "readonly", source: "prop" },
        { name: "readOnly", source: "prop" },
        { name: "required", source: "prop" },
        { name: "tabindex", source: "constant", value: "-1" },
        { name: "tabIndex", source: "constant", value: "-1" },
        { name: "value", source: "state" },
      ],
    },
    {
      name: "group",
      defaultElement: "div",
      discoveryAttribute: "data-sw-input-otp-group",
      forwardsRef: true,
    },
    {
      name: "slot",
      defaultElement: "div",
      discoveryAttribute: "data-sw-input-otp-slot",
      forwardsRef: true,
      initialAttributes: [{ name: "data-index", source: "prop" }],
    },
    {
      name: "slotChar",
      defaultElement: "span",
      discoveryAttribute: "data-sw-input-otp-char",
    },
    {
      name: "slotCaret",
      defaultElement: "div",
      discoveryAttribute: "data-sw-input-otp-caret",
      initialAttributes: [
        {
          name: "class",
          source: "constant",
          value: "pointer-events-none absolute inset-0 hidden items-center justify-center",
        },
        {
          name: "className",
          source: "constant",
          value: "pointer-events-none absolute inset-0 hidden items-center justify-center",
        },
        { name: "hidden", source: "state" },
      ],
    },
    {
      name: "separator",
      defaultElement: "div",
      discoveryAttribute: "data-sw-input-otp-separator",
      forwardsRef: true,
      role: "separator",
      initialAttributes: [{ name: "aria-hidden", source: "constant", value: "true" }],
    },
  ],
  props: [
    { name: "value", kind: "control", type: "string" },
    { name: "defaultValue", kind: "control", type: "string" },
    { defaultValue: "false", name: "disabled", kind: "option", type: "boolean" },
    { name: "form", kind: "option", type: "string" },
    { name: "id", kind: "option", type: "string" },
    { defaultValue: "6", name: "maxLength", kind: "option", type: "number" },
    { name: "name", kind: "option", type: "string" },
    { name: "pattern", kind: "option", type: "RegExp | string" },
    { defaultValue: "false", name: "readOnly", kind: "option", type: "boolean" },
    { defaultValue: "false", name: "required", kind: "option", type: "boolean" },
    { name: "onValueChange", kind: "callback", type: "InputOtpValueChangeDetails" },
    { name: "index", kind: "option", targets: ["slot"], type: "number" },
    {
      name: "caret",
      kind: "rendering",
      targets: ["slot"],
      type: "React.ReactNode",
      unsupportedTargets: ["astro"],
    },
  ],
  stateModels: [
    {
      name: "value",
      controlledProp: "value",
      defaultProp: "defaultValue",
      initialAttribute: "data-value",
      runtimeGetter: "getValue",
      runtimeSetter: "setValue",
      valueType: "string",
      controlledStateSync: "unsupported",
    },
  ],
  events: [
    {
      name: "valueChange",
      callbackProp: "onValueChange",
      detailsType: "InputOtpValueChangeDetails",
      domEvent: "starwind:value-change",
      emitsFrom: "root",
      valueProperty: "value",
      valueType: "string",
    },
  ],
  setters: [
    { method: "setValue", options: { emit: false }, stateModel: "value", suppressesEmit: true },
    { method: "setDisabled", prop: "disabled" },
    { method: "setFormOptions", props: ["form", "id", "name", "required"] },
  ],
  form: {
    hiddenInput: { part: "input", type: "text" },
    fieldIntegration: true,
    props: ["form", "id", "name", "required", "value"],
  },
  refs: [
    { part: "root", public: true },
    { part: "group", public: true },
    { part: "slot", public: true },
    { part: "separator", public: true },
  ],
  initialMarkup: [
    {
      part: "root",
      attributes: [
        "data-sw-input-otp",
        "data-default-value",
        "data-disabled",
        "data-form",
        "data-id",
        "data-max-length",
        "data-name",
        "data-pattern",
        "data-readonly",
        "data-required",
        "data-value",
        "aria-disabled",
        "tabindex",
      ],
      reason:
        "The focusable root needs initial value, disabled, form, pattern, and range metadata before runtime hydration.",
    },
    {
      part: "input",
      attributes: [
        "data-sw-input-otp-input",
        "autocomplete",
        "class",
        "form",
        "id",
        "inputmode",
        "maxlength",
        "name",
        "readonly",
        "required",
        "tabindex",
        "value",
      ],
      reason:
        "The native one-time-code input must participate in forms and mobile OTP affordances before hydration.",
    },
    {
      part: "slot",
      attributes: ["data-sw-input-otp-slot", "data-index"],
      reason: "Slots need stable indices before the runtime writes characters and active state.",
    },
    {
      part: "slotCaret",
      attributes: ["data-sw-input-otp-caret", "class", "hidden"],
      reason: "Carets start hidden until the runtime marks the active empty slot.",
    },
    {
      part: "separator",
      attributes: ["data-sw-input-otp-separator", "aria-hidden", "role"],
      reason: "Separators are presentation-only between slot groups.",
    },
  ],
  frameworkNotes: {
    astro: [
      "Render a native OTP input and visual slots; runtime owns keyboard, paste, form reset, and slot state after hydration.",
    ],
    react: [
      "Bridge controlled value and disabled state through setters while preserving callback refs for value changes.",
    ],
  },
  escapeHatches: [
    {
      affectedFrameworks: ["astro", "react", "solid", "svelte", "vue"],
      boundary:
        "The component template still owns pattern normalization, numeric inputMode derivation, native input placement, React callback refs, controlled value sync, caret slot rendering, and the exact Astro named-slot vs React caret prop shape; the runtime owns keyboard, paste, delete, focus, form reset, value normalization, slot active state, character writing, and caret visibility.",
      contractOwnedFacts: [
        "component id",
        "display name",
        "runtime factory/import",
        "root/input/group/slot/slotChar/slotCaret/separator parts and discovery attributes",
        "value state model",
        "value-change event/callback/details value",
        "value, disabled, and form-options setter names",
        "native input form props",
        "slot index and caret rendering props",
        "initial root/input/slot/caret/separator attributes",
      ],
      demotionCriteria:
        "Demote when a shared native-hidden-input value template can express framework-specific slot rendering, pattern normalization, callback refs, controlled sync, and mobile OTP input attributes.",
      reason:
        "Input OTP combines a native form input with custom visual slots and rich keyboard/paste behavior, so only stable adapter facts belong in the primitive contract.",
      tests: [
        "scripts/portable-runtime/tests/generator-structure.test.ts",
        "scripts/portable-runtime/tests/generate-astro-wrappers.test.ts",
        "scripts/portable-runtime/tests/generate-react-wrappers.test.ts",
      ],
    },
  ],
} as const satisfies RuntimeAdapterContract;
