import type { RuntimeAdapterContract } from "../types.js";

export const menuRuntimeAdapterContract = {
  component: "menu",
  category: "composite-menu-overlay",
  displayName: "Menu",
  runtime: {
    factory: "createMenu",
    importSource: "@starwind-ui/runtime/menu",
    rootPart: "root",
    optionProps: [
      "closeDelay",
      "defaultOpen",
      "disabled",
      "modal",
      "onCloseComplete",
      "onOpenChange",
      "open",
      "openOnHover",
    ],
    optionPropLifecycles: {
      closeDelay: "constructor-only",
      defaultOpen: "constructor-only",
      disabled: "constructor-only",
      modal: "constructor-only",
      onCloseComplete: "constructor-only",
      onOpenChange: "constructor-only",
      open: "setter-backed",
      openOnHover: "constructor-only",
    },
    destroys: true,
  },
  parts: [
    {
      name: "root",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu",
      forwardsRef: true,
      ownsRuntime: true,
      initialAttributes: [
        { name: "data-default-open", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "data-modal", source: "prop" },
        { name: "data-open-on-hover", source: "prop" },
        { name: "data-close-delay", source: "prop" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "trigger",
      defaultElement: "button",
      discoveryAttribute: "data-sw-menu-trigger",
      forwardsRef: true,
      initialAttributes: [
        { name: "type", source: "constant", value: "button" },
        { name: "aria-haspopup", source: "constant", value: "menu" },
        { name: "aria-expanded", source: "state" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "portal",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu-portal",
      forwardsRef: true,
    },
    {
      name: "positioner",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu-positioner",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-state", source: "state" },
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
      ],
    },
    {
      name: "popup",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu-popup",
      forwardsRef: true,
      role: "menu",
      initialAttributes: [
        { name: "role", source: "constant", value: "menu" },
        { name: "tabindex", source: "constant", value: "-1" },
        { name: "data-state", source: "state" },
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
        { name: "hidden", source: "state" },
      ],
    },
    {
      name: "item",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu-item",
      forwardsRef: true,
      role: "menuitem",
      initialAttributes: [
        { name: "role", source: "constant", value: "menuitem" },
        { name: "tabindex", source: "constant", value: "0" },
        { name: "data-close-on-click", source: "prop" },
        { name: "aria-disabled", source: "prop" },
        { name: "data-disabled", source: "prop" },
      ],
    },
    {
      name: "linkItem",
      defaultElement: "a",
      discoveryAttribute: "data-sw-menu-link-item",
      forwardsRef: true,
      role: "menuitem",
      initialAttributes: [
        { name: "role", source: "constant", value: "menuitem" },
        { name: "tabindex", source: "constant", value: "0" },
        { name: "data-close-on-click", source: "prop" },
        { name: "aria-disabled", source: "prop" },
        { name: "data-disabled", source: "prop" },
      ],
    },
    {
      name: "checkboxItem",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu-checkbox-item",
      forwardsRef: true,
      role: "menuitemcheckbox",
      initialAttributes: [
        { name: "data-default-checked", source: "state" },
        { name: "data-close-on-click", source: "prop" },
        { name: "role", source: "constant", value: "menuitemcheckbox" },
        { name: "aria-checked", source: "state" },
        { name: "aria-disabled", source: "prop" },
        { name: "data-checked", source: "state" },
        { name: "data-disabled", source: "prop" },
        { name: "data-unchecked", source: "state" },
        { name: "tabindex", source: "constant", value: "0" },
      ],
    },
    {
      name: "checkboxItemIndicator",
      defaultElement: "span",
      discoveryAttribute: "data-sw-menu-checkbox-item-indicator",
      forwardsRef: true,
      initialAttributes: [
        { name: "aria-hidden", source: "constant", value: "true" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "radioGroup",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu-radio-group",
      forwardsRef: true,
      role: "group",
      initialAttributes: [
        { name: "role", source: "constant", value: "group" },
        { name: "data-value", source: "state" },
      ],
    },
    {
      name: "radioItem",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu-radio-item",
      forwardsRef: true,
      role: "menuitemradio",
      initialAttributes: [
        { name: "data-value", source: "prop" },
        { name: "data-default-checked", source: "state" },
        { name: "data-close-on-click", source: "prop" },
        { name: "role", source: "constant", value: "menuitemradio" },
        { name: "aria-checked", source: "state" },
        { name: "aria-disabled", source: "prop" },
        { name: "data-checked", source: "state" },
        { name: "data-disabled", source: "prop" },
        { name: "data-unchecked", source: "state" },
        { name: "tabindex", source: "constant", value: "0" },
      ],
    },
    {
      name: "radioItemIndicator",
      defaultElement: "span",
      discoveryAttribute: "data-sw-menu-radio-item-indicator",
      forwardsRef: true,
      initialAttributes: [
        { name: "aria-hidden", source: "constant", value: "true" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "group",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu-group",
      forwardsRef: true,
      role: "group",
      initialAttributes: [{ name: "role", source: "constant", value: "group" }],
    },
    {
      name: "label",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu-label",
      forwardsRef: true,
    },
    {
      name: "separator",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu-separator",
      forwardsRef: true,
      role: "separator",
      initialAttributes: [
        { name: "role", source: "constant", value: "separator" },
        { name: "aria-orientation", source: "constant", value: "horizontal" },
      ],
    },
    {
      name: "shortcut",
      defaultElement: "span",
      discoveryAttribute: "data-sw-menu-shortcut",
      forwardsRef: true,
    },
    {
      name: "submenuRoot",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu-submenu-root",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-close-delay", source: "prop" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "submenuTrigger",
      defaultElement: "div",
      discoveryAttribute: "data-sw-menu-submenu-trigger",
      forwardsRef: true,
      role: "menuitem",
      initialAttributes: [
        { name: "role", source: "constant", value: "menuitem" },
        { name: "aria-haspopup", source: "constant", value: "menu" },
        { name: "aria-expanded", source: "state" },
        { name: "aria-disabled", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "data-state", source: "state" },
        { name: "tabindex", source: "constant", value: "0" },
      ],
    },
  ],
  props: [
    { name: "open", kind: "control", targets: ["root"], type: "boolean" },
    {
      defaultValue: "false",
      name: "defaultOpen",
      kind: "control",
      targets: ["root"],
      type: "boolean",
    },
    {
      defaultValue: "false",
      name: "disabled",
      kind: "option",
      targets: ["root", "item", "linkItem", "checkboxItem", "radioItem", "submenuTrigger"],
      type: "boolean",
    },
    { defaultValue: "false", name: "modal", kind: "option", targets: ["root"], type: "boolean" },
    {
      defaultValue: "false",
      name: "openOnHover",
      kind: "option",
      targets: ["root"],
      type: "boolean",
    },
    {
      defaultValue: "200",
      name: "closeDelay",
      kind: "option",
      targets: ["root", "submenuRoot"],
      type: "number",
    },
    {
      name: "onCloseComplete",
      kind: "callback",
      targets: ["root"],
      type: "MenuCloseCompleteDetails",
    },
    { name: "onOpenChange", kind: "callback", targets: ["root"], type: "MenuOpenChangeDetails" },
    {
      defaultValue: "false",
      name: "asChild",
      kind: "rendering",
      targets: ["trigger"],
      type: "boolean",
    },
    {
      defaultValue: '"bottom"',
      name: "side",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"top" | "right" | "bottom" | "left"',
    },
    {
      defaultValue: '"start"',
      name: "align",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"start" | "center" | "end"',
    },
    {
      defaultValue: "4",
      name: "sideOffset",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "number",
    },
    {
      defaultValue: "true",
      name: "avoidCollisions",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "boolean",
    },
    {
      name: "checked",
      kind: "control",
      targets: ["checkboxItem", "radioItem"],
      type: "boolean",
    },
    {
      defaultValue: "false",
      name: "defaultChecked",
      kind: "control",
      targets: ["checkboxItem", "radioItem"],
      type: "boolean",
    },
    {
      defaultValue: "true",
      name: "closeOnClick",
      kind: "option",
      targets: ["item"],
      type: "boolean",
    },
    {
      defaultValue: "false",
      name: "closeOnClick",
      kind: "option",
      targets: ["linkItem"],
      type: "boolean",
    },
    {
      defaultValue: "false",
      name: "closeOnClick",
      kind: "option",
      targets: ["checkboxItem", "radioItem"],
      type: "boolean",
    },
    {
      name: "onCheckedChange",
      kind: "callback",
      targets: ["checkboxItem"],
      type: "MenuCheckedChangeDetails",
    },
    { name: "value", kind: "control", targets: ["radioGroup"], type: "string" },
    { name: "defaultValue", kind: "control", targets: ["radioGroup"], type: "string" },
    { name: "value", kind: "option", required: true, targets: ["radioItem"], type: "string" },
    {
      name: "onValueChange",
      kind: "callback",
      targets: ["radioGroup"],
      type: "MenuValueChangeDetails",
    },
  ],
  stateModels: [
    {
      name: "open",
      controlledProp: "open",
      defaultProp: "defaultOpen",
      initialAttribute: "data-default-open",
      runtimeGetter: "getOpen",
      runtimeSetter: "setOpen",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
    {
      name: "checked",
      controlledProp: "checked",
      defaultProp: "defaultChecked",
      initialAttribute: "data-default-checked",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
    {
      name: "radioValue",
      controlledProp: "value",
      defaultProp: "defaultValue",
      initialAttribute: "data-value",
      valueType: "string",
      controlledStateSync: "unsupported",
    },
  ],
  events: [
    {
      name: "openChange",
      callbackTiming: "before-state-commit",
      cancelable: true,
      callbackProp: "onOpenChange",
      detailsType: "MenuOpenChangeDetails",
      domEvent: "starwind:open-change",
      emitsFrom: "root",
      valueProperty: "open",
      valueType: "boolean",
    },
    {
      name: "closeComplete",
      callbackTiming: "after-state-commit",
      cancelable: false,
      callbackProp: "onCloseComplete",
      detailsType: "MenuCloseCompleteDetails",
      domEvent: "starwind:close-complete",
      emitsFrom: "root",
      valueProperty: "open",
      valueType: "boolean",
    },
    {
      name: "checkedChange",
      callbackTiming: "before-state-commit",
      cancelable: true,
      callbackProp: "onCheckedChange",
      detailsType: "MenuCheckedChangeDetails",
      domEvent: "starwind:checked-change",
      emitsFrom: "checkboxItem",
      valueProperty: "checked",
      valueType: "boolean",
    },
    {
      name: "valueChange",
      callbackTiming: "before-state-commit",
      cancelable: true,
      callbackProp: "onValueChange",
      detailsType: "MenuValueChangeDetails",
      domEvent: "starwind:value-change",
      emitsFrom: "radioGroup",
      valueProperty: "value",
      valueType: "string",
    },
  ],
  setters: [
    { method: "setOpen", options: { emit: false }, stateModel: "open", suppressesEmit: true },
  ],
  context: [
    {
      name: "menu-radio-group",
      direction: "provides",
      values: ["value", "defaultValue", "onValueChange"],
    },
    {
      name: "menu-radio-group",
      direction: "consumes",
      values: ["value"],
    },
  ],
  presence: {
    initialHiddenParts: ["popup"],
    unmountPolicy: "runtime-owned",
  },
  floating: {
    anchorPart: "trigger",
    portalPart: "portal",
    positionerPart: "positioner",
    popupPart: "popup",
    optionProps: ["side", "align", "sideOffset", "avoidCollisions"],
  },
  refs: [
    { part: "root", public: true },
    { part: "trigger", public: true },
    { part: "portal", public: true },
    { part: "positioner", public: true },
    { part: "popup", public: true },
    { part: "item", public: true },
    { part: "linkItem", public: true },
    { part: "checkboxItem", public: true },
    { part: "checkboxItemIndicator", public: true },
    { part: "radioGroup", public: true },
    { part: "radioItem", public: true },
    { part: "radioItemIndicator", public: true },
    { part: "group", public: true },
    { part: "label", public: true },
    { part: "separator", public: true },
    { part: "shortcut", public: true },
    { part: "submenuRoot", public: true },
    { part: "submenuTrigger", public: true },
  ],
  asChild: [{ part: "trigger", merges: ["aria", "className", "data", "ref"] }],
  initialMarkup: [
    {
      part: "root",
      attributes: [
        "data-sw-menu",
        "data-default-open",
        "data-disabled",
        "data-modal",
        "data-open-on-hover",
        "data-close-delay",
        "data-state",
      ],
      reason:
        "The menu root needs open, disabled, modal, hover, delay, and initial state markers before hydration.",
    },
    {
      part: "trigger",
      attributes: ["data-sw-menu-trigger", "type", "aria-haspopup", "aria-expanded", "data-state"],
      reason:
        "Triggers need button semantics, menu affordances, and initial closed state before listeners attach.",
    },
    {
      part: "positioner",
      attributes: [
        "data-sw-menu-positioner",
        "data-state",
        "data-side",
        "data-align",
        "data-side-offset",
        "data-avoid-collisions",
      ],
      reason:
        "The floating positioner carries initial placement hints used by the shared floating runtime.",
    },
    {
      part: "popup",
      attributes: [
        "data-sw-menu-popup",
        "role",
        "tabindex",
        "data-state",
        "data-side",
        "data-align",
        "data-side-offset",
        "data-avoid-collisions",
        "hidden",
      ],
      reason:
        "The popup starts hidden and closed with menu semantics and placement hints before runtime positioning.",
    },
    {
      part: "item",
      attributes: [
        "data-sw-menu-item",
        "role",
        "tabindex",
        "data-close-on-click",
        "aria-disabled",
        "data-disabled",
      ],
      reason:
        "Regular menu items need menu item semantics, disabled markers, and optional close behavior markers before activation.",
    },
    {
      part: "linkItem",
      attributes: [
        "data-sw-menu-link-item",
        "role",
        "tabindex",
        "data-close-on-click",
        "aria-disabled",
        "data-disabled",
      ],
      reason:
        "Link menu items need anchor semantics, disabled markers, and optional close behavior markers before activation.",
    },
    {
      part: "checkboxItem",
      attributes: [
        "data-sw-menu-checkbox-item",
        "data-default-checked",
        "data-close-on-click",
        "role",
        "aria-checked",
        "aria-disabled",
        "data-checked",
        "data-disabled",
        "data-unchecked",
        "tabindex",
      ],
      reason:
        "Checkbox menu items need checked, disabled, and close behavior markers before item activation.",
    },
    {
      part: "radioGroup",
      attributes: ["data-sw-menu-radio-group", "role", "data-value"],
      reason:
        "Radio groups need a value marker before runtime normalizes descendant radio item state.",
    },
    {
      part: "radioItem",
      attributes: [
        "data-sw-menu-radio-item",
        "data-value",
        "data-default-checked",
        "data-close-on-click",
        "role",
        "aria-checked",
        "aria-disabled",
        "data-checked",
        "data-disabled",
        "data-unchecked",
        "tabindex",
      ],
      reason:
        "Radio menu items need value, checked, disabled, and close behavior markers before item activation.",
    },
    {
      part: "submenuTrigger",
      attributes: [
        "data-sw-menu-submenu-trigger",
        "role",
        "aria-haspopup",
        "aria-expanded",
        "aria-disabled",
        "data-disabled",
        "data-state",
        "tabindex",
      ],
      reason:
        "Submenu triggers need menu item semantics and closed disclosure state before nested menu listeners attach.",
    },
  ],
  frameworkNotes: {
    astro: [
      "Render static menu, submenu, item, and radio/checkbox item anatomy and self-initialize; do not promise controlled item state beyond initial markup.",
    ],
    react: [
      "Bridge controlled root open state through setOpen, wire onOpenChange and close completion through the factory, and keep radio-group value synchronization in the component template until a shared collection helper exists.",
    ],
  },
  escapeHatches: [
    {
      affectedFrameworks: ["astro", "react", "solid", "svelte", "vue"],
      boundary:
        "The component template still owns trigger asChild clone/wrapper rendering, creation-time option remount policy, static portal/positioner/popup composition, root-menu versus context-menu scan filtering, item/link/checkbox/radio/submenu markup branches, radio-group controlled value synchronization without a runtime instance setter, checkbox/radio indicator normalization, framework-specific ref utilities, and index namespace exports; the runtime owns roving focus, typeahead, highlighted state, submenu controllers, pointer and keyboard open reasons, cancellable root open changes, item activation, checkbox/radio item state mutation, portal movement, floating auto-update, outside/Escape dismissal, hover close timers, and animation-delayed hiding.",
      contractOwnedFacts: [
        "component id",
        "display name",
        "runtime factory/import",
        "root/trigger/portal/positioner/popup/item/linkItem/checkboxItem/checkboxItemIndicator/radioGroup/radioItem/radioItemIndicator/group/label/separator/shortcut/submenuRoot/submenuTrigger parts and discovery attributes",
        "root open state model",
        "checkbox item checked state model",
        "radio group value state model",
        "open-change event/callback/details value",
        "close-complete event/callback/details value",
        "radio-group value-change event/callback/details value",
        "open setter name and suppressed emit option",
        "root disabled, modal, hover, and close-delay option prop names and defaults",
        "floating placement prop names and defaults",
        "trigger asChild merge requirements",
        "initial root/trigger/positioner/popup/checkboxItem/radioGroup/radioItem/submenuTrigger attributes",
      ],
      demotionCriteria:
        "Demote when shared collection, roving-item, controlled radio-group, asChild, and presence-floating templates can express Menu without encoding item-kind and submenu-specific branches.",
      reason:
        "Menu combines floating presence with collection, submenu, checkbox, and radio behaviors; forcing those behaviors into generic contract metadata now would turn the contract into a second runtime.",
      tests: [
        "scripts/portable-runtime/tests/runtime-adapter-contract.test.ts",
        "scripts/portable-runtime/tests/generator-structure.test.ts",
        "scripts/portable-runtime/tests/generate-astro-wrappers.test.ts",
        "scripts/portable-runtime/tests/generate-react-wrappers.test.ts",
      ],
    },
  ],
} as const satisfies RuntimeAdapterContract;
