import type { RuntimeAdapterContract } from "../types.js";

export const navigationMenuRuntimeAdapterContract = {
  component: "navigation-menu",
  category: "floating-value-control",
  displayName: "NavigationMenu",
  runtime: {
    factory: "createNavigationMenu",
    importSource: "@starwind-ui/runtime/navigation-menu",
    rootPart: "root",
    optionProps: [
      "closeDelay",
      "closeOnEscape",
      "closeOnOutsideInteract",
      "defaultValue",
      "onValueChange",
      "openDelay",
      "value",
    ],
    optionPropLifecycles: {
      closeDelay: "constructor-only",
      closeOnEscape: "constructor-only",
      closeOnOutsideInteract: "constructor-only",
      defaultValue: "constructor-only",
      onValueChange: "constructor-only",
      openDelay: "constructor-only",
      value: "setter-backed",
    },
    destroys: true,
  },
  parts: [
    {
      name: "root",
      defaultElement: "nav",
      discoveryAttribute: "data-sw-nav-menu",
      forwardsRef: true,
      ownsRuntime: true,
      initialAttributes: [
        { name: "data-value", source: "prop" },
        { name: "data-controlled-value", source: "prop" },
        { name: "data-default-value", source: "prop" },
        { name: "data-open-delay", source: "prop" },
        { name: "data-close-delay", source: "prop" },
        { name: "data-close-on-escape", source: "prop" },
        { name: "data-close-on-outside-interact", source: "prop" },
        { name: "data-orientation", source: "prop" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "list",
      defaultElement: "ul",
      discoveryAttribute: "data-sw-nav-menu-list",
      forwardsRef: true,
    },
    {
      name: "item",
      defaultElement: "li",
      discoveryAttribute: "data-sw-nav-menu-item",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-value", source: "prop" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "trigger",
      defaultElement: "button",
      discoveryAttribute: "data-sw-nav-menu-trigger",
      forwardsRef: true,
      initialAttributes: [
        { name: "type", source: "constant", value: "button" },
        { name: "data-as-child", source: "prop" },
        { name: "data-open-delay", source: "prop" },
        { name: "data-close-delay", source: "prop" },
        { name: "aria-haspopup", source: "constant", value: "menu" },
        { name: "aria-expanded", source: "state" },
        { name: "data-disabled", source: "prop" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "icon",
      defaultElement: "span",
      discoveryAttribute: "data-sw-nav-menu-icon",
      forwardsRef: true,
      initialAttributes: [
        { name: "aria-hidden", source: "constant", value: "true" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "content",
      defaultElement: "div",
      discoveryAttribute: "data-sw-nav-menu-content",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-state", source: "state" },
        { name: "hidden", source: "state" },
      ],
    },
    {
      name: "link",
      defaultElement: "a",
      discoveryAttribute: "data-sw-nav-menu-link",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-active", source: "prop" },
        { name: "aria-current", source: "prop" },
        { name: "data-close-on-click", source: "prop" },
      ],
    },
    {
      name: "portal",
      defaultElement: "div",
      discoveryAttribute: "data-sw-nav-menu-portal",
      forwardsRef: true,
    },
    {
      name: "positioner",
      defaultElement: "div",
      discoveryAttribute: "data-sw-nav-menu-positioner",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-state", source: "state" },
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-align-offset", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
        { name: "data-collision-padding", source: "prop" },
      ],
    },
    {
      name: "popup",
      defaultElement: "div",
      discoveryAttribute: "data-sw-nav-menu-popup",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-state", source: "state" },
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "hidden", source: "state" },
      ],
    },
    {
      name: "viewport",
      defaultElement: "div",
      discoveryAttribute: "data-sw-nav-menu-viewport",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-state", source: "state" },
        { name: "hidden", source: "state" },
      ],
    },
    {
      name: "arrow",
      defaultElement: "div",
      discoveryAttribute: "data-sw-nav-menu-arrow",
      forwardsRef: true,
      initialAttributes: [
        { name: "aria-hidden", source: "constant", value: "true" },
        { name: "data-state", source: "state" },
      ],
    },
  ],
  props: [
    { name: "value", kind: "control", targets: ["root"], type: "string | null" },
    {
      defaultValue: "null",
      name: "defaultValue",
      kind: "control",
      targets: ["root"],
      type: "string | null",
    },
    {
      defaultValue: "50",
      name: "openDelay",
      kind: "option",
      targets: ["root", "trigger"],
      type: "number",
    },
    {
      defaultValue: "50",
      name: "closeDelay",
      kind: "option",
      targets: ["root", "trigger"],
      type: "number",
    },
    { defaultValue: "true", name: "closeOnEscape", kind: "option", type: "boolean" },
    {
      defaultValue: "true",
      name: "closeOnOutsideInteract",
      kind: "option",
      type: "boolean",
    },
    { name: "onValueChange", kind: "callback", type: "NavigationMenuValueChangeDetails" },
    {
      defaultValue: '"horizontal"',
      name: "orientation",
      kind: "option",
      targets: ["root"],
      type: '"horizontal" | "vertical"',
    },
    { name: "value", kind: "option", targets: ["item"], type: "string" },
    { name: "asChild", kind: "rendering", targets: ["trigger"], type: "boolean" },
    {
      defaultValue: "false",
      name: "disabled",
      kind: "option",
      targets: ["trigger"],
      type: "boolean",
    },
    { name: "href", kind: "attribute", targets: ["link"], type: "string" },
    { defaultValue: "false", name: "active", kind: "option", targets: ["link"], type: "boolean" },
    {
      defaultValue: "true",
      name: "closeOnClick",
      kind: "option",
      targets: ["link"],
      type: "boolean",
    },
    {
      defaultValue: '"bottom"',
      name: "side",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"top" | "right" | "bottom" | "left"',
    },
    {
      defaultValue: '"start"',
      name: "align",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"start" | "center" | "end"',
    },
    {
      defaultValue: "4",
      name: "sideOffset",
      kind: "option",
      targets: ["positioner"],
      type: "number",
    },
    {
      defaultValue: "0",
      name: "alignOffset",
      kind: "option",
      targets: ["positioner"],
      type: "number",
    },
    {
      defaultValue: "true",
      name: "avoidCollisions",
      kind: "option",
      targets: ["positioner"],
      type: "boolean",
    },
    {
      defaultValue: "8",
      name: "collisionPadding",
      kind: "option",
      targets: ["positioner"],
      type: "number",
    },
  ],
  stateModels: [
    {
      name: "value",
      controlledProp: "value",
      defaultProp: "defaultValue",
      initialAttribute: "data-default-value",
      runtimeGetter: "getValue",
      runtimeSetter: "setValue",
      valueType: "string | null",
      controlledStateSync: "unsupported",
    },
  ],
  events: [
    {
      name: "valueChange",
      callbackTiming: "before-state-commit",
      cancelable: true,
      callbackProp: "onValueChange",
      detailsType: "NavigationMenuValueChangeDetails",
      domEvent: "starwind:value-change",
      emitsFrom: "root",
      valueProperty: "value",
      valueType: "string | null",
    },
  ],
  setters: [
    { method: "setValue", options: { emit: false }, stateModel: "value", suppressesEmit: true },
  ],
  presence: {
    initialHiddenParts: ["content", "popup", "viewport"],
    unmountPolicy: "runtime-owned",
  },
  floating: {
    anchorPart: "trigger",
    portalPart: "portal",
    positionerPart: "positioner",
    popupPart: "popup",
    optionProps: [
      "side",
      "align",
      "sideOffset",
      "alignOffset",
      "avoidCollisions",
      "collisionPadding",
    ],
  },
  refs: [
    { part: "root", public: true },
    { part: "list", public: true },
    { part: "item", public: true },
    { part: "trigger", public: true },
    { part: "icon", public: true },
    { part: "content", public: true },
    { part: "link", public: true },
    { part: "portal", public: true },
    { part: "positioner", public: true },
    { part: "popup", public: true },
    { part: "viewport", public: true },
    { part: "arrow", public: true },
  ],
  asChild: [{ part: "trigger", merges: ["aria", "className", "data", "ref", "style"] }],
  initialMarkup: [
    {
      part: "root",
      attributes: [
        "data-sw-nav-menu",
        "data-default-value",
        "data-open-delay",
        "data-close-delay",
        "data-close-on-escape",
        "data-close-on-outside-interact",
        "data-orientation",
        "data-state",
      ],
      reason:
        "The root needs initial value, dismissal, orientation, and closed state before hydration.",
    },
    {
      part: "trigger",
      attributes: [
        "data-sw-nav-menu-trigger",
        "type",
        "data-as-child",
        "data-open-delay",
        "data-close-delay",
        "aria-haspopup",
        "aria-expanded",
        "data-disabled",
        "data-state",
      ],
      reason: "Triggers need button semantics and closed ARIA state before hydration.",
    },
    {
      part: "content",
      attributes: ["data-sw-nav-menu-content", "data-state", "hidden"],
      reason: "Content starts hidden until the runtime moves the active panel into the viewport.",
    },
    {
      part: "positioner",
      attributes: [
        "data-sw-nav-menu-positioner",
        "data-state",
        "data-side",
        "data-align",
        "data-side-offset",
        "data-align-offset",
        "data-avoid-collisions",
        "data-collision-padding",
      ],
      reason: "The positioner owns initial floating options before hydration.",
    },
    {
      part: "popup",
      attributes: ["data-sw-nav-menu-popup", "data-state", "hidden"],
      reason: "The popup starts hidden until a trigger activates a panel.",
    },
    {
      part: "viewport",
      attributes: ["data-sw-nav-menu-viewport", "data-state", "hidden"],
      reason: "The shared viewport starts hidden and receives active content at runtime.",
    },
  ],
  frameworkNotes: {
    astro: [
      "Render static uncontrolled anatomy and self-initialize; use explicit item values for defaultValue and stable app state.",
      "Runtime treats an empty string as a valid NavigationMenuValue; open state is value !== null.",
      "Navigation Menu roots nested inside Content are intentionally not auto-initialized; use static links or lists for second-level panels.",
    ],
    react: [
      "Render static anatomy and initialize the runtime in a layout effect; controlled value is setter-backed and should use explicit item values.",
      "Runtime treats an empty string as a valid NavigationMenuValue; open state is value !== null.",
      "Navigation Menu roots nested inside Content are intentionally not auto-initialized; use static links or lists for second-level panels.",
    ],
  },
  escapeHatches: [
    {
      affectedFrameworks: ["astro", "react", "solid", "svelte", "vue"],
      boundary: "shared viewport choreography",
      contractOwnedFacts: [
        "supported parts",
        "discovery attributes",
        "initial hidden state",
        "floating option attributes",
      ],
      demotionCriteria:
        "Move viewport measurement details into the contract only when multiple adapters need to generate the same sizing logic.",
      reason:
        "The runtime owns active content movement and shared viewport sizing; adapters only render the anatomy.",
      tests: ["packages/runtime/src/components/navigation-menu/navigation-menu.browser.test.ts"],
    },
    {
      affectedFrameworks: ["astro", "react", "solid", "svelte", "vue"],
      boundary: "nested Navigation Menu roots",
      contractOwnedFacts: [
        "nested roots inside Content are not auto-initialized",
        "parent controllers ignore descendant Navigation Menu parts",
      ],
      demotionCriteria:
        "Promote nested behavior only when Starwind has an important use case that justifies the additional runtime behavior.",
      reason:
        "Navigation Menu v1 stays focused on top-level shared viewport panels to limit JavaScript complexity.",
      tests: ["packages/runtime/src/components/navigation-menu/navigation-menu.browser.test.ts"],
    },
  ],
} as const satisfies RuntimeAdapterContract;
