import type { RuntimeAdapterContract } from "../types.js";

export const popoverRuntimeAdapterContract = {
  component: "popover",
  category: "presence-floating-overlay",
  displayName: "Popover",
  runtime: {
    factory: "createPopover",
    importSource: "@starwind-ui/runtime/popover",
    rootPart: "root",
    optionProps: [
      "closeOnEscape",
      "closeOnOutsideInteract",
      "defaultOpen",
      "modal",
      "onCloseComplete",
      "onOpenChange",
      "open",
      "openOnHover",
    ],
    optionPropLifecycles: {
      closeOnEscape: "constructor-only",
      closeOnOutsideInteract: "constructor-only",
      defaultOpen: "constructor-only",
      modal: "constructor-only",
      onCloseComplete: "constructor-only",
      onOpenChange: "constructor-only",
      open: "setter-backed",
      openOnHover: "constructor-only",
    },
    destroys: true,
  },
  parts: [
    {
      name: "root",
      defaultElement: "div",
      discoveryAttribute: "data-sw-popover",
      forwardsRef: true,
      ownsRuntime: true,
      initialAttributes: [
        { name: "data-default-open", source: "prop" },
        { name: "data-close-on-escape", source: "prop" },
        { name: "data-close-on-outside-interact", source: "prop" },
        { name: "data-modal", source: "prop" },
        { name: "data-open-on-hover", source: "prop" },
        { name: "data-close-delay", source: "prop" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "trigger",
      defaultElement: "button",
      discoveryAttribute: "data-sw-popover-trigger",
      forwardsRef: true,
      initialAttributes: [
        { name: "type", source: "constant", value: "button" },
        { name: "data-as-child", source: "prop" },
        { name: "aria-haspopup", source: "constant", value: "dialog" },
        { name: "aria-expanded", source: "state" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "portal",
      defaultElement: "div",
      discoveryAttribute: "data-sw-popover-portal",
      forwardsRef: true,
    },
    {
      name: "positioner",
      defaultElement: "div",
      discoveryAttribute: "data-sw-popover-positioner",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-state", source: "state" },
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
      ],
    },
    {
      name: "popup",
      defaultElement: "div",
      discoveryAttribute: "data-sw-popover-popup",
      forwardsRef: true,
      role: "dialog",
      initialAttributes: [
        { name: "role", source: "constant", value: "dialog" },
        { name: "tabindex", source: "constant", value: "-1" },
        { name: "tabIndex", source: "constant", value: "-1" },
        { name: "data-state", source: "state" },
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
        { name: "hidden", source: "state" },
      ],
    },
    {
      name: "arrow",
      defaultElement: "div",
      discoveryAttribute: "data-sw-popover-arrow",
      forwardsRef: true,
    },
    {
      name: "backdrop",
      defaultElement: "div",
      discoveryAttribute: "data-sw-popover-backdrop",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-state", source: "state" },
        { name: "hidden", source: "state" },
      ],
    },
    {
      name: "title",
      defaultElement: "h2",
      discoveryAttribute: "data-sw-popover-title",
      forwardsRef: true,
    },
    {
      name: "description",
      defaultElement: "p",
      discoveryAttribute: "data-sw-popover-description",
      forwardsRef: true,
    },
    {
      name: "close",
      defaultElement: "button",
      discoveryAttribute: "data-sw-popover-close",
      forwardsRef: true,
      initialAttributes: [{ name: "type", source: "constant", value: "button" }],
    },
    {
      name: "viewport",
      defaultElement: "div",
      discoveryAttribute: "data-sw-popover-viewport",
      forwardsRef: true,
    },
  ],
  props: [
    { name: "open", kind: "control", targets: ["root"], type: "boolean" },
    {
      defaultValue: "false",
      name: "defaultOpen",
      kind: "control",
      targets: ["root"],
      type: "boolean",
    },
    { defaultValue: "true", name: "closeOnEscape", kind: "option", type: "boolean" },
    {
      defaultValue: "true",
      name: "closeOnOutsideInteract",
      kind: "option",
      type: "boolean",
    },
    { defaultValue: "false", name: "modal", kind: "option", type: "boolean" },
    { defaultValue: "false", name: "openOnHover", kind: "option", type: "boolean" },
    { defaultValue: "200", name: "closeDelay", kind: "option", targets: ["root"], type: "number" },
    { name: "onCloseComplete", kind: "callback", type: "PopoverCloseCompleteDetails" },
    { name: "onOpenChange", kind: "callback", type: "PopoverOpenChangeDetails" },
    { name: "asChild", kind: "rendering", targets: ["trigger"], type: "boolean" },
    {
      defaultValue: '"bottom"',
      name: "side",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"top" | "right" | "bottom" | "left"',
    },
    {
      defaultValue: '"center"',
      name: "align",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"start" | "center" | "end"',
    },
    {
      defaultValue: "4",
      name: "sideOffset",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "number",
    },
    {
      defaultValue: "true",
      name: "avoidCollisions",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "boolean",
    },
  ],
  stateModels: [
    {
      name: "open",
      controlledProp: "open",
      defaultProp: "defaultOpen",
      initialAttribute: "data-default-open",
      runtimeGetter: "getOpen",
      runtimeSetter: "setOpen",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
  ],
  events: [
    {
      name: "openChange",
      callbackTiming: "before-state-commit",
      cancelable: true,
      callbackProp: "onOpenChange",
      detailsType: "PopoverOpenChangeDetails",
      domEvent: "starwind:open-change",
      emitsFrom: "root",
      valueProperty: "open",
      valueType: "boolean",
    },
    {
      name: "closeComplete",
      callbackTiming: "after-state-commit",
      cancelable: false,
      callbackProp: "onCloseComplete",
      detailsType: "PopoverCloseCompleteDetails",
      domEvent: "starwind:close-complete",
      emitsFrom: "root",
      valueProperty: "open",
      valueType: "boolean",
    },
  ],
  setters: [
    { method: "setOpen", options: { emit: false }, stateModel: "open", suppressesEmit: true },
  ],
  presence: {
    initialHiddenParts: ["popup", "backdrop"],
    unmountPolicy: "runtime-owned",
  },
  floating: {
    anchorPart: "trigger",
    portalPart: "portal",
    positionerPart: "positioner",
    popupPart: "popup",
    optionProps: ["side", "align", "sideOffset", "avoidCollisions"],
  },
  refs: [
    { part: "root", public: true },
    { part: "trigger", public: true },
    { part: "portal", public: true },
    { part: "positioner", public: true },
    { part: "popup", public: true },
    { part: "arrow", public: true },
    { part: "backdrop", public: true },
    { part: "title", public: true },
    { part: "description", public: true },
    { part: "close", public: true },
    { part: "viewport", public: true },
  ],
  asChild: [{ part: "trigger", merges: ["aria", "className", "data", "ref"] }],
  initialMarkup: [
    {
      part: "root",
      attributes: [
        "data-sw-popover",
        "data-default-open",
        "data-close-on-escape",
        "data-close-on-outside-interact",
        "data-open-on-hover",
        "data-close-delay",
        "data-state",
      ],
      reason:
        "The popover root needs default-open, dismissal, hover, close-delay, and initial state markers before hydration.",
    },
    {
      part: "trigger",
      attributes: [
        "data-sw-popover-trigger",
        "data-as-child",
        "aria-haspopup",
        "aria-expanded",
        "data-state",
        "type",
      ],
      reason:
        "Triggers need dialog affordances, asChild markers, and initial closed state before activation listeners attach.",
    },
    {
      part: "positioner",
      attributes: [
        "data-sw-popover-positioner",
        "data-state",
        "data-side",
        "data-align",
        "data-side-offset",
        "data-avoid-collisions",
      ],
      reason: "The positioner carries initial placement hints used by the shared floating runtime.",
    },
    {
      part: "popup",
      attributes: [
        "data-sw-popover-popup",
        "role",
        "tabindex",
        "data-state",
        "data-side",
        "data-align",
        "data-side-offset",
        "data-avoid-collisions",
        "hidden",
      ],
      reason:
        "The popup starts hidden with dialog semantics, focus targetability, and initial placement hints before hydration.",
    },
    {
      part: "backdrop",
      attributes: ["data-sw-popover-backdrop", "data-state", "hidden"],
      reason:
        "The optional backdrop starts hidden and receives runtime-owned open/close visibility.",
    },
    {
      part: "close",
      attributes: ["data-sw-popover-close", "type"],
      reason: "Close controls need button semantics before runtime listeners attach.",
    },
  ],
  frameworkNotes: {
    astro: [
      "Render static closed popover anatomy and self-initialize; runtime owns nesting, focus, portal movement, and floating updates.",
    ],
    react: [
      "Bridge controlled open state through setOpen, pass close completion through the factory, and clone asChild triggers while keeping latest callback refs.",
    ],
  },
} as const satisfies RuntimeAdapterContract;
