import type { RuntimeAdapterContract } from "../types.js";

export const previewCardRuntimeAdapterContract = {
  component: "preview-card",
  category: "presence-floating-overlay",
  displayName: "PreviewCard",
  runtime: {
    factory: "createPreviewCard",
    importSource: "@starwind-ui/runtime/preview-card",
    rootPart: "root",
    optionProps: [
      "closeDelay",
      "closeOnEscape",
      "closeOnOutsideInteract",
      "defaultOpen",
      "disableHoverableContent",
      "onOpenChange",
      "open",
      "openDelay",
    ],
    optionPropLifecycles: {
      closeDelay: "constructor-only",
      closeOnEscape: "constructor-only",
      closeOnOutsideInteract: "constructor-only",
      defaultOpen: "constructor-only",
      disableHoverableContent: "constructor-only",
      onOpenChange: "constructor-only",
      open: "setter-backed",
      openDelay: "constructor-only",
    },
    destroys: true,
  },
  parts: [
    {
      name: "root",
      defaultElement: "div",
      discoveryAttribute: "data-sw-preview-card",
      forwardsRef: true,
      ownsRuntime: true,
      initialAttributes: [
        { name: "data-default-open", source: "prop" },
        { name: "data-close-delay", source: "prop" },
        { name: "data-close-on-escape", source: "prop" },
        { name: "data-close-on-outside-interact", source: "prop" },
        { name: "data-content-hoverable", source: "prop" },
        { name: "data-open-delay", source: "prop" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "trigger",
      defaultElement: "button",
      discoveryAttribute: "data-sw-preview-card-trigger",
      forwardsRef: true,
      initialAttributes: [
        { name: "type", source: "constant", value: "button" },
        { name: "data-as-child", source: "prop" },
        { name: "data-close-delay", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "data-open-delay", source: "prop" },
        { name: "aria-disabled", source: "prop" },
        { name: "data-state", source: "state" },
        { name: "disabled", source: "prop" },
      ],
    },
    {
      name: "portal",
      defaultElement: "div",
      discoveryAttribute: "data-sw-preview-card-portal",
      forwardsRef: true,
    },
    {
      name: "positioner",
      defaultElement: "div",
      discoveryAttribute: "data-sw-preview-card-positioner",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-state", source: "state" },
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
      ],
    },
    {
      name: "popup",
      defaultElement: "div",
      discoveryAttribute: "data-sw-preview-card-popup",
      forwardsRef: true,
      role: "tooltip",
      initialAttributes: [
        { name: "role", source: "constant", value: "tooltip" },
        { name: "data-state", source: "state" },
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
        { name: "hidden", source: "state" },
      ],
    },
    {
      name: "arrow",
      defaultElement: "div",
      discoveryAttribute: "data-sw-preview-card-arrow",
      forwardsRef: true,
      initialAttributes: [{ name: "data-state", source: "state" }],
    },
    {
      name: "backdrop",
      defaultElement: "div",
      discoveryAttribute: "data-sw-preview-card-backdrop",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-state", source: "state" },
        { name: "hidden", source: "state" },
      ],
    },
    {
      name: "viewport",
      defaultElement: "div",
      discoveryAttribute: "data-sw-preview-card-viewport",
      forwardsRef: true,
      initialAttributes: [{ name: "data-state", source: "state" }],
    },
  ],
  props: [
    { name: "open", kind: "control", targets: ["root"], type: "boolean" },
    {
      defaultValue: "false",
      name: "defaultOpen",
      kind: "control",
      targets: ["root"],
      type: "boolean",
    },
    { defaultValue: "300", name: "closeDelay", kind: "option", type: "number" },
    { defaultValue: "true", name: "closeOnEscape", kind: "option", type: "boolean" },
    {
      defaultValue: "true",
      name: "closeOnOutsideInteract",
      kind: "option",
      type: "boolean",
    },
    {
      defaultValue: "false",
      name: "disableHoverableContent",
      kind: "option",
      targets: ["root"],
      type: "boolean",
    },
    { defaultValue: "600", name: "openDelay", kind: "option", type: "number" },
    { name: "onOpenChange", kind: "callback", type: "PreviewCardOpenChangeDetails" },
    { name: "asChild", kind: "rendering", targets: ["trigger"], type: "boolean" },
    {
      defaultValue: "false",
      name: "disabled",
      kind: "option",
      targets: ["trigger"],
      type: "boolean",
    },
    {
      defaultValue: '"bottom"',
      name: "side",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"top" | "right" | "bottom" | "left"',
    },
    {
      defaultValue: '"center"',
      name: "align",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"start" | "center" | "end"',
    },
    {
      defaultValue: "0",
      name: "sideOffset",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "number",
    },
    {
      defaultValue: "true",
      name: "avoidCollisions",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "boolean",
    },
  ],
  stateModels: [
    {
      name: "open",
      controlledProp: "open",
      defaultProp: "defaultOpen",
      initialAttribute: "data-default-open",
      runtimeGetter: "getOpen",
      runtimeSetter: "setOpen",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
  ],
  events: [
    {
      name: "openChange",
      callbackTiming: "before-state-commit",
      cancelable: true,
      callbackProp: "onOpenChange",
      detailsType: "PreviewCardOpenChangeDetails",
      domEvent: "starwind:open-change",
      emitsFrom: "root",
      valueProperty: "open",
      valueType: "boolean",
    },
  ],
  setters: [
    { method: "setOpen", options: { emit: false }, stateModel: "open", suppressesEmit: true },
  ],
  presence: {
    initialHiddenParts: ["popup", "backdrop"],
    unmountPolicy: "runtime-owned",
  },
  floating: {
    anchorPart: "trigger",
    portalPart: "portal",
    positionerPart: "positioner",
    popupPart: "popup",
    optionProps: ["side", "align", "sideOffset", "avoidCollisions"],
  },
  refs: [
    { part: "root", public: true },
    { part: "trigger", public: true },
    { part: "portal", public: true },
    { part: "positioner", public: true },
    { part: "popup", public: true },
    { part: "arrow", public: true },
    { part: "backdrop", public: true },
    { part: "viewport", public: true },
  ],
  asChild: [{ part: "trigger", merges: ["aria", "className", "data", "ref"] }],
  initialMarkup: [
    {
      part: "root",
      attributes: [
        "data-sw-preview-card",
        "data-default-open",
        "data-close-delay",
        "data-close-on-escape",
        "data-close-on-outside-interact",
        "data-content-hoverable",
        "data-open-delay",
        "data-state",
      ],
      reason:
        "The preview card root needs timing, dismissal, hoverability, and initial state markers before hydration.",
    },
    {
      part: "trigger",
      attributes: [
        "data-sw-preview-card-trigger",
        "data-as-child",
        "data-close-delay",
        "data-disabled",
        "data-open-delay",
        "aria-disabled",
        "data-state",
        "disabled",
        "type",
      ],
      reason:
        "Triggers need delay overrides, disabled state, and initial closed state before pointer/focus listeners attach.",
    },
    {
      part: "positioner",
      attributes: [
        "data-sw-preview-card-positioner",
        "data-state",
        "data-side",
        "data-align",
        "data-side-offset",
        "data-avoid-collisions",
      ],
      reason: "The positioner carries initial placement hints used by the shared floating runtime.",
    },
    {
      part: "popup",
      attributes: [
        "data-sw-preview-card-popup",
        "role",
        "data-state",
        "data-side",
        "data-align",
        "data-side-offset",
        "data-avoid-collisions",
        "hidden",
      ],
      reason:
        "The preview card popup starts hidden with tooltip semantics and initial placement hints before hydration.",
    },
    {
      part: "backdrop",
      attributes: ["data-sw-preview-card-backdrop", "data-state", "hidden"],
      reason: "The optional backdrop starts hidden and receives runtime-owned visibility state.",
    },
    {
      part: "viewport",
      attributes: ["data-sw-preview-card-viewport", "data-state"],
      reason:
        "The optional viewport receives state and placement updates from the floating runtime.",
    },
    {
      part: "arrow",
      attributes: ["data-sw-preview-card-arrow", "data-state"],
      reason: "The optional arrow receives state and placement updates from the floating runtime.",
    },
  ],
  frameworkNotes: {
    astro: [
      "Render static closed preview card anatomy and self-initialize; runtime owns hover/focus timers, portal movement, and floating updates.",
    ],
    react: [
      "Create the controller with creation-time timing/dismissal options and bridge controlled open state through setOpen.",
    ],
  },
  escapeHatches: [
    {
      affectedFrameworks: ["astro", "react", "solid", "svelte", "vue"],
      boundary:
        "The component template still owns trigger clone/wrapper asChild paths, creation-time option remount policy, controlled callback refs, static portal/positioner/popup/backdrop/viewport/arrow composition, and initial closed placement attributes; the runtime owns hover/focus timers, Escape/outside intent events, delayed hide animations, portal movement, floating auto-update, aria-describedby linking, transform origin, arrow placement state, and trigger target resolution.",
      contractOwnedFacts: [
        "component id",
        "display name",
        "runtime factory/import",
        "root/trigger/portal/positioner/popup/arrow/backdrop/viewport parts and discovery attributes",
        "open state model",
        "open-change event/callback/details value",
        "open setter name and suppressed emit option",
        "root timing/dismissal option prop names and defaults",
        "floating placement prop names and defaults",
        "presence initial hidden popup/backdrop",
        "trigger asChild support marker",
        "initial root/trigger/positioner/popup/arrow/backdrop/viewport attributes",
      ],
      demotionCriteria:
        "Demote when a shared presence-floating overlay template can express creation-time option remount policy, trigger clone/wrapper asChild, callback refs, static optional overlay parts, and runtime-owned delayed hide/floating behavior across frameworks.",
      reason:
        "PreviewCard shares Tooltip's hover/focus lifecycle but has richer Base UI overlay anatomy, so it remains a bounded component template until overlay generation is generalized.",
      tests: [
        "scripts/portable-runtime/tests/generator-structure.test.ts",
        "scripts/portable-runtime/tests/generate-astro-wrappers.test.ts",
        "scripts/portable-runtime/tests/generate-react-wrappers.test.ts",
      ],
    },
  ],
} as const satisfies RuntimeAdapterContract;
