import type { RuntimeAdapterContract } from "../types.js";

export const selectRuntimeAdapterContract = {
  component: "select",
  category: "floating-value-control",
  displayName: "Select",
  runtime: {
    factory: "createSelect",
    importSource: "@starwind-ui/runtime/select",
    rootPart: "root",
    optionProps: [
      "autoComplete",
      "defaultOpen",
      "defaultValue",
      "disabled",
      "form",
      "highlightItemOnHover",
      "modal",
      "open",
      "readOnly",
      "value",
    ],
    optionPropLifecycles: {
      autoComplete: "constructor-only",
      defaultOpen: "constructor-only",
      defaultValue: "constructor-only",
      disabled: "constructor-only",
      form: "constructor-only",
      highlightItemOnHover: "constructor-only",
      modal: "constructor-only",
      open: "setter-backed",
      readOnly: "constructor-only",
      value: "setter-backed",
    },
    destroys: true,
  },
  parts: [
    {
      name: "root",
      defaultElement: "div",
      discoveryAttribute: "data-sw-select",
      forwardsRef: true,
      ownsRuntime: true,
      initialAttributes: [
        { name: "data-state", source: "state" },
        { name: "data-autocomplete", source: "prop" },
        { name: "data-default-open", source: "prop" },
        { name: "data-default-value", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "data-form", source: "prop" },
        { name: "data-highlight-item-on-hover", source: "prop" },
        { name: "data-modal", source: "prop" },
        { name: "data-name", source: "prop" },
        { name: "data-readonly", source: "prop" },
        { name: "data-required", source: "prop" },
      ],
    },
    {
      name: "label",
      defaultElement: "div",
      discoveryAttribute: "data-sw-select-label",
      forwardsRef: true,
    },
    {
      name: "trigger",
      defaultElement: "button",
      discoveryAttribute: "data-sw-select-trigger",
      forwardsRef: true,
      role: "combobox",
      initialAttributes: [
        { name: "aria-haspopup", source: "constant", value: "listbox" },
        { name: "aria-expanded", source: "state" },
        { name: "aria-readonly", source: "prop" },
        { name: "data-state", source: "state" },
        { name: "data-readonly", source: "prop" },
      ],
    },
    {
      name: "value",
      defaultElement: "span",
      discoveryAttribute: "data-sw-select-value",
      forwardsRef: true,
    },
    {
      name: "icon",
      defaultElement: "span",
      discoveryAttribute: "data-sw-select-icon",
      forwardsRef: true,
      initialAttributes: [{ name: "aria-hidden", source: "constant", value: "true" }],
    },
    {
      name: "input",
      defaultElement: "input",
      discoveryAttribute: "data-sw-select-input",
      initialAttributes: [
        { name: "type", source: "constant", value: "hidden" },
        { name: "autocomplete", source: "prop" },
        { name: "form", source: "prop" },
        { name: "value", source: "state" },
      ],
    },
    {
      name: "portal",
      defaultElement: "div",
      discoveryAttribute: "data-sw-select-portal",
      forwardsRef: true,
    },
    {
      name: "positioner",
      defaultElement: "div",
      discoveryAttribute: "data-sw-select-positioner",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-align-offset", source: "prop" },
        { name: "data-align-item-with-trigger", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
      ],
    },
    {
      name: "popup",
      defaultElement: "div",
      discoveryAttribute: "data-sw-select-popup",
      forwardsRef: true,
      role: "listbox",
      initialAttributes: [
        { name: "hidden", source: "state" },
        { name: "tabIndex", source: "constant", value: "-1" },
        { name: "data-state", source: "state" },
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-align-offset", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
      ],
    },
    { name: "list", defaultElement: "div", discoveryAttribute: "data-sw-select-list" },
    {
      name: "group",
      defaultElement: "div",
      discoveryAttribute: "data-sw-select-group",
      forwardsRef: true,
      role: "group",
    },
    {
      name: "groupLabel",
      defaultElement: "div",
      discoveryAttribute: "data-sw-select-group-label",
      forwardsRef: true,
    },
    {
      name: "item",
      defaultElement: "div",
      discoveryAttribute: "data-sw-select-item",
      forwardsRef: true,
      role: "option",
      initialAttributes: [
        { name: "data-value", source: "prop" },
        { name: "aria-selected", source: "state" },
        { name: "aria-disabled", source: "prop" },
        { name: "data-disabled", source: "prop" },
      ],
    },
    {
      name: "itemText",
      defaultElement: "span",
      discoveryAttribute: "data-sw-select-item-text",
      forwardsRef: true,
    },
    {
      name: "itemIndicator",
      defaultElement: "span",
      discoveryAttribute: "data-sw-select-item-indicator",
      forwardsRef: true,
      initialAttributes: [
        { name: "aria-hidden", source: "constant", value: "true" },
        { name: "data-state", source: "state" },
        { name: "data-hidden", source: "state" },
        { name: "hidden", source: "state" },
      ],
    },
    {
      name: "separator",
      defaultElement: "div",
      discoveryAttribute: "data-sw-select-separator",
      forwardsRef: true,
      role: "separator",
      initialAttributes: [{ name: "aria-orientation", source: "constant", value: "horizontal" }],
    },
    {
      name: "scrollUpArrow",
      defaultElement: "div",
      discoveryAttribute: "data-sw-select-scroll-up-arrow",
      forwardsRef: true,
      initialAttributes: [{ name: "aria-hidden", source: "constant", value: "true" }],
    },
    {
      name: "scrollDownArrow",
      defaultElement: "div",
      discoveryAttribute: "data-sw-select-scroll-down-arrow",
      forwardsRef: true,
      initialAttributes: [{ name: "aria-hidden", source: "constant", value: "true" }],
    },
  ],
  props: [
    { name: "open", kind: "control", type: "boolean" },
    { name: "defaultOpen", kind: "control", type: "boolean" },
    { name: "value", kind: "control", type: "string | null" },
    { name: "defaultValue", kind: "control", type: "string | null" },
    { name: "autoComplete", kind: "option", type: "string" },
    { name: "disabled", kind: "option", type: "boolean" },
    { name: "form", kind: "option", type: "string" },
    { defaultValue: "true", name: "highlightItemOnHover", kind: "option", type: "boolean" },
    { defaultValue: "true", name: "modal", kind: "option", targets: ["root"], type: "boolean" },
    { name: "name", kind: "option", type: "string" },
    { defaultValue: "false", name: "readOnly", kind: "option", type: "boolean" },
    { name: "required", kind: "option", type: "boolean" },
    { name: "onOpenChange", kind: "callback", type: "SelectOpenChangeDetails" },
    { name: "onValueChange", kind: "callback", type: "SelectValueChangeDetails" },
    { name: "asChild", kind: "rendering", targets: ["trigger"], type: "boolean" },
    {
      defaultValue: '"bottom"',
      name: "side",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"top" | "right" | "bottom" | "left"',
    },
    {
      defaultValue: '"start"',
      name: "align",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"start" | "center" | "end"',
    },
    {
      defaultValue: "4",
      name: "sideOffset",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "number",
    },
    {
      defaultValue: "0",
      name: "alignOffset",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "number",
    },
    {
      defaultValue: "true",
      name: "avoidCollisions",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "boolean",
    },
    {
      defaultValue: "true",
      name: "alignItemWithTrigger",
      kind: "option",
      targets: ["positioner"],
      type: "boolean",
    },
  ],
  stateModels: [
    {
      name: "open",
      controlledProp: "open",
      defaultProp: "defaultOpen",
      initialAttribute: "data-default-open",
      runtimeGetter: "getOpen",
      runtimeSetter: "setOpen",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
    {
      name: "value",
      controlledProp: "value",
      defaultProp: "defaultValue",
      initialAttribute: "data-default-value",
      runtimeGetter: "getValue",
      runtimeSetter: "setValue",
      valueType: "string | null",
      controlledStateSync: "unsupported",
    },
  ],
  events: [
    {
      name: "openChange",
      callbackProp: "onOpenChange",
      detailsType: "SelectOpenChangeDetails",
      domEvent: "starwind:open-change",
      emitsFrom: "root",
      valueProperty: "open",
    },
    {
      name: "valueChange",
      callbackProp: "onValueChange",
      detailsType: "SelectValueChangeDetails",
      domEvent: "starwind:value-change",
      emitsFrom: "root",
      valueProperty: "value",
    },
  ],
  setters: [
    { method: "setOpen", stateModel: "open", suppressesEmit: true },
    { method: "setValue", stateModel: "value", suppressesEmit: true },
  ],
  form: {
    hiddenInput: { part: "input", type: "hidden" },
    fieldIntegration: true,
    props: ["autoComplete", "form", "name", "required", "value"],
  },
  presence: {
    initialHiddenParts: ["popup", "itemIndicator"],
    unmountPolicy: "runtime-owned",
  },
  floating: {
    anchorPart: "trigger",
    portalPart: "portal",
    positionerPart: "positioner",
    popupPart: "popup",
    optionProps: [
      "side",
      "align",
      "sideOffset",
      "alignOffset",
      "avoidCollisions",
      "alignItemWithTrigger",
    ],
  },
  refs: [
    { part: "root", public: true },
    { part: "trigger", public: true },
    { part: "popup", public: true },
    { part: "item", public: true },
  ],
  asChild: [{ part: "trigger", merges: ["aria", "className", "data", "ref"] }],
  initialMarkup: [
    {
      part: "trigger",
      attributes: ["role", "aria-haspopup", "aria-expanded", "aria-readonly", "data-state"],
      reason: "Keyboard and assistive technology affordances must be present before hydration.",
    },
    {
      part: "popup",
      attributes: ["role", "hidden", "data-state", "data-side", "data-align"],
      reason: "Floating content starts closed and is positioned by the runtime once opened.",
    },
  ],
  frameworkNotes: {
    astro: ["Generate static listbox markup plus self-init; do not promise controlled props."],
    react: ["Bridge open/value as separate controlled models and keep callbacks in latest refs."],
  },
  escapeHatches: [
    {
      affectedFrameworks: ["astro", "react", "solid", "svelte", "vue"],
      boundary:
        "Multi-part collection rendering, portal/floating wiring, item text extraction, and scroll-arrow behavior remain component-template logic.",
      contractOwnedFacts: [
        "runtime bridge",
        "parts",
        "controlled state models",
        "events",
        "form input",
        "floating parts",
        "asChild trigger merge requirements",
      ],
      demotionCriteria:
        "Demote when shared collection and floating templates can render option/item structures without Select-specific branches.",
      reason:
        "Large multi-part floating controls would distort the first generic renderer if encoded before smaller categories settle.",
      tests: [
        "scripts/portable-runtime/tests/runtime-adapter-contract.test.ts",
        "scripts/portable-runtime/tests/generate-astro-wrappers.test.ts",
        "scripts/portable-runtime/tests/generate-react-wrappers.test.ts",
      ],
    },
  ],
} as const satisfies RuntimeAdapterContract;
