import type { RuntimeAdapterContract } from "../types.js";

export const sidebarRuntimeAdapterContract = {
  component: "sidebar",
  category: "presence-disclosure-control",
  displayName: "Sidebar",
  runtime: {
    factory: "createSidebarController",
    importSource: "@starwind-ui/runtime/sidebar",
    rootPart: "provider",
    optionProps: [
      "defaultMobileOpen",
      "defaultOpen",
      "keyboardShortcut",
      "mobileOpen",
      "mobileQuery",
      "onMobileOpenChange",
      "onOpenChange",
      "open",
      "persistOpen",
      "persistenceKey",
      "persistenceMaxAge",
      "persistenceStorage",
    ],
    optionPropLifecycles: {
      defaultMobileOpen: "constructor-only",
      defaultOpen: "constructor-only",
      keyboardShortcut: "constructor-only",
      mobileOpen: "setter-backed",
      mobileQuery: "constructor-only",
      onMobileOpenChange: "constructor-only",
      onOpenChange: "constructor-only",
      open: "setter-backed",
      persistOpen: "constructor-only",
      persistenceKey: "constructor-only",
      persistenceMaxAge: "constructor-only",
      persistenceStorage: "constructor-only",
    },
    destroys: true,
  },
  parts: [
    {
      name: "provider",
      defaultElement: "div",
      discoveryAttribute: "data-sw-sidebar-provider",
      forwardsRef: true,
      ownsRuntime: true,
      initialAttributes: [
        { name: "data-sw-sidebar-provider", source: "constant" },
        { name: "data-default-open", source: "prop" },
        { name: "data-default-mobile-open", source: "prop" },
        { name: "data-state", source: "state" },
        { name: "data-mobile-open", source: "state" },
        { name: "data-keyboard-shortcut", source: "prop" },
        { name: "data-mobile-query", source: "prop" },
        { name: "data-persist-open", source: "prop" },
        { name: "data-persistence-key", source: "prop" },
        { name: "data-persistence-storage", source: "prop" },
        { name: "data-persistence-max-age", source: "prop" },
      ],
    },
    {
      name: "sidebar",
      defaultElement: "div",
      discoveryAttribute: "data-sw-sidebar",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-sw-sidebar", source: "constant" },
        { name: "data-state", source: "state" },
        { name: "data-collapsible", source: "state" },
        { name: "data-collapsible-mode", source: "prop" },
        { name: "data-variant", source: "prop" },
        { name: "data-side", source: "prop" },
      ],
    },
    {
      name: "trigger",
      defaultElement: "button",
      discoveryAttribute: "data-sw-sidebar-trigger",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-sw-sidebar-trigger", source: "constant" },
        { name: "type", source: "constant", value: "button" },
        { name: "aria-expanded", source: "state" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "rail",
      defaultElement: "button",
      discoveryAttribute: "data-sw-sidebar-rail",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-sw-sidebar-rail", source: "constant" },
        { name: "type", source: "constant", value: "button" },
        { name: "aria-expanded", source: "state" },
        { name: "data-state", source: "state" },
        { name: "tabindex", source: "constant", value: "-1" },
      ],
    },
    {
      name: "menuButton",
      defaultElement: "button",
      discoveryAttribute: "data-sw-sidebar-menu-button",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-sw-sidebar-menu-button", source: "constant" },
        { name: "data-sidebar-state", source: "state" },
      ],
    },
  ],
  props: [
    { name: "open", kind: "control", targets: ["provider"], type: "boolean" },
    {
      defaultValue: "true",
      name: "defaultOpen",
      kind: "control",
      targets: ["provider"],
      type: "boolean",
    },
    { name: "mobileOpen", kind: "control", targets: ["provider"], type: "boolean" },
    {
      defaultValue: "false",
      name: "defaultMobileOpen",
      kind: "control",
      targets: ["provider"],
      type: "boolean",
    },
    {
      defaultValue: '"b"',
      name: "keyboardShortcut",
      kind: "option",
      targets: ["provider"],
      type: "string",
    },
    {
      defaultValue: '"(max-width: 767.98px)"',
      name: "mobileQuery",
      kind: "option",
      targets: ["provider"],
      type: "string",
    },
    {
      defaultValue: "false",
      name: "persistOpen",
      kind: "option",
      targets: ["provider"],
      type: "boolean",
    },
    {
      defaultValue: '"starwind-sidebar-open"',
      name: "persistenceKey",
      kind: "option",
      targets: ["provider"],
      type: "string",
    },
    {
      defaultValue: '"localStorage"',
      name: "persistenceStorage",
      kind: "option",
      targets: ["provider"],
      type: "SidebarPersistenceStorage",
    },
    {
      defaultValue: "604800",
      name: "persistenceMaxAge",
      kind: "option",
      targets: ["provider"],
      type: "number",
    },
    {
      name: "onOpenChange",
      kind: "callback",
      targets: ["provider"],
      type: "SidebarOpenChangeDetails",
    },
    {
      name: "onMobileOpenChange",
      kind: "callback",
      targets: ["provider"],
      type: "SidebarMobileOpenChangeDetails",
    },
    {
      defaultValue: '"left"',
      name: "side",
      kind: "attribute",
      targets: ["sidebar"],
      type: '"left" | "right"',
    },
    {
      defaultValue: '"sidebar"',
      name: "variant",
      kind: "attribute",
      targets: ["sidebar"],
      type: '"sidebar" | "floating" | "inset"',
    },
    {
      defaultValue: '"offcanvas"',
      name: "collapsible",
      kind: "attribute",
      targets: ["sidebar"],
      type: '"offcanvas" | "icon"',
    },
    {
      defaultValue: "false",
      name: "asChild",
      kind: "rendering",
      targets: ["trigger", "menuButton"],
      type: "boolean",
    },
  ],
  stateModels: [
    {
      name: "open",
      controlledProp: "open",
      defaultProp: "defaultOpen",
      initialAttribute: "data-default-open",
      runtimeGetter: "getOpen",
      runtimeSetter: "setOpen",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
    {
      name: "mobileOpen",
      controlledProp: "mobileOpen",
      defaultProp: "defaultMobileOpen",
      initialAttribute: "data-default-mobile-open",
      runtimeGetter: "getMobileOpen",
      runtimeSetter: "setMobileOpen",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
  ],
  events: [
    {
      name: "openChange",
      callbackProp: "onOpenChange",
      detailsType: "SidebarOpenChangeDetails",
      domEvent: "starwind:sidebar-change",
      emitsFrom: "provider",
      valueProperty: "open",
      valueType: "boolean",
    },
    {
      name: "mobileOpenChange",
      callbackProp: "onMobileOpenChange",
      detailsType: "SidebarMobileOpenChangeDetails",
      domEvent: "starwind:sidebar-mobile-change",
      emitsFrom: "provider",
      valueProperty: "open",
      valueType: "boolean",
    },
  ],
  setters: [
    { method: "setOpen", options: { emit: false }, stateModel: "open", suppressesEmit: true },
    {
      method: "setMobileOpen",
      options: { emit: false },
      stateModel: "mobileOpen",
      suppressesEmit: true,
    },
  ],
  refs: [
    { part: "provider", public: true },
    { part: "sidebar", public: true },
    { part: "trigger", public: true },
    { part: "rail", public: true },
    { part: "menuButton", public: true },
  ],
  asChild: [
    { part: "trigger", merges: ["aria", "className", "data", "ref"] },
    { part: "menuButton", merges: ["aria", "className", "data", "events", "ref"] },
  ],
  initialMarkup: [
    {
      part: "provider",
      attributes: [
        "data-sw-sidebar-provider",
        "data-default-open",
        "data-default-mobile-open",
        "data-state",
        "data-mobile-open",
        "data-keyboard-shortcut",
        "data-mobile-query",
        "data-persist-open",
        "data-persistence-key",
        "data-persistence-storage",
        "data-persistence-max-age",
      ],
      reason:
        "The provider needs initial desktop/mobile state, shortcut, media query, and opt-in persistence markers before hydration.",
    },
    {
      part: "sidebar",
      attributes: [
        "data-sw-sidebar",
        "data-state",
        "data-collapsible",
        "data-collapsible-mode",
        "data-variant",
        "data-side",
      ],
      reason:
        "The desktop sidebar uses initial state, collapsible mode, variant, and side attributes for layout before hydration.",
    },
    {
      part: "trigger",
      attributes: ["data-sw-sidebar-trigger", "type", "aria-expanded", "data-state"],
      reason:
        "Triggers need button semantics, expanded state, and discovery before listeners attach.",
    },
    {
      part: "rail",
      attributes: ["data-sw-sidebar-rail", "type", "aria-expanded", "data-state", "tabindex"],
      reason:
        "The resize rail acts as an unfocusable toggle target with stable expanded state before hydration.",
    },
    {
      part: "menuButton",
      attributes: ["data-sw-sidebar-menu-button", "data-sidebar-state"],
      reason: "Menu buttons receive the current sidebar state for icon-mode tooltip styling.",
    },
  ],
  frameworkNotes: {
    astro: [
      "Render uncontrolled provider markup and let the runtime own desktop/mobile state and persistence.",
    ],
    react: [
      "Bridge controlled desktop and mobile state through setOpen/setMobileOpen while retaining uncontrolled defaults.",
    ],
  },
  escapeHatches: [
    {
      affectedFrameworks: ["astro", "react", "solid", "svelte", "vue"],
      boundary:
        "The primitive owns only the behavior-bearing provider/sidebar/trigger/rail/menuButton parts. Styled wrappers own sidebar inset layout, mobile Sheet composition, headers, footers, groups, menu structure, badges, skeletons, separators, inputs, and submenu anatomy.",
      contractOwnedFacts: [
        "provider/sidebar/trigger/rail/menuButton parts and discovery attributes",
        "desktop open and mobile open state models",
        "open and mobile-open callback/event details",
        "desktop persistence option prop names",
        "styled-only sidebar anatomy boundary",
      ],
      demotionCriteria:
        "Demote additional sidebar anatomy only if it starts requiring runtime behavior beyond layout or styling.",
      reason:
        "Most sidebar pieces are styled composition, while provider state, triggers, rail, and menu-button state markers need shared runtime behavior.",
      tests: [
        "packages/runtime/src/components/sidebar/sidebar.browser.test.ts",
        "scripts/portable-runtime/tests/generator-structure.test.ts",
        "scripts/portable-runtime/tests/generate-astro-wrappers.test.ts",
        "scripts/portable-runtime/tests/generate-react-wrappers.test.ts",
      ],
    },
  ],
} as const satisfies RuntimeAdapterContract;
