import type { RuntimeAdapterContract } from "../types.js";

export const sliderRuntimeAdapterContract = {
  component: "slider",
  category: "form-value-control",
  displayName: "Slider",
  runtime: {
    factory: "createSlider",
    importSource: "@starwind-ui/runtime/slider",
    rootPart: "root",
    optionProps: [
      "defaultValue",
      "disabled",
      "form",
      "largeStep",
      "max",
      "min",
      "minStepsBetweenValues",
      "name",
      "orientation",
      "step",
      "value",
    ],
    optionPropLifecycles: {
      disabled: "setter-backed",
      form: "setter-backed",
      largeStep: "setter-backed",
      max: "setter-backed",
      min: "setter-backed",
      minStepsBetweenValues: "setter-backed",
      name: "setter-backed",
      orientation: "setter-backed",
      step: "setter-backed",
      value: "setter-backed",
    },
    destroys: true,
  },
  parts: [
    {
      name: "root",
      defaultElement: "div",
      discoveryAttribute: "data-sw-slider",
      forwardsRef: true,
      ownsRuntime: true,
      role: "group",
      initialAttributes: [
        { name: "data-default-value", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "data-form", source: "prop" },
        { name: "data-large-step", source: "prop" },
        { name: "data-max", source: "prop" },
        { name: "data-min", source: "prop" },
        { name: "data-min-steps-between-values", source: "prop" },
        { name: "data-name", source: "prop" },
        { name: "data-orientation", source: "prop" },
        { name: "data-step", source: "prop" },
        { name: "data-value", source: "state" },
      ],
    },
    {
      name: "control",
      defaultElement: "div",
      discoveryAttribute: "data-sw-slider-control",
      forwardsRef: true,
    },
    {
      name: "track",
      defaultElement: "div",
      discoveryAttribute: "data-sw-slider-track",
      forwardsRef: true,
    },
    {
      name: "indicator",
      defaultElement: "div",
      discoveryAttribute: "data-sw-slider-indicator",
      forwardsRef: true,
    },
    {
      name: "label",
      defaultElement: "span",
      discoveryAttribute: "data-sw-slider-label",
      forwardsRef: true,
    },
    {
      name: "thumb",
      defaultElement: "div",
      discoveryAttribute: "data-sw-slider-thumb",
      forwardsRef: true,
      initialAttributes: [{ name: "data-index", source: "prop" }],
    },
    {
      name: "input",
      defaultElement: "input",
      discoveryAttribute: "data-sw-slider-input",
      initialAttributes: [
        { name: "type", source: "constant", value: "range" },
        { name: "aria-hidden", source: "constant", value: "true" },
        { name: "tabIndex", source: "constant", value: "-1" },
      ],
    },
  ],
  props: [
    { name: "value", kind: "control", type: "SliderValue" },
    { defaultValue: "0", name: "defaultValue", kind: "control", type: "SliderValue" },
    { defaultValue: "false", name: "disabled", kind: "option", type: "boolean" },
    { name: "form", kind: "option", type: "string" },
    { defaultValue: "10", name: "largeStep", kind: "option", type: "number" },
    { defaultValue: "100", name: "max", kind: "option", type: "number" },
    { defaultValue: "0", name: "min", kind: "option", type: "number" },
    { defaultValue: "0", name: "minStepsBetweenValues", kind: "option", type: "number" },
    { name: "name", kind: "option", type: "string" },
    {
      defaultValue: '"horizontal"',
      name: "orientation",
      kind: "option",
      type: "SliderOrientation",
    },
    { defaultValue: "1", name: "step", kind: "option", type: "number" },
    { name: "onValueChange", kind: "callback", type: "SliderValueChangeDetails" },
    { name: "onValueCommitted", kind: "callback", type: "SliderValueCommitDetails" },
    { name: "index", kind: "attribute", targets: ["thumb"], type: "number" },
  ],
  stateModels: [
    {
      name: "value",
      controlledProp: "value",
      defaultProp: "defaultValue",
      initialAttribute: "data-default-value",
      runtimeGetter: "getValue",
      runtimeSetter: "setValue",
      valueType: "SliderValue",
      controlledStateSync: "unsupported",
    },
  ],
  events: [
    {
      name: "valueChange",
      callbackProp: "onValueChange",
      detailsType: "SliderValueChangeDetails",
      domEvent: "starwind:value-change",
      emitsFrom: "root",
      valueProperty: "value",
      valueType: "SliderValue",
    },
    {
      name: "valueCommitted",
      callbackProp: "onValueCommitted",
      detailsType: "SliderValueCommitDetails",
      domEvent: "starwind:value-committed",
      emitsFrom: "root",
      valueProperty: "value",
      valueType: "SliderValue",
    },
  ],
  setters: [
    { method: "setValue", options: { emit: false }, stateModel: "value", suppressesEmit: true },
    { method: "setDisabled", prop: "disabled" },
    { method: "setName", prop: "name" },
    {
      method: "setOptions",
      props: ["form", "largeStep", "max", "min", "minStepsBetweenValues", "orientation", "step"],
    },
  ],
  form: {
    hiddenInput: { part: "input", type: "range" },
    fieldIntegration: true,
    props: ["form", "name", "value"],
  },
  refs: [
    { part: "root", public: true },
    { part: "control", public: true },
    { part: "track", public: true },
    { part: "indicator", public: true },
    { part: "label", public: true },
    { part: "thumb", public: true },
  ],
  initialMarkup: [
    {
      part: "root",
      attributes: [
        "data-sw-slider",
        "role",
        "data-default-value",
        "data-min",
        "data-max",
        "data-step",
        "data-large-step",
        "data-min-steps-between-values",
        "data-orientation",
        "data-value",
      ],
      reason: "Range values and orientation styling must be present before controller hydration.",
    },
    {
      part: "label",
      attributes: ["data-sw-slider-label"],
      reason: "Visible labels can be linked to slider thumbs by the runtime after hydration.",
    },
    {
      part: "input",
      attributes: ["data-sw-slider-input", "type", "aria-hidden", "tabIndex"],
      reason:
        "Each thumb needs a nested range input placeholder so the runtime can wire form submission and input-change behavior.",
    },
  ],
  frameworkNotes: {
    astro: [
      "Render uncontrolled initial values; runtime owns range input state and form naming after hydration.",
      "Slider controlledness is fixed when the Runtime is created; do not switch between controlled and uncontrolled after hydration.",
    ],
    react: [
      "Bridge controlled values through setValue after refreshing thumbs so newly rendered range thumbs participate.",
      "Slider controlledness is fixed when the Runtime is created; do not switch between controlled and uncontrolled after mount.",
    ],
  },
  escapeHatches: [
    {
      affectedFrameworks: ["astro", "react", "solid", "svelte", "vue"],
      boundary:
        "The component template still owns SliderValue serialization, thumb/input nesting and visually-hidden style, React inputRef composition, creation-only form/range options, runtime-owned thumb ARIA/name/form reflection, and the refresh-before-controlled-sync timing.",
      contractOwnedFacts: [
        "component id",
        "display name",
        "runtime factory/import",
        "root/control/track/indicator/thumb/input parts and discovery attributes",
        "label part and discovery attribute",
        "public prop names and defaults",
        "value state model",
        "value-change and value-committed events/callback/details values",
        "value, disabled, name, and mutable options setter names",
        "form props, Field integration, and range input part",
        "initial root/input placeholder attributes",
      ],
      demotionCriteria:
        "Demote when a shared range-control template can express value serialization, nested form input refs, creation-only form/numeric options, runtime-owned thumb ARIA, and refresh timing across frameworks.",
      reason:
        "Slider is a form value control but its multi-thumb DOM choreography and native range input bridge are more specific than the current generic value-control templates.",
      tests: [
        "scripts/portable-runtime/tests/generator-structure.test.ts",
        "scripts/portable-runtime/tests/generate-astro-wrappers.test.ts",
        "scripts/portable-runtime/tests/generate-react-wrappers.test.ts",
      ],
    },
  ],
} as const satisfies RuntimeAdapterContract;
