import type { RuntimeAdapterContract } from "../types.js";

export const tooltipRuntimeAdapterContract = {
  component: "tooltip",
  category: "presence-floating-overlay",
  displayName: "Tooltip",
  runtime: {
    factory: "createTooltip",
    importSource: "@starwind-ui/runtime/tooltip",
    rootPart: "root",
    optionProps: [
      "closeDelay",
      "closeOnEscape",
      "closeOnOutsideInteract",
      "defaultOpen",
      "disabled",
      "disableHoverableContent",
      "onOpenChange",
      "open",
      "openDelay",
    ],
    optionPropLifecycles: {
      closeDelay: "constructor-only",
      closeOnEscape: "constructor-only",
      closeOnOutsideInteract: "constructor-only",
      defaultOpen: "constructor-only",
      disabled: "setter-backed",
      disableHoverableContent: "constructor-only",
      onOpenChange: "constructor-only",
      open: "setter-backed",
      openDelay: "constructor-only",
    },
    destroys: true,
  },
  parts: [
    {
      name: "root",
      defaultElement: "div",
      discoveryAttribute: "data-sw-tooltip",
      forwardsRef: true,
      ownsRuntime: true,
      initialAttributes: [
        { name: "data-default-open", source: "prop" },
        { name: "data-close-delay", source: "prop" },
        { name: "data-close-on-escape", source: "prop" },
        { name: "data-close-on-outside-interact", source: "prop" },
        { name: "data-content-hoverable", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "data-open-delay", source: "prop" },
        { name: "data-state", source: "state" },
      ],
    },
    {
      name: "trigger",
      defaultElement: "button",
      discoveryAttribute: "data-sw-tooltip-trigger",
      forwardsRef: true,
      initialAttributes: [
        { name: "type", source: "constant", value: "button" },
        { name: "data-as-child", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "aria-disabled", source: "prop" },
        { name: "data-state", source: "state" },
        { name: "disabled", source: "prop" },
      ],
    },
    {
      name: "portal",
      defaultElement: "div",
      discoveryAttribute: "data-sw-tooltip-portal",
      forwardsRef: true,
    },
    {
      name: "positioner",
      defaultElement: "div",
      discoveryAttribute: "data-sw-tooltip-positioner",
      forwardsRef: true,
      initialAttributes: [
        { name: "data-state", source: "state" },
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
      ],
    },
    {
      name: "popup",
      defaultElement: "div",
      discoveryAttribute: "data-sw-tooltip-popup",
      forwardsRef: true,
      role: "tooltip",
      initialAttributes: [
        { name: "role", source: "constant", value: "tooltip" },
        { name: "data-state", source: "state" },
        { name: "data-side", source: "prop" },
        { name: "data-align", source: "prop" },
        { name: "data-side-offset", source: "prop" },
        { name: "data-avoid-collisions", source: "prop" },
        { name: "hidden", source: "state" },
      ],
    },
    {
      name: "arrow",
      defaultElement: "div",
      discoveryAttribute: "data-sw-tooltip-arrow",
      forwardsRef: true,
      initialAttributes: [{ name: "data-state", source: "state" }],
    },
  ],
  props: [
    { name: "open", kind: "control", targets: ["root"], type: "boolean" },
    {
      defaultValue: "false",
      name: "defaultOpen",
      kind: "control",
      targets: ["root"],
      type: "boolean",
    },
    { defaultValue: "200", name: "closeDelay", kind: "option", type: "number" },
    { defaultValue: "true", name: "closeOnEscape", kind: "option", type: "boolean" },
    {
      defaultValue: "true",
      name: "closeOnOutsideInteract",
      kind: "option",
      type: "boolean",
    },
    { defaultValue: "false", name: "disabled", kind: "option", type: "boolean" },
    {
      defaultValue: "false",
      name: "disableHoverableContent",
      kind: "option",
      targets: ["root"],
      type: "boolean",
    },
    { defaultValue: "200", name: "openDelay", kind: "option", type: "number" },
    { name: "onOpenChange", kind: "callback", type: "TooltipOpenChangeDetails" },
    { name: "asChild", kind: "rendering", targets: ["trigger"], type: "boolean" },
    {
      defaultValue: '"top"',
      name: "side",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"top" | "right" | "bottom" | "left"',
    },
    {
      defaultValue: '"center"',
      name: "align",
      kind: "option",
      targets: ["positioner", "popup"],
      type: '"start" | "center" | "end"',
    },
    {
      defaultValue: "8",
      name: "sideOffset",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "number",
    },
    {
      defaultValue: "true",
      name: "avoidCollisions",
      kind: "option",
      targets: ["positioner", "popup"],
      type: "boolean",
    },
  ],
  stateModels: [
    {
      name: "open",
      controlledProp: "open",
      defaultProp: "defaultOpen",
      initialAttribute: "data-default-open",
      runtimeGetter: "getOpen",
      runtimeSetter: "setOpen",
      valueType: "boolean",
      controlledStateSync: "unsupported",
    },
  ],
  events: [
    {
      name: "openChange",
      callbackTiming: "before-state-commit",
      cancelable: true,
      callbackProp: "onOpenChange",
      detailsType: "TooltipOpenChangeDetails",
      domEvent: "starwind:open-change",
      emitsFrom: "root",
      valueProperty: "open",
      valueType: "boolean",
    },
  ],
  setters: [
    { method: "setOpen", options: { emit: false }, stateModel: "open", suppressesEmit: true },
    { method: "setDisabled", prop: "disabled" },
  ],
  presence: {
    initialHiddenParts: ["popup"],
    unmountPolicy: "runtime-owned",
  },
  floating: {
    anchorPart: "trigger",
    portalPart: "portal",
    positionerPart: "positioner",
    popupPart: "popup",
    optionProps: ["side", "align", "sideOffset", "avoidCollisions"],
  },
  refs: [
    { part: "root", public: true },
    { part: "trigger", public: true },
    { part: "portal", public: true },
    { part: "positioner", public: true },
    { part: "popup", public: true },
    { part: "arrow", public: true },
  ],
  asChild: [{ part: "trigger", merges: ["data", "ref"] }],
  initialMarkup: [
    {
      part: "root",
      attributes: [
        "data-sw-tooltip",
        "data-default-open",
        "data-close-delay",
        "data-close-on-escape",
        "data-close-on-outside-interact",
        "data-content-hoverable",
        "data-disabled",
        "data-open-delay",
        "data-state",
      ],
      reason:
        "The tooltip root needs timing, dismissal, disabled, hoverability, and initial state markers before hydration.",
    },
    {
      part: "trigger",
      attributes: [
        "data-sw-tooltip-trigger",
        "data-as-child",
        "data-disabled",
        "aria-disabled",
        "data-state",
        "disabled",
        "type",
      ],
      reason:
        "Triggers need disabled state and initial closed state before pointer/focus listeners attach.",
    },
    {
      part: "positioner",
      attributes: [
        "data-sw-tooltip-positioner",
        "data-state",
        "data-side",
        "data-align",
        "data-side-offset",
        "data-avoid-collisions",
      ],
      reason: "The positioner carries initial placement hints used by the shared floating runtime.",
    },
    {
      part: "popup",
      attributes: [
        "data-sw-tooltip-popup",
        "role",
        "data-state",
        "data-side",
        "data-align",
        "data-side-offset",
        "data-avoid-collisions",
        "hidden",
      ],
      reason:
        "The tooltip popup starts hidden with tooltip semantics and initial placement hints before hydration.",
    },
    {
      part: "arrow",
      attributes: ["data-sw-tooltip-arrow", "data-state"],
      reason: "The arrow receives state and placement updates from the floating runtime.",
    },
  ],
  frameworkNotes: {
    astro: [
      "Render static closed tooltip anatomy and self-initialize; runtime owns hover/focus timers, portal movement, and floating updates.",
    ],
    react: [
      "Create the controller with creation-time timing/dismissal options and bridge controlled open state through setOpen.",
    ],
  },
  escapeHatches: [
    {
      affectedFrameworks: ["astro", "react", "solid", "svelte", "vue"],
      boundary:
        "The component template still owns wrapper-style asChild rendering, creation-time option remount policy, controlled callback refs, portal/positioner/popup static composition, popup tabIndex omission, and initial closed placement attributes; the runtime owns hover/focus timers, raw trigger delay data-attribute escape hatches, Escape/outside intent events, non-interactive content guardrails, aria-describedby linking, delayed hide animations, portal movement, floating auto-update, transform origin, arrow placement state, and trigger target resolution.",
      contractOwnedFacts: [
        "component id",
        "display name",
        "runtime factory/import",
        "root/trigger/portal/positioner/popup/arrow parts and discovery attributes",
        "open state model",
        "open-change event/callback/details value",
        "open setter name and suppressed emit option",
        "root timing/dismissal/disabled option prop names and defaults",
        "floating placement prop names and defaults",
        "presence initial hidden popup",
        "trigger asChild support marker",
        "initial root/trigger/positioner/popup/arrow attributes",
      ],
      demotionCriteria:
        "Demote when a shared presence-floating overlay template can express creation-time option remount policy, trigger wrapper asChild, callback refs, static portal composition, tabIndex exclusion, and runtime-owned delayed hide/floating behavior across frameworks.",
      reason:
        "Tooltip is the smallest floating overlay, but its behavior is timer-, focus-, portal-, and floating-heavy enough that the first pass should keep component-template logic bounded.",
      tests: [
        "scripts/portable-runtime/tests/generator-structure.test.ts",
        "scripts/portable-runtime/tests/generate-astro-wrappers.test.ts",
        "scripts/portable-runtime/tests/generate-react-wrappers.test.ts",
      ],
    },
  ],
} as const satisfies RuntimeAdapterContract;
