/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type AccordionPanelProps = React.HTMLAttributes<HTMLDivElement>;

const AccordionPanel = React.forwardRef<HTMLDivElement, AccordionPanelProps>(
  function AccordionPanel({ style, ...props }, forwardedRef) {
    return (
      <div
        data-sw-accordion-content
        data-state="closed"
        hidden
        ref={forwardedRef}
        style={{ animation: "none", ...style }}
        {...props}
      />
    );
  },
);

AccordionPanel.displayName = "Accordion.Panel";

export default AccordionPanel;
