/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type AccordionItemProps = React.HTMLAttributes<HTMLDivElement> & {
  value?: string;
  disabled?: boolean;
};

const AccordionItem = React.forwardRef<HTMLDivElement, AccordionItemProps>(function AccordionItem(
  { value, disabled = false, ...props },
  forwardedRef,
) {
  return (
    <div
      data-sw-accordion-item
      data-value={value}
      data-disabled={disabled ? "" : undefined}
      data-state="closed"
      ref={forwardedRef}
      {...props}
    />
  );
});

AccordionItem.displayName = "Accordion.Item";

export default AccordionItem;
