/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import AccordionHeader from "./AccordionHeader";
import AccordionItem from "./AccordionItem";
import AccordionPanel from "./AccordionPanel";
import AccordionRoot from "./AccordionRoot";
import AccordionTrigger from "./AccordionTrigger";

const Accordion = {
  Root: AccordionRoot,
  Item: AccordionItem,
  Header: AccordionHeader,
  Trigger: AccordionTrigger,
  Panel: AccordionPanel,
};

export {
  Accordion,
  AccordionHeader,
  AccordionItem,
  AccordionPanel,
  AccordionRoot,
  AccordionTrigger,
};

export default Accordion;

export type { AccordionValue, AccordionValueChangeDetails } from "@starwind-ui/runtime";
