/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import { type InjectionKey, inject } from "vue";

export type AccordionItemContextValue = Readonly<{
  value: string | undefined;
  disabled: boolean;
}>;

export const accordionItemContextKey: InjectionKey<AccordionItemContextValue> =
  Symbol("StarwindAccordionItem");

export function useAccordionItemContext(componentName: string): AccordionItemContextValue {
  const context = inject(accordionItemContextKey);
  if (!context) {
    throw new Error(`${componentName} must be used within AccordionItem.`);
  }
  return context;
}
