<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { provide, ref } from "vue";
import { type AccordionItemContextValue, accordionItemContextKey } from "./AccordionItemContext";

defineOptions({ inheritAttrs: false });
const props = withDefaults(defineProps<{ value?: string; disabled?: boolean }>(), {
  value: undefined,
  disabled: false,
});
defineSlots<{ default?: () => unknown }>();
const element = ref<HTMLDivElement | null>(null);
const itemContext: AccordionItemContextValue = {
  get value() {
    return props.value;
  },
  get disabled() {
    return props.disabled;
  },
};
provide(accordionItemContextKey, itemContext);
defineExpose({ element });
</script>

<template>
  <div
    ref="element"
    v-bind="$attrs"
    data-sw-accordion-item
    data-sw-part="item"
    :data-value="props.value"
    :data-disabled="props.disabled ? '' : undefined"
    data-state="closed"
  >
    <slot />
  </div>
</template>
