<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();
const element = ref<HTMLElement | null>(null);
defineExpose({ element });
</script>

<template>
  <h3 ref="element" v-bind="$attrs" data-sw-accordion-header data-sw-part="header">
    <slot />
  </h3>
</template>
