<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script module lang="ts">
  import { getContext, setContext } from "svelte";
  import { createAvatar } from "@starwind-ui/runtime/avatar";
  const contextKey = Symbol("Avatar");
  type Instance = ReturnType<typeof createAvatar>;
  type Context = { readonly instance: Instance | null; requestRefresh(): void };
  export function getMediaContext(): Context | undefined { return getContext(contextKey); }
</script>
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { Attachment } from "svelte/attachments";
  type Props = HTMLAttributes<HTMLSpanElement> & { children?: Snippet; ref?: (element: HTMLSpanElement | null) => void };
  let { children, ref, ...rest }: Props = $props();
  let rootNode = $state.raw<HTMLSpanElement | null>(null);
  let instance = $state.raw<Instance | null>(null);
  let refreshPending = false;
  function requestRefresh(): void {
    const owner = instance;
    if (!owner || refreshPending) return;
    refreshPending = true;
    queueMicrotask(() => {
      refreshPending = false;
      if (instance === owner && rootNode === owner.root) owner.refresh();
    });
  }
  setContext<Context>(contextKey, {
    get instance() { return instance; },
    requestRefresh,
  });
  const attachRoot: Attachment<HTMLSpanElement> = (element) => {
    rootNode = element;
    return () => { rootNode = null; };
  };
  $effect(() => {
    const element = rootNode;
    if (!element) return;
    const controller = untrack(() => createAvatar(element));
    instance = controller;
    return () => { instance = null; controller.destroy(); };
  });
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLSpanElement>(() => ref);
</script>
<span {...rest} data-sw-avatar data-image-loading-status="idle" {@attach attachRoot} {@attach attachRef}>
  {@render children?.()}
</span>
