<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { HTMLImgAttributes } from "svelte/elements";
  import type { Attachment } from "svelte/attachments";
  import { getMediaContext } from "./AvatarRoot.svelte";
  import type { AvatarImageLoadingStatus, AvatarLoadingStatusChangeDetails } from "@starwind-ui/runtime/avatar";
  type Props = Omit<HTMLImgAttributes, "children" | "alt"> & {
    ref?: (element: HTMLImageElement | null) => void;
    alt: string; onLoadingStatusChange?: (status: AvatarImageLoadingStatus, details: AvatarLoadingStatusChangeDetails) => void;
  };
  let { ref, alt, style, onLoadingStatusChange, ...rest }: Props = $props();
  const context = getMediaContext();
  // Preserve Runtime's committed visibility when caller styles change.
  const initialStyle = untrack(() => style);
  const attachPart: Attachment<HTMLImageElement> = (element) => {
    untrack(() => context?.requestRefresh());
    $effect(() => {
      const value = style;
      untrack(() => {
        const visibility = element.style.visibility;
        element.style.cssText = value ?? "";
        element.style.visibility = visibility;
      });
    });
    return () => context?.requestRefresh();
  };
  $effect(() => {
    const controller = context?.instance;
    if (!controller) return;
    const notify = (details: AvatarLoadingStatusChangeDetails) => untrack(() => onLoadingStatusChange?.(details.status, details));
    const unsubscribe = controller.subscribe("loadingStatusChange", notify);
untrack(() => { const status = controller.getImageLoadingStatus();
if (status && status !== "idle") {
  notify({ previousStatus: "idle", status });
} });
    return unsubscribe;
  });
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLImageElement>(() => ref);
</script>
<img {...rest} data-sw-avatar-image alt={alt} data-image-loading-status="idle" style={(initialStyle ?? "") + "; visibility: hidden !important"} hidden={false} {@attach attachPart} {@attach attachRef} />
