/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import AvatarRoot from "./AvatarRoot.svelte";
import AvatarImage from "./AvatarImage.svelte";
import AvatarFallback from "./AvatarFallback.svelte";
const Avatar = { Fallback: AvatarFallback, Image: AvatarImage, Root: AvatarRoot };
export { Avatar, AvatarRoot, AvatarImage, AvatarFallback };
export default Avatar;
export type {
  AvatarImageLoadingStatus,
  AvatarLoadingStatusChangeDetails,
} from "@starwind-ui/runtime/avatar";
