/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type AlertDialogTriggerProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  targetId?: string;
};

const AlertDialogTrigger = React.forwardRef<HTMLButtonElement, AlertDialogTriggerProps>(
  function AlertDialogTrigger({ targetId, ...props }, forwardedRef) {
    return (
      <button
        type="button"
        data-sw-alert-dialog-trigger
        aria-haspopup="dialog"
        data-sw-alert-dialog-target-id={targetId}
        data-state="closed"
        ref={forwardedRef}
        {...props}
      />
    );
  },
);

AlertDialogTrigger.displayName = "AlertDialog.Trigger";

export default AlertDialogTrigger;
