/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type AlertDialogCloseProps = React.ButtonHTMLAttributes<HTMLButtonElement>;

const AlertDialogClose = React.forwardRef<HTMLButtonElement, AlertDialogCloseProps>(
  function AlertDialogClose(props, forwardedRef) {
    return <button type="button" data-sw-alert-dialog-close ref={forwardedRef} {...props} />;
  },
);

AlertDialogClose.displayName = "AlertDialog.Close";

export default AlertDialogClose;
