/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type AlertDialogPortalProps = React.HTMLAttributes<HTMLDivElement>;

const AlertDialogPortal = React.forwardRef<HTMLDivElement, AlertDialogPortalProps>(
  function AlertDialogPortal(props, forwardedRef) {
    return <div data-sw-alert-dialog-portal ref={forwardedRef} {...props} />;
  },
);

AlertDialogPortal.displayName = "AlertDialog.Portal";

export default AlertDialogPortal;
