/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import * as React from "react";
import { useNativeOverlayControl } from "../internal/native-overlay-control";
import { NativeOverlayControlContext } from "./AlertDialogRoot";

export type AlertDialogTriggerProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  asChild?: boolean;
  targetId?: string;
};

const AlertDialogTrigger = React.forwardRef<HTMLButtonElement, AlertDialogTriggerProps>(
  function AlertDialogTrigger(
    { asChild = false, children, className, targetId, ...props },
    forwardedRef,
  ) {
    const requestRefresh = React.useContext(NativeOverlayControlContext);
    const { controlKey, setControlElement } = useNativeOverlayControl({
      asChild,
      children,
      forwardedRef,
      requestRefresh,
    });

    if (asChild) {
      return (
        <div
          className={className}
          data-as-child
          data-sw-alert-dialog-target-id={targetId}
          {...(props as React.HTMLAttributes<HTMLDivElement>)}
          data-sw-alert-dialog-trigger
          key={controlKey}
          ref={setControlElement}
        >
          {children}
        </div>
      );
    }

    return (
      <button
        type="button"
        data-sw-alert-dialog-trigger
        aria-haspopup="dialog"
        data-sw-alert-dialog-target-id={targetId}
        data-state="closed"
        className={className}
        ref={setControlElement as React.Ref<HTMLButtonElement>}
        {...props}
      >
        {children}
      </button>
    );
  },
);

AlertDialogTrigger.displayName = "AlertDialog.Trigger";

export default AlertDialogTrigger;
