/**
 * Authored descriptions for styled props whose meaning is consistent across components.
 * Component-specific semantics belong in `StyledDocsAnnotation.styledApi` instead.
 */
export const commonStyledPropDescriptions: Readonly<Record<string, string>> = {
  activateOnFocus: "Activates the focused item while moving through the collection.",
  active: "Marks the item as the currently active destination.",
  align: "Aligns the component within its available axis.",
  alignItemWithTrigger: "Aligns the selected item with the trigger when the popup opens.",
  alignOffset: "Offsets the component from its selected alignment in pixels.",
  alt: "Provides alternative text for the rendered image.",
  appearance: "Selects the component's visual treatment.",
  ariaLabel: "Provides an accessible label when visible text is not available.",
  as: "Selects the rendered element or component.",
  asChild: "Merges the component behavior and props into its child element.",
  autoComplete: "Provides the browser autocomplete token used by the control.",
  autoInit: "Controls whether Runtime behavior initializes automatically.",
  autoPlay: "Starts media playback automatically when supported by the browser.",
  autoplay: "Starts media playback automatically when supported by the browser.",
  avoidCollisions: "Repositions floating content to keep it inside the collision boundary.",
  checked: "Controls whether the choice is checked.",
  closeDelay: "Sets the delay in milliseconds before closing.",
  closeOnClick: "Closes the containing surface after the item is activated.",
  closeOnEscape: "Allows the surface to close when Escape is pressed.",
  closeOnOutsideInteract: "Allows the surface to close after an outside interaction.",
  collapsible: "Selects how the component can collapse.",
  collisionPadding: "Sets the minimum space retained around a collision boundary.",
  controls: "Shows the browser's native media controls.",
  defaultChecked: "Sets the initial checked state when the choice is uncontrolled.",
  defaultInputValue: "Sets the initial input text when the control is uncontrolled.",
  defaultMobileOpen: "Sets the initial mobile open state when uncontrolled.",
  defaultOpen: "Sets the initial open state when the component is uncontrolled.",
  defaultPressed: "Sets the initial pressed state when the control is uncontrolled.",
  defaultValue: "Sets the initial value when the component is uncontrolled.",
  delay: "Sets the delay in milliseconds before the behavior begins.",
  dirty: "Marks the field as changed from its initial value.",
  disableHoverableContent: "Prevents pointer movement into floating content from keeping it open.",
  disabled: "Disables interaction with the component.",
  duration: "Sets the display or transition duration in milliseconds.",
  errorVisibility: "Selects when validation errors become visible.",
  exitMotion: "Selects the motion treatment used while floating content closes.",
  eyebrow: "Uses the compact uppercase eyebrow text treatment.",
  filterMode: "Selects how typed text is matched against available options.",
  focusableWhenDisabled: "Keeps the disabled control in the keyboard focus order.",
  form: "Associates the control with a form by id.",
  gap: "Sets the space between repeated items.",
  highlightItemOnHover: "Highlights collection items as the pointer moves over them.",
  iconClass: "Adds classes to the component's generated icon.",
  id: "Sets the element id used by labels and related controls.",
  image: "Provides Astro image metadata for optimized image rendering.",
  indeterminate: "Shows the mixed checkbox state.",
  index: "Identifies the item's zero-based position in the collection.",
  indicatorClass: "Adds classes to the generated selection indicator.",
  inferSize: "Infers missing image dimensions from the source when possible.",
  inputValue: "Controls the current editable input text.",
  inset: "Adds leading inset spacing for visual alignment.",
  invalid: "Marks the field as invalid.",
  isActive: "Applies the active visual state.",
  isUploading: "Shows that an upload is currently in progress.",
  keepMounted: "Keeps hidden content mounted in the DOM.",
  keyboardShortcut: "Sets the keyboard key used by the component shortcut.",
  label: "Provides accessible text for the component.",
  largeStep: "Sets the larger keyboard step increment.",
  legend: "Provides accessible text for the grouped choices.",
  limit: "Limits the number of simultaneously rendered items.",
  locale: "Selects the locale used for text comparison and formatting.",
  loop: "Restarts media playback after it reaches the end.",
  loopFocus: "Wraps keyboard focus from the last item to the first and vice versa.",
  match: "Selects the validation state that renders this message.",
  max: "Sets the maximum accepted value.",
  maxLength: "Sets the maximum number of accepted characters.",
  messageSource: "Selects whether the message comes from children or browser validation.",
  min: "Sets the minimum accepted value.",
  mobileOpen: "Controls the mobile open state.",
  mobileQuery: "Sets the media query used to enter the mobile layout.",
  modal: "Controls whether interaction outside the surface is blocked while open.",
  multiple: "Allows more than one value to be selected.",
  muted: "Starts or renders media with audio muted.",
  name: "Sets the form field name.",
  nativeButton: "Uses native button semantics for the interactive control.",
  onCheckedChange: "Runs after the checked state changes.",
  onCloseComplete: "Runs after the closing transition and cleanup complete.",
  onFilesChange: "Runs when the selected file collection changes.",
  onFormatChange: "Runs after the accepted color format changes.",
  onInputValueChange: "Runs when the editable input text changes.",
  onLoadingStatusChange: "Runs when image loading status changes.",
  onMobileOpenChange: "Runs when the mobile open state changes.",
  onOpenChange: "Runs when the open state changes.",
  onPressedChange: "Runs when the pressed state changes.",
  onValueChange: "Runs when the component value changes.",
  onValueCommitted: "Runs when an interaction commits its final value.",
  open: "Controls the open state.",
  openDelay: "Sets the delay in milliseconds before opening.",
  openOnHover: "Allows pointer hover to open the surface.",
  opts: "Provides options to the underlying carousel engine.",
  orientation: "Selects the horizontal or vertical layout direction.",
  overflowEdgeThreshold: "Sets the distance from an edge that counts as overflow.",
  padding: "Sets the component's internal padding.",
  pattern: "Sets the accepted input pattern.",
  peek: "Sets how much of an adjacent item remains visible.",
  persistOpen: "Persists the open state between visits.",
  persistenceKey: "Sets the storage key used for persisted state.",
  persistenceMaxAge: "Sets the maximum persisted-state age in seconds.",
  persistenceStorage: "Selects where persisted state is stored.",
  placeholder: "Provides fallback text when no value is available.",
  plugins: "Provides plugins to the underlying carousel engine.",
  position: "Selects the viewport position used by the component.",
  poster: "Provides the image displayed before video playback starts.",
  pressed: "Controls the pressed state.",
  ratio: "Sets the rendered width-to-height ratio.",
  readOnly: "Prevents value changes while preserving focus and submission behavior.",
  required: "Marks the control as required for form validation.",
  revalidationTiming: "Selects when a previously validated field is validated again.",
  setApi: "Receives the initialized carousel API.",
  showClear: "Shows the generated clear-value control.",
  showIcon: "Shows the component's generated icon.",
  showIndicator: "Shows the generated selection indicator.",
  showOnHover: "Reveals the action when its containing item is hovered.",
  showTrigger: "Shows the generated popup trigger.",
  side: "Selects the preferred side for floating content.",
  sideOffset: "Sets the distance in pixels between floating content and its anchor.",
  size: "Selects the component's visual size.",
  spacing: "Sets the space between grouped controls.",
  src: "Provides the media source URL.",
  step: "Sets the smallest allowed value increment.",
  syncGroup: "Groups controls that synchronize the same state.",
  syncKey: "Sets the key used to synchronize state across matching controls.",
  targetId: "Identifies the surface controlled by the trigger.",
  title: "Provides an accessible title for embedded media.",
  tone: "Selects the component's semantic color tone.",
  tooltip: "Provides tooltip content for the control.",
  touched: "Marks the field as having received user interaction.",
  type: "Selects the component's interaction or selection mode.",
  uncheckedValue: "Sets the form value submitted for an unchecked control.",
  validationTiming: "Selects when validation first runs.",
  value: "Controls or identifies the component value.",
  valueClass: "Adds classes to the generated value element.",
  variant: "Selects the component's visual variant.",
  viewportClass: "Adds classes to the generated viewport element.",
  viewportClassName: "Adds React classes to the generated viewport element.",
  width: "Sets the component width.",
};
