/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

export type { ThemeInitScriptOptions } from "@starwind-ui/runtime/theme";
/** The document owner destroys the shared controller on teardown. Mounted controls only resynchronize it. */
export { getThemeInitScript, initThemeController } from "@starwind-ui/runtime/theme";
