/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import * as React from "react";
import { useSidebarContext } from "./SidebarContext";

export type SidebarRailProps = React.ButtonHTMLAttributes<HTMLButtonElement>;

const SidebarRail = React.forwardRef<HTMLButtonElement, SidebarRailProps>(
  function SidebarRail(props, forwardedRef) {
    const sidebarContext = useSidebarContext();

    return (
      <button
        {...props}
        data-sw-sidebar-rail={""}
        data-sw-part={"rail"}
        data-state={sidebarContext?.state ?? "expanded"}
        aria-expanded={sidebarContext?.expanded ?? false}
        type={"button"}
        tabIndex={-1}
        ref={forwardedRef}
      />
    );
  },
);

SidebarRail.displayName = "Sidebar.Rail";

export default SidebarRail;
