/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type SidebarContextValue = {
  expanded: boolean;
  mobileOpen: boolean;
  open: boolean;
  state: "collapsed" | "expanded";
};

export const SidebarContext = React.createContext<SidebarContextValue | null>(null);

export function useSidebarContext(): SidebarContextValue | null {
  return React.useContext(SidebarContext);
}
