<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->

<script lang="ts">import{createToggleGroup,type ToggleGroupValueChangeDetails,type ToggleGroupValue}from'@starwind-ui/runtime/toggle-group';import{onMount,untrack,setContext,type Snippet}from'svelte';import type{HTMLAttributes}from'svelte/elements';import{ToggleGroupContext,type ToggleGroupContextValue}from'../toggle/ToggleRoot.svelte';
type RootElement=HTMLDivElement;
type Props=Omit<HTMLAttributes<HTMLDivElement>,'children'|'defaultValue'|'onChange'> & {defaultValue?:ToggleGroupValue;
disabled?:boolean;
loopFocus?:boolean;
multiple?:boolean;
orientation?:"horizontal" | "vertical";
value?:ToggleGroupValue;children?:Snippet;ref?:(node:HTMLDivElement|null)=>void;onValueChange?:(value:ToggleGroupValue,detail:ToggleGroupValueChangeDetails)=>void};let{children,ref,defaultValue,disabled=false,loopFocus=true,multiple=false,orientation="horizontal",value=$bindable(),onValueChange,...rest}:Props=$props();const initialDefault=untrack(()=>normalizeValue(defaultValue??[],multiple));let renderedValue=$state<ToggleGroupValue>(initialDefault),rootElement=$state<RootElement>(),ready=$state(false);const connection:{instance?:ReturnType<typeof createToggleGroup>;unsubscribe?:()=>void;observer?:MutationObserver;ownDisabled?:boolean;accepted:ToggleGroupValue}={accepted:initialDefault};

let effectiveDisabled=$derived(disabled);let selected=$derived(normalizeValue(value??renderedValue,multiple));setContext<ToggleGroupContextValue>(ToggleGroupContext,{get value(){return selected;},get disabled(){return disabled;}});function normalizeValue(value:string[],multiple:boolean){const next=Array.from(new Set(value.filter(item=>item.length>0)));return multiple?next:next.slice(0,1);}
function isModelEqual(left:string[]|undefined,right:string[]|undefined){return left===right||left!==undefined&&right!==undefined&&left.length===right.length&&left.every((entry,index)=>entry===right[index]);}
function copyModel(value:string[]){return [...value];}
function disconnect(){const owned=connection.instance;connection.observer?.disconnect();connection.observer=undefined;connection.unsubscribe?.();connection.unsubscribe=undefined;connection.instance=undefined;owned?.destroy();}
function publishReadback(owned:ReturnType<typeof createToggleGroup>){if(connection.instance!==owned)return;const next=owned.getValue();if(!isModelEqual(connection.accepted,next)){connection.accepted=next;renderedValue=next;}if (!isModelEqual(value, next)) value = copyModel(next);if(connection.instance!==owned)return;const canonical=value;if(canonical!==undefined&&!isModelEqual(canonical,next)){owned.setValue(normalizeValue(canonical,multiple),{emit:false});const retained=owned.getValue();connection.accepted=retained;renderedValue=retained;}}
function connect(root:HTMLDivElement){disconnect();const desired=normalizeValue(value??initialDefault,multiple);const owned=createToggleGroup(root,{defaultValue:desired,disabled:disabled,loopFocus:loopFocus,multiple:multiple,orientation:orientation,...(false?{value:desired}:{}),onValueChange:(next,detail)=>{untrack(() => { onValueChange?.(next, detail); });}});connection.instance=owned;
connection.unsubscribe=owned.subscribe('valueChange',detail=>{if(connection.instance!==owned||detail.isCanceled)return;untrack(() => { publishReadback(owned); });});
connection.observer=new MutationObserver(()=>{untrack(() => { publishReadback(owned); });});connection.observer.observe(root,{attributes:true,attributeFilter:['data-value']});publishReadback(owned);}
function applyParent(){const owned=connection.instance,input=value;if(!owned||input===undefined)return;const next=normalizeValue(input,multiple);if(isModelEqual(owned.getValue(),next))return;owned.setValue(next,{emit:false});publishReadback(owned);}
function applyOptions(){const owned=connection.instance;if(!owned)return;owned.refresh();
owned.setDisabled(disabled);
owned.setLoopFocus(loopFocus);
owned.setMultiple(multiple);
owned.setOrientation(orientation);
applyParent();
publishReadback(owned);}
onMount(()=>{let alive=true;queueMicrotask(()=>{if(!alive)return;untrack(()=>{if(rootElement)connect(rootElement);ready=true;});});return()=>{alive=false;ready=false;disconnect();};});
$effect(()=>{ready;disabled;loopFocus;multiple;orientation;untrack(applyOptions);});
$effect(()=>{ready;value;multiple;untrack(applyParent);});$effect(()=>{const node=rootElement,callback=ref as ((node:RootElement|null)=>void)|undefined;if(!node||!ready)return;untrack(()=>callback?.(node));return()=>untrack(()=>callback?.(null));});
</script><div bind:this={rootElement} {...rest} data-sw-toggle-group="" data-sw-part="root" data-default-value={initialDefault.length ? JSON.stringify(initialDefault) : undefined} data-value={JSON.stringify(selected)} data-disabled={effectiveDisabled ? "" : undefined} data-loop-focus={loopFocus ? undefined : "false"} data-multiple={multiple ? "" : undefined} data-orientation={orientation} role="group">{@render children?.()}</div>
