/**
 * Generated by scripts/portable-runtime/generate-astro-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import SelectGroup from "./SelectGroup.astro";
import SelectGroupLabel from "./SelectGroupLabel.astro";
import SelectIcon from "./SelectIcon.astro";
import SelectItem from "./SelectItem.astro";
import SelectItemIndicator from "./SelectItemIndicator.astro";
import SelectItemText from "./SelectItemText.astro";
import SelectLabel from "./SelectLabel.astro";
import SelectList from "./SelectList.astro";
import SelectPopup from "./SelectPopup.astro";
import SelectPortal from "./SelectPortal.astro";
import SelectPositioner from "./SelectPositioner.astro";
import SelectRoot from "./SelectRoot.astro";
import SelectScrollDownArrow from "./SelectScrollDownArrow.astro";
import SelectScrollUpArrow from "./SelectScrollUpArrow.astro";
import SelectSeparator from "./SelectSeparator.astro";
import SelectTrigger from "./SelectTrigger.astro";
import SelectValue from "./SelectValue.astro";

const Select = {
  Root: SelectRoot,
  Label: SelectLabel,
  Trigger: SelectTrigger,
  Value: SelectValue,
  Icon: SelectIcon,
  Portal: SelectPortal,
  Positioner: SelectPositioner,
  Popup: SelectPopup,
  List: SelectList,
  Group: SelectGroup,
  GroupLabel: SelectGroupLabel,
  Item: SelectItem,
  ItemText: SelectItemText,
  ItemIndicator: SelectItemIndicator,
  Separator: SelectSeparator,
  ScrollUpArrow: SelectScrollUpArrow,
  ScrollDownArrow: SelectScrollDownArrow,
};

export {
  Select,
  SelectGroup,
  SelectGroupLabel,
  SelectIcon,
  SelectItem,
  SelectItemIndicator,
  SelectItemText,
  SelectLabel,
  SelectList,
  SelectPopup,
  SelectPortal,
  SelectPositioner,
  SelectRoot,
  SelectScrollDownArrow,
  SelectScrollUpArrow,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
};

export default Select;

export type { SelectOpenChangeDetails, SelectValueChangeDetails } from "@starwind-ui/runtime";
