/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";
import { useColorPickerPartProjection } from "./ColorPickerRoot";

export type ColorPickerSwatchGroupProps = React.ComponentPropsWithoutRef<"div"> & {
  children?: React.ReactNode;
};

const ColorPickerSwatchGroup = React.forwardRef<HTMLDivElement, ColorPickerSwatchGroupProps>(
  function ColorPickerSwatchGroup({ children, ...props }, forwardedRef) {
    const { props: projectedProps } = useColorPickerPartProjection(
      { part: "swatchGroup" },
      { ...props, "data-sw-color-picker-swatch-group": "" },
    );
    return (
      <div {...projectedProps} ref={forwardedRef}>
        {children}
      </div>
    );
  },
);

ColorPickerSwatchGroup.displayName = "ColorPicker.SwatchGroup";

export default ColorPickerSwatchGroup;
