/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";
import { useColorPickerAreaContext, useColorPickerPartProjection } from "./ColorPickerRoot";

export type ColorPickerAreaInputProps = React.ComponentPropsWithoutRef<"input"> & {
  axis?: "x" | "y";
  step?: number;
};

const ColorPickerAreaInput = React.forwardRef<HTMLInputElement, ColorPickerAreaInputProps>(
  function ColorPickerAreaInput({ axis = "x", step, ...props }, forwardedRef) {
    const areaContext = useColorPickerAreaContext();
    const { props: projectedProps } = useColorPickerPartProjection(
      {
        part: "areaInput",
        ...areaContext,
        axis,
        ...(axis === "x"
          ? { xStep: step ?? areaContext.xStep }
          : { yStep: step ?? areaContext.yStep }),
      },
      {
        ...props,
        "data-sw-color-picker-area-input": "",
        "data-axis": axis,
        "data-step": step ?? (axis === "x" ? areaContext.xStep : areaContext.yStep),
      },
    );
    return <input {...projectedProps} ref={forwardedRef} />;
  },
);

ColorPickerAreaInput.displayName = "ColorPicker.AreaInput";

export default ColorPickerAreaInput;
