/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import * as React from "react";
import { useColorPickerAreaContext, useColorPickerPartProjection } from "./ColorPickerRoot";

export type ColorPickerAreaBackgroundProps = React.ComponentPropsWithoutRef<"div"> & {
  children?: React.ReactNode;
};

const ColorPickerAreaBackground = React.forwardRef<HTMLDivElement, ColorPickerAreaBackgroundProps>(
  function ColorPickerAreaBackground({ children, ...props }, forwardedRef) {
    const areaContext = useColorPickerAreaContext();
    const { props: projectedProps } = useColorPickerPartProjection(
      {
        part: "areaBackground",
        xChannel: areaContext.xChannel,
        yChannel: areaContext.yChannel,
        xStep: areaContext.xStep,
        yStep: areaContext.yStep,
      },
      { ...props, "data-sw-color-picker-area-background": "" },
    );
    return (
      <div {...projectedProps} ref={forwardedRef}>
        {children}
      </div>
    );
  },
);

ColorPickerAreaBackground.displayName = "ColorPicker.AreaBackground";

export default ColorPickerAreaBackground;
