/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import type { ColorPickerValue } from "@starwind-ui/runtime/color-picker";
import * as React from "react";
import { useColorPickerPartProjection } from "./ColorPickerRoot";

export type ColorPickerSwatchProps = React.ComponentPropsWithoutRef<"button"> & {
  children?: React.ReactNode;
  swatchValue: ColorPickerValue;
  swatchDisabled?: boolean;
};

const ColorPickerSwatch = React.forwardRef<HTMLButtonElement, ColorPickerSwatchProps>(
  function ColorPickerSwatch(
    { children, swatchValue, swatchDisabled = false, ...props },
    forwardedRef,
  ) {
    const { props: projectedProps } = useColorPickerPartProjection(
      { part: "swatch", value: swatchValue, disabled: swatchDisabled },
      {
        ...props,
        "data-sw-color-picker-swatch": "",
        "data-value":
          typeof swatchValue === "string" ? swatchValue : (swatchValue?.toString() ?? undefined),
        "data-disabled": swatchDisabled ? "" : undefined,
      },
    );
    return (
      <button {...projectedProps} ref={forwardedRef}>
        {children}
      </button>
    );
  },
);

ColorPickerSwatch.displayName = "ColorPicker.Swatch";

export default ColorPickerSwatch;
