/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";
import { useColorPickerPartProjection } from "./ColorPickerRoot";

export type ColorPickerLabelProps = React.ComponentPropsWithoutRef<"span"> & {
  children?: React.ReactNode;
};

const ColorPickerLabel = React.forwardRef<HTMLSpanElement, ColorPickerLabelProps>(
  function ColorPickerLabel({ children, ...props }, forwardedRef) {
    const { props: projectedProps } = useColorPickerPartProjection(
      { part: "label" },
      { ...props, "data-sw-color-picker-label": "" },
    );
    return (
      <span {...projectedProps} ref={forwardedRef}>
        {children}
      </span>
    );
  },
);

ColorPickerLabel.displayName = "ColorPicker.Label";

export default ColorPickerLabel;
