/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import { createButton } from "@starwind-ui/runtime/button";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export type ButtonRootProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  disabled?: boolean;
  focusableWhenDisabled?: boolean;
  type?: React.ButtonHTMLAttributes<HTMLButtonElement>["type"];
};

const ButtonRoot = React.forwardRef<HTMLButtonElement, ButtonRootProps>(function ButtonRoot(
  { disabled = false, focusableWhenDisabled = false, type, ...props },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLButtonElement>(null);
  const instanceRef = React.useRef<ReturnType<typeof createButton> | null>(null);
  const disabledRef = React.useRef(disabled);
  disabledRef.current = disabled;

  const composedRef = React.useCallback(
    (node: HTMLButtonElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  useIsomorphicLayoutEffect(() => {
    if (!focusableWhenDisabled) {
      instanceRef.current?.destroy();
      instanceRef.current = null;
      return;
    }

    const root = rootRef.current;
    if (!root) return;

    const instance = createButton(root, {
      disabled: disabledRef.current,
    });
    instanceRef.current = instance;

    return () => {
      if (instanceRef.current === instance) {
        instanceRef.current = null;
      }
      instance.destroy();
    };
  }, [focusableWhenDisabled]);

  useIsomorphicLayoutEffect(() => {
    instanceRef.current?.setDisabled(disabled);
  }, [disabled]);

  return (
    <button
      data-focusable-when-disabled={focusableWhenDisabled ? "true" : undefined}
      aria-disabled={disabled && focusableWhenDisabled ? "true" : undefined}
      data-disabled={disabled ? "" : undefined}
      disabled={disabled && !focusableWhenDisabled}
      ref={composedRef}
      type={type ?? "button"}
      {...props}
      data-sw-button
    />
  );
});

ButtonRoot.displayName = "Button.Root";

export default ButtonRoot;
