<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Svelte proof output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";

  type Props = Omit<HTMLAttributes<HTMLDialogElement>, "children"> & { children?: Snippet;  ref?: (element: HTMLDialogElement | null) => void };
  let { children, ref, ...rest }: Props = $props();
  const attachRef: Attachment<HTMLDialogElement> = (element) => {
    const callback = ref;
    untrack(() => callback?.(element));
    return () => callback?.(null);
  };
</script>

<dialog
  {...rest}
  data-sw-dialog-content=""
  data-state="closed"
  data-sw-part="popup"
  {@attach attachRef}
>
  {@render children?.()}
</dialog>
