/**
 * Generated by scripts/portable-runtime/generate-astro-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import ColorPickerArea from "./ColorPickerArea.astro";
import ColorPickerAreaBackground from "./ColorPickerAreaBackground.astro";
import ColorPickerAreaInput from "./ColorPickerAreaInput.astro";
import ColorPickerAreaThumb from "./ColorPickerAreaThumb.astro";
import ColorPickerChannelInput from "./ColorPickerChannelInput.astro";
import ColorPickerChannelSlider from "./ColorPickerChannelSlider.astro";
import ColorPickerChannelSliderInput from "./ColorPickerChannelSliderInput.astro";
import ColorPickerChannelSliderThumb from "./ColorPickerChannelSliderThumb.astro";
import ColorPickerChannelSliderTrack from "./ColorPickerChannelSliderTrack.astro";
import ColorPickerClear from "./ColorPickerClear.astro";
import ColorPickerControl from "./ColorPickerControl.astro";
import ColorPickerEyeDropperTrigger from "./ColorPickerEyeDropperTrigger.astro";
import ColorPickerFormatControl from "./ColorPickerFormatControl.astro";
import ColorPickerFormatSelect from "./ColorPickerFormatSelect.astro";
import ColorPickerHiddenInput from "./ColorPickerHiddenInput.astro";
import ColorPickerLabel from "./ColorPickerLabel.astro";
import ColorPickerRoot from "./ColorPickerRoot.astro";
import ColorPickerSwatch from "./ColorPickerSwatch.astro";
import ColorPickerSwatchGroup from "./ColorPickerSwatchGroup.astro";
import ColorPickerTransparencyGrid from "./ColorPickerTransparencyGrid.astro";
import ColorPickerValueInput from "./ColorPickerValueInput.astro";
import ColorPickerValueSwatch from "./ColorPickerValueSwatch.astro";
import ColorPickerValueText from "./ColorPickerValueText.astro";

const ColorPicker = {
  Root: ColorPickerRoot,
  Label: ColorPickerLabel,
  Control: ColorPickerControl,
  ValueInput: ColorPickerValueInput,
  ValueSwatch: ColorPickerValueSwatch,
  ValueText: ColorPickerValueText,
  Area: ColorPickerArea,
  AreaBackground: ColorPickerAreaBackground,
  AreaThumb: ColorPickerAreaThumb,
  AreaInput: ColorPickerAreaInput,
  ChannelSlider: ColorPickerChannelSlider,
  ChannelSliderTrack: ColorPickerChannelSliderTrack,
  ChannelSliderThumb: ColorPickerChannelSliderThumb,
  ChannelSliderInput: ColorPickerChannelSliderInput,
  ChannelInput: ColorPickerChannelInput,
  FormatSelect: ColorPickerFormatSelect,
  FormatControl: ColorPickerFormatControl,
  TransparencyGrid: ColorPickerTransparencyGrid,
  SwatchGroup: ColorPickerSwatchGroup,
  Swatch: ColorPickerSwatch,
  EyeDropperTrigger: ColorPickerEyeDropperTrigger,
  Clear: ColorPickerClear,
  HiddenInput: ColorPickerHiddenInput,
};

export {
  ColorPicker,
  ColorPickerArea,
  ColorPickerAreaBackground,
  ColorPickerAreaInput,
  ColorPickerAreaThumb,
  ColorPickerChannelInput,
  ColorPickerChannelSlider,
  ColorPickerChannelSliderInput,
  ColorPickerChannelSliderThumb,
  ColorPickerChannelSliderTrack,
  ColorPickerClear,
  ColorPickerControl,
  ColorPickerEyeDropperTrigger,
  ColorPickerFormatControl,
  ColorPickerFormatSelect,
  ColorPickerHiddenInput,
  ColorPickerLabel,
  ColorPickerRoot,
  ColorPickerSwatch,
  ColorPickerSwatchGroup,
  ColorPickerTransparencyGrid,
  ColorPickerValueInput,
  ColorPickerValueSwatch,
  ColorPickerValueText,
};

export default ColorPicker;

export type {
  ColorPickerChannel,
  ColorPickerColor,
  ColorPickerDirection,
  ColorPickerFormat,
  ColorPickerFormatChangeDetails,
  ColorPickerHsbChannels,
  ColorPickerHsbChannelUpdates,
  ColorPickerHslChannels,
  ColorPickerHslChannelUpdates,
  ColorPickerInitialAxis,
  ColorPickerInitialChannel,
  ColorPickerInitialDirection,
  ColorPickerInitialOrientation,
  ColorPickerInitialPartName,
  ColorPickerInitialPartProjection,
  ColorPickerInitialPartRequest,
  ColorPickerInitialState,
  ColorPickerInitialStateOptions,
  ColorPickerInitialValue,
  ColorPickerInstance,
  ColorPickerOptions,
  ColorPickerRgbChannels,
  ColorPickerRgbChannelUpdates,
  ColorPickerSetOptions,
  ColorPickerSetValueOptions,
  ColorPickerStringFormat,
  ColorPickerValue,
  ColorPickerValueChangeDetails,
  ColorPickerValueChangeReason,
  ColorPickerValueCommitDetails,
} from "@starwind-ui/runtime/color-picker";
export {
  createColorPickerInitialState,
  parseColor,
  projectColorPickerInitialPart,
} from "@starwind-ui/runtime/color-picker";
export type {
  ColorPickerAreaProjection,
  ColorPickerChannelSliderProjection,
  ColorPickerInitialProps,
  ColorPickerRenderProjection,
} from "./ColorPickerRenderProjection";
