<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script lang="ts">
  import { projectColorPickerInitialPart, type ColorPickerInitialPartRequest, type ColorPickerChannel, type ColorPickerValue } from "@starwind-ui/runtime/color-picker";
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { getRoot, getArea, setArea, getChannel, setChannel, mergeProjection, refreshPart } from "./context.js";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & { children?: Snippet; xChannel?: ColorPickerChannel; yChannel?: ColorPickerChannel; xStep?: number; yStep?: number; ref?: (element: HTMLDivElement | null) => void };
  let { children, xChannel = "saturation", yChannel = "brightness", xStep, yStep, ref, ...rest }: Props = $props();
  const context = getRoot();
  setArea({ owner: context, get xChannel() { return xChannel; }, get yChannel() { return yChannel; }, get xStep() { return xStep; }, get yStep() { return yStep; } });
  const request = (): ColorPickerInitialPartRequest => ({ part: "area", xChannel: xChannel, yChannel: yChannel, xStep: xStep, yStep: yStep });
  const projection = untrack(() => projectColorPickerInitialPart(context.initialState, request()));
  let elementProps = $derived(mergeProjection(projection, rest, { "data-sw-color-picker-area": "", "data-sw-part": "area",  "data-x-channel": xChannel, "data-y-channel": yChannel, }));
  const attachPart: Attachment<HTMLDivElement> = (element) => {
    const release = untrack(() => context.register(element));
    $effect(() => refreshPart(context, request, rest));
    return release;
  };
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>

<div {...elementProps} {@attach attachPart} {@attach attachRef}>{#if children}{@render children()}{:else}{/if}</div>
