<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script lang="ts">
  import { projectColorPickerInitialPart, type ColorPickerInitialPartRequest, type ColorPickerChannel, type ColorPickerValue } from "@starwind-ui/runtime/color-picker";
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLInputAttributes } from "svelte/elements";
  import { getRoot, getArea, setArea, getChannel, setChannel, mergeProjection, refreshPart } from "./context.js";
  type Props = Omit<HTMLInputAttributes, "children" | "step"> & { children?: Snippet; step?: number; ref?: (element: HTMLInputElement | null) => void };
  let { children, step, ref, ...rest }: Props = $props();
  const context = getRoot();
  const slider = getChannel(context);
  const request = (): ColorPickerInitialPartRequest => ({ part: "channelSliderInput", channel: slider.channel, orientation: slider.orientation, step: step ?? slider.step, ariaLabel: rest["aria-label"] ?? undefined });
  const projection = untrack(() => projectColorPickerInitialPart(context.initialState, request()));
  let elementProps = $derived(mergeProjection(projection, rest, { "data-sw-color-picker-channel-input": "", "data-sw-part": "channelSliderInput", "type": "range", "data-step": step ?? slider.step, }));
  const attachPart: Attachment<HTMLInputElement> = (element) => {
    const release = untrack(() => context.register(element));
    $effect(() => refreshPart(context, request, rest));
    return release;
  };
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLInputElement>(() => ref);
</script>

<input {...elementProps} {@attach attachPart} {@attach attachRef} />
