/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type ScrollAreaContentProps = React.HTMLAttributes<HTMLDivElement>;

const ScrollAreaContent = React.forwardRef<HTMLDivElement, ScrollAreaContentProps>(
  function ScrollAreaContent(props, forwardedRef) {
    return <div data-sw-scroll-area-content ref={forwardedRef} role="presentation" {...props} />;
  },
);

ScrollAreaContent.displayName = "ScrollArea.Content";

export default ScrollAreaContent;
