/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import { createScrollArea } from "@starwind-ui/runtime/scroll-area";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export type ScrollAreaOverflowEdgeThreshold =
  | number
  | Partial<{
      xStart: number;
      xEnd: number;
      yStart: number;
      yEnd: number;
    }>;

type ScrollAreaOverflowEdgeThresholdAttributes = {
  shared?: number;
  xEnd?: number;
  xStart?: number;
  yEnd?: number;
  yStart?: number;
};

export type ScrollAreaRootProps = React.HTMLAttributes<HTMLDivElement> & {
  overflowEdgeThreshold?: ScrollAreaOverflowEdgeThreshold;
};

const ScrollAreaRoot = React.forwardRef<HTMLDivElement, ScrollAreaRootProps>(
  function ScrollAreaRoot({ overflowEdgeThreshold, ...props }, forwardedRef) {
    const rootRef = React.useRef<HTMLDivElement>(null);
    const instanceRef = React.useRef<ReturnType<typeof createScrollArea> | undefined>(undefined);
    const thresholdAttributes = getOverflowEdgeThresholdAttributes(overflowEdgeThreshold);

    const composedRef = React.useCallback(
      (node: HTMLDivElement | null) => {
        rootRef.current = node;
        return setRef(forwardedRef, node);
      },
      [forwardedRef],
    );

    useIsomorphicLayoutEffect(() => {
      const root = rootRef.current;
      if (!root) return;

      const instance = createScrollArea(root);
      instanceRef.current = instance;

      return () => {
        instance.destroy();
        if (instanceRef.current === instance) {
          instanceRef.current = undefined;
        }
      };
    }, []);

    useIsomorphicLayoutEffect(() => {
      const instance = instanceRef.current;
      if (!instance) return;

      instance.refresh();
    }, [
      thresholdAttributes.shared,
      thresholdAttributes.xEnd,
      thresholdAttributes.xStart,
      thresholdAttributes.yEnd,
      thresholdAttributes.yStart,
    ]);

    return (
      <div
        data-sw-scroll-area
        data-overflow-edge-threshold={thresholdAttributes.shared}
        data-overflow-edge-threshold-x-end={thresholdAttributes.xEnd}
        data-overflow-edge-threshold-x-start={thresholdAttributes.xStart}
        data-overflow-edge-threshold-y-end={thresholdAttributes.yEnd}
        data-overflow-edge-threshold-y-start={thresholdAttributes.yStart}
        ref={composedRef}
        role="presentation"
        {...props}
      />
    );
  },
);

ScrollAreaRoot.displayName = "ScrollArea.Root";

export default ScrollAreaRoot;

function getOverflowEdgeThresholdAttributes(
  threshold: ScrollAreaOverflowEdgeThreshold | undefined,
): ScrollAreaOverflowEdgeThresholdAttributes {
  if (typeof threshold === "number") {
    const shared = normalizeOverflowEdgeThresholdValue(threshold);
    return shared === undefined ? {} : { shared };
  }

  if (!threshold) return {};

  return {
    xEnd: "xEnd" in threshold ? normalizeOverflowEdgeThresholdValue(threshold.xEnd) : undefined,
    xStart:
      "xStart" in threshold ? normalizeOverflowEdgeThresholdValue(threshold.xStart) : undefined,
    yEnd: "yEnd" in threshold ? normalizeOverflowEdgeThresholdValue(threshold.yEnd) : undefined,
    yStart:
      "yStart" in threshold ? normalizeOverflowEdgeThresholdValue(threshold.yStart) : undefined,
  };
}

function normalizeOverflowEdgeThresholdValue(value: number | undefined): number | undefined {
  if (value === undefined || !Number.isFinite(value)) return undefined;

  return Math.max(value, 0);
}
