/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

// Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies.

import ScrollAreaContent from "./ScrollAreaContent.vue";
import ScrollAreaCorner from "./ScrollAreaCorner.vue";
import ScrollAreaRoot from "./ScrollAreaRoot.vue";
import ScrollAreaScrollbar from "./ScrollAreaScrollbar.vue";
import ScrollAreaThumb from "./ScrollAreaThumb.vue";
import ScrollAreaViewport from "./ScrollAreaViewport.vue";

const ScrollArea = {
  Content: ScrollAreaContent,
  Corner: ScrollAreaCorner,
  Root: ScrollAreaRoot,
  Scrollbar: ScrollAreaScrollbar,
  Thumb: ScrollAreaThumb,
  Viewport: ScrollAreaViewport,
};

export { default as ScrollAreaContent } from "./ScrollAreaContent.vue";
export { default as ScrollAreaCorner } from "./ScrollAreaCorner.vue";
export { default as ScrollAreaRoot } from "./ScrollAreaRoot.vue";
export { default as ScrollAreaScrollbar } from "./ScrollAreaScrollbar.vue";
export { default as ScrollAreaThumb } from "./ScrollAreaThumb.vue";
export { default as ScrollAreaViewport } from "./ScrollAreaViewport.vue";
export { ScrollArea };

export default ScrollArea;
