<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();

const thumbRef = ref<HTMLDivElement | null>(null);

defineExpose({ element: thumbRef });
</script>

<template>
  <div ref="thumbRef" v-bind="$attrs" data-sw-scroll-area-thumb>
    <slot />
  </div>
</template>
