/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";
import { setRef } from "../internal/compose-refs";

export type CollapsiblePanelProps = React.HTMLAttributes<HTMLDivElement> & {
  hiddenUntilFound?: boolean;
};

const CollapsiblePanel = React.forwardRef<HTMLDivElement, CollapsiblePanelProps>(
  function CollapsiblePanel({ hiddenUntilFound = false, ...props }, forwardedRef) {
    const composedRef = React.useCallback(
      (node: HTMLDivElement | null) => {
        if (node) {
          if (hiddenUntilFound) {
            node.setAttribute("hidden", "until-found");
          } else if (node.getAttribute("hidden") === "until-found") {
            node.hidden = true;
          }
        }

        return setRef(forwardedRef, node);
      },
      [forwardedRef, hiddenUntilFound],
    );

    return (
      <div
        data-sw-collapsible-panel
        data-hidden-until-found={hiddenUntilFound ? "" : undefined}
        data-state="closed"
        hidden
        ref={composedRef}
        {...props}
      />
    );
  },
);

CollapsiblePanel.displayName = "Collapsible.Panel";

export default CollapsiblePanel;
