import { format, resolveConfig } from "prettier";
import type { StyledOutputComponentGroup } from "../../styled-output-model/index.js";
import { projectSvelteStyledGroup } from "./styled/projection.js";
import { renderSvelteStyledFiles } from "./styled/render.js";

const generatedBlockHeader =
  "/**\n * Generated by scripts/portable-runtime/generate-cli-registry.ts.\n * Do not edit by hand; update the contract/template instead.\n */";
const vendoredBlockHeader =
  "/**\n * Vendored by the Starwind CLI.\n * You own this file in your project.\n */";
const generatedHtmlHeader =
  "<!-- Generated by scripts/portable-runtime/generate-cli-registry.ts. Do not edit by hand. -->";
const vendoredHtmlHeader =
  "<!-- Vendored by the Starwind CLI. You own this file in your project. -->";
const generatedLineHeaders = [
  "// Generated by scripts/portable-runtime/generate-cli-registry.ts. Do not edit by hand.",
  "// Generated by scripts/portable-runtime/generate-cli-registry.ts. Do not edit by hand; update the contract/template instead.",
] as const;
const vendoredLineHeader =
  "// Vendored by the Starwind CLI.\n// You own this file in your project.";
const quarantineMessage = "Svelte 5 public beta adapter output.";

export const sveltePrimitiveEditableContentMarkers = [
  { extensions: [".svelte"], markers: [vendoredHtmlHeader], position: "prefix" },
  {
    extensions: [".ts", ".js"],
    markers: [vendoredBlockHeader, vendoredLineHeader],
    position: "prefix",
  },
] as const;
export const sveltePrimitiveForbiddenContent = [
  "Svelte 5 public beta adapter output.",
  "Do not edit by hand",
] as const;

/** Preserve the Svelte printer's validated source; format its TypeScript helper files. */
export async function formatSveltePrimitiveVendoringContent(
  content: string,
  sourcePath: string,
): Promise<string> {
  if (sourcePath.endsWith(".svelte")) return content;
  return format(content, { ...((await resolveConfig(sourcePath)) ?? {}), filepath: sourcePath });
}

export function projectSveltePrimitiveVendoringContent(content: string): string {
  let projected = content
    .replaceAll(generatedBlockHeader, vendoredBlockHeader)
    .replaceAll(generatedHtmlHeader, vendoredHtmlHeader)
    .replaceAll(`<!-- ${quarantineMessage} -->\n`, "")
    .replaceAll(`// ${quarantineMessage}\n`, "");
  // Match the longer header first so its suffix cannot remain in an editable file.
  for (const header of [...generatedLineHeaders].reverse()) {
    projected = projected.replaceAll(header, vendoredLineHeader);
  }
  return projected;
}

export function collectSvelteStyledPackageImportSources(args: {
  group: StyledOutputComponentGroup;
  primitiveImportBase: string;
}): string[] {
  const sources = new Set<string>();
  const files = renderSvelteStyledFiles(projectSvelteStyledGroup(args.group, args));
  const pattern =
    /(?:import|export)\s+(?:type\s+)?(?:[^"';]*?\s+from\s+)?["']([^"']+)["']|import\(["']([^"']+)["']\)/g;
  for (const file of files) {
    for (const match of file.content.matchAll(pattern)) {
      const source = match[1] ?? match[2];
      if (source && !source.startsWith(".") && !source.startsWith("/")) sources.add(source);
    }
  }
  return [...sources].sort();
}
