/** Target policy. Family consumer tests establish behavior as each printer adopts it. */
export const svelteAdapterPublicContract = {
  attrs: {
    destination: "single-semantic-element",
    forwarding: "exactly-once",
    includesAttachmentSymbols: true,
    classAndStyle: "forward-unchanged",
    requiredBehaviorCollisions: "primitive-wins",
    nativeHandlers: "native-svelte-order-exactly-once",
    nativePreventDefaultVeto: false,
  },
  framework: {
    minimumVersion: "5.29.0",
    comparisonVersion: "5.57.0",
    packageIntent: "@starwind-ui/svelte",
    sveltePeerExternalized: true,
    setupModel: "component-with-attachment-owned-runtime-connection",
  },
  models: {
    table: {
      sidebar: { open: "boolean", mobileOpen: "boolean" },
      "color-picker": { value: "ColorPickerColor | null", format: "ColorPickerFormat" },
      combobox: { inputValue: "string", open: "boolean", value: "string | null" },
      "navigation-menu": { value: "string | null" },
      tabs: { value: "string | null" },
      "input-otp": { value: "string" },
      radio: { checked: "boolean" },
      toggle: { pressed: "boolean" },
      "toggle-group": { value: "string[]" },
      "radio-group": { value: "string | undefined" },
      "checkbox-group": { value: "string[]" },
      switch: { checked: "boolean" },
      input: { value: "string | number | string[]" },
      collapsible: { open: "boolean" },
      checkbox: { checked: "boolean" },
      select: { open: "boolean", value: "string | null" },
      accordion: { value: "string | string[] | null" },
      dialog: { open: "boolean" },
      drawer: { open: "boolean" },
      menu: { open: "boolean" },
      "context-menu": { open: "boolean" },
      "context-menu-checkbox-item": { checked: "boolean" },
      "context-menu-radio-group": { value: "string | undefined" },
      "menu-checkbox-item": { checked: "boolean" },
      "menu-radio-group": { value: "string | undefined" },
      popover: { open: "boolean" },
      "preview-card": { open: "boolean" },
      tooltip: { open: "boolean" },
      "alert-dialog": { open: "boolean" },
      slider: { value: "number | number[]" },
    },
    declaration: "$bindable()",
    bindingDetection: false,
    button: "no-model",
    field: { root: "setter-overrides-release-on-undefined", control: "delegate-input-model" },
    form: "no-model",
    fieldset: "no-model",
    services: { carousel: "unchanged", toast: "unchanged" },
    indeterminate: "existing-checkbox-prop-and-callback",
    initialUndefined: "explicit-default-else-component-default",
    undefinedBinding: "publish-normalized-state-after-client-mount",
    initialDefined: "silent-command-preserving-false-null-and-empty-values",
    plainProp: "observable-commands-and-accepted-local-interactions",
    boundProp: "plain-prop-policy-plus-outbound-accepted-changes",
    laterUndefined: "retain-accepted-value",
    sameValueAssignment: "command-not-required",
    arrays: { input: "copy", output: "copy", equality: "contents" },
    normalization: {
      owner: "runtime-public-setter-and-getter",
      accordion: "value-shape",
      select: "empty-value",
      slider: "clamp-snap-order-and-numeric-normalization",
      tabs: "empty-string-and-reserved-null-marker",
      publication: "read-after-silent-setter-or-options-and-publish-once",
    },
    input: {
      definedInputs: "preserve-equivalent-input-shape-and-observe-array-contents",
      nativeOutput: "publish-normalized-string-after-notification-including-canceled-detail",
      nativeNumberBinding: false,
      fileWrites: "empty-native-writes-only",
      formAssociation: "reconnect-on-actual-form-identity-change",
    },
    inputGroup: {
      input: "delegate-input-with-incoming-command-alias",
      textarea: "delegate-existing-native-textarea-binding",
      bindingDefault: "$bindable()",
      addon: "passive-native-owner",
    },
    dropzone: {
      uploading: "setter-input-without-files-model",
      filesChange: "committed-subscription-with-copied-array-containers",
      capturedParts: "reconnect-preserving-public-files-and-uploading",
      formAssociation: "reconnect-on-actual-form-identity-change",
      reset: "existing-runtime-deferred-silent-clear",
      filesList: "runtime-owned-text-rendering",
    },
    inputOtp: {
      input: "internal-native-input-before-visual-slots",
      slot: "explicit-index-with-runtime-character-and-caret-ownership",
      patternAndReadOnly: "recreate-with-frozen-reset-seed-and-accepted-value",
      maxLengthAndSlots: "max-length-recreates-controller-with-fixed-indexed-slots",
      inputReplacement: "fixed-internal-input-without-replacement-guarantee",
      formAssociation: "public-form-options-setter-on-prop-change-without-form-identity-observation",
    },
    sidebar: {
      notifications: "accepted-without-cancellation",
      constructor: "defaults-only-with-silent-current-model-restore",
      persistence: "initial-undefined-open-only-without-transient-reconstruction-publication",
      context: "nearest-provider-state-and-owned-media-query",
      sheet: "defined-model-input-and-silent-accepted-binding-output-with-contained-runtime-events",
    },
    colorPicker: {
      input: "ColorPickerValue | undefined",
      output: "immutable-ColorPickerColor-or-null-from-public-getter",
      format: "independent-accepted-hex-rgb-hsl-hsb-model",
      ownership: "independent-value-and-format-fixed-at-mount",
      initialDefined: "parent-controlled-including-function-bindings",
      initialUndefined: "runtime-owned-with-accepted-binding-output",
      laterUndefined: "retain-last-controlled-value",
      laterDefined: "ignored-by-initially-uncontrolled-model",
      constructor: "frozen-default-with-initial-controlled-value-and-format",
      reset: "capture-actual-form-and-restore-controlled-values-or-uncontrolled-seeds",
      liveParts: "owned-registration-and-preserve-state-refresh",
      initialProjection: "public-root-area-and-channel-context",
    },
    standalone: "runtime-owns-interaction-state",
    reset: {
      seed: ["explicit-default", "initial-defined-model", "component-default"],
      defaultChanges: "ignore-after-construction",
      separateInitialModel: "apply-silently-after-seeding",
      normalization: "current-runtime-options",
      publication: "binding-and-hidden-form-value-together",
      canceled: "retain-accepted-state",
      superseded: "newer-accepted-interaction-or-parent-command-wins",
      deferredWork: "reconcile-with-revision-identity-and-public-setters-getters",
      checkboxIndeterminate: "restore-on-canceled-or-superseded-reset",
      inputOtp: "runtime-and-dom-reset-without-external-model-publication",
    },
    checkboxOwnership: {
      selection: "available-group-context-and-item-key-else-standalone",
      childCheckedAndDefault: "group-membership-takes-precedence",
      publication: "group-owned-child-bindings-stay-unchanged",
      group: "context-owns-checked-and-reset-state",
      dynamicSwitching: false,
    },
  },
  events: {
    input: {
      order: ["native-value-change", "dom-notification", "callback", "subscription-publication"],
      cancellation: "suppresses-form-revalidation-without-rolling-back-native-value",
    },
    order: [
      "detailed-proposal-callback",
      "cancelable-dom-dispatch",
      "runtime-cancellation-decision",
      "runtime-accepted-state",
      "accepted-subscription-model-publication",
    ],
    cancellation: "callback-or-dom-cancellation-preserves-published-value-and-visual-state",
    silentInputs: ["initialization", "parent-command", "option-normalization", "reset"],
    silentInputProposalCallbacks: false,
    slider: ["accepted-value-change", "value-committed", "silent-state-sync"],
    reentrantParent: "outside-direct-model-contract",
    functionBinding: {
      publication: "standard-svelte-binding-write",
      supported: ["identity"],
      transformedReadback: "out-of-scope",
      fixedPointLoops: false,
    },
    recursiveImperativeProposals: "out-of-scope",
  },
  composition: {
    parts: [
      "SidebarTrigger",
      "SelectTrigger",
      "DialogTrigger",
      "DialogClose",
      "CollapsibleTrigger",
      "MenuTrigger",
      "NavigationMenuTrigger",
      "ComboboxTrigger",
      "ComboboxClear",
    ],
    child: "child?: Snippet<[ButtonChildPayload]>",
    payload: { props: "ButtonChildProps", children: "children?: Snippet" },
    buttonProps: ["native-button-attributes", "native-callbacks", "attachment-symbols"],
    typeExports: ["ButtonChildPayload", "ButtonChildProps"],
    typeExportLocation: "each-supported-component-subpath",
    defaultElement: "button",
    replacementWrapper: false,
    content: "separate-children-snippet-rendered-by-consumer",
    forwarding: "whole-props-to-one-HTMLButtonElement-or-forwarding-component",
    noninteractiveSiblings: true,
    developmentDiagnostics: [
      "wrong-element-type",
      "multiple-attached-owners",
      "missing-owner-after-settled-mount",
    ],
    opaqueSnippet: "consumer-owns-complete-prop-and-symbol-forwarding",
    nestedButtonRoot: {
      preserveOuter: ["data-slot", "data-sw-part", "aria"],
      runtimeHooks: "retain-distinct-required-hooks",
      proof: "Trigger-to-ButtonRoot-to-native-button",
    },
    buttonRoot: {
      element: "fixed-native-button",
      childProp: false,
      payloadTypes: "retained-for-trigger-composition",
    },
    accordionTrigger: {
      element: "fixed-native-button",
      childProp: false,
      ownerMap: false,
      liveDisabledRelease: "shared-runtime-limitation-remount-to-clear",
    },
    dataAsChildProcessing: false,
    unrelatedOverlayTriggersOnOneButton: "out-of-scope",
    opaqueMarkupMerging: "consumer-owned",
  },
  sidebarMenuButton: {
    selection: "href-undefined-button-else-anchor-including-empty-string",
    child: "Snippet<[SidebarMenuButtonChildPayload]>",
    payload: "kind-discriminated-button-or-anchor-native-props-with-children",
    ref: "selected-native-element",
    anchorType: "sidebar-local-AnchorChildProps-with-SidebarAnchorChildProps-root-alias",
  },
  breadcrumbLink: {
    asChild: "asChild?: boolean = false",
    children: "children?: Snippet",
    defaultElement: "styled-native-anchor",
    customElement: "render-children-directly",
    customProps: "consumer-owned-href-router-props-classes-callbacks-and-ref",
    wrapperPropTransfer: false,
    replacementWrapper: false,
    ownerDiscovery: false,
  },
  exports: {
    componentSubpaths: ["named-parts", "named-namespace", "default-namespace"],
    root: "named-only",
    partAndServiceNames: "preserve-existing",
  },
  lifecycle: {
    connection: "attachment",
    mutableOptions: "nested-effect-runtime-setter",
    teardown: "attachment-cleanup",
    refs: {
      types: "contracted-element-type-for-every-element-part",
      callback: "element-then-null",
      replacement: "balanced-public-callback-lifecycle",
      callbackReplacement: "exact-order-out-of-scope",
      nativeStyled: "bindable-element-ref-through-bind-this",
    },
    forwardedAttachments: "reactive-public-symbols-with-balanced-setup-cleanup",
    constructorOnlyOptions: "recreate-with-original-reset-seed-and-current-accepted-state",
    comboboxReconstruction: "current-public-models-explicit-defaults-and-fresh-query-cycle",
    keyedChild: "remove-old-listeners-and-connect-new-button",
    compoundReplacement:
      "declared-parts-notify-context-root-use-public-refresh-else-recreate-and-restore",
    progressVisualParts: "initial-value-and-indicator-only",
    popoverActiveTrigger: "current-controller-lifetime",
    tabsSyncKey: "component-creation-including-undefined",
    externalDialogTargetId: "preserve-static-trigger-keyed-replacement-out-of-scope",
    queuedWorkAfterUnmount: false,
    selectPortal: "attachment-owns-target-open-presence-replacement-and-unmount-cleanup",
    nativeOverlayPortal: "public-binding-and-placement-with-owned-capture-reconnection",
    dialogOverlay: "existing-native-overlay-and-top-layer-without-portal-api",
  },
  compatibility: {
    tools: "isolated-consumer-compiler-and-checker-per-version",
    imports: "built-dist-and-package-metadata-for-svelte-and-runtime",
    sourceAliasesAndWorkspaceFallback: false,
    fixtures: "actual-positive-and-negative-svelte-consumers-with-expected-diagnostics",
    provenance: "exact-tool-versions-and-resolved-modules",
    networkFailure: "fail-with-actionable-message",
    gate: "pnpm svelte:compatibility",
    packedHosts: "roadmap-order-02",
  },
  publicSupport: {
    cliRegistry: true,
    demoIntegration: true,
    packageExports: true,
    publicDocsClaim: true,
    status: "public-beta",
  },
  rendering: {
    content: "typed-snippet",
    props: "$props-rest-forwarding",
  },
  server: {
    browserGlobals: false,
    domWork: false,
    bindingPublication: false,
    callbacks: false,
    initialState: "deterministic-type-valid-initial-model-or-default",
    collapsibleParts: "closed-trigger-and-hidden-panel-before-connection",
    normalization: "after-client-mount",
    geometry: "after-client-mount",
    duplicateOwnersAndHandlers: false,
    hydration: "exact-server-markup",
  },
} as const;

export type SvelteAdapterPublicContract = typeof svelteAdapterPublicContract;
