/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import CheckboxGroupRoot from "./CheckboxGroupRoot.svelte";
const CheckboxGroup = { Root: CheckboxGroupRoot };
export { CheckboxGroup, CheckboxGroupRoot };
export default CheckboxGroup;

export type { CheckboxGroupValue, CheckboxGroupValueChangeDetails } from "@starwind-ui/runtime";
