/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import * as React from "react";

export type PopoverBackdropProps = React.HTMLAttributes<HTMLDivElement>;

const PopoverBackdrop = React.forwardRef<HTMLDivElement, PopoverBackdropProps>(
  function PopoverBackdrop(props, forwardedRef) {
    return (
      <div {...props} data-sw-popover-backdrop="" data-state="closed" hidden ref={forwardedRef} />
    );
  },
);

PopoverBackdrop.displayName = "Popover.Backdrop";

export default PopoverBackdrop;
