/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type PopoverPopupProps = React.HTMLAttributes<HTMLDivElement> & {
  side?: "top" | "right" | "bottom" | "left";
  align?: "start" | "center" | "end";
  sideOffset?: number;
  avoidCollisions?: boolean;
  collisionStrategy?: "initial-placement" | "best-fit";
};

const PopoverPopup = React.forwardRef<HTMLDivElement, PopoverPopupProps>(function PopoverPopup(
  {
    side = "bottom",
    align = "center",
    sideOffset = 4,
    avoidCollisions = true,
    collisionStrategy = "initial-placement",
    ...props
  },
  forwardedRef,
) {
  return (
    <div
      data-sw-popover-popup
      role="dialog"
      tabIndex={-1}
      data-state="closed"
      data-side={side}
      data-align={align}
      data-side-offset={sideOffset}
      data-avoid-collisions={avoidCollisions ? "true" : "false"}
      data-collision-strategy={collisionStrategy}
      hidden
      ref={forwardedRef}
      {...props}
    />
  );
});

PopoverPopup.displayName = "Popover.Popup";

export default PopoverPopup;
