/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import {
  createPopover,
  type PopoverCloseCompleteDetails,
  type PopoverOpenChangeDetails,
} from "@starwind-ui/runtime/popover";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export type PopoverRootProps = Omit<React.HTMLAttributes<HTMLDivElement>, "onChange"> & {
  defaultOpen?: boolean;
  open?: boolean;
  closeOnEscape?: boolean;
  closeOnOutsideInteract?: boolean;
  modal?: boolean;
  openOnHover?: boolean;
  closeDelay?: number;
  onCloseComplete?: (details: PopoverCloseCompleteDetails) => void;
  onOpenChange?: (open: boolean, details: PopoverOpenChangeDetails) => void;
};

const PopoverRoot = React.forwardRef<HTMLDivElement, PopoverRootProps>(function PopoverRoot(
  {
    defaultOpen = false,
    open,
    closeOnEscape = true,
    closeOnOutsideInteract = true,
    modal = false,
    openOnHover = false,
    closeDelay = 200,
    onCloseComplete,
    onOpenChange,
    ...props
  },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const instanceRef = React.useRef<ReturnType<typeof createPopover> | undefined>(undefined);
  const onCloseCompleteRef = React.useRef(onCloseComplete);
  const onOpenChangeRef = React.useRef(onOpenChange);
  const openRef = React.useRef(open);
  const defaultOpenRef = React.useRef(defaultOpen);
  const [uncontrolledOpen, setUncontrolledOpenState] = React.useState(defaultOpenRef.current);
  const uncontrolledOpenRef = React.useRef(uncontrolledOpen);

  const setUncontrolledOpen = React.useCallback((nextOpen: boolean) => {
    uncontrolledOpenRef.current = nextOpen;
    setUncontrolledOpenState(nextOpen);
  }, []);

  useIsomorphicLayoutEffect(() => {
    onCloseCompleteRef.current = onCloseComplete;
  }, [onCloseComplete]);

  useIsomorphicLayoutEffect(() => {
    onOpenChangeRef.current = onOpenChange;
  }, [onOpenChange]);

  useIsomorphicLayoutEffect(() => {
    openRef.current = open;
  }, [open]);

  const composedRef = React.useCallback(
    (node: HTMLDivElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  useIsomorphicLayoutEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const instance = createPopover(root, {
      defaultOpen: uncontrolledOpenRef.current,
      closeOnEscape,
      closeOnOutsideInteract,
      modal,
      openOnHover,
      onCloseComplete: (details) => {
        onCloseCompleteRef.current?.(details);
      },
      onOpenChange: (nextOpen, details) => {
        onOpenChangeRef.current?.(nextOpen, details);
        if (details.isCanceled) return;

        if (openRef.current === undefined) {
          setUncontrolledOpen(nextOpen);
        }
      },
      ...(openRef.current !== undefined ? { open: openRef.current } : {}),
    });
    instanceRef.current = instance;

    return () => {
      instance.destroy();
      if (instanceRef.current === instance) {
        instanceRef.current = undefined;
      }
    };
  }, [closeOnEscape, closeOnOutsideInteract, modal, openOnHover]);

  useIsomorphicLayoutEffect(() => {
    if (open === undefined) return;
    const instance = instanceRef.current;
    if (!instance) return;
    if (instance.getOpen() === open) return;

    instance.setOpen(open, { emit: false });
  }, [open]);

  const renderedOpen = open ?? uncontrolledOpen;

  return (
    <div
      data-sw-popover
      data-default-open={defaultOpenRef.current ? "true" : undefined}
      data-close-on-escape={closeOnEscape ? "true" : "false"}
      data-close-on-outside-interact={closeOnOutsideInteract ? "true" : "false"}
      data-modal={modal ? "true" : "false"}
      data-open-on-hover={openOnHover ? "true" : undefined}
      data-close-delay={closeDelay}
      data-state={renderedOpen ? "open" : "closed"}
      ref={composedRef}
      {...props}
    />
  );
});

PopoverRoot.displayName = "Popover.Root";

export default PopoverRoot;
