/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type PopoverCloseProps = React.ButtonHTMLAttributes<HTMLButtonElement>;

const PopoverClose = React.forwardRef<HTMLButtonElement, PopoverCloseProps>(
  function PopoverClose(props, forwardedRef) {
    return <button type="button" data-sw-popover-close ref={forwardedRef} {...props} />;
  },
);

PopoverClose.displayName = "Popover.Close";

export default PopoverClose;
