<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import {
  type CollapsibleOpenChangeDetails,
  createCollapsible,
} from "@starwind-ui/runtime/collapsible";
import { computed, onBeforeUnmount, onMounted, ref, useAttrs, watch } from "vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    defaultOpen?: boolean;
    disabled?: boolean;
    open?: boolean;
  }>(),
  {
    defaultOpen: false,
    disabled: false,
    open: undefined,
  },
);
const emit = defineEmits<{
  openChange: [open: boolean, detail: CollapsibleOpenChangeDetails];
  "update:open": [open: boolean];
}>();
defineSlots<{
  default?: () => unknown;
}>();
const attrs = useAttrs();
const rootRef = ref<HTMLDivElement | null>(null);
const initialDefaultOpen = props.defaultOpen;
const uncontrolledOpen = ref(initialDefaultOpen);
const renderedOpen = computed(() => props.open ?? uncontrolledOpen.value);
let instance: ReturnType<typeof createCollapsible> | undefined;

defineExpose({
  element: rootRef,
});

function handleOpenChange(nextOpen: boolean, detail: CollapsibleOpenChangeDetails): void {
  const eventWasControlled = props.open !== undefined;
  emit("openChange", nextOpen, detail);
  if (detail.isCanceled) return;

  if (!eventWasControlled) uncontrolledOpen.value = nextOpen;
  emit("update:open", nextOpen);
}

function destroyOwnedInstance(): void {
  const ownedInstance = instance;
  if (!ownedInstance) return;

  if (instance === ownedInstance) instance = undefined;
  ownedInstance.destroy();
}

function setupRuntime(): void {
  destroyOwnedInstance();
  const element = rootRef.value;
  if (!element) return;

  instance = createCollapsible(element, {
    defaultOpen: uncontrolledOpen.value,
    disabled: props.disabled,
    onOpenChange: handleOpenChange,
    ...(props.open === undefined ? {} : { open: props.open }),
  });
}

onMounted(setupRuntime);

watch(
  () => props.open,
  (nextOpen, previousOpen) => {
    const controllednessChanged = (nextOpen === undefined) !== (previousOpen === undefined);
    if (controllednessChanged) {
      if (nextOpen === undefined && instance) {
        uncontrolledOpen.value = instance.getOpen();
      }
      setupRuntime();
      return;
    }
    if (nextOpen === undefined || !instance || Object.is(instance.getOpen(), nextOpen)) {
      return;
    }

    instance.setOpen(nextOpen, { emit: false });
  },
  { flush: "post" },
);
watch(() => props.disabled, setupRuntime, { flush: "post" });

onBeforeUnmount(destroyOwnedInstance);
</script>

<template>
  <div
    ref="rootRef"
    v-bind="attrs"
    data-sw-collapsible
    data-sw-part="root"
    :data-default-open="initialDefaultOpen ? 'true' : undefined"
    :data-disabled="props.disabled ? '' : undefined"
    :data-state="renderedOpen ? 'open' : 'closed'"
  >
    <slot />
  </div>
</template>
