/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import CollapsiblePanel from "./CollapsiblePanel.vue";
import CollapsibleRoot from "./CollapsibleRoot.vue";
import CollapsibleTrigger from "./CollapsibleTrigger.vue";

const Collapsible = {
  Root: CollapsibleRoot,
  Trigger: CollapsibleTrigger,
  Panel: CollapsiblePanel,
};

export { default as CollapsiblePanel } from "./CollapsiblePanel.vue";
export { default as CollapsibleRoot } from "./CollapsibleRoot.vue";
export { default as CollapsibleTrigger } from "./CollapsibleTrigger.vue";
export { Collapsible };

export default Collapsible;

export type { CollapsibleOpenChangeDetails } from "@starwind-ui/runtime";
