/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type FieldErrorMatch =
  | boolean
  | "badInput"
  | "customError"
  | "patternMismatch"
  | "rangeOverflow"
  | "rangeUnderflow"
  | "stepMismatch"
  | "tooLong"
  | "tooShort"
  | "typeMismatch"
  | "valid"
  | "valueMissing";

export type FieldValidityProps = React.ComponentPropsWithoutRef<"div"> & {
  match?: FieldErrorMatch;
};

const FieldValidity = React.forwardRef<HTMLDivElement, FieldValidityProps>(function FieldValidity(
  { children, hidden = true, match = true, ...props },
  ref,
) {
  const serializedMatch = typeof match === "boolean" ? String(match) : match;

  return (
    <div data-sw-field-validity data-match={serializedMatch} hidden={hidden} ref={ref} {...props}>
      {children}
    </div>
  );
});

FieldValidity.displayName = "Field.Validity";

export default FieldValidity;
