/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type FieldDescriptionProps = React.ComponentPropsWithoutRef<"p">;

const FieldDescription = React.forwardRef<HTMLParagraphElement, FieldDescriptionProps>(
  function FieldDescription({ children, ...props }, ref) {
    return (
      <p data-sw-field-description ref={ref} {...props}>
        {children}
      </p>
    );
  },
);

FieldDescription.displayName = "Field.Description";

export default FieldDescription;
