/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type FieldLabelProps = React.ComponentPropsWithoutRef<"label">;

const FieldLabel = React.forwardRef<HTMLLabelElement, FieldLabelProps>(function FieldLabel(
  { children, ...props },
  ref,
) {
  return (
    <label data-sw-field-label ref={ref} {...props}>
      {children}
    </label>
  );
});

FieldLabel.displayName = "Field.Label";

export default FieldLabel;
