/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import { createField } from "@starwind-ui/runtime/field";
import type { FormValidationTiming } from "@starwind-ui/runtime/form";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export type FieldRootProps = Omit<React.ComponentPropsWithoutRef<"div">, "onChange"> & {
  "data-error-visibility"?: FormValidationTiming;
  "data-revalidation-timing"?: FormValidationTiming;
  "data-validation-timing"?: FormValidationTiming;
  dirty?: boolean;
  disabled?: boolean;
  errorVisibility?: FormValidationTiming;
  invalid?: boolean;
  name?: string;
  revalidationTiming?: FormValidationTiming;
  touched?: boolean;
  validationTiming?: FormValidationTiming;
};

const FieldRoot = React.forwardRef<HTMLDivElement, FieldRootProps>(function FieldRoot(
  {
    children,
    "data-error-visibility": dataErrorVisibility,
    "data-revalidation-timing": dataRevalidationTiming,
    "data-validation-timing": dataValidationTiming,
    dirty,
    disabled = false,
    errorVisibility,
    invalid,
    name,
    revalidationTiming,
    touched,
    validationTiming,
    ...props
  },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const instanceRef = React.useRef<ReturnType<typeof createField> | undefined>(undefined);

  const composedRef = React.useCallback(
    (node: HTMLDivElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  useIsomorphicLayoutEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const instance = createField(root, {
      dirty,
      disabled,
      invalid,
      name,
      touched,
    });
    instanceRef.current = instance;

    return () => {
      instance.destroy();
      if (instanceRef.current === instance) {
        instanceRef.current = undefined;
      }
    };
  }, []);

  useIsomorphicLayoutEffect(() => {
    instanceRef.current?.setDirty(dirty);
  }, [dirty]);

  useIsomorphicLayoutEffect(() => {
    instanceRef.current?.setDisabled(disabled);
  }, [disabled]);

  useIsomorphicLayoutEffect(() => {
    instanceRef.current?.setInvalid(invalid);
  }, [invalid]);

  useIsomorphicLayoutEffect(() => {
    instanceRef.current?.setName(name);
  }, [name]);

  useIsomorphicLayoutEffect(() => {
    instanceRef.current?.setTouched(touched);
  }, [touched]);

  return (
    <div
      data-sw-field
      data-dirty={dirty ? "" : undefined}
      data-disabled={disabled ? "" : undefined}
      data-error-visibility={dataErrorVisibility ?? errorVisibility}
      data-invalid={invalid ? "" : undefined}
      data-name={name}
      data-revalidation-timing={dataRevalidationTiming ?? revalidationTiming}
      data-touched={touched ? "" : undefined}
      data-validation-timing={dataValidationTiming ?? validationTiming}
      ref={composedRef}
      {...props}
    >
      {children}
    </div>
  );
});

FieldRoot.displayName = "Field.Root";

export default FieldRoot;
