/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import SwitchRoot from "./SwitchRoot.vue";
import SwitchThumb from "./SwitchThumb.vue";

const Switch = {
  Root: SwitchRoot,
  Thumb: SwitchThumb,
};

export { default as SwitchRoot } from "./SwitchRoot.vue";

export { default as SwitchThumb } from "./SwitchThumb.vue";
export { Switch };

export default Switch;

export type { SwitchCheckedChangeDetails } from "@starwind-ui/runtime";
