<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { createSwitch, type SwitchCheckedChangeDetails } from "@starwind-ui/runtime/switch";
import { computed, onBeforeUnmount, onMounted, ref, useAttrs, watch } from "vue";

defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{
    checked?: boolean;
    defaultChecked?: boolean;
    disabled?: boolean;
    form?: string;
    id?: string;
    name?: string;
    nativeButton?: boolean;
    readOnly?: boolean;
    required?: boolean;
    uncheckedValue?: string;
    value?: string;
  }>(),
  {
    checked: undefined,
    disabled: false,
    form: undefined,
    id: undefined,
    name: undefined,
    nativeButton: false,
    readOnly: false,
    required: false,
    uncheckedValue: undefined,
    value: undefined,
  },
);
const emit = defineEmits<{
  checkedChange: [checked: boolean, detail: SwitchCheckedChangeDetails];
  "update:checked": [checked: boolean];
}>();
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const rootRef = ref<HTMLElement | null>(null);
const inputElement = ref<HTMLInputElement | null>(null);

const effectiveDisabledValue = computed(() => props.disabled);

function effectiveChecked(): boolean | undefined {
  return props.checked;
}
function effectiveDisabled(): boolean {
  return effectiveDisabledValue.value;
}
const initialChecked = props.checked ?? props.defaultChecked ?? false;
const resetSeed = props.defaultChecked ?? initialChecked;
const uncontrolledChecked = ref<boolean>(initialChecked);
const renderedChecked = computed(() => effectiveChecked() ?? uncontrolledChecked.value);

const connection: {
  instance?: ReturnType<typeof createSwitch>;
  input?: HTMLInputElement;
  accepted: boolean;
  unsubscribe?: () => void;
  form?: HTMLFormElement;
  resetTimer?: number;
} = { accepted: initialChecked };
defineExpose({ element: rootRef, input: inputElement });

function disconnectRuntime(): void {
  const owned = connection.instance;
  if (!owned) return;
  connection.accepted = owned.getChecked();
  connection.unsubscribe?.();
  connection.unsubscribe = undefined;
  unbindFormReset();
  connection.instance = undefined;
  owned.destroy();
  const unchecked = connection.input?.nextElementSibling;
  if (
    unchecked instanceof HTMLInputElement &&
    unchecked.hasAttribute("data-sw-switch-unchecked-input")
  )
    unchecked.remove();
  connection.input = undefined;
}
function connectRuntime(root: HTMLElement, input: HTMLInputElement): void {
  disconnectRuntime();
  const desired = effectiveChecked() ?? connection.accepted;
  const owned = createSwitch(root, {
    defaultChecked: resetSeed,
    ...(props.checked !== undefined ? { checked: desired } : {}),
    disabled: effectiveDisabled(),
    form: props.form,
    id: props.id,
    name: props.name,
    readOnly: props.readOnly,
    required: props.required,
    uncheckedValue: props.uncheckedValue,
    value: props.value,
    onCheckedChange: (next, detail) => {
      emit("checkedChange", next, detail);
    },
  });
  connection.instance = owned;
  connection.input = input;

  if (owned.getChecked() !== desired) owned.setChecked(desired, { emit: false });
  connection.unsubscribe = owned.subscribe("checkedChange", (detail) => {
    if (connection.instance !== owned || detail.isCanceled) return;

    renderRuntimeState(detail.checked);
    emit("update:checked", connection.accepted);
  });
  bindFormReset();
  renderRuntimeState();
}

function renderRuntimeState(next = connection.instance?.getChecked()): void {
  if (next === undefined) return;
  connection.accepted = next;

  uncontrolledChecked.value = connection.accepted;
}
function applyParentCommand(): void {
  const owned = connection.instance;
  const next = effectiveChecked();
  if (!owned || next === undefined) return;
  if (owned.getChecked() !== next || connection.input?.checked !== next)
    owned.setChecked(next, { emit: false });

  renderRuntimeState();
}
function clearResetTask(): void {
  if (connection.resetTimer !== undefined) window.clearTimeout(connection.resetTimer);
  connection.resetTimer = undefined;
}
function unbindFormReset(): void {
  clearResetTask();
  connection.form?.removeEventListener("reset", handleFormReset);
  connection.form = undefined;
}
function handleFormReset(event: Event): void {
  clearResetTask();
  const owned = connection.instance;
  // Runtime registers its reset task first. Read public state after it settles.
  connection.resetTimer = window.setTimeout(() => {
    connection.resetTimer = undefined;
    if (
      event.defaultPrevented ||
      !owned ||
      connection.instance !== owned ||
      props.checked !== undefined
    )
      return;

    renderRuntimeState(owned.getChecked());
    emit("update:checked", connection.accepted);
  }, 0);
}
function bindFormReset(): void {
  const next = connection.input?.form ?? undefined;
  if (next === connection.form) return;
  unbindFormReset();
  connection.form = next;
  next?.addEventListener("reset", handleFormReset);
}
function applyLive0(): void {
  const owned = connection.instance;
  if (!owned) return;
  owned.setDisabled(effectiveDisabled());
}
function applyLive1(): void {
  const owned = connection.instance;
  if (!owned) return;
  owned.setFormOptions({
    form: props.form,
    name: props.name,
    required: props.required,
    uncheckedValue: props.uncheckedValue,
    value: props.value,
  });
  bindFormReset();
}

function reconnectRuntime(): void {
  if (rootRef.value && inputElement.value) connectRuntime(rootRef.value, inputElement.value);
}
onMounted(reconnectRuntime);
watch(
  () => props.checked,
  (next, previous) => {
    if ((next === undefined) !== (previous === undefined)) void reconnectRuntime();
    else applyParentCommand();
  },
  { flush: "post" },
);

watch([() => props.id, () => props.readOnly, () => props.nativeButton], reconnectRuntime, {
  flush: "post",
});
watch([effectiveDisabledValue], applyLive0, { flush: "post" });
watch(
  [
    () => props.form,
    () => props.name,
    () => props.required,
    () => props.uncheckedValue,
    () => props.value,
  ],
  applyLive1,
  { flush: "post" },
);
onBeforeUnmount(disconnectRuntime);
</script>
<template>
  <component
    :is="props.nativeButton ? 'button' : 'span'"
    ref="rootRef"
    v-bind="attrs"
    :data-sw-switch="''"
    :data-sw-part="'root'"
    :role="'switch'"
    :aria-checked="String(renderedChecked)"
    :aria-disabled="effectiveDisabledValue ? 'true' : undefined"
    :aria-readonly="String(props.readOnly)"
    :aria-required="String(props.required)"
    :data-default-checked="resetSeed ? 'true' : undefined"
    :data-checked="renderedChecked ? '' : undefined"
    :data-unchecked="renderedChecked ? undefined : ''"
    :data-disabled="effectiveDisabledValue ? '' : undefined"
    :data-readonly="props.readOnly ? '' : undefined"
    :data-required="props.required ? '' : undefined"
    :data-filled="renderedChecked ? '' : undefined"
    :data-form="props.form"
    :data-id="props.id"
    :data-name="props.name"
    :data-unchecked-value="props.uncheckedValue"
    :data-value="props.value"
    :id="props.nativeButton ? props.id : undefined"
    :tabindex="effectiveDisabledValue ? -1 : 0"
    :type="props.nativeButton ? 'button' : undefined"
    :disabled="props.nativeButton ? effectiveDisabledValue : undefined"
    ><slot /></component
  ><input
    data-sw-switch-input
    aria-hidden="true"
    type="checkbox"
    tabindex="-1"
    ref="inputElement"
    :checked="initialChecked"
    :disabled="effectiveDisabledValue"
    :form="props.form"
    :id="props.id ? (props.nativeButton ? `${props.id}-input` : props.id) : undefined"
    :name="props.name"
    :required="props.required"
    :value="props.value"
    style="
      position: absolute;
      width: 1px;
      height: 1px;
      margin: -1px;
      overflow: hidden;
      clip: rect(0 0 0 0);
      white-space: nowrap;
      border: 0;
    "
  />
</template>
