<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";

defineOptions({ inheritAttrs: false });

defineSlots<{
  default?: () => unknown;
}>();
const indicatorRef = ref<HTMLElement | null>(null);

defineExpose({
  element: indicatorRef,
});
</script>

<template>
  <span ref="indicatorRef" v-bind="$attrs" data-sw-switch-thumb data-sw-part="thumb">
    <slot />
  </span>
</template>
