/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type ComboboxIconProps = React.HTMLAttributes<HTMLSpanElement>;

const ComboboxIcon = React.forwardRef<HTMLSpanElement, ComboboxIconProps>(
  function ComboboxIcon(props, forwardedRef) {
    return <span data-sw-combobox-icon aria-hidden="true" ref={forwardedRef} {...props} />;
  },
);

ComboboxIcon.displayName = "Combobox.Icon";

export default ComboboxIcon;
