/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type ComboboxLabelProps = React.HTMLAttributes<HTMLDivElement>;

const ComboboxLabel = React.forwardRef<HTMLDivElement, ComboboxLabelProps>(
  function ComboboxLabel(props, forwardedRef) {
    return <div data-sw-combobox-label ref={forwardedRef} {...props} />;
  },
);

ComboboxLabel.displayName = "Combobox.Label";

export default ComboboxLabel;
