/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";
import type { RefCapableElementProps } from "../internal/compose-refs";
import {
  getAsChildElement,
  getElementRef,
  mergeAsChildProps,
  useComposedRefs,
} from "../internal/compose-refs";

import { useComboboxContext } from "./ComboboxContext";

export type ComboboxClearProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  asChild?: boolean;
};

const ComboboxClear = React.forwardRef<HTMLElement, ComboboxClearProps>(function ComboboxClear(
  { asChild = false, children, className, ...props },
  forwardedRef,
) {
  const combobox = useComboboxContext();
  const protectedClearProps = {
    "data-sw-combobox-clear": "",
    "aria-disabled": combobox.disabled ? "true" : undefined,
    "aria-readonly": combobox.readOnly ? "true" : undefined,
    "data-disabled": combobox.disabled ? "" : undefined,
    "data-readonly": combobox.readOnly ? "" : undefined,
    disabled: combobox.disabled || undefined,
  } satisfies React.HTMLAttributes<HTMLElement> & { disabled?: boolean } & Record<
      `data-${string}`,
      string | undefined
    >;
  const clearProps = {
    ...protectedClearProps,
    ...props,
  } satisfies React.HTMLAttributes<HTMLElement> & { disabled?: boolean } & Record<
      `data-${string}`,
      string | undefined
    >;

  const asChildElement = getAsChildElement(children);
  const composedRef = useComposedRefs(
    forwardedRef,
    asChildElement ? getElementRef(asChildElement) : undefined,
  );

  if (asChild && asChildElement) {
    const child = asChildElement;
    const childProps = child.props;
    const mergedProps = mergeAsChildProps({ ...clearProps, className }, childProps, {
      protectedProps: protectedClearProps,
    });

    return React.cloneElement(child, {
      ...mergedProps,
      ref: composedRef,
    });
  }

  return (
    <button
      type="button"
      className={className}
      ref={forwardedRef as React.Ref<HTMLButtonElement>}
      {...(clearProps as React.ButtonHTMLAttributes<HTMLButtonElement>)}
      disabled={combobox.disabled}
    >
      {children}
    </button>
  );
});

ComboboxClear.displayName = "Combobox.Clear";

export default ComboboxClear;
