/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

import { useComboboxContext } from "./ComboboxContext";

export type ComboboxInputProps = React.InputHTMLAttributes<HTMLInputElement>;

const ComboboxInput = React.forwardRef<HTMLInputElement, ComboboxInputProps>(
  function ComboboxInput(props, forwardedRef) {
    const combobox = useComboboxContext();
    const inputDisabled = combobox.disabled || props.disabled === true;
    const inputReadOnly = combobox.readOnly || props.readOnly === true;

    return (
      <input
        {...props}
        data-sw-combobox-input
        role="combobox"
        aria-autocomplete="list"
        aria-disabled={inputDisabled ? "true" : undefined}
        aria-expanded={combobox.open ? "true" : "false"}
        aria-readonly={inputReadOnly ? "true" : "false"}
        aria-required={combobox.required ? "true" : "false"}
        autoComplete="off"
        data-disabled={inputDisabled ? "" : undefined}
        data-readonly={inputReadOnly ? "" : undefined}
        data-required={combobox.required ? "" : undefined}
        disabled={inputDisabled}
        readOnly={inputReadOnly}
        ref={forwardedRef}
        value={props.value ?? combobox.inputValue}
        onChange={props.onChange ?? noopComboboxInputChange}
      />
    );
  },
);

ComboboxInput.displayName = "Combobox.Input";

export default ComboboxInput;

function noopComboboxInputChange(_event: React.ChangeEvent<HTMLInputElement>): void {}
