/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import { reportPortalPlacement, resolvePortalPlacement } from "@starwind-ui/runtime/combobox";
import * as React from "react";
import { ReactPortal, type ReactPortalProps } from "../internal/portal";

export type ComboboxPortalProps = ReactPortalProps;

const ComboboxPortal = React.forwardRef<HTMLDivElement, ComboboxPortalProps>(
  function ComboboxPortal(props, forwardedRef) {
    return (
      <ReactPortal
        discoveryAttribute="data-sw-combobox-portal"
        reportPlacement={reportPortalPlacement}
        resolvePlacement={resolvePortalPlacement}
        ref={forwardedRef}
        {...props}
      />
    );
  },
);

ComboboxPortal.displayName = "Combobox.Portal";

export default ComboboxPortal;
