/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

import { useComboboxContext, useComboboxItemContext } from "./ComboboxContext";

export type ComboboxItemIndicatorProps = React.HTMLAttributes<HTMLSpanElement>;

const ComboboxItemIndicator = React.forwardRef<HTMLSpanElement, ComboboxItemIndicatorProps>(
  function ComboboxItemIndicator(props, forwardedRef) {
    const combobox = useComboboxContext();
    const item = useComboboxItemContext();
    const selected = combobox.value === item.value;

    return (
      <span
        data-sw-combobox-item-indicator
        aria-hidden="true"
        data-state={selected ? "checked" : "unchecked"}
        data-visible={selected ? "" : undefined}
        data-hidden={selected ? undefined : ""}
        hidden={!selected}
        ref={forwardedRef}
        {...props}
      />
    );
  },
);

ComboboxItemIndicator.displayName = "Combobox.ItemIndicator";

export default ComboboxItemIndicator;
