/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import ComboboxClear from "./ComboboxClear";
import ComboboxEmpty from "./ComboboxEmpty";
import ComboboxGroup from "./ComboboxGroup";
import ComboboxGroupLabel from "./ComboboxGroupLabel";
import ComboboxIcon from "./ComboboxIcon";
import ComboboxInput from "./ComboboxInput";
import ComboboxInputGroup from "./ComboboxInputGroup";
import ComboboxItem from "./ComboboxItem";
import ComboboxItemIndicator from "./ComboboxItemIndicator";
import ComboboxItemText from "./ComboboxItemText";
import ComboboxLabel from "./ComboboxLabel";
import ComboboxList from "./ComboboxList";
import ComboboxPopup from "./ComboboxPopup";
import ComboboxPortal from "./ComboboxPortal";
import ComboboxPositioner from "./ComboboxPositioner";
import ComboboxRoot from "./ComboboxRoot";
import ComboboxSeparator from "./ComboboxSeparator";
import ComboboxTrigger from "./ComboboxTrigger";
import ComboboxValue from "./ComboboxValue";

export {
  ComboboxContext,
  ComboboxItemContext,
  useComboboxContext,
  useComboboxItemContext,
} from "./ComboboxContext";

const Combobox = {
  Root: ComboboxRoot,
  Label: ComboboxLabel,
  InputGroup: ComboboxInputGroup,
  Input: ComboboxInput,
  Trigger: ComboboxTrigger,
  Icon: ComboboxIcon,
  Clear: ComboboxClear,
  Value: ComboboxValue,
  Portal: ComboboxPortal,
  Positioner: ComboboxPositioner,
  Popup: ComboboxPopup,
  Empty: ComboboxEmpty,
  List: ComboboxList,
  Group: ComboboxGroup,
  GroupLabel: ComboboxGroupLabel,
  Item: ComboboxItem,
  ItemText: ComboboxItemText,
  ItemIndicator: ComboboxItemIndicator,
  Separator: ComboboxSeparator,
};

export {
  Combobox,
  ComboboxClear,
  ComboboxEmpty,
  ComboboxGroup,
  ComboboxGroupLabel,
  ComboboxIcon,
  ComboboxInput,
  ComboboxInputGroup,
  ComboboxItem,
  ComboboxItemIndicator,
  ComboboxItemText,
  ComboboxLabel,
  ComboboxList,
  ComboboxPopup,
  ComboboxPortal,
  ComboboxPositioner,
  ComboboxRoot,
  ComboboxSeparator,
  ComboboxTrigger,
  ComboboxValue,
};

export default Combobox;

export type {
  ComboboxInputValueChangeDetails,
  ComboboxOpenChangeDetails,
  ComboboxValueChangeDetails,
} from "@starwind-ui/runtime";
