<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { createField } from "@starwind-ui/runtime/field";
import type { FormValidationTiming } from "@starwind-ui/runtime/form";
import { onBeforeUnmount, onMounted, ref, watch } from "vue";

defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{
    dataErrorVisibility?: FormValidationTiming;
    dataRevalidationTiming?: FormValidationTiming;
    dataValidationTiming?: FormValidationTiming;
    dirty?: boolean;
    disabled?: boolean;
    errorVisibility?: FormValidationTiming;
    invalid?: boolean;
    name?: string;
    revalidationTiming?: FormValidationTiming;
    touched?: boolean;
    validationTiming?: FormValidationTiming;
  }>(),
  {
    dirty: undefined,
    disabled: false,
    invalid: undefined,
    touched: undefined,
  },
);
defineSlots<{ default?: () => unknown }>();
const rootRef = ref<HTMLDivElement | null>(null);
let instance: ReturnType<typeof createField> | undefined;
defineExpose({ element: rootRef });

function destroyOwnedInstance(): void {
  const ownedInstance = instance;
  if (!ownedInstance) return;
  if (instance === ownedInstance) instance = undefined;
  ownedInstance.destroy();
}

onMounted(() => {
  const element = rootRef.value;
  if (!element) throw new Error("FieldRoot requires its root before Runtime setup.");
  instance = createField(element, {
    dirty: props.dirty,
    disabled: props.disabled,
    invalid: props.invalid,
    name: props.name,
    touched: props.touched,
  });
});

watch(
  () => props.dirty,
  (value) => instance?.setDirty(value),
  { flush: "post" },
);
watch(
  () => props.disabled,
  (value) => instance?.setDisabled(value),
  { flush: "post" },
);
watch(
  () => props.invalid,
  (value) => instance?.setInvalid(value),
  { flush: "post" },
);
watch(
  () => props.name,
  (value) => instance?.setName(value),
  { flush: "post" },
);
watch(
  () => props.touched,
  (value) => instance?.setTouched(value),
  { flush: "post" },
);
onBeforeUnmount(destroyOwnedInstance);
</script>

<template>
  <div
    ref="rootRef"
    v-bind="$attrs"
    data-sw-field
    data-sw-part="root"
    :data-dirty="props.dirty ? '' : undefined"
    :data-disabled="props.disabled ? '' : undefined"
    :data-error-visibility="props.dataErrorVisibility ?? props.errorVisibility"
    :data-invalid="props.invalid ? '' : undefined"
    :data-name="props.name"
    :data-revalidation-timing="props.dataRevalidationTiming ?? props.revalidationTiming"
    :data-touched="props.touched ? '' : undefined"
    :data-validation-timing="props.dataValidationTiming ?? props.validationTiming"
  >
    <slot />
  </div>
</template>
