<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();
const element = ref<HTMLParagraphElement | null>(null);
defineExpose({ element });
</script>

<template>
  <p ref="element" v-bind="$attrs" data-sw-field-description data-sw-part="description">
    <slot />
  </p>
</template>
