<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";

defineOptions({ inheritAttrs: false });
export type FieldErrorMatch =
  | boolean
  | "badInput"
  | "customError"
  | "patternMismatch"
  | "rangeOverflow"
  | "rangeUnderflow"
  | "stepMismatch"
  | "tooLong"
  | "tooShort"
  | "typeMismatch"
  | "valid"
  | "valueMissing";
export type FieldErrorMessageSource = "children" | "validation";
const props = withDefaults(
  defineProps<{
    hidden?: boolean;
    match?: FieldErrorMatch;
    messageSource?: FieldErrorMessageSource;
  }>(),
  {
    hidden: true,
    match: false,
  },
);
defineSlots<{ default?: () => unknown }>();
const element = ref<HTMLDivElement | null>(null);
defineExpose({ element });

function serializeMatch(value: FieldErrorMatch): string {
  return typeof value === "boolean" ? String(value) : value;
}
</script>

<template>
  <div
    ref="element"
    v-bind="$attrs"
    data-sw-field-error
    data-sw-part="error"
    :data-match="serializeMatch(props.match)"
    :data-message-source="props.messageSource"
    :hidden="props.hidden"
  >
    <slot />
  </div>
</template>
