<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script lang="ts">
import { type ComputedRef, type InjectionKey, inject, type Ref } from "vue";

export type NavigationMenuOrientation = "horizontal" | "vertical";
export type NavigationMenuRootContextValue = {
  mounted: Ref<boolean>;
  orientation: ComputedRef<NavigationMenuOrientation>;
  refreshPortalTarget: () => Promise<void>;
  value: ComputedRef<string | null>;
};
export type NavigationMenuItemContextValue = {
  open: ComputedRef<boolean>;
  value: ComputedRef<string | undefined>;
};
export type NavigationMenuViewportContextValue = { element: Ref<HTMLDivElement | null> };

export const NavigationMenuRootContext: InjectionKey<NavigationMenuRootContextValue> = Symbol(
  "NavigationMenuRootContext",
);
export const NavigationMenuItemContext: InjectionKey<NavigationMenuItemContextValue> = Symbol(
  "NavigationMenuItemContext",
);
export const NavigationMenuViewportContext: InjectionKey<NavigationMenuViewportContextValue> =
  Symbol("NavigationMenuViewportContext");

function required<T>(key: InjectionKey<T>, consumer: string): T {
  const value = inject(key);
  if (!value) throw new TypeError(consumer + " must be used inside NavigationMenu.Root.");
  return value;
}
export function useNavigationMenuRootContext(consumer: string) {
  return required(NavigationMenuRootContext, consumer);
}
export function useNavigationMenuItemContext(consumer: string) {
  return required(NavigationMenuItemContext, consumer);
}
export function useNavigationMenuViewportContext(consumer: string) {
  return required(NavigationMenuViewportContext, consumer);
}
</script>
<script setup lang="ts">
import {
  createNavigationMenu,
  type NavigationMenuValueChangeDetails,
} from "@starwind-ui/runtime/navigation-menu";
import {
  computed,
  nextTick,
  onBeforeUnmount,
  onMounted,
  onUpdated,
  provide,
  ref,
  useAttrs,
  watch,
} from "vue";
import { useVueAsChildRuntimeOwner } from "../_internal/as-child";
defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();
const props = withDefaults(
  defineProps<{
    modelValue?: string | null;
    defaultValue?: string | null;
    openDelay?: number;
    closeDelay?: number;
    closeOnEscape?: boolean;
    closeOnOutsideInteract?: boolean;
    orientation?: NavigationMenuOrientation;
  }>(),
  {
    modelValue: undefined,
    defaultValue: null,
    openDelay: 50,
    closeDelay: 50,
    closeOnEscape: true,
    closeOnOutsideInteract: true,
    orientation: "horizontal",
  },
);
const emit = defineEmits<{
  "update:modelValue": [value: string | null];
  valueChange: [value: string | null, detail: NavigationMenuValueChangeDetails];
}>();
const publicAttrs = useAttrs();
const element = ref<HTMLElement | null>(null);
const mounted = ref(false);
const initialDefaultValue = props.defaultValue;
const uncontrolledValue = ref<string | null>(initialDefaultValue);
const value = computed(() =>
  props.modelValue !== undefined ? props.modelValue : uncontrolledValue.value,
);
const orientation = computed(() => props.orientation);
let instance: ReturnType<typeof createNavigationMenu> | undefined;
let generation = 0;
let pendingDetail: NavigationMenuValueChangeDetails | undefined;
let acceptedDetail: NavigationMenuValueChangeDetails | undefined;
let unsubscribeValueChange: (() => void) | undefined;
provide(NavigationMenuRootContext, { mounted, orientation, refreshPortalTarget, value });
defineExpose({
  element,
  getValue: () => instance?.getValue(),
  setValue: (next: string | null) => instance?.setValue(next),
});
function handleValueChange(next: string | null, detail: NavigationMenuValueChangeDetails) {
  pendingDetail = detail;
  emit("valueChange", next, detail);
}
function handleAcceptedValueChange(detail: NavigationMenuValueChangeDetails) {
  if (pendingDetail === detail) pendingDetail = undefined;
  if (props.modelValue === undefined) uncontrolledValue.value = detail.value;
  emit("update:modelValue", detail.value);
  if (props.modelValue !== undefined) {
    acceptedDetail = detail;
    void resyncControlled(detail);
  }
}
async function resyncControlled(detail: NavigationMenuValueChangeDetails) {
  await nextTick();
  if (acceptedDetail !== detail || props.modelValue === undefined || !instance) return;
  acceptedDetail = undefined;
  instance.setValue(props.modelValue, {
    emit: false,
    event: detail.event,
    reason: detail.reason,
    trigger: detail.trigger,
  });
}
function syncUncontrolledFromRuntime() {
  if (props.modelValue !== undefined || !instance) return;
  const current = instance.getValue();
  if (!Object.is(uncontrolledValue.value, current)) uncontrolledValue.value = current;
}
async function refreshPortalTarget() {
  const owned = instance;
  const ownGeneration = generation;
  if (!mounted.value || !owned) return;
  await nextTick();
  if (!mounted.value || ownGeneration !== generation || instance !== owned) return;
  const replayValue = props.modelValue !== undefined ? props.modelValue : owned.getValue();
  owned.setValue(replayValue, { emit: false });
}
function destroyOwnedInstance() {
  const owned = instance;
  instance = undefined;
  unsubscribeValueChange?.();
  unsubscribeValueChange = undefined;
  pendingDetail = undefined;
  acceptedDetail = undefined;
  owned?.destroy();
}
function setupRuntime() {
  if (!element.value) return;
  instance = createNavigationMenu(element.value, {
    defaultValue: uncontrolledValue.value,
    openDelay: props.openDelay,
    closeDelay: props.closeDelay,
    closeOnEscape: props.closeOnEscape,
    closeOnOutsideInteract: props.closeOnOutsideInteract,
    ...(props.modelValue === undefined ? {} : { value: props.modelValue }),
    onValueChange: handleValueChange,
  });
  unsubscribeValueChange = instance.subscribe("valueChange", handleAcceptedValueChange);
}
async function recreateRuntime() {
  const current = instance?.getValue();
  if (props.modelValue === undefined && current !== undefined) uncontrolledValue.value = current;
  const ownGeneration = ++generation;
  mounted.value = false;
  destroyOwnedInstance();
  await nextTick();
  if (ownGeneration !== generation || !element.value) return;
  setupRuntime();
  mounted.value = true;
}
useVueAsChildRuntimeOwner(element, recreateRuntime);
onMounted(() => {
  setupRuntime();
  mounted.value = true;
});
onUpdated(syncUncontrolledFromRuntime);
watch(
  () => props.modelValue,
  (next, previous) => {
    if ((next === undefined) !== (previous === undefined)) {
      void recreateRuntime();
      return;
    }
    if (next === undefined || !instance || Object.is(instance.getValue(), next)) return;
    instance.setValue(next, { emit: false });
  },
  { flush: "post" },
);
watch(
  [
    () => props.openDelay,
    () => props.closeDelay,
    () => props.closeOnEscape,
    () => props.closeOnOutsideInteract,
  ],
  () => {
    void recreateRuntime();
  },
  { flush: "post" },
);
onBeforeUnmount(() => {
  generation += 1;
  mounted.value = false;
  destroyOwnedInstance();
});
</script>
<template>
  <nav
    ref="element"
    v-bind="publicAttrs"
    data-sw-nav-menu
    data-sw-part="root"
    :data-default-value="
      props.modelValue === undefined ? (initialDefaultValue ?? undefined) : undefined
    "
    :data-controlled-value="props.modelValue === null ? '' : undefined"
    :data-value="props.modelValue ?? undefined"
    :data-open-delay="props.openDelay"
    :data-close-delay="props.closeDelay"
    :data-close-on-escape="props.closeOnEscape ? 'true' : 'false'"
    :data-close-on-outside-interact="props.closeOnOutsideInteract ? 'true' : 'false'"
    :data-orientation="props.orientation"
    :data-state="value === null ? 'closed' : 'open'"
  >
    <slot />
  </nav>
</template>
