<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { computed, provide, ref, useAttrs } from "vue";
import { NavigationMenuItemContext, useNavigationMenuRootContext } from "./NavigationMenuRoot.vue";

defineOptions({ inheritAttrs: false });
const props = defineProps<{ value?: string }>();
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const root = useNavigationMenuRootContext("NavigationMenuItem");
const element = ref<HTMLLIElement | null>(null);
const itemValue = computed(() => props.value);
const open = computed(() => itemValue.value !== undefined && root.value.value === itemValue.value);
provide(NavigationMenuItemContext, { open, value: itemValue });
defineExpose({ element });
</script>
<template>
  <li
    ref="element"
    v-bind="attrs"
    data-sw-nav-menu-item
    data-sw-part="item"
    :data-value="props.value"
    :data-state="open ? 'open' : 'closed'"
  >
    <slot />
  </li>
</template>
