<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";
import { useNavigationMenuItemContext } from "./NavigationMenuRoot.vue";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();
const item = useNavigationMenuItemContext("NavigationMenuContent");
const element = ref<HTMLDivElement | null>(null);
defineExpose({ element });
</script>
<template>
  <div
    ref="element"
    v-bind="$attrs"
    data-sw-nav-menu-content
    data-sw-part="content"
    :data-state="item.open.value ? 'open' : 'closed'"
    hidden
  >
    <slot />
  </div>
</template>
