<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";

defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{
    side?: "top" | "right" | "bottom" | "left";
    align?: "start" | "center" | "end";
    sideOffset?: number;
    alignOffset?: number;
    avoidCollisions?: boolean;
    collisionPadding?: number;
  }>(),
  {
    side: "bottom",
    align: "start",
    sideOffset: 4,
    alignOffset: 0,
    avoidCollisions: true,
    collisionPadding: 8,
  },
);
defineSlots<{ default?: () => unknown }>();
const element = ref<HTMLDivElement | null>(null);
defineExpose({ element });
</script>
<template>
  <div
    ref="element"
    v-bind="$attrs"
    data-sw-nav-menu-positioner
    data-sw-part="positioner"
    data-state="closed"
    :data-side="props.side"
    :data-align="props.align"
    :data-side-offset="props.sideOffset"
    :data-align-offset="props.alignOffset"
    :data-avoid-collisions="props.avoidCollisions ? 'true' : 'false'"
    :data-collision-padding="props.collisionPadding"
  >
    <slot />
  </div>
</template>
