<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { computed, ref, useAttrs } from "vue";
import { useComboboxContext, useComboboxItemContext } from "./ComboboxRoot.vue";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const element = ref<HTMLSpanElement | null>(null);
const combobox = useComboboxContext("ItemIndicator");
const item = useComboboxItemContext("ItemIndicator");
const selected = computed(() => combobox.value.value === item.value.value);
defineExpose({ element });
</script>
<template>
  <span
    ref="element"
    v-bind="attrs"
    data-sw-combobox-item-indicator
    data-sw-part="itemIndicator"
    aria-hidden="true"
    :data-state="selected ? 'checked' : 'unchecked'"
    :data-hidden="selected ? undefined : ''"
    :hidden="!selected"
    ><slot
  /></span>
</template>
