<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { ref, useAttrs } from "vue";
import { useComboboxContext } from "./ComboboxRoot.vue";

defineOptions({ inheritAttrs: false });
const props = defineProps<{ placeholder?: string }>();
const slots = defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const element = ref<HTMLSpanElement | null>(null);
const initialPlaceholder = props.placeholder;
useComboboxContext("Value");
defineExpose({ element });
</script>
<template>
  <span
    ref="element"
    v-bind="attrs"
    :data-sw-combobox-value="slots.default ? undefined : ''"
    data-sw-part="value"
    :data-placeholder="props.placeholder"
    ><slot>{{ initialPlaceholder }}</slot></span
  >
</template>
