<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { ref } from "vue";
import { useComboboxContext } from "./ComboboxRoot.vue";

defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{
    align?: "start" | "center" | "end";
    alignOffset?: number;
    avoidCollisions?: boolean;
    side?: "top" | "right" | "bottom" | "left";
    sideOffset?: number;
  }>(),
  { align: "start", alignOffset: 0, avoidCollisions: true, side: "bottom", sideOffset: 6 },
);
defineSlots<{ default?: () => unknown }>();
const element = ref<HTMLDivElement | null>(null);
const combobox = useComboboxContext("Positioner");
defineExpose({ element });
</script>
<template>
  <div
    ref="element"
    v-bind="$attrs"
    data-sw-combobox-positioner
    data-sw-part="positioner"
    :data-state="combobox.open.value ? 'open' : 'closed'"
    :data-side="props.side"
    :data-align="props.align"
    :data-side-offset="props.sideOffset"
    :data-align-offset="props.alignOffset"
    :data-avoid-collisions="props.avoidCollisions ? 'true' : 'false'"
  >
    <slot />
  </div>
</template>
