<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { reportPortalPlacement, resolvePortalPlacement } from "@starwind-ui/runtime/combobox";
import { onBeforeUnmount, onMounted, ref } from "vue";
import { useVuePortalPlacement } from "../_internal/portal";
import { useComboboxContext } from "./ComboboxRoot.vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{ container?: string | HTMLElement; disabled?: boolean }>(),
  { disabled: false },
);
defineSlots<{ default?: () => unknown }>();
const combobox = useComboboxContext("Portal");
const portalRef = ref<HTMLDivElement | null>(null);
const owner = Symbol("ComboboxPortal");
const placement = useVuePortalPlacement({
  active: () => combobox.mounted.value,
  container: () => props.container,
  disabled: () => props.disabled,
  element: portalRef,
  reference: () => combobox.element.value,
  runtime: { reportPortalPlacement, resolvePortalPlacement },
});
onMounted(() => {
  combobox.registerPortal(owner, portalRef.value);
});
onBeforeUnmount(() => {
  combobox.registerPortal(owner, null);
});
</script>
<template>
  <Teleport :to="placement.target.value" :disabled="placement.disabled.value"
    ><div
      ref="portalRef"
      v-bind="$attrs"
      data-sw-combobox-portal
      :data-container="typeof props.container === 'string' ? props.container : undefined"
      :data-disabled="props.disabled ? '' : undefined"
      :data-placement="placement.ready.value ? 'ready' : 'pending'"
      data-sw-portal-placement="framework"
      data-sw-part="portal"
      data-floating-root
    >
      <slot /></div
  ></Teleport>
</template>
