/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import InputOtpGroup from "./InputOtpGroup.vue";
import InputOtpRoot from "./InputOtpRoot.vue";
import InputOtpSeparator from "./InputOtpSeparator.vue";
import InputOtpSlot from "./InputOtpSlot.vue";

const InputOtp = {
  Root: InputOtpRoot,
  Group: InputOtpGroup,
  Separator: InputOtpSeparator,
  Slot: InputOtpSlot,
};

export { InputOtp, InputOtpGroup, InputOtpRoot, InputOtpSeparator, InputOtpSlot };

export default InputOtp;

export type { InputOtpValueChangeDetails } from "@starwind-ui/runtime";
