/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

// Svelte 5 public beta adapter output.
import ContextMenuCheckboxItem from "../menu/MenuCheckboxItem.svelte";
import ContextMenuCheckboxItemIndicator from "../menu/MenuCheckboxItemIndicator.svelte";
import ContextMenuGroup from "../menu/MenuGroup.svelte";
import ContextMenuItem from "../menu/MenuItem.svelte";
import ContextMenuLabel from "../menu/MenuLabel.svelte";
import ContextMenuLinkItem from "../menu/MenuLinkItem.svelte";
import ContextMenuPopup from "../menu/MenuPopup.svelte";
import ContextMenuPortal from "../menu/MenuPortal.svelte";
import ContextMenuPositioner from "../menu/MenuPositioner.svelte";
import ContextMenuRadioGroup from "../menu/MenuRadioGroup.svelte";
import ContextMenuRadioItem from "../menu/MenuRadioItem.svelte";
import ContextMenuRadioItemIndicator from "../menu/MenuRadioItemIndicator.svelte";
import ContextMenuSeparator from "../menu/MenuSeparator.svelte";
import ContextMenuShortcut from "../menu/MenuShortcut.svelte";
import ContextMenuSubmenuRoot from "../menu/MenuSubmenuRoot.svelte";
import ContextMenuSubmenuTrigger from "../menu/MenuSubmenuTrigger.svelte";
import ContextMenuRoot from "./ContextMenuRoot.svelte";
import ContextMenuTrigger from "./ContextMenuTrigger.svelte";
const ContextMenu = {
  Root: ContextMenuRoot,
  Trigger: ContextMenuTrigger,
  Portal: ContextMenuPortal,
  Positioner: ContextMenuPositioner,
  Popup: ContextMenuPopup,
  Item: ContextMenuItem,
  LinkItem: ContextMenuLinkItem,
  CheckboxItem: ContextMenuCheckboxItem,
  CheckboxItemIndicator: ContextMenuCheckboxItemIndicator,
  RadioGroup: ContextMenuRadioGroup,
  RadioItem: ContextMenuRadioItem,
  RadioItemIndicator: ContextMenuRadioItemIndicator,
  Group: ContextMenuGroup,
  Label: ContextMenuLabel,
  Separator: ContextMenuSeparator,
  Shortcut: ContextMenuShortcut,
  SubmenuRoot: ContextMenuSubmenuRoot,
  SubmenuTrigger: ContextMenuSubmenuTrigger,
};
export {
  ContextMenu,
  ContextMenuRoot,
  ContextMenuTrigger,
  ContextMenuCheckboxItem,
  ContextMenuCheckboxItemIndicator,
  ContextMenuGroup,
  ContextMenuItem,
  ContextMenuLabel,
  ContextMenuLinkItem,
  ContextMenuPopup,
  ContextMenuPortal,
  ContextMenuPositioner,
  ContextMenuRadioGroup,
  ContextMenuRadioItem,
  ContextMenuRadioItemIndicator,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuSubmenuRoot,
  ContextMenuSubmenuTrigger,
};
export default ContextMenu;
export type {
  ContextMenuCloseCompleteDetails,
  ContextMenuOpenChangeDetails,
  MenuCheckedChangeDetails,
  MenuValueChangeDetails,
} from "@starwind-ui/runtime";
