/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import PreviewCardArrow from "./PreviewCardArrow";
import PreviewCardBackdrop from "./PreviewCardBackdrop";
import PreviewCardPopup from "./PreviewCardPopup";
import PreviewCardPortal from "./PreviewCardPortal";
import PreviewCardPositioner from "./PreviewCardPositioner";
import PreviewCardRoot from "./PreviewCardRoot";
import PreviewCardTrigger from "./PreviewCardTrigger";
import PreviewCardViewport from "./PreviewCardViewport";

const PreviewCard = {
  Root: PreviewCardRoot,
  Trigger: PreviewCardTrigger,
  Portal: PreviewCardPortal,
  Positioner: PreviewCardPositioner,
  Popup: PreviewCardPopup,
  Arrow: PreviewCardArrow,
  Backdrop: PreviewCardBackdrop,
  Viewport: PreviewCardViewport,
};

export {
  PreviewCard,
  PreviewCardArrow,
  PreviewCardBackdrop,
  PreviewCardPopup,
  PreviewCardPortal,
  PreviewCardPositioner,
  PreviewCardRoot,
  PreviewCardTrigger,
  PreviewCardViewport,
};

export default PreviewCard;

export type { PreviewCardOpenChangeDetails } from "@starwind-ui/runtime";
