/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import * as React from "react";
export type PreviewCardViewportProps = React.HTMLAttributes<HTMLDivElement>;
const PreviewCardViewport = React.forwardRef<HTMLDivElement, PreviewCardViewportProps>(
  function PreviewCardViewport(props, ref) {
    return (
      <div
        {...props}
        data-sw-preview-card-viewport=""
        data-sw-part="viewport"
        data-state="closed"
        ref={ref}
      />
    );
  },
);
PreviewCardViewport.displayName = "PreviewCard.Viewport";
export default PreviewCardViewport;
