/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type PreviewCardPortalProps = React.HTMLAttributes<HTMLDivElement>;

const PreviewCardPortal = React.forwardRef<HTMLDivElement, PreviewCardPortalProps>(
  function PreviewCardPortal(props, forwardedRef) {
    return <div data-sw-preview-card-portal ref={forwardedRef} {...props} />;
  },
);

PreviewCardPortal.displayName = "PreviewCard.Portal";

export default PreviewCardPortal;
