<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script lang="ts">
  import { createInputOtp, type InputOtpValueChangeDetails } from "@starwind-ui/runtime/input-otp";
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children" | "id"> & {
    children?: Snippet;
    value?: string;
    defaultValue?: string;
    disabled?: boolean;
    form?: string;
    id?: string;
    maxLength?: number;
    name?: string;
    pattern?: RegExp | string;
    readOnly?: boolean;
    required?: boolean;
    onValueChange?: (value: string, detail: InputOtpValueChangeDetails) => void;
    ref?: (element: HTMLDivElement | null) => void;
  };
  let { children, value = $bindable(), defaultValue, disabled = false, form, id, maxLength = 6, name, pattern, readOnly = false, required = false, onValueChange, ref, ...rest }: Props = $props();
  const initialModel = untrack(() => value);
  const seed = untrack(() => defaultValue ?? initialModel ?? "");
  const initial = initialModel ?? seed;
  let renderedValue = $state(initial);
  let rootNode = $state.raw<HTMLDivElement | null>(null);
  let connection = $state.raw<ReturnType<typeof connectOtp> | undefined>();
  let patternText = $derived((pattern instanceof RegExp ? pattern.source : pattern ?? "\\d").replace(/^\^|\$$/g, ""));
  let inputMode = $derived<"numeric" | "text">(["\\d","[0-9]","\\d+","[0-9]+"].includes(patternText) ? "numeric" : "text");
  function readInputs() { return { value, disabled, form, id, maxLength, name, pattern: patternText, readOnly, required }; }
  function connectOtp(root: HTMLElement) {
    let previous = readInputs();
    const controlled = false;
    let instance: ReturnType<typeof createInputOtp>;
    let unsubscribe = () => {};
    let disposed = false;
    let associated: HTMLFormElement | null = null;
    let resetTimer: number | undefined;
    function publishCurrent(): void { const accepted = instance.getValue();
    if (!controlled) { renderedValue = accepted; }
    if ((readInputs()).value !== accepted) { value = accepted; } }
    function synchronize(value: string | undefined): void {
      if (value === undefined) return;
      if (instance.getValue() !== value) instance.setValue(value, {"emit":false});
      publishCurrent();
    }
    function clearReset(): void {
      if (resetTimer !== undefined) window.clearTimeout(resetTimer);
      resetTimer = undefined;
    }
    function reset(event: Event): void {
      clearReset();
      resetTimer = window.setTimeout(() => {
        resetTimer = undefined;
        if (disposed || event.defaultPrevented) return;
        untrack(() => { if (controlled) synchronize((readInputs()).value); else publishCurrent(); });
      }, 0);
    }
    function bindReset(): void {
      const form = root.querySelector<HTMLInputElement>('[data-sw-input-otp-input]')?.form ?? null;
      if (associated === form) return;
      clearReset();
      associated?.removeEventListener('reset', reset);
      associated = form;
      associated?.addEventListener('reset', reset);
    }
    function stop(): void {
      clearReset();
      associated?.removeEventListener('reset', reset);
      associated = null;
      unsubscribe();
      instance.destroy();
    }
    function start(value: string): void {
      const options = readInputs();
      instance = createInputOtp(root, {
        disabled: options.disabled,
form: options.form,
id: options.id,
maxLength: options.maxLength,
name: options.name,
pattern: options.pattern,
readOnly: options.readOnly,
required: options.required,
        defaultValue: seed,
        onValueChange(next, detail) { untrack(() => { onValueChange?.(next, detail); }); },
        ...(controlled && options.value !== undefined ? { value: options.value } : {}),
      });
      instance.setValue(controlled ? options.value ?? value : value, {"emit":false});
      publishCurrent();
      const owner = instance;
      unsubscribe = instance.subscribe('valueChange', () => { untrack(() => {
        if (disposed || owner !== instance) return;
        publishCurrent();


       }); });
      bindReset();
    }
    start(previous.value ?? renderedValue);
    return {
      update(): void {
        const next = readInputs();
        if (next.pattern !== previous.pattern || next.readOnly !== previous.readOnly || next.maxLength !== previous.maxLength) {
          const accepted = instance.getValue();
          stop();
          start(accepted);
        } else {
          instance.refresh();
        }
          if (next.disabled !== previous.disabled) instance.setDisabled(next.disabled);
          if (next.form !== previous.form || next.id !== previous.id || next.name !== previous.name || next.required !== previous.required) {
            instance.setFormOptions({
              ...(next.form !== previous.form ? { form: next.form } : {}),
...(next.id !== previous.id ? { id: next.id } : {}),
...(next.name !== previous.name ? { name: next.name } : {}),
...(next.required !== previous.required ? { required: next.required } : {}),
            });
          }
        if (next.value !== previous.value) synchronize(next.value);
        publishCurrent();
        bindReset();
        previous = next;
      },
      destroy(): void {
        disposed = true;
        stop();
      },
    };
  }
  const attachRuntime: Attachment<HTMLDivElement> = (element) => {
    rootNode = element;
    return () => { rootNode = null; };
  };
  $effect(() => {
    const root = rootNode;
    if (!root) return;
    const owned = untrack(() => connectOtp(root));
    connection = owned;
    return () => { if (connection === owned) connection = undefined; owned.destroy(); };
  });
  $effect(() => {
    const owned = connection;
    readInputs();
    if (owned) untrack(() => owned.update());
  });
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>
<!-- Runtime forwards root focus to the internal native input. -->
<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
<div {...rest} data-sw-input-otp="" data-default-value={seed} data-disabled={disabled ? "" : undefined}
  data-form={form} data-id={id} data-max-length={maxLength} data-name={name} data-pattern={patternText}
  data-readonly={readOnly ? "" : undefined} data-required={required ? "" : undefined} data-value={renderedValue}
  aria-disabled={disabled} tabindex={disabled ? -1 : 0} {@attach attachRuntime} {@attach attachRef}>
  <input data-sw-input-otp-input="" autocomplete="one-time-code" class="sr-only"
    {disabled} {form} {id} inputmode={inputMode} maxlength={maxLength} {name} readonly={readOnly} {required} tabindex="-1" value={initial} />
  {@render children?.()}
</div>
