/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type DropzoneInputProps = Omit<React.InputHTMLAttributes<HTMLInputElement>, "type">;

const DropzoneInput = React.forwardRef<HTMLInputElement, DropzoneInputProps>(function DropzoneInput(
  { className, disabled = false, ...props },
  forwardedRef,
) {
  return (
    <input
      {...props}
      data-sw-dropzone-input
      type="file"
      data-disabled={disabled ? "" : undefined}
      className={["sr-only", className].filter(Boolean).join(" ") || undefined}
      disabled={disabled}
      ref={forwardedRef}
      tabIndex={-1}
    />
  );
});

DropzoneInput.displayName = "Dropzone.Input";

export default DropzoneInput;
