/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import ToggleRoot from "./ToggleRoot.svelte";
const Toggle = { Root: ToggleRoot };
export { Toggle, ToggleRoot };
export default Toggle;

export type { TogglePressedChangeDetails } from "@starwind-ui/runtime";
