/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import { createFieldset } from "@starwind-ui/runtime/fieldset";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";
export type FieldsetRootProps = Omit<React.ComponentPropsWithoutRef<"fieldset">, "disabled"> & {
  disabled?: boolean;
};
const FieldsetRoot = React.forwardRef<HTMLFieldSetElement, FieldsetRootProps>(function FieldsetRoot(
  { children, disabled = false, ...rest },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLFieldSetElement>(null);
  const composedRef = React.useCallback(
    (element: HTMLFieldSetElement | null) => {
      rootRef.current = element;
      return setRef(forwardedRef, element);
    },
    [forwardedRef],
  );
  const initialDisabled = React.useRef(disabled).current;
  const owned = React.useRef<ReturnType<typeof createFieldset> | undefined>(undefined);
  useIsomorphicLayoutEffect(() => {
    const element = rootRef.current;
    if (!element) return;
    owned.current = createFieldset(element, { disabled: disabled });
    return () => {
      const previous = owned.current;
      owned.current = undefined;
      previous?.destroy();
    };
  }, []);
  useIsomorphicLayoutEffect(() => {
    owned.current?.setDisabled(disabled);
  }, [disabled]);
  return (
    <fieldset
      {...rest}
      data-sw-fieldset={""}
      disabled={initialDisabled}
      data-disabled={initialDisabled ? "" : undefined}
      ref={composedRef}
    >
      {children}
    </fieldset>
  );
});
FieldsetRoot.displayName = "Fieldset.Root";
export default FieldsetRoot;
