<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script lang="ts">
  import type { Snippet } from "svelte";

  import type { HTMLAttributes } from "svelte/elements";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    children?: Snippet; isUploading?: boolean;
    ref?: (element: HTMLDivElement | null) => void;
  };
  let { children, isUploading = false, ref, ...rest }: Props = $props();
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>
<div {...rest} data-sw-dropzone-upload-indicator="" data-is-uploading={String(isUploading)} hidden={isUploading} {@attach attachRef}>{@render children?.()}</div>
