<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script lang="ts">

  import type { HTMLInputAttributes } from "svelte/elements";
  type Props = Omit<HTMLInputAttributes, "children" | "type" | "files"> & {
    disabled?: boolean;
    ref?: (element: HTMLInputElement | null) => void;
  };
  let { disabled = false, class: className, ref, ...rest }: Props = $props();
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLInputElement>(() => ref);
</script>
<input {...rest} data-sw-dropzone-input="" class={["sr-only", className]} data-disabled={disabled ? "" : undefined}
  {disabled} type="file" tabindex="-1" {@attach attachRef} />
