/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import ToastAction from "./ToastAction";
import ToastClose from "./ToastClose";
import ToastContent from "./ToastContent";
import ToastDescription from "./ToastDescription";
import ToastRoot from "./ToastRoot";
import ToastTemplate from "./ToastTemplate";
import ToastTitle from "./ToastTitle";
import ToastTitleText from "./ToastTitleText";
import ToastViewport from "./ToastViewport";

const Toast = {
  Viewport: ToastViewport,
  Template: ToastTemplate,
  Root: ToastRoot,
  Content: ToastContent,
  Title: ToastTitle,
  TitleText: ToastTitleText,
  Description: ToastDescription,
  Action: ToastAction,
  Close: ToastClose,
};

export {
  Toast,
  ToastAction,
  ToastClose,
  ToastContent,
  ToastDescription,
  ToastRoot,
  ToastTemplate,
  ToastTitle,
  ToastTitleText,
  ToastViewport,
};

export default Toast;

export type { ToastApi, ToastOptions, ToastPromiseOptions } from "@starwind-ui/runtime";
export { toast } from "@starwind-ui/runtime/toast";
