/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

type Variant = "default" | "error" | "info" | "loading" | "success" | "warning";

export type ToastRootProps = React.HTMLAttributes<HTMLDivElement> & {
  variant?: Variant;
};

const ToastRoot = React.forwardRef<HTMLDivElement, ToastRootProps>(function ToastRoot(
  { variant = "default", ...props },
  forwardedRef,
) {
  return (
    <div
      data-sw-toast-root
      data-state="open"
      data-variant={variant}
      role="dialog"
      aria-modal="false"
      ref={forwardedRef}
      {...props}
    />
  );
});

ToastRoot.displayName = "Toast.Root";

export default ToastRoot;
