/**
 * Generated by scripts/portable-runtime/generate-astro-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import ScrollAreaContent from "./ScrollAreaContent.astro";
import ScrollAreaCorner from "./ScrollAreaCorner.astro";
import ScrollAreaRoot from "./ScrollAreaRoot.astro";
import ScrollAreaScrollbar from "./ScrollAreaScrollbar.astro";
import ScrollAreaThumb from "./ScrollAreaThumb.astro";
import ScrollAreaViewport from "./ScrollAreaViewport.astro";

const ScrollArea = {
  Root: ScrollAreaRoot,
  Viewport: ScrollAreaViewport,
  Content: ScrollAreaContent,
  Scrollbar: ScrollAreaScrollbar,
  Thumb: ScrollAreaThumb,
  Corner: ScrollAreaCorner,
};

export {
  ScrollArea,
  ScrollAreaContent,
  ScrollAreaCorner,
  ScrollAreaRoot,
  ScrollAreaScrollbar,
  ScrollAreaThumb,
  ScrollAreaViewport,
};

export default ScrollArea;
