/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import { createForm, type FormValidationTiming } from "@starwind-ui/runtime/form";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export type FormRootProps = React.ComponentPropsWithoutRef<"form"> & {
  "data-error-visibility"?: FormValidationTiming;
  "data-revalidation-timing"?: FormValidationTiming;
  "data-validation-timing"?: FormValidationTiming;
  errorVisibility?: FormValidationTiming;
  revalidationTiming?: FormValidationTiming;
  validationTiming?: FormValidationTiming;
};

const FormRoot = React.forwardRef<HTMLFormElement, FormRootProps>(function FormRoot(
  {
    children,
    "data-error-visibility": dataErrorVisibility,
    "data-revalidation-timing": dataRevalidationTiming,
    "data-validation-timing": dataValidationTiming,
    errorVisibility,
    revalidationTiming,
    validationTiming,
    ...props
  },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLFormElement>(null);
  const instanceRef = React.useRef<ReturnType<typeof createForm> | undefined>(undefined);

  const composedRef = React.useCallback(
    (node: HTMLFormElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  useIsomorphicLayoutEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const instance = createForm(root);
    instanceRef.current = instance;

    return () => {
      instance.destroy();
      if (instanceRef.current === instance) {
        instanceRef.current = undefined;
      }
    };
  }, []);

  return (
    <form
      data-sw-form
      data-slot="form"
      data-error-visibility={dataErrorVisibility ?? errorVisibility}
      data-revalidation-timing={dataRevalidationTiming ?? revalidationTiming}
      data-validation-timing={dataValidationTiming ?? validationTiming}
      ref={composedRef}
      {...props}
    >
      {children}
    </form>
  );
});

FormRoot.displayName = "Form.Root";

export default FormRoot;
