/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import {
  createForm,
  type FormExternalErrorOptions,
  type FormExternalErrors,
  type FormOptions,
  type FormValidationTiming,
} from "@starwind-ui/runtime/form";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export type FormRootProps = React.ComponentPropsWithoutRef<"form"> & {
  options?: FormOptions;
  errors?: FormExternalErrors;
  errorOptions?: FormExternalErrorOptions;
  "data-error-visibility"?: FormValidationTiming;
  "data-revalidation-timing"?: FormValidationTiming;
  "data-validation-timing"?: FormValidationTiming;
  errorVisibility?: FormValidationTiming;
  revalidationTiming?: FormValidationTiming;
  validationTiming?: FormValidationTiming;
};

const FormRoot = React.forwardRef<HTMLFormElement, FormRootProps>(function FormRoot(
  {
    children,
    options,
    errors,
    errorOptions,
    "data-error-visibility": dataErrorVisibility,
    "data-revalidation-timing": dataRevalidationTiming,
    "data-validation-timing": dataValidationTiming,
    errorVisibility,
    revalidationTiming,
    validationTiming,
    ...props
  },
  forwardedRef,
) {
  const configured = React.useRef({ options: false, errors: false }).current;
  const rootRef = React.useRef<HTMLFormElement>(null);
  const instanceRef = React.useRef<ReturnType<typeof createForm> | undefined>(undefined);

  const composedRef = React.useCallback(
    (node: HTMLFormElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  useIsomorphicLayoutEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const instance = createForm(root);
    instanceRef.current = instance;

    return () => {
      if (instanceRef.current === instance) instanceRef.current = undefined;
      instance.destroy();
    };
  }, []);

  useIsomorphicLayoutEffect(() => {
    const instance = instanceRef.current;
    if (instance) {
      if (options !== undefined || configured.options) {
        configured.options = options !== undefined;
        instance.setOptions({
          fieldValidators: undefined,
          formValidators: undefined,
          asyncFieldValidators: undefined,
          asyncFormValidators: undefined,
          asyncValidationDebounceMs: undefined,
          externalErrorsOnReset: undefined,
          onSubmit: undefined,
          ...options,
        } satisfies Record<keyof FormOptions, unknown>);
      }
    }
  }, [options]);
  useIsomorphicLayoutEffect(() => {
    const instance = instanceRef.current;
    if (instance) {
      if (errors !== undefined || configured.errors) {
        configured.errors = errors !== undefined;
        instance.setExternalErrors(errors ?? {}, errorOptions);
      }
    }
  }, [errors, errorOptions]);

  return (
    <form
      data-sw-form
      data-slot="form"
      data-error-visibility={dataErrorVisibility ?? errorVisibility}
      data-revalidation-timing={dataRevalidationTiming ?? revalidationTiming}
      data-validation-timing={dataValidationTiming ?? validationTiming}
      ref={composedRef}
      {...props}
    >
      {children}
    </form>
  );
});

FormRoot.displayName = "Form.Root";

export default FormRoot;
