<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { type HTMLAttributes, ref, useAttrs } from "vue";

defineOptions({ inheritAttrs: false });

type NativeElementProps = /* @vue-ignore */ HTMLAttributes;
const props = defineProps<{ targetId?: string } & NativeElementProps>();
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const element = ref<HTMLButtonElement | null>(null);

defineExpose({ element });
</script>

<template>
  <button
    ref="element"
    v-bind="attrs"
    data-sw-drawer-trigger
    data-sw-part="trigger"
    type="button"
    aria-haspopup="dialog"
    :data-sw-drawer-target-id="props.targetId"
    data-state="closed"
  >
    <slot />
  </button>
</template>
