<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { type HTMLAttributes, ref } from "vue";

defineOptions({ inheritAttrs: false });

type NativeElementProps = /* @vue-ignore */ HTMLAttributes;
const props = defineProps<{ side?: "top" | "right" | "bottom" | "left" } & NativeElementProps>();
defineSlots<{ default?: () => unknown }>();
const element = ref<HTMLDialogElement | null>(null);

defineExpose({ element });
</script>

<template>
  <dialog
    ref="element"
    v-bind="$attrs"
    data-sw-drawer-popup
    data-sw-part="popup"
    data-state="closed"
    :data-side="props.side ?? 'right'"
  >
    <slot />
  </dialog>
</template>
