/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import {
  createNavigationMenu,
  type NavigationMenuValueChangeDetails,
} from "@starwind-ui/runtime/navigation-menu";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export type NavigationMenuRootProps = Omit<
  React.HTMLAttributes<HTMLElement>,
  "defaultValue" | "onChange"
> & {
  defaultValue?: string | null;
  value?: string | null;
  openDelay?: number;
  closeDelay?: number;
  closeOnEscape?: boolean;
  closeOnOutsideInteract?: boolean;
  orientation?: "horizontal" | "vertical";
  onValueChange?: (value: string | null, details: NavigationMenuValueChangeDetails) => void;
};

const NavigationMenuRoot = React.forwardRef<HTMLElement, NavigationMenuRootProps>(
  function NavigationMenuRoot(
    {
      defaultValue = null,
      value,
      openDelay = 50,
      closeDelay = 50,
      closeOnEscape = true,
      closeOnOutsideInteract = true,
      orientation = "horizontal",
      onValueChange,
      ...props
    },
    forwardedRef,
  ) {
    const rootRef = React.useRef<HTMLElement>(null);
    const instanceRef = React.useRef<ReturnType<typeof createNavigationMenu> | undefined>(
      undefined,
    );
    const valueRef = React.useRef(value);
    const onValueChangeRef = React.useRef(onValueChange);
    const pendingValueChangeDetailsRef = React.useRef<NavigationMenuValueChangeDetails | null>(
      null,
    );
    const defaultValueRef = React.useRef(defaultValue);
    const [uncontrolledValue, setUncontrolledValue] = React.useState<string | null>(
      defaultValueRef.current,
    );

    useIsomorphicLayoutEffect(() => {
      onValueChangeRef.current = onValueChange;
    }, [onValueChange]);

    useIsomorphicLayoutEffect(() => {
      valueRef.current = value;
      if (value !== undefined) {
        const pendingDetails = pendingValueChangeDetailsRef.current;
        pendingValueChangeDetailsRef.current = null;
        instanceRef.current?.setValue(
          value,
          pendingDetails?.value === value
            ? {
                emit: false,
                event: pendingDetails.event,
                reason: pendingDetails.reason,
                trigger: pendingDetails.trigger,
              }
            : { emit: false },
        );
      }
    }, [value]);

    const composedRef = React.useCallback(
      (node: HTMLElement | null) => {
        rootRef.current = node;
        return setRef(forwardedRef, node);
      },
      [forwardedRef],
    );

    useIsomorphicLayoutEffect(() => {
      const root = rootRef.current;
      if (!root) return;

      const instance = createNavigationMenu(root, {
        defaultValue: defaultValueRef.current,
        openDelay,
        closeDelay,
        closeOnEscape,
        closeOnOutsideInteract,
        ...(value !== undefined ? { value } : {}),
        onValueChange: (nextValue, details) => {
          pendingValueChangeDetailsRef.current = details;
          window.setTimeout(() => {
            if (pendingValueChangeDetailsRef.current === details) {
              pendingValueChangeDetailsRef.current = null;
            }
          }, 0);
          onValueChangeRef.current?.(nextValue, details);
        },
      });
      instanceRef.current = instance;
      const unsubscribe = instance.subscribe("valueChange", (details) => {
        queueMicrotask(() => {
          if (details.isCanceled) return;
          if (valueRef.current === undefined) {
            setUncontrolledValue(instance.getValue());
          }
        });
      });

      return () => {
        unsubscribe();
        instance.destroy();
        if (instanceRef.current === instance) {
          instanceRef.current = undefined;
        }
      };
    }, [openDelay, closeDelay, closeOnEscape, closeOnOutsideInteract]);

    const initialValue = value !== undefined ? value : uncontrolledValue;

    return (
      <nav
        data-sw-nav-menu=""
        data-default-value={
          value === undefined ? (defaultValueRef.current ?? undefined) : undefined
        }
        data-open-delay={String(openDelay)}
        data-close-delay={String(closeDelay)}
        data-close-on-escape={closeOnEscape ? "true" : "false"}
        data-close-on-outside-interact={closeOnOutsideInteract ? "true" : "false"}
        data-orientation={orientation}
        data-state={initialValue !== null ? "open" : "closed"}
        ref={composedRef}
        {...props}
      />
    );
  },
);

NavigationMenuRoot.displayName = "NavigationMenu.Root";

export default NavigationMenuRoot;
