/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import {
  reportPortalPlacement,
  resolvePortalPlacement,
} from "@starwind-ui/runtime/navigation-menu";
import * as React from "react";
import { ReactPortal, type ReactPortalProps } from "../internal/portal";

export type NavigationMenuPortalProps = ReactPortalProps;

const NavigationMenuPortal = React.forwardRef<HTMLDivElement, NavigationMenuPortalProps>(
  function NavigationMenuPortal(props, forwardedRef) {
    return (
      <ReactPortal
        discoveryAttribute="data-sw-nav-menu-portal"
        reportPlacement={reportPortalPlacement}
        resolvePlacement={resolvePortalPlacement}
        ref={forwardedRef}
        {...props}
      />
    );
  },
);

NavigationMenuPortal.displayName = "NavigationMenu.Portal";

export default NavigationMenuPortal;
