/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type NavigationMenuContentProps = React.HTMLAttributes<HTMLDivElement>;

const NavigationMenuContent = React.forwardRef<HTMLDivElement, NavigationMenuContentProps>(
  function NavigationMenuContent(props, forwardedRef) {
    return (
      <div data-sw-nav-menu-content="" data-state="closed" hidden ref={forwardedRef} {...props} />
    );
  },
);

NavigationMenuContent.displayName = "NavigationMenu.Content";

export default NavigationMenuContent;
