/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import { createInputOtp, type InputOtpValueChangeDetails } from "@starwind-ui/runtime/input-otp";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";
export type InputOtpRootProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  "defaultValue" | "id" | "onChange" | "pattern" | "value"
> & {
  defaultValue?: string;
  value?: string;
  disabled?: boolean;
  form?: string;
  id?: string;
  maxLength?: number;
  name?: string;
  pattern?: RegExp | string;
  readOnly?: boolean;
  required?: boolean;
  onValueChange?: (value: string, details: InputOtpValueChangeDetails) => void;
};
const InputOtpRoot = React.forwardRef<HTMLDivElement, InputOtpRootProps>(function InputOtpRoot(
  {
    children,
    defaultValue,
    value,
    disabled = false,
    form,
    id,
    maxLength = 6,
    name,
    pattern,
    readOnly = false,
    required = false,
    onValueChange,
    ...props
  },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const seed = React.useRef(defaultValue ?? "");
  const [current, setCurrent] = React.useState(seed.current);
  const currentRef = React.useRef(current);
  const patternText = (pattern instanceof RegExp ? pattern.source : (pattern ?? "\\d")).replace(
    /^\^|\$$/g,
    "",
  );
  const inputs = React.useRef({
    value,
    disabled,
    form,
    id,
    maxLength,
    name,
    pattern: patternText,
    readOnly,
    required,
    onValueChange,
  });
  useIsomorphicLayoutEffect(() => {
    inputs.current = {
      value,
      disabled,
      form,
      id,
      maxLength,
      name,
      pattern: patternText,
      readOnly,
      required,
      onValueChange,
    };
  });
  function connectOtp(root: HTMLElement) {
    let previous = inputs.current;
    const controlled = previous.value !== undefined;
    let instance: ReturnType<typeof createInputOtp>;
    let unsubscribe = () => {};
    let disposed = false;
    let associated: HTMLFormElement | null = null;
    let resetTimer: number | undefined;
    function publishCurrent(): void {
      const accepted = instance.getValue();
      if (!controlled) {
        currentRef.current = accepted;
        setCurrent(accepted);
      }
    }
    function synchronize(value: string | undefined): void {
      if (value === undefined) return;
      if (instance.getValue() !== value) instance.setValue(value, { emit: false });
      publishCurrent();
    }
    function clearReset(): void {
      if (resetTimer !== undefined) window.clearTimeout(resetTimer);
      resetTimer = undefined;
    }
    function reset(event: Event): void {
      clearReset();
      resetTimer = window.setTimeout(() => {
        resetTimer = undefined;
        if (disposed || event.defaultPrevented) return;
        if (controlled) synchronize(inputs.current.value);
        else publishCurrent();
      }, 0);
    }
    function bindReset(): void {
      const form = root.querySelector<HTMLInputElement>("[data-sw-input-otp-input]")?.form ?? null;
      if (associated === form) return;
      clearReset();
      associated?.removeEventListener("reset", reset);
      associated = form;
      associated?.addEventListener("reset", reset);
    }
    function stop(): void {
      clearReset();
      associated?.removeEventListener("reset", reset);
      associated = null;
      unsubscribe();
      instance.destroy();
    }
    function start(value: string): void {
      const options = inputs.current;
      instance = createInputOtp(root, {
        disabled: options.disabled,
        form: options.form,
        id: options.id,
        maxLength: options.maxLength,
        name: options.name,
        pattern: options.pattern,
        readOnly: options.readOnly,
        required: options.required,
        defaultValue: seed.current,
        onValueChange(next, detail) {
          inputs.current.onValueChange?.(next, detail);
        },
        ...(controlled && options.value !== undefined ? { value: options.value } : {}),
      });
      instance.setValue(controlled ? (options.value ?? value) : value, { emit: false });
      publishCurrent();
      const owner = instance;
      unsubscribe = instance.subscribe("valueChange", () => {
        if (disposed || owner !== instance) return;
        publishCurrent();
      });
      bindReset();
    }
    start(previous.value ?? currentRef.current);
    return {
      update(): void {
        const next = inputs.current;
        if (
          next.pattern !== previous.pattern ||
          next.readOnly !== previous.readOnly ||
          next.maxLength !== previous.maxLength
        ) {
          const accepted = instance.getValue();
          stop();
          start(accepted);
        } else {
          instance.refresh();
        }
        if (next.disabled !== previous.disabled) instance.setDisabled(next.disabled);
        if (
          next.form !== previous.form ||
          next.id !== previous.id ||
          next.name !== previous.name ||
          next.required !== previous.required
        ) {
          instance.setFormOptions({
            ...(next.form !== previous.form ? { form: next.form } : {}),
            ...(next.id !== previous.id ? { id: next.id } : {}),
            ...(next.name !== previous.name ? { name: next.name } : {}),
            ...(next.required !== previous.required ? { required: next.required } : {}),
          });
        }
        if (controlled) synchronize(next.value);
        publishCurrent();
        bindReset();
        previous = next;
      },
      destroy(): void {
        disposed = true;
        stop();
      },
    };
  }
  const connectionRef = React.useRef<ReturnType<typeof connectOtp> | undefined>(undefined);
  const composedRef = React.useCallback(
    (node: HTMLDivElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );
  useIsomorphicLayoutEffect(() => {
    const element = rootRef.current;
    if (!element) return;
    const owned = connectOtp(element);
    connectionRef.current = owned;
    return () => {
      if (connectionRef.current === owned) connectionRef.current = undefined;
      owned.destroy();
    };
  }, []);
  useIsomorphicLayoutEffect(() => {
    connectionRef.current?.update();
  });
  const renderedValue = value ?? current;
  return (
    <div
      ref={composedRef}
      data-sw-input-otp
      data-default-value={seed.current}
      data-disabled={disabled ? "" : undefined}
      data-form={form}
      data-id={id}
      data-max-length={maxLength}
      data-name={name}
      data-pattern={patternText}
      data-readonly={readOnly ? "" : undefined}
      data-required={required ? "" : undefined}
      data-value={renderedValue}
      aria-disabled={disabled}
      tabIndex={disabled ? -1 : 0}
      {...props}
    >
      <input
        data-sw-input-otp-input
        autoComplete="one-time-code"
        className="sr-only"
        defaultValue={renderedValue}
        disabled={disabled}
        form={form}
        id={id}
        inputMode={["\\d", "[0-9]", "\\d+", "[0-9]+"].includes(patternText) ? "numeric" : "text"}
        maxLength={maxLength}
        name={name}
        readOnly={readOnly}
        required={required}
        tabIndex={-1}
      />
      {children}
    </div>
  );
});
InputOtpRoot.displayName = "InputOtp.Root";
export default InputOtpRoot;
