/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import { createInputOtp, type InputOtpValueChangeDetails } from "@starwind-ui/runtime/input-otp";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export type InputOtpRootProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  "defaultValue" | "id" | "onChange" | "pattern" | "value"
> & {
  defaultValue?: string;
  disabled?: boolean;
  form?: string;
  id?: string;
  maxLength?: number;
  name?: string;
  onValueChange?: (value: string, details: InputOtpValueChangeDetails) => void;
  pattern?: RegExp | string;
  readOnly?: boolean;
  required?: boolean;
  value?: string;
};

const InputOtpRoot = React.forwardRef<HTMLDivElement, InputOtpRootProps>(function InputOtpRoot(
  {
    children,
    defaultValue,
    disabled = false,
    form,
    id,
    maxLength = 6,
    name,
    onValueChange,
    pattern,
    readOnly = false,
    required = false,
    value,
    ...props
  },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const instanceRef = React.useRef<ReturnType<typeof createInputOtp> | undefined>(undefined);
  const onValueChangeRef = React.useRef(onValueChange);
  const valueRef = React.useRef(value);
  const defaultValueRef = React.useRef(defaultValue);
  const [uncontrolledValue, setUncontrolledValueState] = React.useState(
    defaultValueRef.current ?? "",
  );
  const uncontrolledValueRef = React.useRef(uncontrolledValue);
  const patternText = normalizePattern(pattern);
  const renderedValue = value ?? uncontrolledValue;

  const setUncontrolledValue = React.useCallback((nextValue: string) => {
    uncontrolledValueRef.current = nextValue;
    setUncontrolledValueState(nextValue);
  }, []);

  useIsomorphicLayoutEffect(() => {
    onValueChangeRef.current = onValueChange;
  }, [onValueChange]);

  useIsomorphicLayoutEffect(() => {
    valueRef.current = value;
  }, [value]);

  const composedRef = React.useCallback(
    (node: HTMLDivElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  useIsomorphicLayoutEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const instance = createInputOtp(root, {
      defaultValue: uncontrolledValueRef.current,
      disabled,
      maxLength,
      onValueChange: (nextValue, details) => {
        onValueChangeRef.current?.(nextValue, details);
        if (details.isCanceled) return;

        if (valueRef.current === undefined) {
          setUncontrolledValue(nextValue);
        }
      },
      pattern: patternText,
      readOnly,
      ...(valueRef.current !== undefined ? { value: valueRef.current } : {}),
    });
    instanceRef.current = instance;

    return () => {
      instance.destroy();
      if (instanceRef.current === instance) {
        instanceRef.current = undefined;
      }
    };
  }, [maxLength, patternText, readOnly]);

  useIsomorphicLayoutEffect(() => {
    if (value === undefined) return;
    const instance = instanceRef.current;
    if (!instance) return;
    if (instance.getValue() === value) return;

    instance.setValue(value, { emit: false });
  }, [value]);

  useIsomorphicLayoutEffect(() => {
    const instance = instanceRef.current;
    if (!instance) return;

    instance.setDisabled(disabled);
  }, [disabled]);

  useIsomorphicLayoutEffect(() => {
    const instance = instanceRef.current;
    if (!instance) return;

    instance.setFormOptions({ form, id, name, required });
  }, [form, id, name, required]);

  return (
    <div
      data-sw-input-otp
      data-default-value={defaultValueRef.current}
      data-disabled={disabled ? "" : undefined}
      data-form={form}
      data-id={id}
      data-max-length={maxLength}
      data-name={name}
      data-pattern={patternText}
      data-readonly={readOnly ? "" : undefined}
      data-required={required ? "" : undefined}
      data-value={renderedValue}
      aria-disabled={disabled}
      ref={composedRef}
      tabIndex={disabled ? -1 : 0}
      {...props}
    >
      <input
        data-sw-input-otp-input
        autoComplete="one-time-code"
        className="sr-only"
        defaultValue={renderedValue}
        disabled={disabled}
        form={form}
        id={id}
        inputMode={isNumericPattern(patternText) ? "numeric" : "text"}
        maxLength={maxLength}
        name={name}
        readOnly={readOnly}
        required={required}
        tabIndex={-1}
      />
      {children}
    </div>
  );
});

InputOtpRoot.displayName = "InputOtp.Root";

export default InputOtpRoot;

function normalizePattern(pattern: RegExp | string | undefined): string {
  const source = pattern instanceof RegExp ? pattern.source : pattern;
  return (source ?? "\\d").replace(/^\^|\$$/g, "");
}

function isNumericPattern(pattern: string): boolean {
  return ["\\d", "[0-9]", "\\d+", "[0-9]+"].includes(pattern);
}
