<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { defineComponent, ref, useAttrs, type VNode } from "vue";
import { createVueAsChild } from "../_internal/as-child";

defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{
    asChild?: boolean;
    disabled?: boolean;
    closeDelay?: number;
    openDelay?: number;
  }>(),
  {
    asChild: false,
    disabled: false,
  },
);
const slots = defineSlots<{ default?: () => VNode[] }>();
const attrs = useAttrs();
const element = ref<HTMLElement | null>(null);
const asChild = createVueAsChild("PreviewCardTrigger", element);
const { setElement } = asChild;
defineExpose({ element });
function handleClick(event: MouseEvent): void {
  if (!props.disabled) return;
  event.preventDefault();
  event.stopPropagation();
}
function protectedProps() {
  return {
    "data-sw-preview-card-trigger": "",
    "data-disabled": props.disabled ? "" : undefined,
    "aria-disabled": props.disabled ? "true" : undefined,
    "data-state": "closed",
    "data-close-delay": props.closeDelay,
    "data-open-delay": props.openDelay,
    href: props.disabled ? undefined : attrs.href,
    tabindex: props.disabled ? -1 : attrs.tabindex,
    onClick: handleClick,
    "data-sw-part": "trigger",
  };
}
const AsChildTrigger = defineComponent({
  inheritAttrs: false,
  setup() {
    return () => {
      const children = slots.default?.() ?? [];
      return asChild.render({
        children,
        consumerProps: attrs,
        protectedProps: protectedProps(),
      });
    };
  },
});
</script>

<template>
  <AsChildTrigger v-if="props.asChild" />
  <a
    v-else
    :ref="setElement"
    v-bind="attrs"
    data-sw-preview-card-trigger
    data-sw-part="trigger"
    :data-disabled="props.disabled ? '' : undefined"
    :aria-disabled="props.disabled ? 'true' : undefined"
    data-state="closed"
    :data-close-delay="props.closeDelay"
    :data-open-delay="props.openDelay"
    :href="props.disabled ? undefined : (attrs.href as string | undefined)"
    :tabindex="props.disabled ? -1 : (attrs.tabindex as number | undefined)"
    @click="handleClick"
  >
    <slot />
  </a>
</template>
