<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { inject, ref, watchEffect } from "vue";
import { PreviewCardContext } from "./PreviewCardRoot.vue";

defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{
    side?: "top" | "right" | "bottom" | "left";
    align?: "start" | "center" | "end";
    sideOffset?: number;
    avoidCollisions?: boolean;
  }>(),
  { side: "bottom", align: "center", sideOffset: 0, avoidCollisions: true },
);
defineSlots<{ default?: () => unknown }>();
const element = ref<HTMLDivElement | null>(null),
  owner = inject(PreviewCardContext, undefined);
watchEffect(
  (onCleanup) => {
    const node = element.value;
    if (!node) return;
    owner?.registerPlacement(node, {
      "data-side": String(props.side),
      "data-align": String(props.align),
      "data-side-offset": String(props.sideOffset),
      "data-avoid-collisions": String(props.avoidCollisions),
    });
    onCleanup(() => owner?.registerPlacement(node, null));
  },
  { flush: "post" },
);
defineExpose({ element });
</script>
<template>
  <div
    ref="element"
    v-bind="$attrs"
    data-sw-preview-card-popup=""
    data-sw-part="popup"
    data-state="closed"
    :data-side="props.side"
    :data-align="props.align"
    :data-side-offset="props.sideOffset"
    :data-avoid-collisions="String(props.avoidCollisions)"
    role="tooltip"
    hidden
  >
    <slot />
  </div>
</template>
