<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { type HTMLAttributes, ref } from "vue";

defineOptions({ inheritAttrs: false });
type NativeElementProps = /* @vue-ignore */ HTMLAttributes;
defineProps<NativeElementProps>();
defineSlots<{ default?: () => unknown }>();
const element = ref<HTMLElement | null>(null);
defineExpose({ element });
</script>
<template>
  <div
    ref="element"
    v-bind="$attrs"
    data-sw-preview-card-backdrop
    data-sw-part="backdrop"
    data-state="closed"
    hidden
  >
    <slot />
  </div>
</template>
