<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script lang="ts">
  import { createForm, type FormValidationTiming, type FormOptions, type FormExternalErrors, type FormExternalErrorOptions } from "@starwind-ui/runtime/form";
  import { untrack, type Snippet } from "svelte";
  import { provideFormOwner } from "./FormFieldContext.js";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLFormAttributes } from "svelte/elements";
  type Props = Omit<HTMLFormAttributes, "children"> & {
    options?: FormOptions;
errors?: FormExternalErrors;
errorOptions?: FormExternalErrorOptions;
    children?: Snippet;
    ref?: (element: HTMLFormElement | null) => void;
    "data-slot"?: string;
    "data-error-visibility"?: FormValidationTiming;
    "data-revalidation-timing"?: FormValidationTiming;
    "data-validation-timing"?: FormValidationTiming;
    errorVisibility?: FormValidationTiming;
    revalidationTiming?: FormValidationTiming;
    validationTiming?: FormValidationTiming;
  };
  let { children, ref, options, errors, errorOptions, "data-slot": dataSlot = "form",
    "data-error-visibility": dataErrorVisibility,
    "data-revalidation-timing": dataRevalidationTiming,
    "data-validation-timing": dataValidationTiming,
    errorVisibility = "submit",
    revalidationTiming = "change",
    validationTiming = "submit",
    ...rest }: Props = $props();
  const configured = { options: false, errors: false };
  const owner = provideFormOwner();
  let ready = $state.raw<ReturnType<typeof createForm> | null>(null);
  const attachForm: Attachment<HTMLFormElement> = (element) => {
    let active = true;
    let instance: ReturnType<typeof createForm> | undefined;
    queueMicrotask(() => {
      if (!active) return;
      instance = owner.connect(element);
      ready = instance;
    });
    return () => { active = false; ready = null; if (instance) owner.disconnect(instance); };
  };
  $effect(() => {
    const instance = ready, value = options;
    if (instance) untrack(() => { if (value !== undefined || configured.options) { configured.options = value !== undefined; instance.setOptions({ fieldValidators: undefined, formValidators: undefined, asyncFieldValidators: undefined, asyncFormValidators: undefined, asyncValidationDebounceMs: undefined, externalErrorsOnReset: undefined, onSubmit: undefined, ...value } satisfies Record<keyof FormOptions, unknown>); } });
  });
  $effect(() => {
    const instance = ready, value = errors, settings = errorOptions;
    if (instance) untrack(() => { if (value !== undefined || configured.errors) { configured.errors = value !== undefined; instance.setExternalErrors(value ?? {}, settings); } });
  });
  $effect(() => {
    const element = ready?.root, callback = ref;
    if (!element) return;
    untrack(() => callback?.(element));
    return () => untrack(() => callback?.(null));
  });
</script>
<form {...rest} data-sw-form="" data-slot={dataSlot}
  data-error-visibility={dataErrorVisibility ?? errorVisibility}
  data-revalidation-timing={dataRevalidationTiming ?? revalidationTiming}
  data-validation-timing={dataValidationTiming ?? validationTiming}
  {@attach attachForm}>
  {@render children?.()}
</form>
