/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import SwitchRoot from "./SwitchRoot";
import SwitchThumb from "./SwitchThumb";

const Switch = {
  Root: SwitchRoot,
  Thumb: SwitchThumb,
};

export { Switch, SwitchRoot, SwitchThumb };

export default Switch;

export type { SwitchCheckedChangeDetails } from "@starwind-ui/runtime";
