/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import { createSwitch, type SwitchCheckedChangeDetails } from "@starwind-ui/runtime/switch";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export type SwitchRootProps = Omit<
  React.HTMLAttributes<HTMLSpanElement>,
  "defaultChecked" | "onChange"
> &
  Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "defaultChecked" | "onChange" | "type"> & {
    checked?: boolean;
    defaultChecked?: boolean;
    disabled?: boolean;
    form?: string;
    id?: string;
    name?: string;
    nativeButton?: boolean;
    readOnly?: boolean;
    required?: boolean;
    uncheckedValue?: string;
    value?: string;
    onCheckedChange?: (checked: boolean, details: SwitchCheckedChangeDetails) => void;
    inputRef?: React.Ref<HTMLInputElement>;
  };
const visuallyHiddenStyle = {
  position: "absolute",
  width: "1px",
  height: "1px",
  margin: "-1px",
  overflow: "hidden",
  clip: "rect(0 0 0 0)",
  whiteSpace: "nowrap",
  border: 0,
} satisfies React.CSSProperties;

const SwitchRoot = React.forwardRef<HTMLSpanElement | HTMLButtonElement, SwitchRootProps>(
  function SwitchRoot(
    {
      children,
      checked,
      defaultChecked,
      disabled = false,
      form,
      id,
      name,
      nativeButton = false,
      readOnly = false,
      required = false,
      uncheckedValue,
      value,
      onCheckedChange,
      inputRef,
      ...props
    },
    forwardedRef,
  ) {
    const rootRef = React.useRef<HTMLSpanElement | HTMLButtonElement>(null);
    const inputElement = React.useRef<HTMLInputElement>(null);

    const effectiveDisabledValue = disabled;
    const inputs = React.useRef({ checked, onCheckedChange });
    useIsomorphicLayoutEffect(() => {
      inputs.current = { checked, onCheckedChange };
    });

    function effectiveChecked(): boolean | undefined {
      return inputs.current.checked;
    }
    function effectiveDisabled(): boolean {
      return effectiveDisabledValue;
    }
    const initial = React.useRef<{ checked: boolean; reset: boolean } | undefined>(undefined);
    if (!initial.current) {
      const initialChecked = checked ?? defaultChecked ?? false;
      const resetSeed = defaultChecked ?? initialChecked;
      initial.current = { checked: initialChecked, reset: resetSeed };
    }
    const initialChecked = initial.current.checked;
    const resetSeed = initial.current.reset;
    const [renderedState, setRenderedChecked] = React.useState<boolean>(initialChecked);

    const connection = React.useRef<{
      instance?: ReturnType<typeof createSwitch>;
      input?: HTMLInputElement;
      accepted: boolean;
      unsubscribe?: () => void;
      form?: HTMLFormElement;
      resetTimer?: number;
      runtimeInputName?: string;
      nameObserver?: MutationObserver;
    }>({ accepted: initialChecked }).current;
    const composedRef = React.useCallback(
      (node: HTMLSpanElement | HTMLButtonElement | null) => {
        rootRef.current = node;
        return setRef(forwardedRef, node);
      },
      [forwardedRef],
    );
    const composedInputRef = React.useCallback(
      (node: HTMLInputElement | null) => {
        inputElement.current = node;
        return setRef(inputRef, node);
      },
      [inputRef],
    );

    function disconnectRuntime(): void {
      const owned = connection.instance;
      if (!owned) return;
      connection.accepted = owned.getChecked();
      connection.unsubscribe?.();
      connection.unsubscribe = undefined;
      connection.nameObserver?.disconnect();
      connection.nameObserver = undefined;
      unbindFormReset();
      connection.instance = undefined;
      owned.destroy();
      const unchecked = connection.input?.nextElementSibling;
      if (
        unchecked instanceof HTMLInputElement &&
        unchecked.hasAttribute("data-sw-switch-unchecked-input")
      )
        unchecked.remove();
      connection.input = undefined;
    }
    function connectRuntime(root: HTMLElement, input: HTMLInputElement): void {
      disconnectRuntime();
      const desired = effectiveChecked() ?? connection.accepted;
      const owned = createSwitch(root, {
        defaultChecked: resetSeed,
        ...(inputs.current.checked !== undefined ? { checked: desired } : {}),
        disabled: effectiveDisabled(),
        form: form,
        id: id,
        name: name,
        readOnly: readOnly,
        required: required,
        uncheckedValue: uncheckedValue,
        value: value,
        onCheckedChange: (next, detail) => {
          inputs.current.onCheckedChange?.(next, detail);
        },
      });
      connection.instance = owned;
      connection.input = input;
      connection.nameObserver = new MutationObserver(captureNativeInputAttributes);
      connection.nameObserver.observe(input, { attributes: true, attributeFilter: ["name"] });
      if (owned.getChecked() !== desired) owned.setChecked(desired, { emit: false });
      connection.unsubscribe = owned.subscribe("checkedChange", (detail) => {
        if (connection.instance !== owned || detail.isCanceled) return;

        renderRuntimeState(detail.checked);
      });
      bindFormReset();
      renderRuntimeState();
    }
    function captureNativeInputAttributes(): void {
      connection.runtimeInputName = connection.input?.name;
    }
    function restoreNativeInputAttributes(): void {
      const input = connection.input;
      if (
        name === undefined &&
        input &&
        connection.runtimeInputName !== undefined &&
        input.name !== connection.runtimeInputName
      )
        input.name = connection.runtimeInputName;
    }
    function renderRuntimeState(next = connection.instance?.getChecked()): void {
      if (next === undefined) return;
      connection.accepted = next;
      captureNativeInputAttributes();
      if (inputs.current.checked === undefined) setRenderedChecked(connection.accepted);
    }
    function applyParentCommand(): void {
      const owned = connection.instance;
      const next = effectiveChecked();
      if (!owned || next === undefined) return;
      if (owned.getChecked() !== next || connection.input?.checked !== next)
        owned.setChecked(next, { emit: false });

      renderRuntimeState();
    }
    function clearResetTask(): void {
      if (connection.resetTimer !== undefined) window.clearTimeout(connection.resetTimer);
      connection.resetTimer = undefined;
    }
    function unbindFormReset(): void {
      clearResetTask();
      connection.form?.removeEventListener("reset", handleFormReset);
      connection.form = undefined;
    }
    function handleFormReset(event: Event): void {
      clearResetTask();
      const owned = connection.instance;
      // Runtime registers its reset task first. Read public state after it settles.
      connection.resetTimer = window.setTimeout(() => {
        connection.resetTimer = undefined;
        if (
          event.defaultPrevented ||
          !owned ||
          connection.instance !== owned ||
          inputs.current.checked !== undefined
        )
          return;

        renderRuntimeState(owned.getChecked());
      }, 0);
    }
    function bindFormReset(): void {
      const next = connection.input?.form ?? undefined;
      if (next === connection.form) return;
      unbindFormReset();
      connection.form = next;
      next?.addEventListener("reset", handleFormReset);
    }
    function applyLive0(): void {
      const owned = connection.instance;
      if (!owned) return;
      owned.setDisabled(effectiveDisabled());
    }
    function applyLive1(): void {
      const owned = connection.instance;
      if (!owned) return;
      owned.setFormOptions({
        form: form,
        name: name,
        required: required,
        uncheckedValue: uncheckedValue,
        value: value,
      });
      bindFormReset();
      captureNativeInputAttributes();
    }

    useIsomorphicLayoutEffect(() => {
      if (rootRef.current && inputElement.current)
        connectRuntime(rootRef.current, inputElement.current);
      return disconnectRuntime;
    }, [id, readOnly, nativeButton]);
    useIsomorphicLayoutEffect(restoreNativeInputAttributes);
    useIsomorphicLayoutEffect(applyParentCommand, [checked]);
    useIsomorphicLayoutEffect(applyLive0, [effectiveDisabledValue]);
    useIsomorphicLayoutEffect(applyLive1, [form, name, required, uncheckedValue, value]);
    const renderedChecked = checked ?? renderedState;

    const input = (
      <input
        data-sw-switch-input
        aria-hidden="true"
        type="checkbox"
        tabIndex={-1}
        defaultChecked={initialChecked}
        disabled={effectiveDisabledValue}
        form={form}
        id={id ? (nativeButton ? `${id}-input` : id) : undefined}
        name={name}
        required={required}
        defaultValue={value}
        style={visuallyHiddenStyle}
        ref={composedInputRef}
      />
    );
    const Root = nativeButton ? "button" : "span";
    return (
      <>
        <Root
          {...props}
          data-sw-switch={""}
          data-sw-part={"root"}
          role={"switch"}
          aria-checked={renderedChecked}
          aria-disabled={effectiveDisabledValue ? "true" : undefined}
          aria-readonly={readOnly}
          aria-required={required}
          data-default-checked={resetSeed ? "true" : undefined}
          data-checked={renderedChecked ? "" : undefined}
          data-unchecked={renderedChecked ? undefined : ""}
          data-disabled={effectiveDisabledValue ? "" : undefined}
          data-readonly={readOnly ? "" : undefined}
          data-required={required ? "" : undefined}
          data-filled={renderedChecked ? "" : undefined}
          data-form={form}
          data-id={id}
          data-name={name}
          data-unchecked-value={uncheckedValue}
          data-value={value}
          id={nativeButton ? id : undefined}
          tabIndex={effectiveDisabledValue ? -1 : 0}
          disabled={nativeButton ? effectiveDisabledValue : undefined}
          type={nativeButton ? "button" : undefined}
          ref={composedRef}
        >
          {children}
        </Root>
        {input}
      </>
    );
  },
);
SwitchRoot.displayName = "Switch.Root";
export default SwitchRoot;
