/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

// Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies.

import ProgressIndicator from "./ProgressIndicator.vue";
import ProgressLabel from "./ProgressLabel.vue";
import ProgressRoot from "./ProgressRoot.vue";
import ProgressTrack from "./ProgressTrack.vue";
import ProgressValue from "./ProgressValue.vue";

const Progress = {
  Root: ProgressRoot,
  Track: ProgressTrack,
  Indicator: ProgressIndicator,
  Value: ProgressValue,
  Label: ProgressLabel,
};

export { default as ProgressIndicator } from "./ProgressIndicator.vue";
export { default as ProgressLabel } from "./ProgressLabel.vue";
export { default as ProgressRoot } from "./ProgressRoot.vue";
export { default as ProgressTrack } from "./ProgressTrack.vue";
export { default as ProgressValue } from "./ProgressValue.vue";
export { Progress };

export default Progress;
