<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";

defineOptions({ inheritAttrs: false });
const slots = defineSlots<{ default?: () => unknown }>();
const indicatorRef = ref<HTMLDivElement | null>(null);

defineExpose({ element: indicatorRef });
</script>

<template>
  <div ref="indicatorRef" v-bind="$attrs" data-sw-progress-indicator>
    <slot />
  </div>
</template>
