<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { ref, useAttrs } from "vue";

defineOptions({ inheritAttrs: false });
const slots = defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const valueRef = ref<HTMLSpanElement | null>(null);

defineExpose({ element: valueRef });
</script>

<template>
  <span
    ref="valueRef"
    v-bind="attrs"
    data-sw-progress-value
    :data-preserve-text="slots.default ? '' : undefined"
    aria-hidden="true"
  >
    <slot />
  </span>
</template>
