<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { getNavigationMenuContext, getNavigationMenuItemContext } from "./NavigationMenuRoot.svelte";
  type Props = Omit<HTMLAttributes<HTMLUListElement>, "children"> & { children?: Snippet;  ref?: (element: HTMLUListElement | null) => void };
  let { children,  ref, ...rest }: Props = $props();
  const menu = getNavigationMenuContext(); const item = getNavigationMenuItemContext();
  const owner = Symbol("NavigationMenuList owner");
  const attachPart: Attachment<HTMLUListElement> = (element) => {
    $effect(() => {
      const attributes = {};
      untrack(() => menu?.registerPart(owner, { element, part: "list", attributes }));
      return () => menu?.registerPart(owner, null);
    });
    return () => {  };
  };
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLUListElement>(() => ref);
</script>
<ul {...rest} data-sw-nav-menu-list="" data-sw-part="list" data-orientation={menu?.orientation} {@attach attachPart} {@attach attachRef}>{@render children?.()}</ul>
