<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { getNavigationMenuContext, getNavigationMenuItemContext } from "./NavigationMenuRoot.svelte";
  type Props = Omit<HTMLAttributes<HTMLSpanElement>, "children"> & { children?: Snippet;  ref?: (element: HTMLSpanElement | null) => void };
  let { children,  ref, ...rest }: Props = $props();
  const menu = getNavigationMenuContext(); const item = getNavigationMenuItemContext();
  const owner = Symbol("NavigationMenuIcon owner");
  const attachPart: Attachment<HTMLSpanElement> = (element) => {
    $effect(() => {
      const attributes = {};
      untrack(() => menu?.registerPart(owner, { element, part: "icon", attributes }));
      return () => menu?.registerPart(owner, null);
    });
    return () => {  };
  };
  let elementProps = $derived({ ...rest });
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLSpanElement>(() => ref);
</script>
<span {...elementProps} data-sw-nav-menu-icon="" data-sw-part="icon" aria-hidden="true" data-state={item?.open ? "open" : "closed"} {@attach attachPart} {@attach attachRef}>{@render children?.()}</span>
