<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { getNavigationMenuContext, getNavigationMenuItemContext } from "./NavigationMenuRoot.svelte";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & { children?: Snippet;  ref?: (element: HTMLDivElement | null) => void };
  let { children,  ref, ...rest }: Props = $props();
  const menu = getNavigationMenuContext(); const item = getNavigationMenuItemContext();
  const owner = Symbol("NavigationMenuViewport owner");
  const attachPart: Attachment<HTMLDivElement> = (element) => {
    $effect(() => {
      const attributes = {};
      untrack(() => menu?.registerPart(owner, { element, part: "viewport", attributes }));
      return () => menu?.registerPart(owner, null);
    });
    return () => {  };
  };
  let elementProps = $derived({ ...rest });
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>
<div {...elementProps} data-sw-nav-menu-viewport="" data-sw-part="viewport" data-state="closed" hidden {@attach attachPart} {@attach attachRef}>{@render children?.()}</div>
