/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import InputRoot from "./InputRoot.svelte";
const Input = { Root: InputRoot };
export { Input, InputRoot };
export default Input;

export type { InputValue, InputValueChangeDetails } from "@starwind-ui/runtime";
