<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script lang="ts">
  import { createInput, type InputValue, type InputValueChangeDetails } from "@starwind-ui/runtime/input";
  import { untrack } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import { observeFormDiscovery } from "../_internal/form-discovery.js";
  import type { HTMLInputAttributes } from "svelte/elements";
  type Props = Omit<HTMLInputAttributes, "children" | "value" | "defaultValue" | "disabled"> & {
    disabled?: boolean;
    value?: InputValue;
    defaultValue?: InputValue;
    onValueChange?: (value: string, detail: InputValueChangeDetails) => void;
    ref?: (element: HTMLInputElement | null) => void;
  };
  let { value = $bindable(), defaultValue, disabled = false, type, onValueChange, ref, ...rest }: Props = $props();
  const seed = untrack(() => defaultValue ?? value);
  const initialMarkup = untrack(() => type === "file" ? undefined : value ?? defaultValue);
  function connectInput(element: HTMLInputElement) {
    const initialModel = value;

    let disposed = false;
    let associated: HTMLFormElement | null = null;
    let resetTimer: number | undefined;

    function synchronize(next: InputValue | undefined): void {
      if (next === undefined || disposed) return;
      const normalized = String(next);
      if (instance.getValue() === normalized && element.value === normalized) return;
      instance.setValue(next, {"emit":false});
    }
    function clearReset(): void {
      if (resetTimer !== undefined) window.clearTimeout(resetTimer);
      resetTimer = undefined;
    }
    function reset(event: Event): void {
      clearReset();
      resetTimer = window.setTimeout(() => {
        resetTimer = undefined;
        if (disposed || event.defaultPrevented) return;
        untrack(() => { value = instance.getValue(); });
      }, 0);
    }
    function bindReset(): void {

      const form = element.form;
      if (associated === form) return;
      clearReset();
      associated?.removeEventListener('reset', reset);
      associated = form;
      associated?.addEventListener('reset', reset);
    }
    element.defaultValue = String(seed ?? initialModel ?? "");
    const instance = createInput(element, {
      defaultValue: seed,
      disabled: disabled,
      onValueChange(next, detail) { untrack(() => {
       onValueChange?.(next, detail);
       value = next;
       synchronize(value); }); },

    });
    synchronize(initialModel);
    if (value === undefined || String(value) !== instance.getValue()) { value = instance.getValue(); }
    bindReset();
    const stopDiscovery = observeFormDiscovery(element.ownerDocument, () => {
      instance.refresh();
      bindReset();
    });
    return {
      instance,
      synchronize,

      destroy(): void {
        disposed = true;
        stopDiscovery();
        clearReset();
        associated?.removeEventListener('reset', reset);

        instance.destroy();
      },
    };
  }
  const attachInput: Attachment<HTMLInputElement> = (element) => {
    const connection = untrack(() => connectInput(element));
    $effect(() => {
      const next = value;
      untrack(() => connection.synchronize(next));
    });
    $effect(() => {
      const next = disabled;
      untrack(() => connection.instance.setDisabled(next));
    });
    let appliedType = untrack(() => type);
    $effect(() => {
      const next = type;
      if (next === appliedType) return;
      appliedType = next;
      untrack(() => connection.synchronize(connection.instance.getValue()));
    });
    return () => connection.destroy();
  };
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLInputElement>(() => ref);
</script>
<input {...rest} {type} value={initialMarkup} {disabled} data-sw-input="" data-disabled={disabled ? "" : undefined} {@attach attachInput} {@attach attachRef} />
