<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { ref, useAttrs } from "vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<{ isUploading?: boolean }>(), { isUploading: false });
const attrs = useAttrs();
const element = ref<HTMLDivElement | null>(null);

defineExpose({ element });
</script>

<template>
  <div
    ref="element"
    data-sw-dropzone-loading-indicator
    :data-is-uploading="props.isUploading ? 'true' : 'false'"
    :hidden="!props.isUploading"
    v-bind="attrs"
  >
    <slot />
  </div>
</template>
