<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { computed, ref, useAttrs } from "vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    accept?: string;
    disabled?: boolean;
    multiple?: boolean;
    name?: string;
    required?: boolean;
  }>(),
  {
    disabled: false,
  },
);
const attrs = useAttrs();
const element = ref<HTMLInputElement | null>(null);
const classes = computed(() => ["sr-only", attrs.class].filter(Boolean).join(" "));

defineExpose({ element });
</script>

<template>
  <input
    ref="element"
    v-bind="{ ...attrs, class: undefined }"
    data-sw-dropzone-input
    :accept="props.accept"
    :class="classes"
    :data-disabled="props.disabled ? '' : undefined"
    :disabled="props.disabled"
    :multiple="props.multiple"
    :name="props.name"
    :required="props.required"
    tabindex="-1"
    type="file"
  />
</template>
