/**
 * Generated by scripts/portable-runtime/generate-astro-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import FormErrorSummary from "./FormErrorSummary.astro";
import FormRoot from "./FormRoot.astro";

const Form = {
  ErrorSummary: FormErrorSummary,
  Root: FormRoot,
};

export { Form, FormErrorSummary, FormRoot };

export default Form;

export type {
  FormExternalErrorOptions,
  FormExternalErrors,
  FormInstance,
  FormOptions,
  FormResetValidationOptions,
  FormSchemaResult,
  FormValidateOptions,
  FormValidationCause,
  FormValidationOutcome,
  FormValidationTiming,
  FormValues,
} from "@starwind-ui/runtime";
export {
  createForm,
  createFormSchemaValidator,
  validateFormSchema,
} from "@starwind-ui/runtime/form";
