/**
 * Generated by scripts/portable-runtime/generate-astro-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import CarouselContainer from "./CarouselContainer.astro";
import CarouselItem from "./CarouselItem.astro";
import CarouselNext from "./CarouselNext.astro";
import CarouselPrevious from "./CarouselPrevious.astro";
import CarouselRoot from "./CarouselRoot.astro";
import CarouselViewport from "./CarouselViewport.astro";

const Carousel = {
  Root: CarouselRoot,
  Viewport: CarouselViewport,
  Container: CarouselContainer,
  Item: CarouselItem,
  Previous: CarouselPrevious,
  Next: CarouselNext,
};

export {
  Carousel,
  CarouselContainer,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
  CarouselRoot,
  CarouselViewport,
};

export default Carousel;

export type { CarouselInstance, CarouselOptions } from "@starwind-ui/runtime";
export { createCarousel } from "@starwind-ui/runtime/carousel";
