/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */
export { default as CheckboxRoot, CheckboxGroupContext } from "./CheckboxRoot.svelte";
export { default as CheckboxIndicator } from "./CheckboxIndicator.svelte";
