<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { createPortalPlacement } from "../_internal/portal-placement.js";
  import { reportPortalPlacement, resolvePortalPlacement } from "@starwind-ui/runtime/menu";
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { getMenuOwnerContext } from "./MenuRoot.svelte";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & { children?: Snippet; container?: string | HTMLElement; disabled?: boolean; ref?: (element: HTMLDivElement | null) => void };
  let { children, container, disabled = false, ref, ...rest }: Props = $props();
  const select = getMenuOwnerContext()!;
  const owner = Symbol("MenuPortalOwner");
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
  const attachPortal: Attachment<HTMLDivElement> = (element) => {
    const placement = createPortalPlacement(element, element.parentElement?.closest<HTMLElement>("[data-sw-menu-submenu-root], [data-sw-menu]") ?? element.parentElement ?? element, {
      reportPortalPlacement, resolvePortalPlacement,
    }, true);
    select.registerPortal(owner, element, placement.authoredParent as HTMLElement, placement.prepare);
    $effect(() => placement.update(select.mounted && !disabled, container));
    $effect(() => attachRef(element));
    return () => {
      placement.disconnect();
      select.registerPortal(owner, null);
      placement.restore();
      // Svelte removes the authored range; a moved wrapper needs explicit release.
      element.remove();
    };
  };
</script>
<div {...rest} data-sw-menu-portal="" data-sw-part="portal" data-placement="pending" data-sw-portal-placement="framework" data-disabled={disabled ? "" : undefined} {@attach attachPortal}>{@render children?.()}</div>
