<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script module lang="ts">
  import { getContext } from "svelte";
  export type MenuPart = { element: HTMLElement; scope: symbol; part: string; attributes?: Record<string, string> };
  export type MenuItemModel = { prepare(): void; accept(): void };
  export type MenuTreeContext = {
    registerPart(owner: symbol, part: MenuPart | null): void;
    registerModel(owner: symbol, model: MenuItemModel | null): void;
    beginTransaction?(): () => void;
    readonly mounted: boolean;
  };
  export type MenuOwnerContext = {
    readonly scope: symbol;
    readonly open: boolean;
    readonly mounted: boolean;
    registerPortal(owner: symbol, element: HTMLElement | null, authoredParent?: HTMLElement, prepare?: () => () => void): void;
  };
  export const menuTreeKey = Symbol("Menu tree");
  export const menuOwnerKey = Symbol("Menu surface owner");
  export const menuRadioKey = Symbol("Menu radio group");
  export const menuCheckedKey = Symbol("Menu item checked");
  export function getMenuTreeContext(): MenuTreeContext | undefined { return getContext(menuTreeKey); }
  export function getMenuOwnerContext(): MenuOwnerContext | undefined { return getContext(menuOwnerKey); }
  export function getMenuRadioContext(): { readonly value: string | undefined } | undefined { return getContext(menuRadioKey); }
  export function getMenuCheckedContext(): { readonly checked: boolean } | undefined { return getContext(menuCheckedKey); }
</script>
<script lang="ts">
  import { createMenu, createPortalBinding, readyPortalBindingSnapshot, type MenuOpenChangeDetails, type MenuCloseCompleteDetails } from "@starwind-ui/runtime/menu";
  import { setContext, untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    children?: Snippet<[boolean]>; open?: boolean; defaultOpen?: boolean;
    disabled?: boolean; modal?: boolean; openOnHover?: boolean; closeDelay?: number;
    onOpenChange?: (open: boolean, detail: MenuOpenChangeDetails) => void;
    onCloseComplete?: (detail: MenuCloseCompleteDetails) => void;
    ref?: (element: HTMLDivElement | null) => void;
  };
  let { children, open = $bindable(), defaultOpen, disabled = false, modal = false, openOnHover = false, closeDelay = 200, onOpenChange, onCloseComplete, ref, ...rest }: Props = $props();
  const initialModel = untrack(() => open);
  const initialDefault = untrack(() => defaultOpen) ?? initialModel ?? false;
  let accepted = $state(initialModel ?? initialDefault);
  let mounted = $state(false);
  let revision = $state(0);
  const scope = Symbol("Menu root scope");
  const parts = new Map<symbol, MenuPart>();
  const models = new Map<symbol, MenuItemModel>();
  const portals = new Map<symbol, { wrapper: HTMLElement; authoredParent: HTMLElement; prepare?: () => () => void }>();
  let binding: ReturnType<typeof createPortalBinding> | undefined;
  let rootElement: HTMLDivElement | undefined;
  setContext<MenuTreeContext>(menuTreeKey, {
    get mounted() { return mounted; },
    registerPart(owner, part) { if (part) parts.set(owner, part); else parts.delete(owner); untrack(() => revision++); },
    registerModel(owner, model) { if (model) models.set(owner, model); else models.delete(owner); },
  });
  setContext<MenuOwnerContext>(menuOwnerKey, {
    scope, get open() { return accepted; }, get mounted() { return mounted; },
    registerPortal(owner, element, authoredParent, prepare) {
      if (element && authoredParent) portals.set(owner, { wrapper: element, authoredParent, prepare }); else portals.delete(owner);
      if (rootElement) binding?.publish(readyPortalBindingSnapshot(rootElement, [...portals.values()]));
      untrack(() => revision++);
    },
  });
  const attachRuntime: Attachment<HTMLDivElement> = (root) => {
    rootElement = root;
    binding = createPortalBinding(root);
    binding.publish(readyPortalBindingSnapshot(root, [...portals.values()]));
    mounted = true;
    let instance: ReturnType<typeof createMenu> | undefined;
    $effect(() => {
      revision;
      void disabled; void modal; void openOnHover; void closeDelay;
      return untrack(() => {
        const captures = [...parts.values()];
      const own = captures.filter(part => part.scope === scope);
      if (!["trigger","popup"].every(name => own.some(part => part.part === name && part.element.isConnected))) return;
      for (const sub of captures.filter(part => part.part === "submenuRoot")) {
        if (!["submenuTrigger","popup"].every(name => captures.some(part => part.scope === sub.scope && part.part === name && part.element.isConnected))) return;
      }
for (const {element,attributes} of captures) for (const [name,value] of Object.entries(attributes ?? {})) element.setAttribute(name,value);
for (const model of models.values()) model.prepare();
const owned = createMenu(root, {
    defaultOpen:false,
    disabled:disabled,
modal:modal,
openOnHover:openOnHover,
closeDelay:closeDelay,
    onOpenChange:(next,details)=>{ untrack(() => { onOpenChange?.(next,details); }); },
    onCloseComplete:(details)=>{ if (instance !== owned) return; untrack(() => { onCloseComplete?.(details); }); },


  });
  instance=owned;
const unsubscribeOpenChange = owned.subscribe("openChange", details=>{ if (instance !== owned) return;
    untrack(() => { accepted=details.open;
      if (open !== details.open) open = details.open; }); });
queueMicrotask(() => {
      untrack(() => { if (instance !== owned || !root.isConnected) return;
for (const model of models.values()) model.accept();
const desired = open ?? accepted;
    if (owned.getOpen() !== desired) owned.setOpen(desired,{emit:false});
    accepted=owned.getOpen(); });
    });
        return () => { unsubscribeOpenChange();
    if (instance === owned) { instance=undefined; }
    owned.destroy(); };
      });
    });
    $effect(() => { void open; untrack(() => { const owned = instance; if (!owned || open === undefined) return;
    const next = open;
    if (owned.getOpen() !== next) owned.setOpen(next,{emit:false});
    accepted=owned.getOpen(); }); });
    return () => { mounted = false; binding?.destroy(); binding = undefined; rootElement = undefined; };
  };
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>
<div {...rest} data-sw-menu="" data-sw-part="root" data-default-open={initialDefault ? "true" : undefined} data-disabled={disabled ? "" : undefined} data-modal={String(modal)} data-open-on-hover={openOnHover ? "" : undefined} data-close-delay={closeDelay} data-state={accepted ? "open" : "closed"} {@attach attachRuntime} {@attach attachRef}>
  {@render children?.(accepted)}
</div>
