<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script module lang="ts">
  export type { ButtonChildProps, ButtonChildPayload } from "../button/ButtonRoot.svelte";
</script>
<script lang="ts">
  import { onMount, tick, untrack, type Snippet } from "svelte";
  import { createAttachmentKey, type Attachment } from "svelte/attachments";
  import type { ButtonChildProps, ButtonChildPayload } from "../button/ButtonRoot.svelte";
  import { getMenuTreeContext, getMenuOwnerContext } from "./MenuRoot.svelte";

  type Props = ButtonChildProps & {
    child?: Snippet<[ButtonChildPayload]>;
    children?: Snippet;
    ref?: (element: HTMLButtonElement | null) => void;
  };
  let allProps: Props = $props();
  let child = $derived(allProps.child);
  let children = $derived(allProps.children);
  let refCallback = $derived(allProps.ref);
  let nativeProps = $derived.by(() => {
    const { child: _child, children: _children, ref: _ref,  ...native } = allProps;
    return { ...native } as ButtonChildProps;
  });
  const tree = getMenuTreeContext(); const menu = getMenuOwnerContext();
  const owner = Symbol("MenuTrigger owner");
  let currentElement = $state.raw<HTMLButtonElement | null>(null);
  let attachmentRevision = 0;
  let mounted = false;
  // Svelte removes this setup in production; bundlers then remove the unset callback calls.
  let diagnoseOwner: ((root: Element, attached: boolean) => void) | undefined;
  $inspect(true).with(() => {
    const owners = new Set<Element>();
    let validationRevision = 0;
    let diagnostic: string | null = null;
    function validateSettledOwner(): void {
      const revision = ++validationRevision;
      void tick().then(() => {
        if (!mounted || revision !== validationRevision) return;
        const message = [...owners].some((element) => !(element instanceof HTMLButtonElement))
          ? "MenuTrigger child props must attach to an HTMLButtonElement."
          : owners.size > 1
            ? "MenuTrigger child props must attach to exactly one button; multiple owners were attached."
            : owners.size === 0
              ? "MenuTrigger child props did not attach to a button after mount. Spread the whole props object onto one button."
              : null;
        if (message !== diagnostic) {
          diagnostic = message;
          if (message) console.warn(message);
        }
      });
    }
    diagnoseOwner = (root, attached) => {
      if (attached) owners.add(root); else owners.delete(root);
      validateSettledOwner();
    };
    onMount(() => {
      validateSettledOwner();
      return () => { validationRevision += 1; };
    });
  });
  onMount(() => {
    mounted = true;
    return () => { mounted = false; attachmentRevision += 1; };
  });
  // Keep ref and Runtime registration tied to the discovered semantic owner. Consumer attachments
  // remain in buttonProps and follow Svelte's native spread lifecycle on that same owner.
  $effect(() => {
    const root = currentElement;
    if (!root) return;
    $effect(() => {
      const callback = refCallback;
      untrack(() => callback?.(root));
      return () => untrack(() => callback?.(null));
    });
    $effect(() => untrack(() => {
      tree?.registerPart(owner, { element: root, scope: menu!.scope, part: "trigger" }); return () => tree?.registerPart(owner, null);
    }));

  });
  const attachOwner: Attachment<Element> = (root) => {
    diagnoseOwner?.(root, true);
    attachmentRevision += 1;
    if (root instanceof HTMLButtonElement) currentElement = root;
    return () => {
      diagnoseOwner?.(root, false);
      if (!root.isConnected) {
        if (untrack(() => currentElement) === root) currentElement = null;
        return;
      }
      const revision = ++attachmentRevision;
      void tick().then(() => {
        if (!mounted || revision !== attachmentRevision) return;
        if (currentElement === root) currentElement = null;
      });
    };
  };
  const ownerKey = createAttachmentKey();
  let buttonProps: ButtonChildProps = $derived({
    ...nativeProps,
    "data-sw-menu-trigger": "", type: "button", "aria-haspopup": "menu", "aria-expanded": !!menu?.open, "data-state": menu?.open ? "open" : "closed", "data-sw-part": "trigger",
    [ownerKey]: attachOwner,
  });
</script>

{#if child}
  {@render child({ props: buttonProps, children })}
{:else}
  <button {...buttonProps}>{@render children?.()}</button>
{/if}
