<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import type { MenuValueChangeDetails } from "@starwind-ui/runtime/menu";
  import { setContext, untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { getMenuTreeContext, menuRadioKey } from "./MenuRoot.svelte";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children" | "defaultValue"> & {
    children?: Snippet; value?: string; defaultValue?: string;
    onValueChange?: (value: string, detail: MenuValueChangeDetails) => void;
    ref?: (element: HTMLDivElement | null) => void;
  };
  let { children, value = $bindable(), defaultValue, onValueChange, ref, ...rest }: Props = $props();
  const initial = untrack(() => value);
  let accepted = $state(initial ?? untrack(() => defaultValue));
  const tree = getMenuTreeContext();
  const owner = Symbol("MenuRadioGroup model");
  setContext(menuRadioKey, { get value() { return accepted; } });
  const attachModel: Attachment<HTMLDivElement> = (element) => {
    let alive = true;
    function project(next: string | undefined): void {
      if (next === undefined) return;
      element.setAttribute("data-value",next);
   for (const item of element.querySelectorAll<HTMLElement>("[data-sw-menu-radio-item]")) {
     if (item.closest("[data-sw-menu-radio-group]") !== element) continue;
     const checked = item.getAttribute("data-value") === next;
     item.setAttribute("aria-checked",String(checked));
   item.toggleAttribute("data-checked",checked);
   item.toggleAttribute("data-unchecked",!checked);
   for (const indicator of item.querySelectorAll<HTMLElement>("[data-sw-menu-radio-item-indicator]")) {
     if (indicator.closest("[data-sw-menu-radio-item]") !== item) continue;
     indicator.setAttribute("aria-hidden","true");
     indicator.setAttribute("data-state",checked?"checked":"unchecked");
     indicator.toggleAttribute("data-visible",checked);
     indicator.toggleAttribute("data-hidden",!checked);
   }
   }
    }
    function prepare(): void {
      if (value !== undefined) accepted = value;
      project(accepted);
    }
    function accept(): void { if (alive) accepted = element.getAttribute("data-value") ?? undefined; }
    function handle(event: Event): void { if (event.target !== element) return;
   const ownerElement = element; if (!ownerElement) return;
   const details = (event as CustomEvent<MenuValueChangeDetails>).detail;

   untrack(() => { onValueChange?.(details.value,details); });
   queueMicrotask(() => {

     if (!(alive && ownerElement.isConnected) || details.isCanceled) return;
     untrack(() => { accepted=details.value;
       if (value !== details.value) value=details.value; });


   }); }
    untrack(prepare);
    tree?.registerModel(owner, {prepare,accept});
    element.addEventListener("starwind:value-change",handle);
    $effect(() => { void value; untrack(prepare); });
    return () => { alive = false; tree?.registerModel(owner, null); element.removeEventListener("starwind:value-change", handle); };
  };
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>
<div {...rest} data-sw-menu-radio-group="" data-sw-part="radioGroup" role="group" data-value={accepted} {@attach attachModel} {@attach attachRef}>{@render children?.()}</div>
