<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { getMenuTreeContext, getMenuOwnerContext } from "./MenuRoot.svelte";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & { children?: Snippet; ref?: (element: HTMLDivElement | null) => void; side?: "top" | "right" | "bottom" | "left"; align?: "start" | "center" | "end"; sideOffset?: number; avoidCollisions?: boolean;   };
  let { children, ref,  side = "bottom", align = "start", sideOffset = 4, avoidCollisions = true,   ...rest }: Props = $props();
  const tree = getMenuTreeContext(); const menu = getMenuOwnerContext(); const owner = Symbol("positioner");
  const attachPart: Attachment<HTMLDivElement> = (element) => {
    $effect(() => {
      const attributes = { "data-side": side, "data-align": align, "data-side-offset": String(sideOffset), "data-avoid-collisions": String(avoidCollisions) };
      untrack(() => tree?.registerPart(owner, { element, scope: menu!.scope, part: "positioner", attributes }));
      return () => tree?.registerPart(owner, null);
    });
  };
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>
<div {...rest} data-sw-menu-positioner="" data-sw-part="positioner" data-state="closed" data-side={side} data-align={align} data-side-offset={sideOffset} data-avoid-collisions={String(avoidCollisions)} {@attach attachPart} {@attach attachRef}>{@render children?.()}</div>
