<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { createPortalBinding, readyPortalBindingSnapshot } from "@starwind-ui/runtime/menu";
  import { setContext, untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";
  import { getMenuTreeContext, menuOwnerKey, type MenuOwnerContext } from "./MenuRoot.svelte";
  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & { children?: Snippet; closeDelay?: number; ref?: (element: HTMLDivElement | null) => void };
  let { children, closeDelay = 200, ref, ...rest }: Props = $props();
  const tree = getMenuTreeContext();
  const scope = Symbol("Menu submenu scope");
  const portals = new Map<symbol, { wrapper: HTMLElement; authoredParent: HTMLElement; prepare?: () => () => void }>();
  let binding: ReturnType<typeof createPortalBinding> | undefined;
  let rootElement: HTMLDivElement | undefined;
  setContext<MenuOwnerContext>(menuOwnerKey, {
    scope, get open() { return false; }, get mounted() { return tree?.mounted ?? false; },
    registerPortal(owner, element, authoredParent, prepare) {
      if (element && authoredParent) portals.set(owner, { wrapper: element, authoredParent, prepare }); else portals.delete(owner);
      if (rootElement) binding?.publish(readyPortalBindingSnapshot(rootElement, [...portals.values()]));
    },
  });
  const attachOwner: Attachment<HTMLDivElement> = (element) => {
    rootElement = element;
    binding = createPortalBinding(element);
    binding.publish(readyPortalBindingSnapshot(element, [...portals.values()]));
    $effect(() => {
      const attributes = { "data-close-delay": String(closeDelay) };
      untrack(() => tree?.registerPart(scope, { element, scope, part: "submenuRoot", attributes }));
      return () => tree?.registerPart(scope, null);
    });
    return () => { binding?.destroy(); binding = undefined; rootElement = undefined; };
  };
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>
<div {...rest} data-sw-menu-submenu-root="" data-sw-part="submenuRoot" data-close-delay={closeDelay} data-state="closed" {@attach attachOwner} {@attach attachRef}>{@render children?.()}</div>
