<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import {
  createRadioGroup,
  type RadioGroupValue,
  type RadioGroupValueChangeDetails,
} from "@starwind-ui/runtime/radio-group";
import { computed, onBeforeUnmount, onMounted, provide, ref, useAttrs, watch } from "vue";
import { RadioGroupContext } from "./RadioGroupContext";

defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{
    defaultValue?: RadioGroupValue;
    disabled?: boolean;
    form?: string;
    name?: string;
    orientation?: "horizontal" | "vertical";
    readOnly?: boolean;
    required?: boolean;
    modelValue?: RadioGroupValue;
  }>(),
  {
    disabled: false,
    orientation: "vertical",
    readOnly: false,
    required: false,
    modelValue: undefined,
    defaultValue: undefined,
  },
);
const emit = defineEmits<{
  valueChange: [value: string, detail: RadioGroupValueChangeDetails];
  "update:modelValue": [value: RadioGroupValue];
}>();
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs(),
  rootRef = ref<HTMLDivElement | null>(null);
defineExpose({ element: rootRef });
const resetSeed = props.defaultValue ?? props.modelValue;
const initialValue = props.modelValue ?? resetSeed;
const renderedValue = ref<RadioGroupValue>(initialValue);
const connection: {
  instance?: ReturnType<typeof createRadioGroup>;
  accepted: RadioGroupValue;
  unsubscribe?: () => void;
  unsubscribeSync?: () => void;
  observer?: MutationObserver;
} = { accepted: initialValue };
const selected = computed(() => props.modelValue ?? renderedValue.value);
function isModelEqual(left: string | undefined, right: string | undefined) {
  return left === right;
}
function disconnect() {
  const owned = connection.instance;
  connection.unsubscribe?.();
  connection.unsubscribeSync?.();
  connection.observer?.disconnect();
  connection.instance = undefined;
  owned?.destroy();
}
function publishRuntime(owned: ReturnType<typeof createRadioGroup>) {
  if (connection.instance !== owned) return;
  const next = owned.getValue();
  if (!isModelEqual(connection.accepted, next)) {
    connection.accepted = next;
    renderedValue.value = next;
  }
}
function connect(root: HTMLDivElement) {
  disconnect();
  const desired = props.modelValue ?? initialValue;
  const owned = createRadioGroup(root, {
    defaultValue: resetSeed,
    disabled: props.disabled,
    form: props.form,
    name: props.name,
    orientation: props.orientation,
    readOnly: props.readOnly,
    required: props.required,
    ...(props.modelValue !== undefined ? { value: desired } : {}),
    onValueChange: (_next, detail) => {
      emit("valueChange", detail.value, detail);
    },
  });
  connection.instance = owned;
  if (!isModelEqual(owned.getValue(), desired)) owned.setValue(desired, { emit: false });
  connection.unsubscribe = owned.subscribe("valueChange", (detail) =>
    detail.onAccepted(() => {
      if (connection.instance !== owned || detail.isCanceled) return;
      publishRuntime(owned);
      emit("update:modelValue", detail.value);
    }),
  );
  connection.unsubscribeSync = owned.subscribe("stateSync", () => {
    publishRuntime(owned);
  });
  publishRuntime(owned);
}
function applyParent() {
  const owned = connection.instance,
    next = props.modelValue;
  if (!owned || next === undefined || isModelEqual(owned.getValue(), next)) return;
  owned.setValue(next, { emit: false });
  publishRuntime(owned);
}
function applyOptions() {
  const owned = connection.instance;
  if (!owned) return;
  owned.refresh();
  owned.setDisabled(props.disabled);
  owned.setFormOptions({ form: props.form, name: props.name, required: props.required });
  owned.setReadOnly(props.readOnly);
  owned.setOrientation(props.orientation);
  applyParent();
  publishRuntime(owned);
}
provide(RadioGroupContext, {
  disabled: computed(() => props.disabled),
  form: computed(() => props.form),
  name: computed(() => props.name),
  readOnly: computed(() => props.readOnly),
  required: computed(() => props.required),
  value: selected,
});
onMounted(() => {
  if (rootRef.value) connect(rootRef.value);
});
onBeforeUnmount(disconnect);
watch(
  () => [props.disabled, props.form, props.name, props.orientation, props.readOnly, props.required],
  () => queueMicrotask(applyOptions),
  { flush: "post" },
);
watch(
  () => [props.modelValue],
  () => queueMicrotask(applyParent),
  { flush: "post" },
);
</script>
<template>
  <div
    ref="rootRef"
    v-bind="attrs"
    data-sw-radio-group=""
    data-sw-part="root"
    role="radiogroup"
    :data-default-value="resetSeed"
    :data-value="selected"
    :data-disabled="props.disabled ? '' : undefined"
    :data-form="props.form"
    :data-name="props.name"
    :data-orientation="props.orientation"
    :data-readonly="props.readOnly ? '' : undefined"
    :data-required="props.required ? '' : undefined"
    :aria-disabled="props.disabled ? 'true' : undefined"
    :aria-readonly="props.readOnly ? 'true' : undefined"
    :aria-required="props.required ? 'true' : undefined"
    :aria-orientation="props.orientation"
  >
    <slot />
  </div>
</template>
