/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

// Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies.
import type { RadioGroupValue } from "@starwind-ui/runtime/radio-group";
import { type InjectionKey, inject, type Ref } from "vue";

export type RadioGroupContextValue = Readonly<{
  disabled: Readonly<Ref<boolean>>;
  form: Readonly<Ref<string | undefined>>;
  name: Readonly<Ref<string | undefined>>;
  readOnly: Readonly<Ref<boolean>>;
  required: Readonly<Ref<boolean>>;
  value: Readonly<Ref<RadioGroupValue>>;
}>;

const RadioGroupContext: InjectionKey<RadioGroupContextValue> = Symbol("StarwindRadioGroupContext");

function useRadioGroupContext(): RadioGroupContextValue | undefined {
  return inject(RadioGroupContext, undefined);
}

export { RadioGroupContext, useRadioGroupContext };
