/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import {
  createTabs,
  type TabsOrientation,
  type TabsValue,
  type TabsValueChangeDetails,
} from "@starwind-ui/runtime/tabs";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

import { TabsContext } from "./TabsContext";

export type TabsRootProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  "defaultValue" | "onChange"
> & {
  defaultValue?: TabsValue;
  onValueChange?: (value: TabsValue, details: TabsValueChangeDetails) => void;
  orientation?: TabsOrientation;
  syncKey?: string;
  value?: TabsValue;
};

const TabsRoot = React.forwardRef<HTMLDivElement, TabsRootProps>(function TabsRoot(
  { defaultValue, onValueChange, orientation = "horizontal", syncKey, value, children, ...props },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const instanceRef = React.useRef<ReturnType<typeof createTabs> | undefined>(undefined);
  const defaultValueRef = React.useRef(defaultValue);
  const onValueChangeRef = React.useRef(onValueChange);
  const orientationRef = React.useRef(orientation);
  const syncKeyRef = React.useRef(syncKey);
  const valueRef = React.useRef(value);
  const [uncontrolledValue, setUncontrolledValue] = React.useState<TabsValue>(
    () => defaultValueRef.current ?? null,
  );

  useIsomorphicLayoutEffect(() => {
    onValueChangeRef.current = onValueChange;
  }, [onValueChange]);

  useIsomorphicLayoutEffect(() => {
    valueRef.current = value;
  }, [value]);

  useIsomorphicLayoutEffect(() => {
    orientationRef.current = orientation;
    const instance = instanceRef.current;
    if (!instance) return;

    instance.refresh();
  }, [orientation]);

  const composedRef = React.useCallback(
    (node: HTMLDivElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  useIsomorphicLayoutEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const instance = createTabs(root, {
      defaultValue: defaultValueRef.current,
      onValueChange: (_nextValue, details) => {
        onValueChangeRef.current?.(details.value, details);
      },
      orientation: orientationRef.current,
      syncKey: syncKeyRef.current,
      ...(valueRef.current !== undefined ? { value: valueRef.current } : {}),
    });
    instanceRef.current = instance;
    if (valueRef.current === undefined) {
      setUncontrolledValue(instance.getValue());
    }

    const unsubscribe = instance.subscribe("valueChange", (details) => {
      if (details.isCanceled) return;

      if (valueRef.current === undefined) {
        setUncontrolledValue(details.value);
      }
    });

    return () => {
      unsubscribe();
      instance.destroy();
      if (instanceRef.current === instance) {
        instanceRef.current = undefined;
      }
    };
  }, []);

  useIsomorphicLayoutEffect(() => {
    if (value === undefined) return;
    const instance = instanceRef.current;
    if (!instance) return;
    instance.refresh();
    if (instance.getValue() === value) return;

    instance.setValue(value, { emit: false, sync: true });
  }, [value]);

  useIsomorphicLayoutEffect(() => {
    instanceRef.current?.refresh();
  }, [children]);

  const renderedValue = value !== undefined ? value : uncontrolledValue;
  const contextValue = React.useMemo(
    () => ({ orientation, value: renderedValue }),
    [orientation, renderedValue],
  );

  return (
    <TabsContext.Provider value={contextValue}>
      <div
        data-sw-tabs
        data-default-value={serializeTabsValue(defaultValueRef.current)}
        data-orientation={orientation}
        data-sync-key={syncKey}
        data-value={serializeTabsValue(renderedValue)}
        ref={composedRef}
        {...props}
      >
        {children}
      </div>
    </TabsContext.Provider>
  );
});

TabsRoot.displayName = "Tabs.Root";

export default TabsRoot;

function serializeTabsValue(value: TabsValue | undefined): string | undefined {
  if (value === undefined) return undefined;
  return value === null ? "null" : value;
}
