/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import type { TabsOrientation, TabsValue } from "@starwind-ui/runtime/tabs";
import * as React from "react";

export type TabsContextValue = {
  orientation: TabsOrientation;
  value: TabsValue;
};

const fallbackContext = {
  orientation: "horizontal",
  value: null,
} satisfies TabsContextValue;

export const TabsContext = React.createContext<TabsContextValue | null>(null);

export function useTabsContext(): TabsContextValue {
  return React.useContext(TabsContext) ?? fallbackContext;
}
