/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import * as React from "react";
import { useTabsContext } from "./TabsContext";
export type TabsPanelProps = Omit<
  React.ComponentPropsWithoutRef<"div">,
  "value" | "keepMounted"
> & { value: string; keepMounted?: boolean };
const TabsPanel = React.forwardRef<HTMLDivElement, TabsPanelProps>(function TabsPanel(
  { children, value, keepMounted = false, ...rest },
  ref,
) {
  const { orientation, value: selected } = useTabsContext();
  const active = selected === value;
  return (
    <div
      {...rest}
      data-sw-tabs-panel={""}
      data-sw-part={"panel"}
      data-orientation={orientation}
      data-value={value}
      data-active={active ? "" : undefined}
      data-state={active ? "active" : "inactive"}
      data-keep-mounted={keepMounted ? "" : undefined}
      hidden={!active}
      tabIndex={active ? 0 : -1}
      role={"tabpanel"}
      ref={ref}
    >
      {children}
    </div>
  );
});
export default TabsPanel;
