/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import AvatarFallback from "./AvatarFallback.vue";
import AvatarImage from "./AvatarImage.vue";
import AvatarRoot from "./AvatarRoot.vue";

const Avatar = {
  Root: AvatarRoot,
  Image: AvatarImage,
  Fallback: AvatarFallback,
};

export { default as AvatarFallback } from "./AvatarFallback.vue";
export { default as AvatarImage } from "./AvatarImage.vue";
export { default as AvatarRoot } from "./AvatarRoot.vue";
export { Avatar };

export default Avatar;

export type {
  AvatarImageLoadingStatus,
  AvatarLoadingStatusChangeDetails,
} from "@starwind-ui/runtime";
