/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import type { CheckboxGroupValue } from "@starwind-ui/runtime/checkbox-group";
import * as React from "react";

export type CheckboxGroupContextValue = {
  disabled: boolean;
  value: CheckboxGroupValue;
};

const CheckboxGroupContext = React.createContext<CheckboxGroupContextValue | undefined>(undefined);
CheckboxGroupContext.displayName = "CheckboxGroupContext";

function useCheckboxGroupContext(): CheckboxGroupContextValue | undefined {
  return React.useContext(CheckboxGroupContext);
}

export { CheckboxGroupContext, useCheckboxGroupContext };
