/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import {
  type CheckboxGroupValue,
  type CheckboxGroupValueChangeDetails,
  createCheckboxGroup,
} from "@starwind-ui/runtime/checkbox-group";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";
import { CheckboxGroupContext } from "./CheckboxGroupContext";
export type CheckboxGroupRootProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  "defaultValue" | "onChange"
> & {
  defaultValue?: CheckboxGroupValue;
  disabled?: boolean;
  value?: CheckboxGroupValue;
  onValueChange?: (value: CheckboxGroupValue, detail: CheckboxGroupValueChangeDetails) => void;
};
const CheckboxGroupRoot = React.forwardRef<HTMLDivElement, CheckboxGroupRootProps>(
  function CheckboxGroupRoot(
    { children, defaultValue, disabled = false, value, onValueChange, ...rest },
    forwardedRef,
  ) {
    const inputs = React.useRef({ defaultValue, disabled, value, onValueChange });
    inputs.current = { defaultValue, disabled, value, onValueChange };
    const resetSeed = React.useRef(
      copyModel(inputs.current.defaultValue ?? inputs.current.value ?? []),
    ).current;
    const initialValue = React.useRef(copyModel(inputs.current.value ?? resetSeed)).current;
    const [renderedValue, setRenderedValue] = React.useState<CheckboxGroupValue>(initialValue);
    const connection = React.useRef<{
      instance?: ReturnType<typeof createCheckboxGroup>;
      accepted: CheckboxGroupValue;
      unsubscribe?: () => void;
      unsubscribeSync?: () => void;
      observer?: MutationObserver;
    }>({ accepted: initialValue }).current;
    const rootRef = React.useRef<HTMLDivElement | null>(null);
    const composedRef = React.useCallback(
      (node: HTMLDivElement | null) => {
        rootRef.current = node;
        return setRef(forwardedRef, node);
      },
      [forwardedRef],
    );
    const selected = inputs.current.value ?? renderedValue;
    function isModelEqual(left: string[] | undefined, right: string[] | undefined) {
      return (
        left === right ||
        (left !== undefined &&
          right !== undefined &&
          left.length === right.length &&
          left.every((value, index) => value === right[index]))
      );
    }
    function copyModel(value: string[]) {
      return [...value];
    }
    function disconnect() {
      const owned = connection.instance;
      connection.unsubscribe?.();
      connection.unsubscribeSync?.();
      connection.observer?.disconnect();
      connection.instance = undefined;
      owned?.destroy();
    }
    function publishRuntime(owned: ReturnType<typeof createCheckboxGroup>) {
      if (connection.instance !== owned) return;
      const next = owned.getValue();
      if (!isModelEqual(connection.accepted, next)) {
        connection.accepted = copyModel(next);
        if (inputs.current.value === undefined) setRenderedValue(next);
      }
    }
    function connect(root: HTMLDivElement) {
      disconnect();
      const desired = inputs.current.value ?? initialValue;
      const owned = createCheckboxGroup(root, {
        defaultValue: copyModel(resetSeed),
        disabled: inputs.current.disabled,
        ...(inputs.current.value !== undefined ? { value: desired } : {}),
        onValueChange: (detail) => {
          inputs.current.onValueChange?.(copyModel(detail.value), detail);
        },
      });
      connection.instance = owned;
      if (!isModelEqual(owned.getValue(), desired)) owned.setValue(desired, { emit: false });
      connection.unsubscribe = owned.subscribe("valueChange", (detail) => {
        if (connection.instance !== owned || detail.isCanceled) return;
        publishRuntime(owned);
      });
      connection.observer = new MutationObserver(() => {
        publishRuntime(owned);
      });
      connection.observer.observe(root, { attributes: true, attributeFilter: ["data-value"] });
      publishRuntime(owned);
    }
    function applyParent() {
      const owned = connection.instance,
        next = inputs.current.value;
      if (!owned || next === undefined || isModelEqual(owned.getValue(), next)) return;
      owned.setValue(next, { emit: false });
      publishRuntime(owned);
    }
    function applyOptions() {
      const owned = connection.instance;
      if (!owned) return;
      owned.refresh();
      owned.setDisabled(inputs.current.disabled);
      applyParent();
      publishRuntime(owned);
    }
    useIsomorphicLayoutEffect(() => {
      if (rootRef.current) connect(rootRef.current);
      return disconnect;
    }, []);
    useIsomorphicLayoutEffect(applyOptions, [disabled]);
    useIsomorphicLayoutEffect(applyParent, [value]);
    const context = React.useMemo(
      () => ({ disabled: inputs.current.disabled, value: selected }),
      [disabled, selected],
    );
    return (
      <CheckboxGroupContext.Provider value={context}>
        <div
          {...rest}
          {...{
            "data-sw-checkbox-group": "",
            "data-sw-part": "root",
            role: "group",
            "data-default-value": JSON.stringify(resetSeed),
            "data-value": JSON.stringify(selected),
            "data-disabled": inputs.current.disabled ? "" : undefined,
          }}
          ref={composedRef}
        >
          {children}
        </div>
      </CheckboxGroupContext.Provider>
    );
  },
);
CheckboxGroupRoot.displayName = "CheckboxGroup.Root";
export default CheckboxGroupRoot;
