<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";

defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{
    side?: "top" | "right" | "bottom" | "left";
    align?: "start" | "center" | "end";
    sideOffset?: number;
    avoidCollisions?: boolean;
  }>(),
  { side: "bottom", align: "start", sideOffset: 4, avoidCollisions: true },
);
defineSlots<{ default?: () => unknown }>();
const element = ref<HTMLDivElement | null>(null);
defineExpose({ element });
</script>
<template>
  <div
    ref="element"
    v-bind="$attrs"
    data-sw-menu-positioner
    data-sw-part="positioner"
    data-state="closed"
    :data-side="props.side"
    :data-align="props.align"
    :data-side-offset="props.sideOffset"
    :data-avoid-collisions="props.avoidCollisions ? 'true' : 'false'"
  >
    <slot />
  </div>
</template>
