<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import {
  createMenu,
  type MenuCloseCompleteDetails,
  type MenuOpenChangeDetails,
} from "@starwind-ui/runtime/menu";
import { computed, nextTick, onBeforeUnmount, onMounted, provide, ref, useAttrs, watch } from "vue";
import { useVueAsChildRuntimeOwner } from "../_internal/as-child";
import { MenuOwnerContext, MenuRootContext } from "./MenuContext";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();
const props = withDefaults(
  defineProps<{
    defaultOpen?: boolean;
    open?: boolean;
    disabled?: boolean;
    modal?: boolean;
    openOnHover?: boolean;
    closeDelay?: number;
  }>(),
  {
    defaultOpen: false,
    open: undefined,
    disabled: false,
    modal: false,
    openOnHover: false,
    closeDelay: 200,
  },
);
const emit = defineEmits<{
  "update:open": [open: boolean];
  openChange: [open: boolean, detail: MenuOpenChangeDetails];
  closeComplete: [detail: MenuCloseCompleteDetails];
}>();
const attrs = useAttrs();
const rootRef = ref<HTMLDivElement | null>(null);
const mounted = ref(false);
const initialDefaultOpen = props.defaultOpen;
const uncontrolledOpen = ref(initialDefaultOpen);
const renderedOpen = computed(() => props.open ?? uncontrolledOpen.value);
let instance: ReturnType<typeof createMenu> | undefined;
let unsubscribeOpenChange: (() => void) | undefined;
let portalOwner: symbol | undefined;
let portalReference: HTMLElement | null = null;
let generation = 0;

provide(MenuRootContext, {
  element: rootRef,
  mounted,
  open: renderedOpen,
  registerPortal(owner, element) {
    if (element) {
      portalOwner = owner;
      portalReference = element;
    } else if (portalOwner === owner) {
      portalOwner = undefined;
      portalReference = null;
    }
  },
});
provide(MenuOwnerContext, { kind: "root" });

defineExpose({
  element: rootRef,
  close: () => instance?.close(),
  open: () => instance?.open(),
  updatePosition: () => instance?.updatePosition(),
});

function destroyOwnedInstance(): void {
  const owned = instance;
  if (!owned) return;
  unsubscribeOpenChange?.();
  unsubscribeOpenChange = undefined;
  if (instance === owned) {
    instance = undefined;
  }
  owned.destroy();
}
function setupRuntime(): void {
  const element = rootRef.value;
  if (!element) return;
  const owned = createMenu(element, {
    defaultOpen: uncontrolledOpen.value,
    disabled: props.disabled,
    modal: props.modal,
    openOnHover: props.openOnHover,
    closeDelay: props.closeDelay,
    onOpenChange: (next, details) => {
      emit("openChange", next, details);
    },
    onCloseComplete: (details) => {
      if (instance !== owned) return;
      emit("closeComplete", details);
    },
    portalReference: portalReference ?? undefined,
    ...(props.open !== undefined ? { open: props.open } : {}),
  });
  instance = owned;
  unsubscribeOpenChange = owned.subscribe("openChange", (details) => {
    if (instance !== owned) return;
    if (props.open === undefined) {
      uncontrolledOpen.value = details.open;
    }
    emit("update:open", details.open);
  });
}
async function recreateRuntime(): Promise<void> {
  const current = instance?.getOpen();
  if (props.open === undefined && current !== undefined) uncontrolledOpen.value = current;
  const ownGeneration = ++generation;
  mounted.value = false;
  destroyOwnedInstance();
  await nextTick();
  if (ownGeneration !== generation || !rootRef.value) return;
  setupRuntime();
  mounted.value = true;
}
useVueAsChildRuntimeOwner(rootRef, recreateRuntime);
onMounted(() => {
  setupRuntime();
  mounted.value = true;
});
watch(
  () => props.open,
  (open, previous) => {
    if ((open === undefined) !== (previous === undefined)) {
      void recreateRuntime();
      return;
    }
    const owned = instance;
    if (!owned || props.open === undefined) return;
    const next = props.open;
    if (owned.getOpen() !== next) owned.setOpen(next, { emit: false });
  },
  { flush: "post" },
);
watch(
  [() => props.disabled, () => props.modal, () => props.openOnHover, () => props.closeDelay],
  () => {
    void recreateRuntime();
  },
  { flush: "post" },
);
onBeforeUnmount(() => {
  generation += 1;
  mounted.value = false;
  destroyOwnedInstance();
});
</script>

<template>
  <div
    ref="rootRef"
    v-bind="attrs"
    data-sw-menu
    data-sw-part="root"
    :data-default-open="initialDefaultOpen ? 'true' : undefined"
    :data-disabled="props.disabled ? '' : undefined"
    :data-modal="props.modal ? 'true' : 'false'"
    :data-open-on-hover="props.openOnHover ? '' : undefined"
    :data-close-delay="props.closeDelay"
    :data-state="renderedOpen ? 'open' : 'closed'"
  >
    <slot />
  </div>
</template>
