<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { defineComponent, ref, useAttrs, type VNode } from "vue";
import { createVueAsChild } from "../_internal/as-child";
import { useMenuRootContext } from "./MenuContext";

defineOptions({ inheritAttrs: false });
const props = withDefaults(defineProps<{ asChild?: boolean; disabled?: boolean }>(), {
  asChild: false,
  disabled: false,
});
const slots = defineSlots<{ default?: () => VNode[] }>();
const attrs = useAttrs();
const menu = useMenuRootContext("Trigger");
const element = ref<HTMLElement | null>(null);
const asChild = createVueAsChild("MenuTrigger", element);
const { setElement } = asChild;
defineExpose({ element });
function protectedProps() {
  return {
    "data-sw-menu-trigger": "",
    "data-sw-part": "trigger",
    "aria-haspopup": "menu",
    "aria-expanded": menu.open.value,
    "data-state": menu.open.value ? "open" : "closed",
    "aria-disabled": props.disabled ? "true" : undefined,
    "data-disabled": props.disabled ? "" : undefined,
  };
}
const AsChildTrigger = defineComponent({
  inheritAttrs: false,
  setup() {
    return () =>
      asChild.render({
        children: slots.default?.() ?? [],
        consumerProps: attrs,
        protectedProps: protectedProps(),
      });
  },
});
</script>
<template>
  <AsChildTrigger v-if="props.asChild" />
  <button
    v-else
    :ref="setElement"
    v-bind="attrs"
    data-sw-menu-trigger
    data-sw-part="trigger"
    type="button"
    aria-haspopup="menu"
    :aria-expanded="menu.open.value"
    :data-state="menu.open.value ? 'open' : 'closed'"
    :disabled="props.disabled"
  >
    <slot />
  </button>
</template>
