<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { ref, useAttrs } from "vue";
import { useMenuCheckboxItemContext } from "./MenuContext";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const item = useMenuCheckboxItemContext("CheckboxItemIndicator");
const element = ref<HTMLElement | null>(null);
defineExpose({ element });
</script>
<template>
  <span
    ref="element"
    v-bind="attrs"
    data-sw-menu-checkbox-item-indicator
    data-sw-part="checkboxItemIndicator"
    aria-hidden="true"
    :data-state="item.checked.value ? 'checked' : 'unchecked'"
    :data-visible="item.checked.value ? '' : undefined"
    :data-hidden="item.checked.value ? undefined : ''"
    ><slot
  /></span>
</template>
