<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref, useAttrs } from "vue";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();
const publicAttrs = useAttrs();
const element = ref<HTMLElement | null>(null);
defineExpose({ element });
</script>
<template>
  <span ref="element" v-bind="publicAttrs" data-sw-menu-shortcut data-sw-part="shortcut"
    ><slot
  /></span>
</template>
