<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { ref, useAttrs } from "vue";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();
const publicAttrs = useAttrs();
const element = ref<HTMLElement | null>(null);
defineExpose({ element });
</script>
<template>
  <div
    ref="element"
    v-bind="publicAttrs"
    data-sw-menu-separator
    data-sw-part="separator"
    role="separator"
    aria-orientation="horizontal"
  >
    <slot />
  </div>
</template>
