<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { provide, ref } from "vue";
import { MenuOwnerContext, MenuSubmenuContext } from "./MenuContext";

defineOptions({ inheritAttrs: false });
const props = withDefaults(defineProps<{ closeDelay?: number }>(), { closeDelay: 200 });
defineSlots<{ default?: () => unknown }>();
const element = ref<HTMLDivElement | null>(null);
provide(MenuSubmenuContext, { root: element });
provide(MenuOwnerContext, { kind: "submenu" });
defineExpose({ element });
</script>
<template>
  <div
    ref="element"
    v-bind="$attrs"
    data-sw-menu-submenu-root
    data-sw-part="submenuRoot"
    :data-close-delay="props.closeDelay"
    data-state="closed"
  >
    <slot />
  </div>
</template>
