<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script lang="ts">
import type { InjectionKey, Ref } from "vue";

export type PopoverContextValue = {
  mounted: Readonly<Ref<boolean>>;
  registerPortal: (owner: symbol, element: HTMLElement | null) => void;
};

export const PopoverContext: InjectionKey<PopoverContextValue> = Symbol("PopoverContext");
</script>

<script setup lang="ts">
import {
  type PopoverCloseCompleteDetails,
  type PopoverOpenChangeDetails,
  createPopover,
} from "@starwind-ui/runtime/popover";
import { computed, nextTick, onBeforeUnmount, onMounted, provide, ref, useAttrs, watch } from "vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    defaultOpen?: boolean;
    open?: boolean;
    closeOnEscape?: boolean;
    closeOnOutsideInteract?: boolean;
    modal?: boolean;
    openOnHover?: boolean;
    closeDelay?: number;
  }>(),
  {
    defaultOpen: false,
    open: undefined,
    closeOnEscape: true,
    closeOnOutsideInteract: true,
    modal: false,
    openOnHover: false,
    closeDelay: 200,
  },
);
const emit = defineEmits<{
  closeComplete: [detail: PopoverCloseCompleteDetails];
  openChange: [open: boolean, detail: PopoverOpenChangeDetails];
  "update:open": [open: boolean];
}>();
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const rootRef = ref<HTMLDivElement | null>(null);
const initialDefaultOpen = props.defaultOpen;
const uncontrolledOpen = ref(initialDefaultOpen);
const renderedOpen = computed(() => props.open ?? uncontrolledOpen.value);
const mounted = ref(false);
let instance: ReturnType<typeof createPopover> | undefined;
let portalOwner: symbol | undefined;
let runtimeGeneration = 0;

provide(PopoverContext, {
  mounted,
  registerPortal(owner, element) {
    if (element) {
      portalOwner = owner;
      return;
    }
    if (portalOwner === owner) portalOwner = undefined;
  },
});

defineExpose({ element: rootRef });

function handleOpenChange(nextOpen: boolean, detail: PopoverOpenChangeDetails): void {
  const eventWasControlled = props.open !== undefined;
  emit("openChange", nextOpen, detail);
  if (detail.isCanceled) return;

  if (!eventWasControlled) uncontrolledOpen.value = nextOpen;
  emit("update:open", nextOpen);
}

function handleCloseComplete(detail: PopoverCloseCompleteDetails): void {
  emit("closeComplete", detail);
}

function destroyOwnedInstance(): void {
  const ownedInstance = instance;
  if (!ownedInstance) return;

  if (instance === ownedInstance) instance = undefined;
  ownedInstance.destroy();
}

function setupRuntime(recreatedOpen?: boolean): void {
  const recreating = recreatedOpen !== undefined || instance !== undefined;
  const acceptedOpen = recreatedOpen ?? instance?.getOpen() ?? renderedOpen.value;
  destroyOwnedInstance();
  const element = rootRef.value;
  if (!element) return;

  if (props.open === undefined) uncontrolledOpen.value = acceptedOpen;
  instance = createPopover(element, {
    defaultOpen: recreating ? false : acceptedOpen,
    closeOnEscape: props.closeOnEscape,
    closeOnOutsideInteract: props.closeOnOutsideInteract,
    modal: props.modal,
    openOnHover: props.openOnHover,
    onCloseComplete: handleCloseComplete,
    onOpenChange: handleOpenChange,
    ...(props.open === undefined ? {} : { open: recreating ? false : props.open }),
  });

  if (recreating && acceptedOpen) {
    instance.setOpen(true, { emit: false });
  }
}

async function recreateRuntime(): Promise<void> {
  const generation = ++runtimeGeneration;
  const acceptedOpen = instance?.getOpen() ?? renderedOpen.value;
  destroyOwnedInstance();
  mounted.value = false;
  await nextTick();
  if (generation !== runtimeGeneration) return;
  setupRuntime(acceptedOpen);
  mounted.value = true;
}

onMounted(() => {
  setupRuntime();
  mounted.value = true;
});

watch(
  () => props.open,
  (nextOpen, previousOpen) => {
    const controllednessChanged = (nextOpen === undefined) !== (previousOpen === undefined);
    if (controllednessChanged) {
      void recreateRuntime();
      return;
    }
    if (nextOpen === undefined || !instance || Object.is(instance.getOpen(), nextOpen)) {
      return;
    }

    instance.setOpen(nextOpen, { emit: false });
  },
  { flush: "post" },
);
watch(
  [
    () => props.closeOnEscape,
    () => props.closeOnOutsideInteract,
    () => props.modal,
    () => props.openOnHover,
  ],
  () => {
    void recreateRuntime();
  },
  { flush: "post" },
);

onBeforeUnmount(() => {
  runtimeGeneration += 1;
  mounted.value = false;
  portalOwner = undefined;
  destroyOwnedInstance();
});
</script>

<template>
  <div
    ref="rootRef"
    v-bind="attrs"
    data-sw-popover
    data-sw-part="root"
    :data-default-open="initialDefaultOpen ? 'true' : undefined"
    :data-close-on-escape="props.closeOnEscape ? 'true' : 'false'"
    :data-close-on-outside-interact="props.closeOnOutsideInteract ? 'true' : 'false'"
    :data-modal="props.modal ? 'true' : 'false'"
    :data-open-on-hover="props.openOnHover ? 'true' : undefined"
    :data-close-delay="props.closeDelay"
    :data-state="renderedOpen ? 'open' : 'closed'"
  >
    <slot />
  </div>
</template>
