<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { type HTMLAttributes, ref, useAttrs } from "vue";

defineOptions({ inheritAttrs: false });

type NativeElementProps = /* @vue-ignore */ HTMLAttributes;
defineProps<NativeElementProps>();
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const element = ref<HTMLElement | null>(null);

defineExpose({ element });
</script>

<template>
  <p ref="element" v-bind="attrs" data-sw-popover-description data-sw-part="description">
    <slot />
  </p>
</template>
