/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import {
  createDialog,
  type DialogCloseCompleteDetails,
  type DialogOpenChangeDetails,
} from "@starwind-ui/runtime/dialog";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export const NativeOverlayControlContext = React.createContext<(() => void) | undefined>(undefined);
export type DialogRootProps = Omit<React.HTMLAttributes<HTMLDivElement>, "onChange"> & {
  open?: boolean;
  defaultOpen?: boolean;
  closeOnEscape?: boolean;
  closeOnOutsideInteract?: boolean;
  modal?: boolean;
  onOpenChange?: (open: boolean, detail: DialogOpenChangeDetails) => void;
  onCloseComplete?: (detail: DialogCloseCompleteDetails) => void;
};
const DialogRoot = React.forwardRef<HTMLDivElement, DialogRootProps>(function DialogRoot(
  {
    open,
    defaultOpen,
    closeOnEscape = true,
    closeOnOutsideInteract = true,
    modal = true,
    onOpenChange,
    onCloseComplete,
    ...props
  },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const inputs = React.useRef({
    open,
    closeOnEscape,
    closeOnOutsideInteract,
    modal,
    onOpenChange,
    onCloseComplete,
  });
  useIsomorphicLayoutEffect(() => {
    inputs.current = {
      open,
      closeOnEscape,
      closeOnOutsideInteract,
      modal,
      onOpenChange,
      onCloseComplete,
    };
  });
  const initialDefaultOpen = React.useRef(defaultOpen ?? false).current;
  const initialOpen = React.useRef(open ?? initialDefaultOpen).current;
  const [renderedState, setRenderedOpen] = React.useState<boolean>(initialOpen);
  const connection = React.useRef<{
    instance?: ReturnType<typeof createDialog>;
    unsubscribe?: () => void;
    accepted: boolean;
    initialized: boolean;
    refreshPending?: boolean;
  }>({ accepted: initialOpen, initialized: false }).current;
  function refreshControls(): void {
    const owned = connection.instance;
    if (!owned || connection.refreshPending) return;
    connection.refreshPending = true;
    queueMicrotask(() => {
      connection.refreshPending = false;
      if (connection.instance === owned) owned.refresh();
    });
  }
  const requestRefresh = React.useCallback(refreshControls, []);
  const composedRef = React.useCallback(
    (node: HTMLDivElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  function disconnectRuntime(): void {
    const owned = connection.instance;
    if (!owned) return;
    connection.accepted = owned.getOpen();
    connection.unsubscribe?.();
    connection.unsubscribe = undefined;
    connection.instance = undefined;
    owned.destroy();
  }
  function connectRuntime(root: HTMLDivElement): void {
    disconnectRuntime();
    const desired = inputs.current.open ?? connection.accepted;
    const recreating = connection.initialized;
    const owned = createDialog(root, {
      defaultOpen: recreating ? false : desired,
      ...(inputs.current.open !== undefined ? { open: recreating ? false : desired } : {}),
      closeOnEscape: inputs.current.closeOnEscape,
      closeOnOutsideInteract: inputs.current.closeOnOutsideInteract,
      modal: inputs.current.modal,
      onOpenChange: (next, detail) => {
        inputs.current.onOpenChange?.(next, detail);
      },
      onCloseComplete: (detail) => {
        inputs.current.onCloseComplete?.(detail);
      },
    });
    connection.instance = owned;
    connection.initialized = true;
    connection.unsubscribe = owned.subscribe("openChange", (detail) => {
      if (connection.instance !== owned) return;
      connection.accepted = detail.open;
      if (inputs.current.open === undefined) setRenderedOpen(detail.open);
    });
    if (recreating && desired) owned.setOpen(desired, { emit: false });
    connection.accepted = owned.getOpen();
    if (inputs.current.open === undefined) setRenderedOpen(connection.accepted);
  }
  function applyParentCommand(): void {
    const next = inputs.current.open;
    const owned = connection.instance;
    if (next === undefined || !owned) return;
    if (owned.getOpen() !== next) owned.setOpen(next, { emit: false });
    connection.accepted = owned.getOpen();
    if (inputs.current.open === undefined) setRenderedOpen(connection.accepted);
  }

  useIsomorphicLayoutEffect(() => {
    const root = rootRef.current;
    if (!root) return;
    connectRuntime(root);
    return disconnectRuntime;
  }, [closeOnEscape, closeOnOutsideInteract, modal]);
  useIsomorphicLayoutEffect(applyParentCommand, [open]);
  const renderedOpen = open ?? renderedState;
  return (
    <NativeOverlayControlContext.Provider value={requestRefresh}>
      <div
        data-sw-dialog
        data-sw-part="root"
        data-default-open={initialDefaultOpen ? "true" : undefined}
        data-close-on-escape={String(closeOnEscape)}
        data-close-on-outside-interact={String(closeOnOutsideInteract)}
        data-modal={String(modal)}
        data-state={renderedOpen ? "open" : "closed"}
        ref={composedRef}
        {...props}
      />
    </NativeOverlayControlContext.Provider>
  );
});
DialogRoot.displayName = "Dialog.Root";
export default DialogRoot;
