/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

const formDocuments = new WeakMap<
  Document,
  { observer: MutationObserver; subscribers: Set<() => void> }
>();

export function observeFormDiscovery(ownerDocument: Document, refresh: () => void): () => void {
  let shared = formDocuments.get(ownerDocument);
  if (!shared) {
    const Observer = ownerDocument.defaultView?.MutationObserver;
    if (!Observer) return () => {};
    const subscribers = new Set<() => void>();
    const observer = new Observer(() => {
      for (const subscriber of [...subscribers]) {
        if (!subscribers.has(subscriber)) continue;
        try {
          subscriber();
        } catch (error) {
          queueMicrotask(() => {
            throw error;
          });
        }
      }
    });
    observer.observe(ownerDocument, {
      subtree: true,
      childList: true,
      attributes: true,
      attributeFilter: ["form", "id"],
    });
    shared = { observer, subscribers };
    formDocuments.set(ownerDocument, shared);
  }
  const subscription = () => refresh();
  shared.subscribers.add(subscription);
  const { observer, subscribers } = shared;
  return () => {
    if (!subscribers.delete(subscription) || subscribers.size > 0) return;
    observer.disconnect();
    formDocuments.delete(ownerDocument);
  };
}
