/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";
import { createPortal } from "react-dom";
import { setRef } from "./compose-refs";
import { useIsomorphicLayoutEffect } from "./use-isomorphic-layout-effect";

export type ReactPortalContainer =
  | HTMLElement
  | React.RefObject<HTMLElement | null>
  | string
  | null;

export type ReactPortalProps = Omit<React.HTMLAttributes<HTMLDivElement>, "children"> & {
  children?: React.ReactNode;
  container?: ReactPortalContainer;
  disabled?: boolean;
};

type PortalPlacement = { disabled: boolean; target: HTMLElement };
type ResolvePortalPlacement = (
  wrapper: HTMLElement,
  options: {
    container?: Element | string | null;
    disabled?: boolean;
    mode?: "framework" | "runtime";
    reference?: Element | null;
  },
) => PortalPlacement;
type ReportPortalPlacement = (
  wrapper: HTMLElement,
  placement: { ready: boolean; target: HTMLElement } | null,
) => void;
type PortalBinding = {
  destroy(): void;
  getSnapshot(): { status: "pending" | "ready" };
  publish(snapshot: unknown): void;
};
type CreatePortalBinding = (root: HTMLElement) => PortalBinding;
type PortalRecord = {
  authoredParent: HTMLElement;
  node: HTMLDivElement;
  ready: boolean;
  target: HTMLElement | null;
};
type PortalToken = string;
type ReactPortalScopeValue = {
  activation: number;
  isReady(): boolean;
  phase: "inline" | "placed";
  register(token: PortalToken, record: PortalRecord): () => void;
  update(token: PortalToken, record: PortalRecord): void;
};
type ReactPortalScopeProviderProps = {
  children?: React.ReactNode;
  scope: ReactPortalScopeValue;
};
type ReactPortalImplementationProps = ReactPortalProps & {
  discoveryAttribute: string;
  reportPlacement: ReportPortalPlacement;
  resolvePlacement: ResolvePortalPlacement;
};

const ReactPortalScopeContext = React.createContext<ReactPortalScopeValue | null>(null);

export function useReactPortalScope<T extends HTMLElement>(
  rootRef: React.RefObject<T | null>,
  createBinding: CreatePortalBinding,
): ReactPortalScopeValue {
  const recordsRef = React.useRef(new Map<PortalToken, PortalRecord>());
  const bindingRef = React.useRef<PortalBinding | null>(null);
  const readyRef = React.useRef(false);
  const [activation, setActivation] = React.useState(0);
  const [phase, setPhase] = React.useState<"inline" | "placed">("inline");
  const [, setRevision] = React.useState(0);

  const publishPending = React.useCallback(() => {
    readyRef.current = false;
    bindingRef.current?.publish(Object.freeze({ status: "pending" }));
  }, []);

  const register = React.useCallback(
    (token: PortalToken, record: PortalRecord) => {
      recordsRef.current.set(token, record);
      publishPending();
      setRevision((current) => current + 1);
      return () => {
        if (recordsRef.current.get(token)?.node !== record.node) return;
        recordsRef.current.delete(token);
        publishPending();
        setRevision((current) => current + 1);
      };
    },
    [publishPending],
  );

  const update = React.useCallback(
    (token: PortalToken, record: PortalRecord) => {
      const current = recordsRef.current.get(token);
      if (
        current?.node === record.node &&
        current.ready === record.ready &&
        current.target === record.target
      )
        return;
      recordsRef.current.set(token, record);
      publishPending();
      setRevision((currentRevision) => currentRevision + 1);
    },
    [publishPending],
  );

  useIsomorphicLayoutEffect(() => {
    const root = rootRef.current;
    if (!root) return;
    const binding = createBinding(root);
    bindingRef.current = binding;
    if (phase === "inline") {
      publishPending();
      setPhase("placed");
      return;
    }

    const records = [...recordsRef.current.values()];
    if (records.some((record) => !record.ready)) {
      publishPending();
      return;
    }
    const portals = Object.freeze(
      records.map((record) =>
        Object.freeze({ authoredParent: record.authoredParent, wrapper: record.node }),
      ),
    );
    const wrappers = Object.freeze(portals.map((portal) => portal.wrapper));
    binding.publish(
      Object.freeze({
        parts: Object.freeze({ portals, root, wrappers }),
        status: "ready",
      }),
    );
    if (!readyRef.current) setActivation((current) => current + 1);
    readyRef.current = true;
  });

  React.useEffect(() => () => bindingRef.current?.destroy(), []);

  return React.useMemo(
    () => ({ activation, isReady: () => readyRef.current, phase, register, update }),
    [activation, phase, register, update],
  );
}

export function useReactPortalRuntimeLifecycle(
  scope: ReactPortalScopeValue,
  initialize: () => (() => void) | undefined,
): void {
  const cleanupRef = React.useRef<(() => void) | null>(null);
  const initializeRef = React.useRef(initialize);
  const scopeRef = React.useRef(scope);
  initializeRef.current = initialize;
  scopeRef.current = scope;

  useIsomorphicLayoutEffect(() => {
    if (!cleanupRef.current && scopeRef.current.isReady()) {
      cleanupRef.current = initializeRef.current() ?? null;
    }
    return () => {
      cleanupRef.current?.();
      cleanupRef.current = null;
    };
  }, [initialize]);

  useIsomorphicLayoutEffect(() => {
    if (cleanupRef.current || !scopeRef.current.isReady()) return;
    cleanupRef.current = initializeRef.current() ?? null;
  }, [scope.activation]);
}

export function ReactPortalScopeProvider({ children, scope }: ReactPortalScopeProviderProps) {
  return (
    <ReactPortalScopeContext.Provider value={scope}>{children}</ReactPortalScopeContext.Provider>
  );
}

export const ReactPortal = React.forwardRef<HTMLDivElement, ReactPortalImplementationProps>(
  function ReactPortal(
    {
      children,
      container = null,
      disabled = false,
      discoveryAttribute,
      reportPlacement,
      resolvePlacement,
      ...props
    },
    forwardedRef,
  ) {
    const scope = React.useContext(ReactPortalScopeContext);
    const token = React.useId();
    const wrapperRef = React.useRef<HTMLDivElement | null>(null);
    const referenceRef = React.useRef<Element | null>(null);
    const [standalonePhase, setStandalonePhase] = React.useState<"inline" | "placed">("inline");
    const [placement, setPlacement] = React.useState<{
      ready: boolean;
      target: HTMLElement | null;
    }>({
      ready: disabled,
      target: null,
    });
    const placementRef = React.useRef(placement);
    placementRef.current = placement;
    const phase = scope?.phase ?? standalonePhase;
    const registerPortal = scope?.register;
    const updatePortal = scope?.update;

    const composedRef = React.useCallback(
      (node: HTMLDivElement | null) => {
        if (!node) return setRef(forwardedRef, null);
        wrapperRef.current = node;
        if (!referenceRef.current) referenceRef.current = node.parentElement;
        const cleanupForwardedRef = setRef(forwardedRef, node);
        const cleanupRegistration = registerPortal?.(token, {
          authoredParent: (referenceRef.current as HTMLElement | null) ?? node,
          node,
          ready: placementRef.current.ready,
          target: placementRef.current.target,
        });
        return () => {
          cleanupRegistration?.();
          reportPlacement(node, null);
          if (wrapperRef.current === node) wrapperRef.current = null;
          cleanupForwardedRef?.();
        };
      },
      [forwardedRef, registerPortal, reportPlacement, token],
    );

    const refreshPlacement = React.useCallback(() => {
      const wrapper = wrapperRef.current;
      if (!wrapper) return;
      const resolved = resolvePlacement(wrapper, {
        container: resolveContainer(container),
        disabled,
        mode: "framework",
        reference: referenceRef.current ?? wrapper,
      });
      const target = resolved.disabled || phase === "inline" ? null : resolved.target;
      const ready = resolved.disabled || Boolean(target && wrapper.parentElement === target);
      reportPlacement(wrapper, { ready, target: resolved.target });
      updatePortal?.(token, {
        authoredParent: (referenceRef.current as HTMLElement | null) ?? wrapper,
        node: wrapper,
        ready,
        target,
      });
      const current = placementRef.current;
      if (current.ready !== ready || current.target !== target) setPlacement({ ready, target });
    }, [container, disabled, phase, reportPlacement, resolvePlacement, token, updatePortal]);

    useIsomorphicLayoutEffect(() => {
      if (!scope && standalonePhase === "inline") {
        setStandalonePhase("placed");
        return;
      }
      refreshPlacement();
    });

    React.useEffect(() => {
      const wrapper = wrapperRef.current;
      const mutationRoot = wrapper?.ownerDocument.documentElement;
      if (disabled || !mutationRoot) return;
      const observer = new MutationObserver(refreshPlacement);
      observer.observe(mutationRoot, { childList: true, subtree: true });
      return () => observer.disconnect();
    }, [disabled, refreshPlacement]);

    const wrapper = (
      <div
        {...props}
        {...{ [discoveryAttribute]: "" }}
        data-container={typeof container === "string" ? container : undefined}
        data-disabled={disabled ? "" : undefined}
        data-placement={disabled || placement.ready ? "ready" : "pending"}
        data-sw-portal-placement="framework"
        ref={composedRef}
      >
        {children}
      </div>
    );
    return phase === "placed" && placement.target
      ? createPortal(wrapper, placement.target, token)
      : wrapper;
  },
);

function resolveContainer(container: ReactPortalContainer): Element | string | null {
  if (container && typeof container === "object" && "current" in container) {
    return container.current;
  }
  return container;
}
