/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";
import { useIsomorphicLayoutEffect } from "./use-isomorphic-layout-effect";

const PRESENCE_ENDING_ATTRIBUTE = "data-ending-style";

export type ClosePresenceOptions = {
  keepMounted?: boolean;
  open: boolean;
};

export type ClosePresenceState<T extends HTMLElement> = {
  hidden: boolean;
  present: boolean;
  ref: React.RefCallback<T>;
};

export function useClosePresence<T extends HTMLElement>({
  keepMounted = false,
  open,
}: ClosePresenceOptions): ClosePresenceState<T> {
  const elementRef = React.useRef<T | null>(null);
  const tokenRef = React.useRef(0);
  const timeoutRef = React.useRef<number | undefined>(undefined);
  const hasOpenedRef = React.useRef(open);
  const [present, setPresent] = React.useState(() => open || keepMounted);
  const [hidden, setHidden] = React.useState(() => !open);

  if (open) {
    hasOpenedRef.current = true;
  }

  const clearScheduledClose = React.useCallback(() => {
    tokenRef.current += 1;

    if (timeoutRef.current !== undefined) {
      window.clearTimeout(timeoutRef.current);
      timeoutRef.current = undefined;
    }
  }, []);

  const ref = React.useCallback((node: T | null) => {
    elementRef.current = node;
  }, []);

  useIsomorphicLayoutEffect(() => {
    return () => {
      clearScheduledClose();
      elementRef.current?.removeAttribute(PRESENCE_ENDING_ATTRIBUTE);
    };
  }, [clearScheduledClose]);

  useIsomorphicLayoutEffect(() => {
    const element = elementRef.current;
    clearScheduledClose();

    if (open) {
      element?.removeAttribute(PRESENCE_ENDING_ATTRIBUTE);
      setPresent(true);
      setHidden(false);
      return;
    }

    if (!hasOpenedRef.current) {
      element?.removeAttribute(PRESENCE_ENDING_ATTRIBUTE);
      setPresent(keepMounted);
      setHidden(true);
      return;
    }

    const token = tokenRef.current;
    setPresent(true);
    setHidden(false);

    const completeClose = () => {
      if (tokenRef.current !== token) return;

      element?.removeAttribute(PRESENCE_ENDING_ATTRIBUTE);
      setHidden(true);
      setPresent(keepMounted);
    };

    if (!element) {
      completeClose();
      return;
    }

    element.setAttribute(PRESENCE_ENDING_ATTRIBUTE, "");
    waitForElementAnimations(element, completeClose, (timeoutId) => {
      timeoutRef.current = timeoutId;
    });
  }, [clearScheduledClose, keepMounted, open]);

  return {
    hidden: open ? false : hidden,
    present: open || keepMounted || present,
    ref,
  };
}

function waitForElementAnimations(
  element: HTMLElement,
  onComplete: () => void,
  onTimeout: (timeoutId: number) => void,
): void {
  const animations = getElementAnimations(element);
  if (animations.length > 0) {
    Promise.allSettled(animations.map((animation) => animation.finished)).then(onComplete);
    return;
  }

  const timeoutMs = getStyleAnimationTimeoutMs(element);
  if (timeoutMs > 0) {
    onTimeout(window.setTimeout(onComplete, timeoutMs));
    return;
  }

  onComplete();
}

function getElementAnimations(element: HTMLElement): Animation[] {
  if (typeof element.getAnimations !== "function") return [];

  return element.getAnimations();
}

function getStyleAnimationTimeoutMs(element: HTMLElement): number {
  if (typeof window === "undefined" || typeof window.getComputedStyle !== "function") return 0;

  const styles = window.getComputedStyle(element);
  return Math.max(
    getMaxTimePairMs(styles.animationDuration, styles.animationDelay),
    getMaxTimePairMs(styles.transitionDuration, styles.transitionDelay),
  );
}

function getMaxTimePairMs(durationsValue: string, delaysValue: string): number {
  const durations = parseTimeListMs(durationsValue);
  const delays = parseTimeListMs(delaysValue);
  const itemCount = Math.max(durations.length, delays.length);
  let max = 0;

  for (let index = 0; index < itemCount; index += 1) {
    const duration = durations[index % durations.length] ?? 0;
    const delay = delays[index % delays.length] ?? 0;
    max = Math.max(max, duration + delay);
  }

  return max;
}

function parseTimeListMs(value: string): number[] {
  const times = value
    .split(",")
    .map((part) => parseTimeMs(part.trim()))
    .filter((time) => Number.isFinite(time));

  return times.length > 0 ? times : [0];
}

function parseTimeMs(value: string): number {
  if (value.endsWith("ms")) return Number.parseFloat(value);
  if (value.endsWith("s")) return Number.parseFloat(value) * 1000;
  return Number.parseFloat(value) || 0;
}
