<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";

  type Props = Omit<HTMLAttributes<HTMLDialogElement>, "children"> & { children?: Snippet;  ref?: (element: HTMLDialogElement | null) => void };
  let { children, ref, ...rest }: Props = $props();
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDialogElement>(() => ref);
</script>

<dialog
  {...rest}
  data-sw-alert-dialog-popup=""
  data-state="closed"
  role="alertdialog"
  data-sw-part="popup"
  {@attach attachRef}
>
  {@render children?.()}
</dialog>
