<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { createFieldset } from "@starwind-ui/runtime/fieldset";
import { onBeforeUnmount, onMounted, ref, watch } from "vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    disabled?: boolean;
  }>(),
  {
    disabled: false,
  },
);
defineSlots<{
  default?: () => unknown;
}>();
const rootRef = ref<HTMLFieldSetElement | null>(null);
let instance: ReturnType<typeof createFieldset> | undefined;

defineExpose({
  element: rootRef,
});

function destroyOwnedInstance(): void {
  const ownedInstance = instance;
  if (!ownedInstance) return;

  if (instance === ownedInstance) instance = undefined;
  ownedInstance.destroy();
}

onMounted(() => {
  const element = rootRef.value;
  if (!element) throw new Error("Fieldset requires its native root before Runtime setup.");

  instance = createFieldset(element, {
    disabled: props.disabled,
  });
});

watch(
  () => props.disabled,
  (nextDisabled) => {
    instance?.setDisabled(nextDisabled);
  },
);

onBeforeUnmount(destroyOwnedInstance);
</script>

<template>
  <fieldset
    ref="rootRef"
    v-bind="$attrs"
    data-sw-fieldset
    :data-disabled="props.disabled ? '' : undefined"
    :disabled="props.disabled"
  >
    <slot />
  </fieldset>
</template>
