/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import {
  ToggleGroupContext,
  type ToggleGroupContextValue,
  useToggleGroupContext,
} from "./ToggleGroupContext";
import ToggleGroupRoot from "./ToggleGroupRoot";

const ToggleGroup = {
  Root: ToggleGroupRoot,
};

export {
  ToggleGroup,
  ToggleGroupContext,
  type ToggleGroupContextValue,
  ToggleGroupRoot,
  useToggleGroupContext,
};

export default ToggleGroup;

export type { ToggleGroupValue, ToggleGroupValueChangeDetails } from "@starwind-ui/runtime";
