/**
 * Generated by scripts/portable-runtime/generate-astro-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import SliderControl from "./SliderControl.astro";
import SliderIndicator from "./SliderIndicator.astro";
import SliderLabel from "./SliderLabel.astro";
import SliderRoot from "./SliderRoot.astro";
import SliderThumb from "./SliderThumb.astro";
import SliderTrack from "./SliderTrack.astro";

const Slider = {
  Root: SliderRoot,
  Control: SliderControl,
  Track: SliderTrack,
  Indicator: SliderIndicator,
  Label: SliderLabel,
  Thumb: SliderThumb,
};

export {
  Slider,
  SliderControl,
  SliderIndicator,
  SliderLabel,
  SliderRoot,
  SliderThumb,
  SliderTrack,
};

export default Slider;

export type {
  SliderValue,
  SliderValueChangeDetails,
  SliderValueCommitDetails,
} from "@starwind-ui/runtime";
