<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Svelte proof output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";

  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    children?: Snippet;
    index?: number;
    ref?: (element: HTMLDivElement | null) => void;
    inputRef?: (element: HTMLInputElement | null) => void;
  };
  let { children, index, ref, inputRef, ...rest }: Props = $props();
  const attachRef: Attachment<HTMLDivElement> = (element) => {
    const callback = ref;
    untrack(() => callback?.(element));
    return () => callback?.(null);
  };
  const attachInputRef: Attachment<HTMLInputElement> = (element) => {
    const callback = inputRef;
    untrack(() => callback?.(element));
    return () => callback?.(null);
  };
</script>

<div
  {...rest}
  data-sw-slider-thumb=""
  data-index={index}
  data-sw-part="thumb"
  {@attach attachRef}
>
  {@render children?.()}
  <input
    data-sw-slider-input=""
    aria-hidden="true"
    tabindex={-1}
    type="range"
    style:border="0"
    style:clip-path="inset(50%)"
    style:height="1px"
    style:margin="-1px"
    style:overflow="hidden"
    style:position="absolute"
    style:white-space="nowrap"
    style:width="1px"
    {@attach attachInputRef}
  />
</div>
