<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { getContext, untrack, type Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import { CheckboxIndicatorContext, type CheckboxIndicatorContextValue } from "./CheckboxRoot.svelte";

  type Props = Omit<HTMLAttributes<HTMLSpanElement>, "children"> & {
    children?: Snippet;
    keepMounted?: boolean;
    ref?: (element: HTMLSpanElement | null) => void;
  };

  let {
    children,
    hidden,
    keepMounted = false,
    ref,
    ...rest
  }: Props = $props();
  const state = getContext<CheckboxIndicatorContextValue | undefined>(CheckboxIndicatorContext) ?? {
    checked: false,
    disabled: false,
    indeterminate: false,
    readOnly: false,
    required: false,
  };
  let active = $derived(state.checked || state.indeterminate);
  let nativeProps = $derived({ ...rest } as HTMLAttributes<HTMLSpanElement>);
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLSpanElement>(() => ref);
</script>

{#if keepMounted || active}
  <span
    {...nativeProps}
    data-sw-checkbox-indicator=""
    data-keep-mounted={keepMounted ? "" : undefined}
    data-checked={state.checked ? "" : undefined}
    data-disabled={state.disabled ? "" : undefined}
    data-indeterminate={state.indeterminate ? "" : undefined}
    data-readonly={state.readOnly ? "" : undefined}
    data-required={state.required ? "" : undefined}
    data-unchecked={!state.checked ? "" : undefined}
    hidden={hidden ?? false}
    {@attach attachRef}
  >
    {@render children?.()}
  </span>
{/if}
