<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Svelte proof output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLButtonAttributes } from "svelte/elements";

  type Props = Omit<HTMLButtonAttributes, "children"> & { children?: Snippet; ref?: (element: HTMLButtonElement | null) => void };
  let { children, ref, ...rest }: Props = $props();
  const attachRef: Attachment<HTMLButtonElement> = (element) => {
    const callback = ref;
    untrack(() => callback?.(element));
    return () => callback?.(null);
  };
</script>

<button {...rest} data-sw-carousel-next=""
  type="button" data-sw-part="next" {@attach attachRef}>
  {@render children?.()}
</button>
