<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<!-- Svelte 5 public beta adapter output. -->
<script lang="ts">
  import { createCarousel, type CarouselInstance, type CarouselOptions } from "@starwind-ui/runtime/carousel";
  import { untrack, type Snippet } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import type { HTMLAttributes } from "svelte/elements";

  type Props = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    children?: Snippet;
    orientation?: "horizontal" | "vertical";
    opts?: CarouselOptions["opts"];
    plugins?: CarouselOptions["plugins"];
    setApi?: (api: CarouselInstance["api"]) => void;
    ref?: (element: HTMLDivElement | null) => void;
  };

  let { children, orientation = "horizontal", opts = {}, plugins, setApi, ref, ...rest }: Props = $props();

  const connection: { instance?: CarouselInstance; inputs?: CarouselOptions; callback?: CarouselOptions["setApi"] } = {};
  function readCarouselInputs(): CarouselOptions {
    return { orientation: orientation, opts: opts, plugins: plugins };
  }
  function connectCarousel(root: HTMLElement): void {
    disconnectCarousel();
    const initial = readCarouselInputs();
    connection.inputs = initial;
    connection.callback = setApi;
    connection.instance = createCarousel(root, {
      ...initial,
      setApi: (api) => setApi?.(api),
    });
  }
  function syncCarouselOptions(): void {
    const instance = connection.instance;
    const previous = connection.inputs;
    if (!instance || !previous) return;
    const next = readCarouselInputs();
    if (next.orientation === previous.orientation && next.opts === previous.opts && next.plugins === previous.plugins) return;
    connection.inputs = next;
    const options: CarouselOptions["opts"] = { axis: next.orientation === "vertical" ? "y" : "x", ...next.opts };
    const nextPlugins = next.plugins;
    instance.reInit(options, nextPlugins);
  }
  function publishCarouselApi(): void {
    const instance = connection.instance;
    const callback = setApi;
    if (!instance || callback === connection.callback) return;
    connection.callback = callback;
    callback?.(instance.api);
  }
  function disconnectCarousel(): void {
    const instance = connection.instance;
    connection.instance = undefined;
    connection.inputs = undefined;
    connection.callback = undefined;
    instance?.destroy();
  }
  const attachRuntime: Attachment<HTMLDivElement> = (root) => {
    untrack(() => connectCarousel(root));
    $effect(() => {
      void orientation; void opts; void plugins;
      untrack(syncCarouselOptions);
    });
    $effect(() => {
      void setApi;
      untrack(publishCarouselApi);
    });
    return disconnectCarousel;
  };
  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>

<div
  {...rest}
  data-sw-carousel=""
  role="region"
  aria-roledescription="carousel"
  data-auto-init="false"
  data-axis={orientation === "vertical" ? "y" : "x"}
  data-opts={JSON.stringify(opts)}
  data-sw-part="root"
  {@attach attachRuntime}
  {@attach attachRef}
>
  {@render children?.()}
</div>
