<!-- Generated by scripts/portable-runtime/generate-svelte-wrappers.ts. Do not edit by hand. -->
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { Attachment } from "svelte/attachments";
  type Props = HTMLAttributes<HTMLDivElement> & { children?: Snippet; ref?: (element: HTMLDivElement | null) => void };
  let { children, ref, ...rest }: Props = $props();

  import { createRefAttachment as createAttachRef } from "../_internal/ref-attachment.js";
  const attachRef = createAttachRef<HTMLDivElement>(() => ref);
</script>
<div {...rest} data-sw-progress-track {@attach attachRef}>
  {@render children?.()}
</div>
