/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

import { useSelectContext } from "./SelectContext";

export type SelectValueProps = React.HTMLAttributes<HTMLSpanElement> & {
  placeholder?: string;
};

const SelectValue = React.forwardRef<HTMLSpanElement, SelectValueProps>(function SelectValue(
  { children, placeholder, ...props },
  forwardedRef,
) {
  const select = useSelectContext();
  const fallback =
    select.value !== null && select.selectedLabel !== null ? select.selectedLabel : placeholder;

  return (
    <span data-sw-select-value data-placeholder={placeholder} ref={forwardedRef} {...props}>
      {children ?? fallback}
    </span>
  );
});

SelectValue.displayName = "Select.Value";

export default SelectValue;
