/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type SelectScrollUpArrowProps = React.HTMLAttributes<HTMLDivElement>;

const SelectScrollUpArrow = React.forwardRef<HTMLDivElement, SelectScrollUpArrowProps>(
  function SelectScrollUpArrow(props, forwardedRef) {
    return <div data-sw-select-scroll-up-arrow aria-hidden="true" ref={forwardedRef} {...props} />;
  },
);

SelectScrollUpArrow.displayName = "Select.ScrollUpArrow";

export default SelectScrollUpArrow;
