<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { ref } from "vue";

defineOptions({ inheritAttrs: false });
const element = ref<HTMLSpanElement | null>(null);

defineExpose({ element });
</script>

<template>
  <span ref="element" data-sw-slider-label v-bind="$attrs"><slot /></span>
</template>
