import type { Component } from "vue";

import {
  AvatarRoot,
  ButtonRoot,
  CheckboxRoot,
  ProgressRoot,
  ScrollAreaRoot,
  SelectRoot,
} from "@starwind-ui/vue";
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
  AvatarRoot as AvatarSubpath,
  type AvatarImageLoadingStatus,
  type AvatarLoadingStatusChangeDetails,
} from "@starwind-ui/vue/avatar";
import AvatarDefault from "@starwind-ui/vue/avatar";
import { Button, ButtonRoot as ButtonSubpath } from "@starwind-ui/vue/button";
import ButtonDefault from "@starwind-ui/vue/button";
import {
  Checkbox,
  CheckboxIndicator,
  CheckboxRoot as CheckboxSubpath,
} from "@starwind-ui/vue/checkbox";
import CheckboxDefault from "@starwind-ui/vue/checkbox";
import {
  Progress,
  ProgressIndicator,
  ProgressLabel,
  ProgressRoot as ProgressSubpath,
  ProgressTrack,
  ProgressValue as ProgressValuePart,
} from "@starwind-ui/vue/progress";
import ProgressDefault from "@starwind-ui/vue/progress";
import {
  ScrollArea,
  ScrollAreaContent,
  ScrollAreaCorner,
  ScrollAreaRoot as ScrollAreaSubpath,
  ScrollAreaScrollbar,
  ScrollAreaThumb,
  ScrollAreaViewport,
} from "@starwind-ui/vue/scroll-area";
import ScrollAreaDefault from "@starwind-ui/vue/scroll-area";
import {
  Select,
  SelectGroup,
  SelectGroupLabel,
  SelectIcon,
  SelectItem,
  SelectItemIndicator,
  SelectItemText,
  SelectLabel,
  SelectList,
  SelectPopup,
  SelectPortal,
  SelectPositioner,
  SelectRoot as SelectSubpath,
  SelectScrollDownArrow,
  SelectScrollUpArrow,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
  type SelectContextValue,
} from "@starwind-ui/vue/select";
import SelectDefault from "@starwind-ui/vue/select";
import {
  getThemeInitScript,
  initThemeController,
  type ThemeInitScriptOptions,
} from "@starwind-ui/vue/theme";

const components: Component[] = [
  AvatarRoot,
  AvatarSubpath,
  AvatarImage,
  AvatarFallback,
  Avatar.Root,
  Avatar.Image,
  Avatar.Fallback,
  AvatarDefault.Root,
  AvatarDefault.Image,
  AvatarDefault.Fallback,
  ButtonRoot,
  ButtonSubpath,
  Button.Root,
  ButtonDefault.Root,
  CheckboxRoot,
  CheckboxSubpath,
  CheckboxIndicator,
  Checkbox.Root,
  Checkbox.Indicator,
  CheckboxDefault.Root,
  CheckboxDefault.Indicator,
  ProgressRoot,
  ProgressSubpath,
  ProgressTrack,
  ProgressIndicator,
  ProgressValuePart,
  ProgressLabel,
  Progress.Root,
  Progress.Track,
  Progress.Indicator,
  Progress.Value,
  Progress.Label,
  ProgressDefault.Root,
  ProgressDefault.Track,
  ProgressDefault.Indicator,
  ProgressDefault.Value,
  ProgressDefault.Label,
  ScrollAreaRoot,
  ScrollAreaSubpath,
  ScrollAreaViewport,
  ScrollAreaContent,
  ScrollAreaScrollbar,
  ScrollAreaThumb,
  ScrollAreaCorner,
  ScrollArea.Root,
  ScrollArea.Viewport,
  ScrollArea.Content,
  ScrollArea.Scrollbar,
  ScrollArea.Thumb,
  ScrollArea.Corner,
  ScrollAreaDefault.Root,
  ScrollAreaDefault.Viewport,
  ScrollAreaDefault.Content,
  ScrollAreaDefault.Scrollbar,
  ScrollAreaDefault.Thumb,
  ScrollAreaDefault.Corner,
  SelectRoot,
  SelectSubpath,
  SelectLabel,
  SelectTrigger,
  SelectValue,
  SelectIcon,
  SelectPortal,
  SelectPositioner,
  SelectPopup,
  SelectList,
  SelectGroup,
  SelectGroupLabel,
  SelectItem,
  SelectItemText,
  SelectItemIndicator,
  SelectSeparator,
  SelectScrollUpArrow,
  SelectScrollDownArrow,
  Select.Root,
  Select.Label,
  Select.Trigger,
  Select.Value,
  Select.Icon,
  Select.Portal,
  Select.Positioner,
  Select.Popup,
  Select.List,
  Select.Group,
  Select.GroupLabel,
  Select.Item,
  Select.ItemText,
  Select.ItemIndicator,
  Select.Separator,
  Select.ScrollUpArrow,
  Select.ScrollDownArrow,
  SelectDefault.Root,
  SelectDefault.Label,
  SelectDefault.Trigger,
  SelectDefault.Value,
  SelectDefault.Icon,
  SelectDefault.Portal,
  SelectDefault.Positioner,
  SelectDefault.Popup,
  SelectDefault.List,
  SelectDefault.Group,
  SelectDefault.GroupLabel,
  SelectDefault.Item,
  SelectDefault.ItemText,
  SelectDefault.ItemIndicator,
  SelectDefault.Separator,
  SelectDefault.ScrollUpArrow,
  SelectDefault.ScrollDownArrow,
];
const context: SelectContextValue | undefined = undefined;
const themeOptions: ThemeInitScriptOptions = { defaultTheme: "system" };
const avatarStatus: AvatarImageLoadingStatus = "idle";
const avatarDetail: AvatarLoadingStatusChangeDetails = {
  previousStatus: avatarStatus,
  status: "loading",
};

void components;
void context;
void avatarDetail;
void getThemeInitScript(themeOptions);
void initThemeController;
