/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */
import ToastAction from "./ToastAction.svelte";
import ToastClose from "./ToastClose.svelte";
import ToastContent from "./ToastContent.svelte";
import ToastDescription from "./ToastDescription.svelte";
import ToastRoot from "./ToastRoot.svelte";
import ToastTemplate from "./ToastTemplate.svelte";
import ToastTitle from "./ToastTitle.svelte";
import ToastTitleText from "./ToastTitleText.svelte";
import ToastViewport from "./ToastViewport.svelte";
declare const Toast: {
    Viewport: import("svelte").Component<Omit<import("svelte/elements").HTMLAttributes<HTMLDivElement>, "children"> & {
        children?: import("svelte").Snippet;
        duration?: number;
        gap?: string;
        limit?: number;
        peek?: string;
        position?: "bottom-center" | "bottom-left" | "bottom-right" | "top-center" | "top-left" | "top-right";
        ref?: (element: HTMLDivElement | null) => void;
    }, {}, "">;
    Template: import("svelte").Component<Omit<import("svelte/elements").HTMLAttributes<HTMLTemplateElement>, "children"> & {
        children?: import("svelte").Snippet;
        variant?: "error" | "loading" | "default" | "info" | "success" | "warning";
        ref?: (element: HTMLTemplateElement | null) => void;
    }, {}, "">;
    Root: import("svelte").Component<Omit<import("svelte/elements").HTMLAttributes<HTMLDivElement>, "children"> & {
        children?: import("svelte").Snippet;
        variant?: "error" | "loading" | "default" | "info" | "success" | "warning";
        ref?: (element: HTMLDivElement | null) => void;
    }, {}, "">;
    Content: import("svelte").Component<Omit<import("svelte/elements").HTMLAttributes<HTMLDivElement>, "children"> & {
        children?: import("svelte").Snippet;
        ref?: (element: HTMLDivElement | null) => void;
    }, {}, "">;
    Title: import("svelte").Component<Omit<import("svelte/elements").HTMLAttributes<HTMLDivElement>, "children"> & {
        children?: import("svelte").Snippet;
        ref?: (element: HTMLDivElement | null) => void;
    }, {}, "">;
    TitleText: import("svelte").Component<Omit<import("svelte/elements").HTMLAttributes<HTMLSpanElement>, "children"> & {
        children?: import("svelte").Snippet;
        ref?: (element: HTMLSpanElement | null) => void;
    }, {}, "">;
    Description: import("svelte").Component<Omit<import("svelte/elements").HTMLAttributes<HTMLDivElement>, "children"> & {
        children?: import("svelte").Snippet;
        ref?: (element: HTMLDivElement | null) => void;
    }, {}, "">;
    Action: import("svelte").Component<Omit<import("svelte/elements").HTMLButtonAttributes, "children"> & {
        children?: import("svelte").Snippet;
        ref?: (element: HTMLButtonElement | null) => void;
    }, {}, "">;
    Close: import("svelte").Component<Omit<import("svelte/elements").HTMLButtonAttributes, "children"> & {
        children?: import("svelte").Snippet;
        ref?: (element: HTMLButtonElement | null) => void;
    }, {}, "">;
};
export { Toast, ToastAction, ToastClose, ToastContent, ToastDescription, ToastRoot, ToastTemplate, ToastTitle, ToastTitleText, ToastViewport, };
export default Toast;
export type { ToastApi, ToastOptions, ToastPromiseOptions } from "@starwind-ui/runtime";
export { toast } from "@starwind-ui/runtime/toast";
//# sourceMappingURL=index.d.ts.map