import type { RuntimeAdapterContract } from "./types.js";

/** Ticket 07 consumes these names when Color Picker joins the Primitive Inventory. */
export const colorPickerRuntimeFacade = {
  values: ["createColorPickerInitialState", "parseColor", "projectColorPickerInitialPart"],
  types: [
    "ColorPickerChannel",
    "ColorPickerColor",
    "ColorPickerDirection",
    "ColorPickerFormat",
    "ColorPickerFormatChangeDetails",
    "ColorPickerHsbChannelUpdates",
    "ColorPickerHsbChannels",
    "ColorPickerHslChannelUpdates",
    "ColorPickerHslChannels",
    "ColorPickerInstance",
    "ColorPickerInitialAxis",
    "ColorPickerInitialChannel",
    "ColorPickerInitialDirection",
    "ColorPickerInitialOrientation",
    "ColorPickerInitialPartName",
    "ColorPickerInitialPartProjection",
    "ColorPickerInitialPartRequest",
    "ColorPickerInitialState",
    "ColorPickerInitialStateOptions",
    "ColorPickerInitialValue",
    "ColorPickerOptions",
    "ColorPickerRgbChannelUpdates",
    "ColorPickerRgbChannels",
    "ColorPickerSetOptions",
    "ColorPickerSetValueOptions",
    "ColorPickerStringFormat",
    "ColorPickerValue",
    "ColorPickerValueChangeDetails",
    "ColorPickerValueChangeReason",
    "ColorPickerValueCommitDetails",
  ],
} as const;

export const colorPickerRuntimeAdapterContract = {
  component: "color-picker",
  category: "form-value-control",
  displayName: "Color Picker",
  runtime: {
    factory: "createColorPicker",
    importSource: "@starwind-ui/runtime/color-picker",
    rootPart: "root",
    optionProps: [
      "value",
      "defaultValue",
      "format",
      "alpha",
      "allowEmpty",
      "disabled",
      "readOnly",
      "name",
      "form",
      "required",
      "locale",
      "dir",
      "getAriaValueText",
      "getAreaRoleDescription",
      "getColorDescription",
      "onValueChange",
      "onValueCommitted",
      "onFormatChange",
    ],
    optionPropLifecycles: {
      value: "setter-backed",
      defaultValue: "constructor-only",
      format: "setter-backed",
      alpha: "setter-backed",
      allowEmpty: "setter-backed",
      disabled: "setter-backed",
      readOnly: "setter-backed",
      name: "setter-backed",
      form: "setter-backed",
      required: "setter-backed",
      locale: "setter-backed",
      dir: "setter-backed",
      getAriaValueText: "setter-backed",
      getAreaRoleDescription: "setter-backed",
      getColorDescription: "setter-backed",
      onValueChange: "constructor-only",
      onValueCommitted: "constructor-only",
      onFormatChange: "constructor-only",
    },
    destroys: true,
  },
  parts: [
    {
      name: "root",
      defaultElement: "div",
      discoveryAttribute: "data-sw-color-picker",
      forwardsRef: true,
      ownsRuntime: true,
      role: "group",
      initialAttributes: [
        { name: "role", source: "constant", value: "group" },
        { name: "data-value", source: "state" },
        { name: "data-format", source: "state" },
        { name: "data-alpha", source: "prop" },
        { name: "data-allow-empty", source: "prop" },
        { name: "data-disabled", source: "prop" },
        { name: "data-readonly", source: "prop" },
        { name: "data-invalid", source: "state" },
        { name: "data-name", source: "prop" },
        { name: "data-form", source: "prop" },
        { name: "data-required", source: "prop" },
        { name: "data-locale", source: "prop" },
        { name: "dir", source: "prop" },
      ],
    },
    part("label", "span", "data-sw-color-picker-label"),
    part("control", "div", "data-sw-color-picker-control"),
    part("valueInput", "input", "data-sw-color-picker-value-input", [
      { name: "aria-invalid", source: "state" },
      { name: "data-invalid", source: "state" },
    ]),
    part("valueSwatch", "span", "data-sw-color-picker-value-swatch"),
    part("valueText", "span", "data-sw-color-picker-value-text"),
    part("area", "div", "data-sw-color-picker-area", [
      { name: "data-x-channel", source: "prop" },
      { name: "data-y-channel", source: "prop" },
      { name: "data-focused", source: "state" },
      { name: "data-dragging", source: "state" },
      { name: "data-disabled", source: "state" },
      { name: "data-readonly", source: "state" },
    ]),
    part("areaBackground", "div", "data-sw-color-picker-area-background"),
    part("areaThumb", "span", "data-sw-color-picker-area-thumb", surfaceState()),
    part("areaInput", "input", "data-sw-color-picker-area-input", [
      { name: "type", source: "constant", value: "range" },
      { name: "data-axis", source: "prop" },
      { name: "data-step", source: "prop" },
      { name: "aria-roledescription", source: "runtime" },
      { name: "aria-valuetext", source: "runtime" },
      { name: "aria-description", source: "runtime" },
    ]),
    part("channelSlider", "div", "data-sw-color-picker-channel-slider", [
      { name: "data-channel", source: "prop" },
      { name: "data-orientation", source: "prop" },
      { name: "data-focused", source: "state" },
      { name: "data-dragging", source: "state" },
      { name: "data-disabled", source: "state" },
      { name: "data-readonly", source: "state" },
    ]),
    part("channelSliderTrack", "div", "data-sw-color-picker-channel-slider-track"),
    part("channelSliderThumb", "span", "data-sw-color-picker-channel-slider-thumb", surfaceState()),
    part("channelSliderInput", "input", "data-sw-color-picker-channel-input", [
      { name: "type", source: "constant", value: "range" },
      { name: "data-step", source: "prop" },
      { name: "aria-valuetext", source: "runtime" },
      { name: "aria-description", source: "runtime" },
    ]),
    part("channelInput", "input", "data-sw-color-picker-channel-field", [
      { name: "data-channel", source: "prop" },
      { name: "aria-invalid", source: "state" },
      { name: "data-invalid", source: "state" },
    ]),
    part("formatSelect", "select", "data-sw-color-picker-format-select", [
      { name: "aria-readonly", source: "state" },
    ]),
    part("formatControl", "div", "data-sw-color-picker-format-control", [
      { name: "data-format", source: "state" },
      { name: "data-disabled", source: "state" },
      { name: "data-readonly", source: "state" },
    ]),
    part("transparencyGrid", "span", "data-sw-color-picker-transparency-grid"),
    part("swatchGroup", "div", "data-sw-color-picker-swatch-group", undefined, "group"),
    part("swatch", "button", "data-sw-color-picker-swatch", [
      { name: "type", source: "constant", value: "button" },
      { name: "data-value", source: "prop" },
      { name: "data-disabled", source: "prop" },
      { name: "data-selected", source: "state" },
      { name: "aria-pressed", source: "state" },
    ]),
    part("eyeDropperTrigger", "button", "data-sw-color-picker-eye-dropper", [
      { name: "type", source: "constant", value: "button" },
      { name: "hidden", source: "runtime" },
      { name: "data-unsupported", source: "runtime" },
    ]),
    part("clear", "button", "data-sw-color-picker-clear", [
      { name: "type", source: "constant", value: "button" },
    ]),
    part("hiddenInput", "input", "data-sw-color-picker-hidden-input", [
      { name: "type", source: "constant", value: "text" },
      { name: "aria-hidden", source: "constant", value: "true" },
      { name: "tabIndex", source: "constant", value: "-1" },
      { name: "name", source: "prop" },
      { name: "form", source: "prop" },
      { name: "required", source: "prop" },
      { name: "value", source: "state" },
    ]),
  ],
  props: [
    { name: "value", kind: "control", type: "ColorPickerValue" },
    { defaultValue: '"#000000"', name: "defaultValue", kind: "control", type: "ColorPickerValue" },
    { defaultValue: '"hex"', name: "format", kind: "control", type: "ColorPickerFormat" },
    { defaultValue: "true", name: "alpha", kind: "option", type: "boolean" },
    { defaultValue: "false", name: "allowEmpty", kind: "option", type: "boolean" },
    { defaultValue: "false", name: "disabled", kind: "option", type: "boolean" },
    { defaultValue: "false", name: "readOnly", kind: "option", type: "boolean" },
    { name: "name", kind: "option", type: "string" },
    { name: "form", kind: "option", type: "string" },
    { defaultValue: "false", name: "required", kind: "option", type: "boolean" },
    { name: "locale", kind: "option", type: "string" },
    { name: "dir", kind: "option", type: "ColorPickerDirection" },
    { name: "getAriaValueText", kind: "option", type: "ColorPickerOptions['getAriaValueText']" },
    {
      name: "getAreaRoleDescription",
      kind: "option",
      type: "ColorPickerOptions['getAreaRoleDescription']",
    },
    {
      name: "getColorDescription",
      kind: "option",
      type: "ColorPickerOptions['getColorDescription']",
    },
    { name: "onValueChange", kind: "callback", type: "ColorPickerValueChangeDetails" },
    { name: "onValueCommitted", kind: "callback", type: "ColorPickerValueCommitDetails" },
    { name: "onFormatChange", kind: "callback", type: "ColorPickerFormatChangeDetails" },
    { name: "xChannel", kind: "attribute", targets: ["area"], type: "ColorPickerChannel" },
    { name: "yChannel", kind: "attribute", targets: ["area"], type: "ColorPickerChannel" },
    { name: "axis", kind: "attribute", targets: ["areaInput"], type: '"x" | "y"' },
    {
      name: "channel",
      kind: "attribute",
      targets: ["channelSlider", "channelInput"],
      type: "ColorPickerChannel",
    },
    {
      defaultValue: '"horizontal"',
      name: "orientation",
      kind: "attribute",
      targets: ["channelSlider"],
      type: '"horizontal" | "vertical"',
    },
    {
      name: "step",
      kind: "attribute",
      targets: ["areaInput", "channelSliderInput"],
      type: "number",
    },
    { name: "swatchValue", kind: "attribute", targets: ["swatch"], type: "ColorPickerValue" },
    { name: "swatchDisabled", kind: "attribute", targets: ["swatch"], type: "boolean" },
  ],
  stateModels: [
    {
      name: "value",
      controlledProp: "value",
      defaultProp: "defaultValue",
      initialAttribute: "data-value",
      runtimeGetter: "getValue",
      runtimeSetter: "setValue",
      valueType: "ColorPickerColor | null",
      controlledStateSync: "imperative",
    },
    {
      name: "format",
      controlledProp: "format",
      initialAttribute: "data-format",
      runtimeGetter: "getFormat",
      runtimeSetter: "setFormat",
      valueType: "ColorPickerFormat",
      controlledStateSync: "imperative",
    },
  ],
  events: [
    {
      name: "valueChange",
      callbackProp: "onValueChange",
      callbackTiming: "before-state-commit",
      cancelable: true,
      detailsType: "ColorPickerValueChangeDetails",
      domEvent: "starwind:value-change",
      emitsFrom: "root",
      valueProperty: "value",
      valueType: "ColorPickerColor | null",
    },
    {
      name: "valueCommitted",
      callbackProp: "onValueCommitted",
      callbackTiming: "after-state-commit",
      detailsType: "ColorPickerValueCommitDetails",
      domEvent: "starwind:value-committed",
      emitsFrom: "root",
      valueProperty: "value",
      valueType: "ColorPickerColor | null",
    },
    {
      name: "formatChange",
      callbackProp: "onFormatChange",
      callbackTiming: "after-state-commit",
      detailsType: "ColorPickerFormatChangeDetails",
      domEvent: "starwind:format-change",
      emitsFrom: "root",
      valueProperty: "format",
      valueType: "ColorPickerFormat",
    },
  ],
  setters: [
    { method: "setValue", options: { emit: false }, stateModel: "value", suppressesEmit: true },
    { method: "setFormat", options: { emit: false }, stateModel: "format", suppressesEmit: true },
    { method: "setDisabled", prop: "disabled" },
    { method: "setReadOnly", prop: "readOnly" },
    { method: "setName", prop: "name" },
    {
      method: "setOptions",
      props: [
        "alpha",
        "allowEmpty",
        "dir",
        "form",
        "getAreaRoleDescription",
        "getAriaValueText",
        "getColorDescription",
        "locale",
        "required",
      ],
    },
  ],
  form: {
    hiddenInput: { part: "hiddenInput", type: "text" },
    fieldIntegration: true,
    props: ["form", "name", "required", "value"],
  },
  refs: [
    "root",
    "label",
    "control",
    "valueInput",
    "valueSwatch",
    "valueText",
    "area",
    "areaBackground",
    "areaThumb",
    "areaInput",
    "channelSlider",
    "channelSliderTrack",
    "channelSliderThumb",
    "channelSliderInput",
    "channelInput",
    "formatSelect",
    "formatControl",
    "transparencyGrid",
    "swatchGroup",
    "swatch",
    "eyeDropperTrigger",
    "clear",
    "hiddenInput",
  ].map((part) => ({ part, public: true })),
  initialMarkup: [
    {
      part: "root",
      attributes: [
        "data-sw-color-picker",
        "role",
        "data-value",
        "data-format",
        "data-alpha",
        "data-allow-empty",
        "data-disabled",
        "data-readonly",
        "data-invalid",
        "data-name",
        "data-form",
        "data-required",
        "data-locale",
        "dir",
      ],
      reason:
        "Initial value, capability, form, and interaction state must be styleable before Runtime initialization.",
    },
    {
      part: "areaInput",
      attributes: [
        "data-sw-color-picker-area-input",
        "type",
        "data-axis",
        "data-step",
        "aria-roledescription",
        "aria-valuetext",
        "aria-description",
      ],
      reason:
        "Both area axes expose native range semantics and accessible value context before enhancement.",
    },
    {
      part: "channelSliderInput",
      attributes: [
        "data-sw-color-picker-channel-input",
        "type",
        "data-step",
        "aria-valuetext",
        "aria-description",
      ],
      reason: "Each visual channel slider has a keyboard-operable native range control.",
    },
    {
      part: "swatch",
      attributes: [
        "data-sw-color-picker-swatch",
        "type",
        "data-value",
        "data-disabled",
        "data-selected",
        "aria-pressed",
      ],
      reason: "Preset selection is a native button with value, disabled, and selected semantics.",
    },
    {
      part: "hiddenInput",
      attributes: [
        "data-sw-color-picker-hidden-input",
        "type",
        "aria-hidden",
        "tabIndex",
        "name",
        "form",
        "required",
        "value",
      ],
      reason:
        "The sole submitting control carries the canonical color string and remains programmatically focusable for native required validation while staying visually hidden, outside the tab order, and hidden from assistive technology.",
    },
  ],
  initialStateProjection: {
    importSource: "@starwind-ui/runtime/color-picker",
    createFunction: "createColorPickerInitialState",
    projectFunction: "projectColorPickerInitialPart",
    ownershipAttribute: "data-sw-color-picker-initial-owned",
    rootStateProps: [
      "value",
      "defaultValue",
      "format",
      "alpha",
      "allowEmpty",
      "disabled",
      "readOnly",
      "required",
      "name",
      "form",
      "locale",
      "dir",
      "getAriaValueText",
      "getAreaRoleDescription",
      "getColorDescription",
    ],
    compositionDependencies: [
      dependency("root"),
      dependency("label", "root"),
      dependency("control", "root"),
      dependency("valueInput", "root"),
      dependency("valueSwatch", "root"),
      dependency("valueText", "root"),
      dependency("area", "root"),
      dependency("areaBackground", "root", "area"),
      dependency("areaThumb", "root", "area"),
      dependency("areaInput", "root", "area"),
      dependency("channelSlider", "root"),
      dependency("channelSliderTrack", "root", "channelSlider"),
      dependency("channelSliderThumb", "root", "channelSlider"),
      dependency("channelSliderInput", "root", "channelSlider"),
      dependency("channelInput", "root"),
      dependency("formatSelect", "root"),
      dependency("formatControl", "root"),
      dependency("transparencyGrid", "root"),
      dependency("swatchGroup", "root"),
      dependency("swatch", "root", "swatch"),
      dependency("eyeDropperTrigger", "root"),
      dependency("clear", "root"),
      dependency("hiddenInput", "root"),
    ],
  },
  cssVariables: [
    css(
      "--sw-color-picker-color",
      "Canonical accepted color serialized for CSS painting.",
      "root",
      "runtime",
    ),
    css("--sw-color-picker-hue", "Accepted HSB hue as a unitless number.", "root", "runtime"),
    css("--sw-color-picker-saturation", "Accepted HSB saturation percentage.", "root", "runtime"),
    css("--sw-color-picker-brightness", "Accepted HSB brightness percentage.", "root", "runtime"),
    css(
      "--sw-color-picker-alpha",
      "Accepted alpha as a unitless zero-to-one number.",
      "root",
      "runtime",
    ),
    css("--sw-color-picker-area-x", "Horizontal area thumb position.", "areaThumb", "runtime"),
    css("--sw-color-picker-area-y", "Vertical area thumb position.", "areaThumb", "runtime"),
    css(
      "--sw-color-picker-area-thumb-color",
      "Resolved display color painted by the color-area thumb.",
      "areaThumb",
      "runtime",
    ),
    css(
      "--sw-color-picker-channel-position",
      "Channel slider thumb position.",
      "channelSlider",
      "runtime",
    ),
    css(
      "--sw-color-picker-channel-thumb-color",
      "Resolved display color painted by a channel slider thumb.",
      "channelSliderThumb",
      "runtime",
    ),
    css("--sw-color-picker-swatch-color", "Resolved swatch color.", "swatch", "runtime"),
    css(
      "--sw-color-picker-area-background",
      "Base color-area background layer.",
      "areaBackground",
      "styled-adapter",
    ),
    css(
      "--sw-color-picker-area-background-overlay",
      "Color-area saturation/brightness overlay layer.",
      "areaBackground",
      "styled-adapter",
    ),
    css(
      "--sw-color-picker-channel-gradient",
      "Gradient painted behind a channel slider.",
      "channelSliderTrack",
      "styled-adapter",
    ),
    css(
      "--sw-color-picker-transparency-grid-size",
      "Checkerboard tile size used beneath translucent colors.",
      "transparencyGrid",
      "styled-adapter",
    ),
  ],
  frameworkNotes: {
    astro: [
      "Render uncontrolled initial state and repeatable area/channel/swatch parts; Runtime owns color math, drafts, pointer/keyboard interaction, form synchronization, and EyeDropper capability detection.",
    ],
    react: [
      "Bridge value and format through their imperative setters after structural refresh; keep callbacks current without recreating the Runtime controller.",
    ],
  },
  escapeHatches: [
    {
      affectedFrameworks: ["astro", "react"],
      boundary:
        "Adapters own the compound part tree, repeatable axis/channel/swatch rendering, refs, controlled prop projection, and immutable Runtime facade re-exports. Runtime owns parsing, color state, editing drafts, interaction sessions, accessibility reflection, form synchronization, and EyeDropper behavior.",
      contractOwnedFacts: [
        "all 23 public parts, discovery attributes, roles, initial attributes, and refs",
        "value and format state models",
        "value-change, value-committed, and format-change events",
        "value, format, disabled, read-only, name, and mutable option setters",
        "hidden text input form participation and Field integration",
        "CSS variable names, owners, sources, and descriptions",
        "Runtime facade value parseColor",
        `Runtime facade values: ${colorPickerRuntimeFacade.values.join(", ")}`,
        `Runtime facade types: ${colorPickerRuntimeFacade.types.join(", ")}`,
        "Runtime-owned immutable initial-state and exhaustive part projection",
      ],
      demotionCriteria:
        "Demote when a reusable compound form-value Adapter Family Plan can express repeated paired axes, repeatable channel controls, immutable value facade exports, controlled refresh ordering, and the sole hidden submission input without Color Picker-specific branches.",
      reason:
        "Color Picker combines repeated visual controls, two coordinated state models, cancellable continuous updates, immutable color values, draft fields, and a single form bridge; those adapter facts do not fit an existing generic family without recreating Runtime behavior.",
      tests: [
        "scripts/portable-runtime/tests/primitive-contracts/color-picker.test.ts",
        "scripts/portable-runtime/tests/generate-astro-wrappers.test.ts",
        "scripts/portable-runtime/tests/generate-react-wrappers.test.ts",
      ],
    },
  ],
} as const satisfies RuntimeAdapterContract;

function part(
  name: string,
  defaultElement: string,
  discoveryAttribute: string,
  initialAttributes?: Array<{
    name: string;
    source: "constant" | "prop" | "state" | "runtime";
    value?: string;
  }>,
  role?: string,
) {
  return { name, defaultElement, discoveryAttribute, forwardsRef: true, role, initialAttributes };
}

function surfaceState() {
  return [
    { name: "data-focused", source: "state" as const },
    { name: "data-dragging", source: "state" as const },
    { name: "data-disabled", source: "state" as const },
    { name: "data-readonly", source: "state" as const },
  ];
}

function css(
  name: `--${string}`,
  description: string,
  part: string,
  source: "runtime" | "styled-adapter",
) {
  return { name, description, parts: [part] as [string], source };
}

function dependency(part: string, ...dependsOn: string[]) {
  return { part, dependsOn };
}
