/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type DrawerDescriptionProps = React.HTMLAttributes<HTMLParagraphElement>;

const DrawerDescription = React.forwardRef<HTMLParagraphElement, DrawerDescriptionProps>(
  function DrawerDescription(props, forwardedRef) {
    return <p data-sw-drawer-description ref={forwardedRef} {...props} />;
  },
);

DrawerDescription.displayName = "Drawer.Description";

export default DrawerDescription;
