/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import * as React from "react";
import { useNativeOverlayControl } from "../internal/native-overlay-control";
import { NativeOverlayControlContext } from "./DrawerRoot";

export type DrawerTriggerProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  asChild?: boolean;
  targetId?: string;
};

const DrawerTrigger = React.forwardRef<HTMLButtonElement, DrawerTriggerProps>(
  function DrawerTrigger(
    { asChild = false, children, className, targetId, ...props },
    forwardedRef,
  ) {
    const requestRefresh = React.useContext(NativeOverlayControlContext);
    const { controlKey, setControlElement } = useNativeOverlayControl({
      asChild,
      children,
      forwardedRef,
      requestRefresh,
    });

    if (asChild) {
      return (
        <div
          className={className}
          data-as-child
          data-sw-drawer-target-id={targetId}
          {...(props as React.HTMLAttributes<HTMLDivElement>)}
          data-sw-drawer-trigger
          key={controlKey}
          ref={setControlElement}
        >
          {children}
        </div>
      );
    }

    return (
      <button
        type="button"
        data-sw-drawer-trigger
        aria-haspopup="dialog"
        data-sw-drawer-target-id={targetId}
        data-state="closed"
        className={className}
        ref={setControlElement as React.Ref<HTMLButtonElement>}
        {...props}
      >
        {children}
      </button>
    );
  },
);

DrawerTrigger.displayName = "Drawer.Trigger";

export default DrawerTrigger;
