/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type DrawerCloseProps = React.ButtonHTMLAttributes<HTMLButtonElement>;

const DrawerClose = React.forwardRef<HTMLButtonElement, DrawerCloseProps>(
  function DrawerClose(props, forwardedRef) {
    return <button type="button" data-sw-drawer-close ref={forwardedRef} {...props} />;
  },
);

DrawerClose.displayName = "Drawer.Close";

export default DrawerClose;
