/**
 * Generated by scripts/portable-runtime/generate-astro-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import ComboboxClear from "./ComboboxClear.astro";
import ComboboxEmpty from "./ComboboxEmpty.astro";
import ComboboxGroup from "./ComboboxGroup.astro";
import ComboboxGroupLabel from "./ComboboxGroupLabel.astro";
import ComboboxIcon from "./ComboboxIcon.astro";
import ComboboxInput from "./ComboboxInput.astro";
import ComboboxInputGroup from "./ComboboxInputGroup.astro";
import ComboboxItem from "./ComboboxItem.astro";
import ComboboxItemIndicator from "./ComboboxItemIndicator.astro";
import ComboboxItemText from "./ComboboxItemText.astro";
import ComboboxLabel from "./ComboboxLabel.astro";
import ComboboxList from "./ComboboxList.astro";
import ComboboxPopup from "./ComboboxPopup.astro";
import ComboboxPortal from "./ComboboxPortal.astro";
import ComboboxPositioner from "./ComboboxPositioner.astro";
import ComboboxRoot from "./ComboboxRoot.astro";
import ComboboxSeparator from "./ComboboxSeparator.astro";
import ComboboxTrigger from "./ComboboxTrigger.astro";
import ComboboxValue from "./ComboboxValue.astro";

const Combobox = {
  Root: ComboboxRoot,
  Label: ComboboxLabel,
  InputGroup: ComboboxInputGroup,
  Input: ComboboxInput,
  Trigger: ComboboxTrigger,
  Icon: ComboboxIcon,
  Clear: ComboboxClear,
  Value: ComboboxValue,
  Portal: ComboboxPortal,
  Positioner: ComboboxPositioner,
  Popup: ComboboxPopup,
  Empty: ComboboxEmpty,
  List: ComboboxList,
  Group: ComboboxGroup,
  GroupLabel: ComboboxGroupLabel,
  Item: ComboboxItem,
  ItemText: ComboboxItemText,
  ItemIndicator: ComboboxItemIndicator,
  Separator: ComboboxSeparator,
};

export {
  Combobox,
  ComboboxClear,
  ComboboxEmpty,
  ComboboxGroup,
  ComboboxGroupLabel,
  ComboboxIcon,
  ComboboxInput,
  ComboboxInputGroup,
  ComboboxItem,
  ComboboxItemIndicator,
  ComboboxItemText,
  ComboboxLabel,
  ComboboxList,
  ComboboxPopup,
  ComboboxPortal,
  ComboboxPositioner,
  ComboboxRoot,
  ComboboxSeparator,
  ComboboxTrigger,
  ComboboxValue,
};

export default Combobox;

export type {
  ComboboxInputValueChangeDetails,
  ComboboxOpenChangeDetails,
  ComboboxValueChangeDetails,
} from "@starwind-ui/runtime";
