/**
 * Generated by scripts/portable-runtime/generate-svelte-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

// Internal non-shipping Svelte proof output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies.

import ToastAction from "./ToastAction.svelte";
import ToastClose from "./ToastClose.svelte";
import ToastContent from "./ToastContent.svelte";
import ToastDescription from "./ToastDescription.svelte";
import ToastRoot from "./ToastRoot.svelte";
import ToastTemplate from "./ToastTemplate.svelte";
import ToastTitle from "./ToastTitle.svelte";
import ToastTitleText from "./ToastTitleText.svelte";
import ToastViewport from "./ToastViewport.svelte";

const Toast = {
  Viewport: ToastViewport,
  Template: ToastTemplate,
  Root: ToastRoot,
  Content: ToastContent,
  Title: ToastTitle,
  TitleText: ToastTitleText,
  Description: ToastDescription,
  Action: ToastAction,
  Close: ToastClose,
};

export {
  Toast,
  ToastAction,
  ToastClose,
  ToastContent,
  ToastDescription,
  ToastRoot,
  ToastTemplate,
  ToastTitle,
  ToastTitleText,
  ToastViewport,
};

export default Toast;

export type { ToastApi, ToastOptions, ToastPromiseOptions } from "@starwind-ui/runtime";
export { toast } from "@starwind-ui/runtime/toast";
