/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import TooltipArrow from "./TooltipArrow";
import TooltipPopup from "./TooltipPopup";
import TooltipPortal from "./TooltipPortal";
import TooltipPositioner from "./TooltipPositioner";
import TooltipRoot from "./TooltipRoot";
import TooltipTrigger from "./TooltipTrigger";

const Tooltip = {
  Root: TooltipRoot,
  Trigger: TooltipTrigger,
  Portal: TooltipPortal,
  Positioner: TooltipPositioner,
  Popup: TooltipPopup,
  Arrow: TooltipArrow,
};

export {
  Tooltip,
  TooltipArrow,
  TooltipPopup,
  TooltipPortal,
  TooltipPositioner,
  TooltipRoot,
  TooltipTrigger,
};

export default Tooltip;

export type { TooltipOpenChangeDetails } from "@starwind-ui/runtime";
