/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import { createTooltip, type TooltipOpenChangeDetails } from "@starwind-ui/runtime/tooltip";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";

export type TooltipRootProps = Omit<React.HTMLAttributes<HTMLDivElement>, "onChange"> & {
  defaultOpen?: boolean;
  open?: boolean;
  closeDelay?: number;
  closeOnEscape?: boolean;
  closeOnOutsideInteract?: boolean;
  disabled?: boolean;
  disableHoverableContent?: boolean;
  openDelay?: number;
  onOpenChange?: (open: boolean, details: TooltipOpenChangeDetails) => void;
};

const TooltipRoot = React.forwardRef<HTMLDivElement, TooltipRootProps>(function TooltipRoot(
  {
    defaultOpen = false,
    open,
    closeDelay = 200,
    closeOnEscape = true,
    closeOnOutsideInteract = true,
    disabled = false,
    disableHoverableContent = false,
    openDelay = 200,
    onOpenChange,
    ...props
  },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const instanceRef = React.useRef<ReturnType<typeof createTooltip> | undefined>(undefined);
  const onOpenChangeRef = React.useRef(onOpenChange);
  const openRef = React.useRef(open);
  const defaultOpenRef = React.useRef(defaultOpen);
  const [uncontrolledOpen, setUncontrolledOpenState] = React.useState(defaultOpenRef.current);
  const uncontrolledOpenRef = React.useRef(uncontrolledOpen);

  const setUncontrolledOpen = React.useCallback((nextOpen: boolean) => {
    uncontrolledOpenRef.current = nextOpen;
    setUncontrolledOpenState(nextOpen);
  }, []);

  useIsomorphicLayoutEffect(() => {
    onOpenChangeRef.current = onOpenChange;
  }, [onOpenChange]);

  useIsomorphicLayoutEffect(() => {
    openRef.current = open;
  }, [open]);

  const composedRef = React.useCallback(
    (node: HTMLDivElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  useIsomorphicLayoutEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const instance = createTooltip(root, {
      defaultOpen: uncontrolledOpenRef.current,
      closeDelay,
      closeOnEscape,
      closeOnOutsideInteract,
      disabled,
      disableHoverableContent,
      openDelay,
      onOpenChange: (nextOpen, details) => {
        onOpenChangeRef.current?.(nextOpen, details);
        if (details.isCanceled) return;

        if (openRef.current === undefined) {
          setUncontrolledOpen(nextOpen);
        }
      },
      ...(openRef.current !== undefined ? { open: openRef.current } : {}),
    });
    instanceRef.current = instance;

    return () => {
      instance.destroy();
      if (instanceRef.current === instance) {
        instanceRef.current = undefined;
      }
    };
  }, [closeDelay, closeOnEscape, closeOnOutsideInteract, disableHoverableContent, openDelay]);

  useIsomorphicLayoutEffect(() => {
    const instance = instanceRef.current;
    if (!instance) return;

    instance.setDisabled(disabled);
    if (disabled && openRef.current === undefined) {
      setUncontrolledOpen(false);
    }
  }, [disabled, setUncontrolledOpen]);

  useIsomorphicLayoutEffect(() => {
    if (open === undefined) return;
    const instance = instanceRef.current;
    if (!instance) return;
    if (instance.getOpen() === open) return;

    instance.setOpen(open, { emit: false });
  }, [disabled, open]);

  const renderedOpen = !disabled && (open ?? uncontrolledOpen);

  return (
    <div
      data-sw-tooltip
      data-default-open={defaultOpenRef.current ? "true" : undefined}
      data-close-delay={closeDelay}
      data-close-on-escape={closeOnEscape ? "true" : "false"}
      data-close-on-outside-interact={closeOnOutsideInteract ? "true" : "false"}
      data-content-hoverable={!disableHoverableContent ? "true" : "false"}
      data-disabled={disabled ? "" : undefined}
      data-open-delay={openDelay}
      data-state={renderedOpen ? "open" : "closed"}
      ref={composedRef}
      {...props}
    />
  );
});

TooltipRoot.displayName = "Tooltip.Root";

export default TooltipRoot;
