/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type TooltipArrowProps = React.HTMLAttributes<HTMLDivElement>;

const TooltipArrow = React.forwardRef<HTMLDivElement, TooltipArrowProps>(
  function TooltipArrow(props, forwardedRef) {
    return <div data-sw-tooltip-arrow data-state="closed" ref={forwardedRef} {...props} />;
  },
);

TooltipArrow.displayName = "Tooltip.Arrow";

export default TooltipArrow;
