/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import {
  createPortalBinding,
  createTooltip,
  refreshTooltipPortalSurface,
  type TooltipOpenChangeDetails,
} from "@starwind-ui/runtime/tooltip";
import * as React from "react";
import { setRef } from "../internal/compose-refs";
import {
  ReactPortalScopeProvider,
  useReactPortalRuntimeLifecycle,
  useReactPortalScope,
} from "../internal/portal";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";
export const TimedPlacementContext = React.createContext<
  ((element: HTMLElement, attributes: Record<string, string> | null) => void) | undefined
>(undefined);
export type TooltipRootProps = Omit<React.HTMLAttributes<HTMLDivElement>, "onChange"> & {
  defaultOpen?: boolean;
  open?: boolean;
  closeDelay?: number;
  closeOnEscape?: boolean;
  closeOnOutsideInteract?: boolean;
  disableHoverableContent?: boolean;
  openDelay?: number;
  disabled?: boolean;
  onOpenChange?: (open: boolean, detail: TooltipOpenChangeDetails) => void;
};
const TooltipRoot = React.forwardRef<HTMLDivElement, TooltipRootProps>(function TooltipRoot(
  {
    defaultOpen = false,
    open,
    closeDelay = 200,
    closeOnEscape = true,
    closeOnOutsideInteract = true,
    disableHoverableContent = false,
    openDelay = 200,
    disabled = false,
    onOpenChange,
    ...props
  },
  forwardedRef,
) {
  const rootRef = React.useRef<HTMLDivElement>(null);
  const inputs = React.useRef({
    open,
    closeDelay,
    closeOnEscape,
    closeOnOutsideInteract,
    disableHoverableContent,
    openDelay,
    disabled,
    onOpenChange,
  });
  useIsomorphicLayoutEffect(() => {
    inputs.current = {
      open,
      closeDelay,
      closeOnEscape,
      closeOnOutsideInteract,
      disableHoverableContent,
      openDelay,
      disabled,
      onOpenChange,
    };
  });
  const initialDefaultOpen = React.useRef(defaultOpen ?? false).current;
  const initialOpen = React.useRef(!disabled && (open ?? initialDefaultOpen)).current;
  const [renderedState, setRenderedOpen] = React.useState<boolean>(initialOpen);
  const connection = React.useRef<{
    instance?: ReturnType<typeof createTooltip>;
    unsubscribe?: () => void;
    accepted: boolean;
    initialized: boolean;
    trigger?: HTMLElement;
  }>({ accepted: initialOpen, initialized: false }).current;
  const authoredPlacement = React.useRef(new Map<HTMLElement, Record<string, string>>()).current;

  function registerPlacement(
    element: HTMLElement,
    attributes: Record<string, string> | null,
  ): void {
    if (attributes) authoredPlacement.set(element, attributes);
    else authoredPlacement.delete(element);
  }
  const publishPlacement = React.useCallback(registerPlacement, []);
  const composedRef = React.useCallback(
    (node: HTMLDivElement | null) => {
      rootRef.current = node;
      return setRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  function disconnectRuntime(): void {
    const owned = connection.instance;
    if (!owned) return;
    connection.accepted = owned.getOpen();
    connection.unsubscribe?.();
    connection.unsubscribe = undefined;
    connection.instance = undefined;
    owned.destroy();
  }
  function connectRuntime(root: HTMLDivElement): void {
    disconnectRuntime();
    const desired = inputs.current.open ?? connection.accepted;
    const owned = createTooltip(root, {
      defaultOpen: false,
      ...(inputs.current.open !== undefined ? { open: false } : {}),
      closeDelay: inputs.current.closeDelay,
      closeOnEscape: inputs.current.closeOnEscape,
      closeOnOutsideInteract: inputs.current.closeOnOutsideInteract,
      disableHoverableContent: inputs.current.disableHoverableContent,
      openDelay: inputs.current.openDelay,
      disabled: inputs.current.disabled,
      onOpenChange: (next, detail) => {
        inputs.current.onOpenChange?.(next, detail);
      },
    });
    connection.instance = owned;
    connection.initialized = true;
    connection.unsubscribe = owned.subscribe("openChange", (detail) => {
      if (connection.instance !== owned) return;
      connection.accepted = detail.open;
      if (detail.open && detail.trigger instanceof HTMLElement) connection.trigger = detail.trigger;
      if (inputs.current.open === undefined) setRenderedOpen(detail.open);
    });
    if (owned.getOpen() !== desired)
      owned.setOpen(desired, { emit: false, trigger: connection.trigger });
    connection.accepted = owned.getOpen();
    if (inputs.current.open === undefined) setRenderedOpen(connection.accepted);
  }
  function applyParentCommand(): void {
    const next = inputs.current.open;
    const owned = connection.instance;
    if (next === undefined || !owned) return;
    if (owned.getOpen() !== next) owned.setOpen(next, { emit: false });
    connection.accepted = owned.getOpen();
    if (inputs.current.open === undefined) setRenderedOpen(connection.accepted);
  }

  function connectSurface(root: HTMLDivElement): void {
    for (const [element, attributes] of authoredPlacement) {
      for (const [name, value] of Object.entries(attributes)) element.setAttribute(name, value);
    }
    connectRuntime(root);
  }
  const portalScope = useReactPortalScope(rootRef, createPortalBinding);
  const initializePortalRuntime = React.useCallback(() => {
    const root = rootRef.current;
    if (!root) return;
    const snapshot = createPortalBinding(root).getSnapshot();
    if (snapshot.status === "ready" && snapshot.parts.portals.length === 0)
      throw new Error("Starwind UI: <Tooltip.Portal> is missing.");
    connectSurface(root);
    return disconnectRuntime;
  }, [closeDelay, closeOnEscape, closeOnOutsideInteract, disableHoverableContent, openDelay]);
  useReactPortalRuntimeLifecycle(portalScope, initializePortalRuntime);
  useIsomorphicLayoutEffect(() => {
    if (portalScope.isReady() && rootRef.current) refreshTooltipPortalSurface(rootRef.current);
  }, [portalScope.activation]);
  useIsomorphicLayoutEffect(applyParentCommand, [open]);
  function synchronizeDisabled(): void {
    const owned = connection.instance;
    if (!owned) return;
    owned.setDisabled(inputs.current.disabled);
    applyParentCommand();
    connection.accepted = owned.getOpen();
    if (inputs.current.open === undefined) setRenderedOpen(connection.accepted);
  }
  useIsomorphicLayoutEffect(() => {
    synchronizeDisabled();
  }, [disabled]);
  const renderedOpen = open ?? renderedState;
  return (
    <ReactPortalScopeProvider scope={portalScope}>
      <TimedPlacementContext.Provider value={publishPlacement}>
        <div
          {...props}
          data-sw-tooltip
          data-sw-part={"root"}
          data-default-open={initialDefaultOpen ? "true" : undefined}
          data-close-delay={closeDelay}
          data-close-on-escape={String(closeOnEscape)}
          data-close-on-outside-interact={String(closeOnOutsideInteract)}
          data-content-hoverable={String(!disableHoverableContent)}
          data-open-delay={openDelay}
          data-state={!disabled && renderedOpen ? "open" : "closed"}
          data-disabled={disabled ? "" : undefined}
          ref={composedRef}
        />
      </TimedPlacementContext.Provider>
    </ReactPortalScopeProvider>
  );
});
TooltipRoot.displayName = "Tooltip.Root";
export default TooltipRoot;
