/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import * as React from "react";

export type TooltipPopupProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  "tabIndex" | "tabindex"
> & {
  side?: "top" | "right" | "bottom" | "left";
  align?: "start" | "center" | "end";
  sideOffset?: number;
  avoidCollisions?: boolean;
};

const TooltipPopup = React.forwardRef<HTMLDivElement, TooltipPopupProps>(function TooltipPopup(
  { side = "top", align = "center", sideOffset = 8, avoidCollisions = true, ...props },
  forwardedRef,
) {
  return (
    <div
      data-sw-tooltip-popup
      role="tooltip"
      data-state="closed"
      data-side={side}
      data-align={align}
      data-side-offset={sideOffset}
      data-avoid-collisions={avoidCollisions ? "true" : "false"}
      hidden
      ref={forwardedRef}
      {...props}
    />
  );
});

TooltipPopup.displayName = "Tooltip.Popup";

export default TooltipPopup;
