/**
 * Generated by scripts/portable-runtime/generate-react-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

"use client";

import * as React from "react";
import { useComposedRefs } from "../internal/compose-refs";
import { useIsomorphicLayoutEffect } from "../internal/use-isomorphic-layout-effect";
import { TimedPlacementContext } from "./TooltipRoot";
export type TooltipPositionerProps = React.HTMLAttributes<HTMLDivElement> & {
  side?: "top" | "right" | "bottom" | "left";
  align?: "start" | "center" | "end";
  sideOffset?: number;
  avoidCollisions?: boolean;
};
const TooltipPositioner = React.forwardRef<HTMLDivElement, TooltipPositionerProps>(
  function TooltipPositioner(
    { side = "top", align = "center", sideOffset = 8, avoidCollisions = true, ...props },
    forwardedRef,
  ) {
    const register = React.useContext(TimedPlacementContext),
      element = React.useRef<HTMLDivElement>(null);
    const composedRef = useComposedRefs(forwardedRef, element);
    useIsomorphicLayoutEffect(() => {
      const node = element.current;
      if (!node) return;
      register?.(node, {
        "data-side": String(side),
        "data-align": String(align),
        "data-side-offset": String(sideOffset),
        "data-avoid-collisions": String(avoidCollisions),
      });
      return () => register?.(node, null);
    }, [register, side, align, sideOffset, avoidCollisions]);
    return (
      <div
        {...props}
        data-sw-tooltip-positioner=""
        data-sw-part="positioner"
        data-state="closed"
        data-side={side}
        data-align={align}
        data-side-offset={sideOffset}
        data-avoid-collisions={String(avoidCollisions)}
        ref={composedRef}
      />
    );
  },
);
TooltipPositioner.displayName = "Tooltip.Positioner";
export default TooltipPositioner;
