<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<!-- Internal non-shipping Vue adapter output. Do not publish, expose through the CLI registry, claim in public docs, or copy into public demo dependencies. -->
<script setup lang="ts">
import { ref, useAttrs } from "vue";
import { useTabsContext } from "./TabsContext";

defineOptions({ inheritAttrs: false });
defineSlots<{ default?: () => unknown }>();
const attrs = useAttrs();
const element = ref<HTMLSpanElement | null>(null);
const { orientation } = useTabsContext("TabsIndicator");
defineExpose({ element });
</script>

<template>
  <span
    ref="element"
    v-bind="attrs"
    data-sw-tabs-indicator
    data-sw-part="indicator"
    :data-orientation="orientation"
    role="presentation"
  >
    <slot />
  </span>
</template>
