/**
 * Generated by scripts/portable-runtime/generate-vue-wrappers.ts.
 * Do not edit by hand; update the contract/template instead.
 */

import type { TabsOrientation, TabsValue } from "@starwind-ui/runtime/tabs";
import { type InjectionKey, inject, type Ref } from "vue";

export type TabsContextValue = Readonly<{
  orientation: Readonly<Ref<TabsOrientation>>;
  value: Readonly<Ref<TabsValue>>;
}>;

export const TabsContext: InjectionKey<TabsContextValue> = Symbol("StarwindTabs");

export function useTabsContext(componentName: string): TabsContextValue {
  const context = inject(TabsContext);
  if (!context) {
    throw new Error(`${componentName} must be used within TabsRoot.`);
  }
  return context;
}
