<!-- Generated by scripts/portable-runtime/generate-vue-wrappers.ts. Do not edit by hand. -->
<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from "vue";
import { useTabsContext } from "./TabsContext";

defineOptions({ inheritAttrs: false });
const props = withDefaults(defineProps<{ value: string; disabled?: boolean }>(), {
  disabled: false,
});
defineSlots<{ default?: (props: { active: boolean }) => unknown }>();
const element = ref<HTMLButtonElement | null>(null);
defineExpose({ element });
const context = useTabsContext("TabsTab");
const { orientation, value: selected } = context;
watch([() => props.value, () => props.disabled], context.refresh, { flush: "post" });
onUnmounted(context.refresh);
const active = computed(() => selected.value === props.value);
const initialTabIndex = active.value && !props.disabled ? 0 : -1;
</script>
<template>
  <button
    v-bind="$attrs"
    ref="element"
    :data-sw-tabs-tab="''"
    :data-sw-part="'tab'"
    :data-orientation="orientation"
    :data-value="props.value"
    :data-active="active ? '' : undefined"
    :data-state="active ? 'active' : 'inactive'"
    :data-disabled="props.disabled ? '' : undefined"
    :disabled="props.disabled"
    :aria-selected="active"
    :tabindex="initialTabIndex"
    :role="'tab'"
    :type="'button'"
  >
    <slot :active="active" />
  </button>
</template>
